### PR TITLE
Obsolete old Graphical Overmap mods

### PR DESCRIPTION
**Pull request by Mom-Bun**
#### Summary
Mods "Obsolete old Graphical Overmap mods" 

#### Purpose of change

With #43203 finally merged, there is now a proper graphical overmap in game for tilesets to use. Which means these old mods can finally be obsoleted, and probably for the best as players enabling them could risk causing issues. 

#### Describe the solution

Obsoleted both of them

#### Describe alternatives you've considered

Potentially waiting until the graphical overmap was more filled out? 

#### Testing

N/A, simple line change and obsoleting an old mod. Shouldn't cause any real issues.

#### Additional context

Thanks for the new graphical overmap KorGgent!

### CODE REVIEW

**Comment by kevingranade** [comment]
We're not feature complete enough to fire this off just yet, but yes it does need to happen.

**Comment by Theawesomeboophis** [comment]
May I have permission to fork Graphical Overmap mods into a third-party repository for anyone who prefers them over new graphical overmap? ( Asking first as I would hate to violate the copyright).

**Comment by anothersimulacrum** [comment]
As long as you attribute correctly, and continue to distribute under CC-BY-SA, there is nothing problematic there.

**Comment by Theawesomeboophis** [comment]
> As long as you attribute correctly, and continue to distribute under CC-BY-SA 3.0, there is nothing problematic there.

Okay, I know Larwck made the mod, is there a list of other contributors?

**Comment by Theawesomeboophis** [comment]
I Looked at Commit History and have made a list of contributors I've seen so far:
Larwck/Larwick
Nyphx
Night-Pryanik
Anothersimulacrum
ZhilkinSerg
Lamandus
ralreegorganon
Kilvoctu
klorpa
Qrox
Does this list look complete or are there some I've missed?

**Comment by Theawesomeboophis** [comment]
[Contributors.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/6795794/Contributors.txt)
This is the file, If I have not attributed properly or anything is wrong, please notify me.

**Comment by I-am-Erk** [comment]
Are you interested in finishing this mombun?

**Comment by Night-Pryanik** [comment]
@Mom-Bun are you planning to finish this?

**Comment by ZhilkinSerg** [comment]
> May I have permission to fork Graphical Overmap mods into a third-party repository for anyone who prefers them over new graphical overmap? ( Asking first as I would hate to violate the copyright).

It might have sense to rework this into an overmap tileset.

**Pull request closed without merging**
