### PR TITLE
[MoM] Dont extract monster/fake spells/effects for translation

### PR DESCRIPTION
**Pull request by Uwuewsky**
#### Summary
I18N "[MoM] Dont extract monster/fake spells/effects for translation"

#### Purpose of change
The names and descriptions of NPC/monster/trap spells/effects etc. were available for translation.

#### Describe the solution
Mark such names with a flag to skip extraction into translation files.
And replace the message in the remaining practice recipe.

*Please let me know if I changed anything wrong, like, if the effect can be seen somewhere during normal play.*

#### Testing
The game loads correctly. Marked names are now missing from .pot file.

### CODE REVIEW

**Comment by Uwuewsky** [comment]
`Merge branch 'master' into no-i18n-mom`?

**Comment by Night-Pryanik** [comment]
@Uwuewsky could you please resolve conflicts?

**Review by Standing-Storm — APPROVED** [review]

**Comment by Uwuewsky** [comment]
@Night-Pryanik done.

**Comment by Night-Pryanik** [comment]
@Uwuewsky could you please resolve conflicts, once again?

**Pull request merged**
