### PR TITLE
build: vcpkg /permissive-

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary

SUMMARY: Build "Build for windows in CI with standards conformance flag"

#### Purpose of change

Change the project definition for Visual Studio to use the standards conformance flag instead of building for a Microsoft dialect.

Fixes: https://github.com/CleverRaven/Cataclysm-DDA/issues/45301

#### Describe the solution

Add the `/fpermissive-` flag to the vcxproj files.

#### Describe alternatives you've considered
Changing the style guide to forbid C++ keywords that VS doesn't understand by default

#### Testing

Appveyor

#### Additional context
[Reference](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-160)

This is required to fix the AppVeyor build errors in my other PR. It should not have any ill effects as both clang and g++ are not permissive by default (and in our Makefiles) and this is just setting Visual Studio to match.

### CODE REVIEW

**Comment by akrieger** [comment]
Imo the VS build should use `/permissive-` *and* the style guide should forbid alternate operators.

**Comment by andrei8l** [comment]
>  _and_ the style guide should forbid alternate operators.

Can you please explain why? I understand forbidding di/trigraphs but I don't see a valid argument against `and`/`or`/etc

**Comment by ZhilkinSerg** [comment]
Strangely enough alternative tokens do not work under MSYS (`gcc version 10.2.0 (Rev4, Built by MSYS2 project)`).

**Review by ZhilkinSerg — APPROVED** [review]
There are actually five projects, so I updated this option in remaining three.

**Comment by andrei8l** [comment]
Thanks!

> Strangely enough alternative tokens do not work under MSYS (`gcc version 10.2.0 (Rev4, Built by MSYS2 project)`).

Strange. My only idea is that it could have `-fno-operator-names` in its built-in specs for some reason.

**Pull request merged**
