### PR TITLE
New Zombie type: Tearjerker

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary
Content "Adds the Tearjerker, a zombie that explodes into a cloud of teargas upon death."

#### Purpose of change

I got this idea after messing with teargas in #61484 and noting how dangerous it was, Not only causing a stat decrease but blinding the player as well. A zombie filled with this stuff would be an interesting variant of the regular poisonous zombie.

#### Describe the solution

discovered there was a death effect in monster_deaths.json called "death_tearburst" and used that as it's death effect. I assume it's from a teargas hack.

#### Describe alternatives you've considered

Not adding it.

#### Testing

Didn't test yet.

### CODE REVIEW

**Comment by ashGlaw** [comment]
Where do you think this zombie would spawn?

**Comment by Daved27hundred** [comment]
> Where do you think this zombie would spawn?

The description is supposed to imply that this was someone who was peppersprayed before they turned, so it'd be something you'd occasionally see in the streets, a leftover from the riots.

**Comment by Theawesomeboophis** [comment]
I have a name suggestion, Crying Bomber, it references the tear gas and it's relation to boomers and other exploding enemies, and I think it sounds cool.

**Comment by Daved27hundred** [comment]
> I have a name suggestion, Crying Bomber, it references the tear gas and it's relation to boomers and other exploding enemies, and I think it sounds cool.

I’ve started to take a liking to “tearjerker”, but changing the name to better indicate it’s a bloated zombie is a good idea. How’s “Swollen Tearjerker” sound?

I’m currently in a car heading to another province for thanksgiving so I can’t make the change right now, but someone else is welcome to.

**Review by MNG-cataclysm — APPROVED** [review]

**Pull request merged**
