### PR TITLE
PRM: Add less hostile wildlife: II of II

### PR DESCRIPTION
**Pull request by pisskop**
adds robins, bluejays, pidgeons, giant maggots, giant pupae, giant moths, giant butterflies.

Moves the pest spawngroup into the spawngroup file now that it is used by more than a handful of custom jsons.

Tweaks times for the appearing of critters, allowing them to come earlier.  Because it turns out that people were playing with long seasonlengths on.

### CODE REVIEW

**Comment by mugling** [comment]
* Try web linter (http://dev.narc.ro/cgi-bin/format/format.pl) on new files
* Same issue as #15863 and #16215

**Comment by pisskop** [comment]
It 404s for me.

These critters are not vermin nor do they exhibit the problems that resulted in the removal of vermin.
  There are many creatures just like these that exist and regularly spawn within the core game.
Examples include, but are not limited to:  opossum, bullfrog, lemming, weasel, dermatik larvae, ant larvae, deer, giant fly, feral dog.
  These creatures exhibit personalities, as opposed to vermin creatures.
These do not spawn in large obnoxious groups or with symbols that blend into the road/dirt
  These do not interfere with combat, nor do they ignore the presence of the player, enemies, or combat.
They provide, in addition to more variation, a better way to deny strong attackers a spawn than using the null monster
  They prevent 3 bears and a moose from spawning withing an area the size of the reality bubble.
The creatures have enough ai tags to make them react to situations in manners befitting their species.
  They provide a new player with meat, similar to how opossums would, and can all be struck down with melee or a sling.
Most can be coaxed into combat, and none will pursue the player unto death without heed (i.e. zombies)


these creatures avoid what caused vermin to be removed, and build on the  world, the mod, in a way that doesn't detract from the world; but instead enhances it.  Unless you consider a pack of wolves, 2 coyotes, and 3 moose in your backyard at once normal and legit.

**Comment by mugling** [comment]
Looks like it was updated to a more permanent home at http://dev.narc.ro/tools/format/

**Comment by mugling** [comment]
I think there's a checklist for reintroducing such monsters in one of those previous issues (or otherwise linked to them?) Are all the criteria fulfillled?

**Comment by pisskop** [comment]
they are not vermin; this checklist wouldnt apply.

and since this is a mod, it neednt apply.  I would even go so far as tio argue that if this pr were a mod to explicitly readd the vermin it wouldnt apply

**Comment by pisskop** [comment]
The linter doesnt approve of the eof it linted itself
Nor the edit-mode flag

**Comment by mugling** [comment]
It's possible @narc0tiq hasn't yet updated the linter to use the repo copy of the ruleset. Can you post a subset of the failing content for me to check

**Comment by BorkBorkGoesTheCode** [comment]
Can confirm 404.

**Comment by pisskop** [comment]
It errs data/mods/pk/insect.json from the cleverraven master
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/PKs_Rebalance/monsters/insect.json

It errs any of the files with an edit-mode tage, including https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/PKs_Rebalance/monsters/robot.json

**Comment by mugling** [comment]
Try http://dev.narc.ro/tools/format

**Comment by BorkBorkGoesTheCode** [comment]
Working link from whitespace exorcism

http://dev.narc.ro/cataclysm/format.html

**Comment by mugling** [comment]
> Try http://dev.narc.ro/tools/format

This works - @pisskop check your file against this version

**Comment by pisskop** [comment]
I did.  I was using it the whole time.

**Comment by BorkBorkGoesTheCode** [comment]
The bad link had a .pl at the end

**Comment by mugling** [comment]
What are the exact messages?

**Comment by pisskop** [comment]
'syntax error at eof'
'unmatched context "Monster<monster>:edit-mode'
Or a 0 return

**Comment by mugling** [comment]
It looks like #18541 broke the buildbot. Separately the web linter is still pending an update to the latest version in `master`

**Comment by narc0tiq** [comment]
The web linter should be perfectly happy now, and following `master` in all things.

**Comment by pisskop** [comment]
oh me and this linter are going to have fights.

**Comment by mugling** [comment]
> I have provided quite enough evidence that these are not vermin

As I told you earlier there was extensive discussion by many developers in #15863 and #16215 which sets out a checklist of changes for re-inclusion. The same discussion also suggests excluding them from mods. If you think this is either solved or not applicable you should address that checklist point-by-point.

> nor that you have the ability to govern the contents of my mod.
> This isnt the 'Mugling Approved™ Pks_Rebalancing Mod'

The entire development team didn't want vermin and a list of criteria was left for re-inclusion. To be clear you don't have carte blanche - might I remind you of this little spat (#16738).

You can either answer the checklist from #15863, which might result in a merge, or you can carry on with this combative approach which won't get you anywhere.

**Comment by pisskop** [comment]
@Rivet-the-Zombie, @illi-kun, @mugling, @kevingranade, @Coolthulhu 
Let me be clear.

You have present zero, ZERO, evidence to support your claim that this is vermin, or comparable.  If you are going to stand united in allowing one dev to dictate demands unjustly than I will halt all progress on this.

**Comment by mugling** [comment]
> If you are going to stand united in allowing one dev to dictate demands unjustly

Quoting from #15863 and #16215:

Coolthulhu:

> Out of all the things that vermin do (or are involved in), not one is a positive contribution to the game:

Illi-kun:

> The moving of vermin to a mod doesn't solve the issue, just masks it. I'm totally for disabling vermin

Rivet:

> I'm okay with this.

Kevingranade:

> See #15863 for an incomplete list of shortcomings and existing discussion on the issue. If someone implements vermin properly, they can be re-added, but it seems no one has sufficient interest in doing so at the moment.

**You have been told to address the checklist. This is how we will determine if the content should be included.**

> than I will halt all progress on this.

**You have a number of edited posts. This PR should not become a repetition of #16738**

**Comment by pisskop** [comment]
Still zero evidence of them being verminlike in any aspect.

**Comment by pisskop** [comment]
Please drop the checklist talk until we establish that it even should apply

**Comment by mugling** [comment]
> Please drop the checklist talk until we establish that it even should apply

It is a good objective test written by one developer, sanctioned by a second and now referred to by a third. You should address each of it's points.

**Comment by pisskop** [comment]
- This is a mod, it is therefore not subject to the same standards or image of the core game.
- These are not vermin, therefore such a list would not apply
- It is not this mods job to solve coregame issues
- This mod is not subject to Mugling approval
- There is a utter lack of evidence to support anything you have said here or in the other prs to support a claim that mods are obligated to solve coregame issues.
- There are mods that exist to house removed coregame content
- The creatures in the coregame at this time are identical in many regards to these creatures.


Please address the points in question, as youve only avoided them in favor of citing some irrelevant checklist.

**Comment by mugling** [comment]
> This is a mod, it is therefore not subject to the same standards or image of the core game.
> There are mods that exist to house removed coregame content

See earlier quote from #15863 (illi-kun)

> It is not this mods job to solve coregame issues
> There is a utter lack of evidence to support anything you have said here or in the other prs to support a claim that mods are obligated to solve coregame issues.

These are duplicate points. See earlier quotes from #15863 (both illi-kun and kevingranade)

> This mod is not subject to Mugling approval

You need another developer to agree. Your previous conduct in #16738 along with your, now edited, 
comments in this PR is likely to discourage any further review

> These are not vermin, therefore such a list would not apply

They are very similar to those removed by #16215 and likely to cause the same issues listed on the checklist in #15863.

> The creatures in the coregame at this time are identical in many regards to these creatures.

And those should be removed - indeed this was suggested in #15863 but was omitted in error:

> Tiny problem: bullfrogs need a vermin flag to prevent spawning.

**You need to answer the checklist from #15863. I've been more than patient with you here but there is a finite amount of time available**

**Comment by pisskop** [comment]
You will not drown me out with your irrelevant insistence that I address problems that dont apply to my content, this mod, or this pr.

Please allow other devs to weigh in and stop being heavy handed about this.  This is a crowd funded open source game and I run a mod that caters to a specific crowd.  This mod does not need to address points that are entirely irrelevant to it.

**Comment by mugling** [comment]
> Please allow other devs to weigh in and stop being heavy handed about this.

You've just hurled a load of abuse at someone and you have form that (#16738)

> This is a crowd funded open source game

Neither myself nor the other active developers have taken anyone's money. Although we put a lot of effort into development we don't owe you anything.

> and I run a mod that caters to a specific crowd.

You are releasing both with the project and separately. It is not our responsibility to maintain compatibility between the two variants. Indeed such an approach is actively discouraged. You might want to look at how much better blaze conducted themself.

> This mod does not need to address points that are entirely irrelevant to it.

It is relevant and you will need to address it.

**Comment by pisskop** [comment]
The mod is SAT, and tested.  It is ready to be merged.

I will not respond further to you, please stop clogging the thread.

**Comment by mugling** [comment]
Add link to #18358 which contains comments from more contributors

**Comment by pisskop** [comment]
*until we have confirmation either way*

**Comment by mugling** [comment]
This is going absolutely nowhere:

1. Two contributors raised the issue of vermin in your first PR #18358
2. I referred you to #15863 but you ignored that and opened #18422
3. The content was then split and I later merged the bulk of it
4. You open this PR and declare #15863 irrelevant
5. When asked you become abusive and similar to #16738 posts are edited
6. You post a lot of questions, I answer them, including quotes from a lot of different authors
7. You state your not going to answer any further questions

Given the enormous amount of words written on this subject over an extended period of time it is perhaps telling that not one comment from anyone is in favor of this content.

This isn't ready to merge and won't be until you address #15863. You can address each points in a comment to this PR which can then be re-opened.

**Comment by pisskop** [comment]
Nope.

This is flagrant abuse

**Comment by mugling** [comment]
> This is flagrant abuse

This is now your third PR on this subject. Nobody else agreed with you in any of the others. You still have an option open to you (#15863). There isn't much much you could reasonably expect.

**Comment by pisskop** [comment]
You have drowned out all chances for discussion 3 times.

you have ignored my statements on the matter and then brushed them aside after drowning out all plausible discussion on the matter.  This is again, flagrant bias and abuse, and my work on the mod in this git will not continue under your eye.

**Comment by pisskop** [comment]
You have railroaded me with syntax requirements, then cite my inability to produce instantly acceptable commits after you ensured that #18481 went was produced after demanding I seperate this pr into 2 smaller ones and commit the less contested one first.

You have closed multiple prs on this subject, denying anyone else a chance to commit.

You have refused to provide evidence that this pr is adding anything similar to vermin, and have taken illukuns quote about not adding a mod for vermin out of the context (replacing coregame vermine with a dedicated mod) out of context to suit your needs.

you have systematically stuck your hand into this mod, by trying to force a name change, by forcing syntax changes, by dictating what content can go into it.

You have drowned out any chance for public discussion from other devs by spamming this thread after being asked to stop.

**Comment by mugling** [comment]
> You have closed multiple prs on this subject, denying anyone else a chance to commit.

As soon as you opened the first PR comments started to appear pointing out the flaw.

> by trying to force a name change

That was proposed by @Cyrano7. In response you had a tantrum and fought absolutely everyone then finally edited your comments.

> by dictating what content can go into it.

Please follow the checklist in #15863

**Comment by narc0tiq** [comment]
> drowned out any chance for public discussion

Personally, I don't tend to want to participate in a flame war (and I just maintain the build system, anyway), but since this is blowing up my inbox now...

I'll just weigh in with a small note: the biggest point I took away from the discussion on vermin was "they break the normal rules for creatures without giving anything in exchange". Assuming the checklist in [this early comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/18553#issuecomment-250008582) is truthful (and I see no reason why it wouldn't be), these do not appear to have the same shortcomings, thus addressing the points in #15863.

To wit:
- they are real creatures of reasonable size, therefore colliding with vehicles and covering them in blood is normal (as it is for collisions with dogs/cats/giant flies);
- No idea about "alarming messages", but see above for reasonability;
- "[Can] all be struck down with melee or a sling", so their becoming hostile and interrupty is resolvable (though potentially irritating -- YMMV);
- No special case for movement code;
- Reasonable size (as per point 1) makes them reasonable to take hits from ranged attacks;
- Same makes them acceptable for critter radar and target selection;
- Tiles are not hidden, they are occupied; see above re: reasonable size; additionally, "[they do not have] symbols that blend into the road/dirt", per the afore-mentioned comment;
- CPU time, memory, etc., is true for any added creature -- this was only a concern originally because of the other problems listed.

---

I'm not a fan of the aggressive responses I've seen from @pisskop (meaning no offense -- it's just how they read to me), but he's being perfectly truthful. These are not vermin, they do address the oft-repeated checklist, and ultimately are desirable within their context (which is PK's mod).

At the same time, please recall that the maintainers (aka "devs"), including @mugling, have the rights and responsibilities to control what goes into the CleverRaven/Cataclysm-DDA repository, including mods that are published as part of the released packages (stable and experimental alike). 

Having reached an inability to come to an agreement, I submit that the discussion between @mugling and @pisskop should have ended there ([around here-ish](https://github.com/CleverRaven/Cataclysm-DDA/pull/18553#issuecomment-250535344)). I won't comment on closing the PR, though I will mention that any maintainer can both comment on and reopen a closed PR, so its state does not prevent an interested party from participating. Finding interested parties is left as an exercise to the reader.

**Comment by pisskop** [comment]
Denying this pr was never about it not meeting any requirement or another.

I have repeatedly explained why this checklist isnt something that would hold back this pr; or the others.

this pr was closed because he never bothered to properly examine the materials or to provide any support for his claims.  Once it was clear he lacked a footing he began attacking my informal style of creating new code.

**Comment by illi-kun** [comment]
@pisskop, first of all, I want to say I respect your efforts to create and support your mod, and I know many users who use it.

I understand why the current conflict happens – @mugling, as dev of C:DDA, is responsible for quality of the code and content which is merged in the repo (and he is authorized to make decisions about acceptation or refusing of proposed PRs). From other side, you, as author of the mod, definitely should be the one who decides how to do your own work. The solution of this conflict is obvious for me: your mod deserve its own (dedicated) repo.

Creating a new repo for your mod allows you to be the real owner of your mod; you will able to make decisions how your project should evolve, what name of the mod should you use, should you use any tools for organization of content or not – all of these thing will be up to you completely. Also, creating a repo is much better than just a forum version of your mod, because in case of repo, someone will able to propose some changes to your code via PRs & issues (and you will decide if you need these changes).

BTW, the same thing is also applicable to other big mods, like Arcana mod or Blazemod.

Of course, separating of mods from core content will require more actions from users to get everything work but here we can think about using of CDDA Game Launcher for downloading actual versions of mods before each run.

**Comment by pisskop** [comment]
I am not taking my toys and going home, as it were.

This community provides  far more content than I will ever be able to produce alone, and its not in my interests to try to split the community like that.

It is in my interests to get my own content merged to improve the mod.


Looking at the pr as it stands; I am no longer the only one saying that the creatures meet the criteria set forth by mugling.  Im more than sure I could get a few more to.  Why wouldnt he have produced a new list or had something more to say than ignoring the handful of times I said so or now another mirroring my own opinions on the matter.

**Comment by mugling** [comment]
> I am not taking my toys and going home, as it were.

Your comments here, and elsewhere, suggest otherwise. If you want to take your toys and leave that's fine but be careful you don't suggest things you actually don't want to later accept.

> This community provides far more content than I will ever be able to produce alone, and its not in my interests to try to split the community like that.

It's ridiculous to suggest that we would fork over the (non)-inclusion of your mod content. Don't elevate the importance of either yourself or your mod.

> It is in my interests to get my own content merged to improve the mod.

It's definitely in your interests as you get a lot of assistance and bug fixes and we make efforts to keep your mod up to date. It's getting harder to see the upside for the developers or other contributors. A lot of time is spend dealing with you and a fair proportion is currently squandered.

> my informal style of creating new code.

You weren't tracking master or testing your PR's. Those are the rules in almost every open source project and everyone else keeps to them. Your aggressive approach has been repeated on a number of previous occasions and is unwelcome. You have been criticised for that both here and elsewhere. As @illi-kun has patiently pointed out if you don't like how we operate you can simply maintain your own source tree - we are neither required nor intending to bend to your wishes.

> Looking at the pr as it stands

Given you believe any outcome other than agreeing with you represents an abuse of our positions it's difficult to see your PR's as anything other than a time sink. We can't hope to convince you of anything and you just become increasingly aggressive as you don't get your way. As a result the most efficient option would probably be just to ignore you.

Some of your monsters fulfill the criteria, some do not. You now need to work through the checklist for each. Your starting point is that this PR has been rejected and you've said you don't want to contribute any more. Do your best to civilly convince the developers otherwise or alternatively take your mod to your own tree and then do as you please without any oversight.

**Comment by pisskop** [comment]
> Given you believe any outcome other than agreeing with you represents an abuse of our positions it's difficult to see your PR's as anything other than a time sink. We can't hope to convince you of anything and you just become increasingly aggressive as you don't get your way. As a result the most efficient option would probably be just to ignore you.

This conflict was caused in large part by your own refusal to explain your own stance and indeed to update it.  If there are 'some' creatures that meet the reqs now there were 'some' that did so before, and you needed to speak up about what you desired before.  If your fellow devs do not wish to speak up about it Im perfectly fine pointing it out for them.  Your unwillingness to refine your opinions or even to glance at an OP in a pr is what sparked a large part of this and is what is inappropriate.

My own aggression has certainly come into play here.  There was little in the way of 'bug-fixes' being offered here.  None that affected gameplay.  Syntax help is always appreciated, since the linter came.

**Comment by mugling** [comment]
This PR began as a 1000 line untested PR that contained a huge amount of unrelated changes. I've done a lot to try and clean it up and indeed some has been merged. It is not my role to wade through every last line of it fighting you as I go.

You've repeatedly stated elsewhere that you're stopping support for the mod as distributed with the game and given you've had similar confrontations with other developer I think it would be best if you went with your plan to support this via the forums.

**Comment by pisskop** [comment]
I will do so, however I don't consider git an inaccessible option for us in the future.

**Pull request closed without merging**
