### PR TITLE
Updated core military vehicles and motorcycles

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
As mugling said, military seats are pointless now; they have been removed. 

Added camera controls (#18995) and mufflers to many.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
I might add ammo_rare and ammo_milspec spawns to the vehicles.

**Comment by mugling** [comment]
I'd avoid `ammo_rare` and just stick with `ammo_milspec`

**Comment by mugling** [comment]
We should aim to deprecate military seat in the same PR. You might want to hunt around in `savegame_json.cpp` for the code that migrates vehicle tanks and add en entry for the seat there. You also need to drop the part definition

**Comment by BorkBorkGoesTheCode** [comment]
I have noticed that most of the vehicles ingame lack mufflers. Why is that?

**Comment by BorkBorkGoesTheCode** [comment]
I have added seat_nocargo to the list by copying the laser entry: will the "none" entry at the end cause issues?

**Comment by mugling** [comment]
No, the second field sets the ammo so that should be fine

**Comment by Rivet-the-Zombie** [comment]
>I have noticed that most of the vehicles ingame lack mufflers. Why is that?

Likely just an oversight.

**Comment by BorkBorkGoesTheCode** [comment]
I'll be adding spawns to the other APCs soon. If I don't post in an hour, I'm done.

**Comment by BorkBorkGoesTheCode** [comment]
I'll add a military tanker to a later PR.

**Comment by BorkBorkGoesTheCode** [comment]
Ready.

**Comment by mugling** [comment]
Multiple errors on load of the form:
`unknown vehicle part seat_nocargo in tank_light`

**Comment by mugling** [comment]
You need to update everything in `data/mods/Tanks/vehicles.json`

**Comment by BorkBorkGoesTheCode** [comment]
Sorry, committed to wrong PR. Rebasing out.

**Comment by BorkBorkGoesTheCode** [comment]
seat_nocargo is removed in #19185

**Comment by BorkBorkGoesTheCode** [comment]
This is dependent on the removal of several CARGO entries from turrets in blazemod/blaze_override.json

**Comment by BorkBorkGoesTheCode** [comment]
This PR depends on #19185

**Comment by mugling** [comment]
JSON load errors:

```
Checking mod Generic Guns [generic_guns]
src/veh_type.cpp:664 [static void vehicle_prototype::finalize()] init_vehicles: 'Armored Personnel Carrier' part 'mounted_browning'(111) can't be installed to 3,1
src/veh_type.cpp:664 [static void vehicle_prototype::finalize()] init_vehicles: 'Mechanized Infantry Carrier' part 'seat'(114) can't be installed to 3,1
src/veh_type.cpp:664 [static void vehicle_prototype::finalize()] init_vehicles: 'Mechanized Infantry Carrier' part 'seatbelt_heavyduty'(114) can't be installed to 3,1
```

Not sure if it has anything to do with generic guns or not.

**Pull request merged**
