### PR TITLE
Added MF_RESPECT_MON_AVOID, and MON_AVOID/TFLAG_MON_AVOID

### PR DESCRIPTION
**Pull request by sired22**
I had an idea for a mod i was unable to implement with the current flags, after poking around i found that number of edits to implement the needed flags was actually quite small. I needed to create a barrier/shield/fake wall but only against a specific set of monsters. 

MF_RESPECT_MON_AVOID is a new tagg added to mtype.h. 
It works with the new terrian flag MON_AVOID/TFLAG_MON_AVOID.

it is implemented in monmove.cpp at monster::can_move_to
it is a simple check that if the monster has the tag, and if the terrian has the tag, it returns false denying the move.

because this may be checked a lot TFLAG_MON_AVOID was also added to ter_bitflags_map

if( has_flag( MF_RESPECT_MON_AVOID ) && g->m.has_flag( "MON_AVOID", p ) ) {
        return false;
    }

### CODE REVIEW

**Comment by kevingranade** [comment]
The idea here is that the mod will override the terrain to add the flag?
My only concern here is that this would need to be repeated for any new
category of monster with different avoidance rules.
I'd prefer for the monster to supply a list of terrains that it abouts to
the pathing code, not sure how simple that would be.

**Comment by Coolthulhu** [comment]
Tying it to pathfinding code would be pretty elegant, though it would decrease efficiency of pathfinding code slightly (currently pathfinding has a special case for the non-special terrain and each weird terrain would need to be outside that special case).

Where possible, simple monster pathing and actual pathfinding should reuse the same structures.

**Comment by sired22** [comment]
the idea for usage for example would be me making a new mod. my mod adds a new creature and a new church type place. i can add the MF_RESPECT_MON_AVOID flag to my monster. then in the new church type place i can add MON_AVOID.

because only my new creature has the MF_RESPECT_MON_AVOID flag only they will be unable to enter.
and all other monsters will be able to walk in.

if( has_flag( MF_RESPECT_MON_AVOID ) && g->m.has_flag( "MON_AVOID", p ) ) {
return false;
}

using these two creates a more targeted approach then MF_AVOID_DANGER_2. i was originally going to make use of MF_AVOID_DANGER_2 but a lot of monsters and creatures use this but i needed a more targeted approach.  i wanted only very specific monsters to make use of it.

> I'd prefer for the monster to supply a list of terrains that it about to the patching code, not sure how simple that would be.

i chose this method because it does the job with the least amount of impact. if lots of people begin using it for mods then yes, each monster type with their own list to avoid would make more sense, but checking each tile against a list of tiles not to enter would be more costly as well.

**Comment by sired22** [comment]
@Coolthulhu yes i added the if check to the pathfinding code in src/monmove.cpp, i looked for a already existing way to get them to avoid a tile but was unable to find an existing method/structure where you can specify a flag to avoid.

Unable to find a better method i added the check near the top, next to the other specific avoidance code so it will return the quickest, using the other avoidance code as a templet for my check.

frankly it seems kind of rude of me to come out of the blue to suggest a change like this just because i want to make use of it (although others can use it too), so please pardon any perceived rudeness on my part.

if you know of a better alternative/suggestion then please, I'm all ears and very willing to listen to advice.

**Comment by sired22** [comment]
this can be closed, i decided to delete everything and try again in code blocks making sure i follow all guides better as from the details it would seem astyle-check is failing.

**Comment by illi-kun** [comment]
FIY, you are able to close your PRs by yourself.

**Pull request closed without merging**
