### PR TITLE
[EOC] Port some functions to item talker

### PR DESCRIPTION
**Pull request by lispcoc**
#### Summary
Features "[EOC] Port some functions to item talker"

#### Purpose of change
EOC is useful, but there are only few functions to operate on items.

#### Describe the solution
Port some functions to item talker and make u_run_inv_eocs more highly functional.

The new u_run_inv_eocs is not compatible with the previous one, but no one is using it yet so it won't affect anyone. In the future I may add the ability to select items from the inventory menu.

```
      {
        "u_run_inv_eocs": "all",
        "search_data": [ {
          "id": "sword_wood",
          "material": "wood",
          "category": "weapons",
          "flags": [ "BELT_CLIP" ],
          "worn_only": false,
          "wielded_only": true
        } ],
        "true_eocs": [ "TRUE_EOC" ],
        "false_eocs": [ "FALSE_EOC" ]
      }
```

- [x] u/npc_teleport - Transport items to any location on map.
- [x] u/npc_activate - u/npc activate item(item must be beta talker)
- [x] u/npc_set_flag - Add flag to items (e.g. FILTHY)
- [x] u/npc_unset_flag - Remove flag from items
- [x] (Math) hp/hp_max - Return item damage. The damage the current item is receiving is treated as a decrease in HP.
- [x] add test
- [x] add document
- [x] enhancement of u_run_inv_eocs

### CODE REVIEW

**Comment by GuardianDll** [comment]
The issue i see with item targeted EoC is there is no good way to find what exact item one would like to interact with. I recall Storm would like to add an ability for teleporter to teleport the gun from the enemy away, but was not able to target "any item u/npc is currently holding". Is it possible to resolve it in some way?

**Comment by lispcoc** [comment]
> The issue i see with item targeted EoC is there is no good way to find what exact item one would like to interact with. I recall Storm would like to add an ability for teleporter to teleport the gun from the enemy away, but was not able to target "any item u/npc is currently holding". Is it possible to resolve it in some way, like new effect that return item of specific properties as context variable?

I added interface to interact with items in inventory #68244. 
If you just want to achieve making item u/npc is currently holding on hand target, I can do it by just modifying this function a little.
If you want to specify items more flexibly, I need to consider a new interface. What kind of JSON format would be easy to use?

**Comment by GuardianDll** [comment]
Okay, so i tested how `u_run_inv_eocs` works now, and have some thoughts: overall i think it would be that type of EoC, that is very depends on different use cases we could brainstorm to make, so i probably should summon someone who could find this EoC useful: @Standing-Storm, @Maleclypse and (sorry to disrupt your rest) @bombasticSlacks, but here is probaby the most generic use cases i can think about:

Main part i see the specific array "search_data", that allow to narrow the list of items returned by effect. Lack of any data return any item npc/player has currently. Within search_data are fields:
- `flag` - pick only items that have flag or flags
- `category` - return only items of specific category 
- `id` - return only item or items of specific id, if presented
- `worn_only` - boolean, return only items that are worn
- `wielded_only` - boolean, return only items that are wielded 
- Maybe more like `material` or some specific way to check item's stats would be nice, like mutators do, but i don't know is it possible to make it, and would it be flexible enough 

And outside of `search_data` would be an additional, mandatory field `pick`, that respond which item would be picked in the end. Could be `random` (from all items found by effect, random one would be picked), `all` (all would be picked simultaneously), `manual` (player would be able to pick one of all returned), `manual_mult` (player would be able to pick multiple of all returned)

Honestly it sound like a giant amount of work, so it would be okay if you just reject it

**Comment by lispcoc** [comment]
I may end up implementing it in a separate PR, but any ideas regarding EOC will help with development. It would be helpful if I could get various opinions.

**Comment by Standing-Storm** [comment]
It's Erev Yom Kippur so this is just some quick thoughts on Guardian's post:

The two immediate use cases I can think I'd want are the previously-mentioned "wielded_only" (as mentioned, for a Teleporter power that lets you teleport away the target's weapon) and "material" (I had an idea in #68207 to give bonus damage when using wooden weapons but it's currently not possible).

There is currently a "u_has_wielded_with_flag" that might be extendable for the flags option

**Comment by Maleclypse** [comment]
Could this be used to jsonize the kaluptic psychosis weapons dialogues and the mp3 players randomized music types?

**Comment by lispcoc** [comment]
> Could this be used to jsonize the kaluptic psychosis weapons dialogues and the mp3 players randomized music types?

I think the former is probably possible, the latter needs to add new music-related functions.

**Comment by GuardianDll** [comment]
i ran through all our effects and thought what purpose they may have from item perspective:
[u_add_trait](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_add_traitnpc_add_trait), [u_lose_trait](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_lose_traitnpc_lose_trait) - adding custom flag (like applying FILTHY on clothes), or removing one
[u_activate_trait](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_activate_traitnpc_activate_trait) - may be possible to use to force activate item, like grenades
[u_add_var](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_add_varnpc_add_var), [u_lose_var](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_lose_varnpc_lose_var), [u_adjust_var](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_adjust_varnpc_adjust_var) - it [already works with items](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/tool/science.json#L1396), so probably not worth mentioning
run_eoc_with - probably must have, when you can find a specific item in player's inventory, and remember it for the future as context var

**Comment by lispcoc** [comment]
Hmm, I dont know why Basic Build fails.

> [u_add_trait](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_add_traitnpc_add_trait), [u_lose_trait](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_lose_traitnpc_lose_trait) - adding custom flag (like applying FILTHY on clothes), or removing one
> [u_activate_trait](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_activate_traitnpc_activate_trait) - may be possible to use to force activate item, like grenades

I agree that I would like to have functions for activating flags and items. 
It is important not to increase the number of functions, but it might cause confusion if the function  has a feature that is difficult to associate with the function name. 
I think it would be better to add functions with names like "u_add_flag", "u_invoke". I would like to hear other developer's opinions.

**Comment by GuardianDll** [comment]
Make sense for me, just didn't know what would be better

**Comment by lispcoc** [comment]
There are many other things I would like to do, but I would like to implement the following functions and close this RP.
- u_add/lose_flag - adding custom flag (like applying FILTHY on clothes), or removing one
- u_activate - force activate item
- u_has_flag - Existing function. Port to items.

In the future, it may be necessary to integrate these functions with u_add_trait, u_activate_trait, etc., but I don't think it's necessary at the moment.

**Comment by lispcoc** [comment]
I think it's ready for review.
I don't know why the Basic Build and Test is failing, but I'll try to run it again later by push.

**Pull request merged**
