### PR TITLE
Warn when your name includes bad chars on creating character.

### LINKED ISSUE #71453: Can't save the game when character name has special characters in it
### Describe the bug

The game fails so save when you have characters in your name that windows doesn't allow in filenames. This only started happening after the new achievement saving system. Pretty sure this is related to #71327 trying to save a file with your player characters name as part of the filename.

### Attach save file

N/A

### Steps to reproduce

1.Start a new game and include characters windows doesn't allow in filenames ( / \ : ? * " < > |  ) in your player's name
2.Try to quicksave the game

### Expected behavior

The game should be able to save

### Screenshots

CDDAsavefailure

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: f2cdb18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rtxyd**
#### Summary
Features "Warn you when your character name contains bad chars"

#### Purpose of change

in order to fix https://github.com/CleverRaven/Cataclysm-DDA/issues/71453
but I think the name can be chosen by player, so this is a soft fix, it will warn you, not forbid you to your special name.

#### Describe the solution

Add a warning on creating character, warn you that you have invalid name with char: %c, 
After this warn, a original warn "Are you SURE" will popup. So basicly, this case will make 2 times of check to ensure that you really want this name. This is an alternative solution, pair with #71464. 

#### Testing

create a new character with special chars like / \ : ? * " < > | "
and test y/n, see if the game do intended behavior.
QQ录屏20240204102655 mp4_20240204_105402

#### Additional context

I'd like other opinions about the PR, need your correction if something wrong.

### CODE REVIEW

**Comment by Qrox** [comment]
Just use base64 encoded filenames. You can create a new file that contains the base64 encoding and filtered character name if you want to be able to search for your character files.

**Comment by rtxyd** [comment]
> Just use base64 encoded filenames. You can create a new file that contains the base64 encoding and filtered character name if you want to be able to search for your character files.
> 
> For example if your character name is `你好` which has base64-encoding `#5L2g5aW9`, create an empty file with the name `#5L2g5aW9.你好` when saving the character and achievements, so when you search for `你好` you find this file and then you can search for `#5L2g5aW9` to get all your character files.

There is obviously this solution, but it's another convert, for user interface, it's not a good idea. Though for programmer, it pay less effort.

**Comment by Qrox** [comment]
Actually please hold off any new changes until I review this and #71327 more. It's more complex than I had expected, and we probably don't need base64 encoding for achievement files, but I can't say for sure right now.

**Comment by rtxyd** [comment]
> Actually please hold off any new changes until I review your PRs and #71327 more. It's more complex than I had expected, and we probably don't need base64 encoding for achievement files, but I can't say for sure right now.

hmm, yes. If I do something wrong, please tell me, I am a beginner of coding so I can't tell if I broke some construct.

**Comment by rtxyd** [comment]
@Qrox If these contents are not considered by now, pls tell me so I can close them or transform them to draft. Followed days, there will be a very long time untill I can use computer again.

**Comment by Qrox** [comment]
@rtxyd sorry for the delay, please see my reviews in #71464.

**Review by Brambor — CHANGES_REQUESTED** [review]
Look into "Files changed". There is an error on this (4166) line.

You are making a newline `\n` after spaces. There is no reason for spaces before newline.

At the same time. Bit later, Cataclysm requires two spaces after each sentence end (`.`).

**Comment by rtxyd** [comment]
> At the same time. Bit later, Cataclysm requires two spaces after each sentence end (`.`).

Thank you for your correction. But does that mean I need print like "  Hello.  Hello.  "
And unfortunately, I have little confidence in this PR, and transformed it to draft now, also I will leave computer for a long time, so this PR may be there for a while then.

**Comment by Brambor** [comment]
> Thank you for your correction. But does that mean I need print like " Hello. Hello. "

We didn't understand each other.

Look at this code:
https://github.com/CleverRaven/Cataclysm-DDA/blob/72a339f128bd3045129f64268c12e69fcd46410e/src/newcharacter.cpp#L1081-L1086

There are two spaces after a sentence: `mode.  Point`
And whenever there is newline, there are no spaces after it: `pools.\n`, not `pools.\n  `

**Comment by rtxyd** [comment]
> But I can see you already got that now!

Actually just add two spaces after this .  .  .  .  .  .  .  .  .  .  .  .  .  .  .

**Comment by Brambor** [comment]
> Can I ask you a astyle cmd code? I use astyle but the format seems sometimes go right but sometimes not.

I thought it was just `make astyle`, but I can see now it does not fix issues inside strings.

Do you know about our Discord? People there are very helpful.
https://discord.com/invite/jFEc7Yp

**Pull request closed without merging**
