### PR TITLE
Updated items description to reflect added ability to repair paper

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah, so that's now a thing. Nifty.

That reminds we, what to do about copper items...

**Comment by Night-Pryanik** [comment]
One possible way - write some metal-processing plant and make all metals (zinc, copper, aluminum etc) spawn there.
Second - spawn them in mines, as Zireal suggested.

**Comment by chaosvolt** [comment]
Huehuehue. Spawning metal, or ore at least, in mines would be interesting.

But i mean, what material should we use for copper repairs? We'd need to either make the repair function use multiples of the copper item (as it's a tiny 200-stack ammo item), or add am ingot equivalent.

**Comment by Rivet-the-Zombie** [comment]
>But I mean, what material should we use for copper repairs?

Most forms of solder work great on copper, but it *also* works great on most metals.

**Comment by chaosvolt** [comment]
Hmm. Maybe, though solder and tin and likewise high-stack items, same as copper.

My point being, we don't have an item like scrap metal that would translate into a basic, 1-volume item. Though I guess having a little copper go a long way also works. >_>

**Comment by Rivet-the-Zombie** [comment]
So make a 'copper scrap' item?

**Comment by chaosvolt** [comment]
Might work I guess, though unsure of the best way to implement it.

**Pull request merged**
