### PR TITLE
Hitbutton_iso tileset

### PR DESCRIPTION
**Pull request by SimonPurdie**
This is an isometric tileset created from scratch, with some inspiration drawn from the excellent Retrodays tileset.

It's drawn at 16x20 (with 16x7 floor tiles), then enlarged to 32x40. This means that the default size shouldn't strain your eyes, but you can (Z)oom out to see a very large area without losing any visual detail.

Here's a few shots of it in action:
image
Facing off with a shocker zombie and a bear on a farm.

image
Pulling a sick maneuver on my superbike in a mall parking lot.

image
This "kill spiders with fire" plan may not have been completely thought through.

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Very nice! I really like what this looks like!

**Comment by kevingranade** [comment]
Wow that looks amazing, will merge soon.

**Comment by Chezzo** [comment]
SICK DUDE! You gotta post this in the forums.

**Comment by sparr** [comment]
not sure how I feel about implementing a "default zoom" by pixel doubling. if you really want the default for this tileset to include a 2x zoom-in, maybe we should just add a default zoom level option to tilesets?

(everything else is amazing)

**Comment by Lain-** [comment]
Beautiful! Hat off to you, sir.

**Comment by hitbutton** [comment]
> maybe we should just add a default zoom level option to tilesets?

That would make a lot of sense. Depending on implementation It could also allow Retrodays10 and 20 to be folded into a single set.

**Comment by hitbutton** [comment]
> SICK DUDE! You gotta post this in the forums.

Thanks! :) But I don't feel the isometric feature is something that's quite ready for public consumption yet, and wouldn't recommend people actually play the game using it until a few creases are ironed out, and features added. I wouldn't want people to have a negative experience with it and write it off before it's fully functional.

**Pull request merged**
