### PR TITLE
Cooked Acorns calorie

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Balance "Cooked Acorns get same calorie value as Acorns instead of 8 times more"```

#### Purpose of change

Cooked acorns recipe use 1 charge of acorns but has 456 ca instead of 114 ca and two portions.

#### Describe the solution

This changes the calorie value to 114 ca and the charges to 1.
#### Additional context

[Forum discussion](https://discourse.cataclysmdda.org/t/acorns-the-super-food/19404/32) that brought the problem up.

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/acorns-the-super-food/19404/34

**Comment by anothersimulacrum** [comment]
There's no need to change the calories manually, you can just remove the `"NUTRIENT_OVERRIDE"` flag.

**Comment by Fris0uman** [comment]
So I remove the calorie and the flag entry ?

**Comment by anothersimulacrum** [comment]
It still needs the calorie entry, but if you remove the flag, it will inherit it's calorie value from what it's made from.

**Comment by Fris0uman** [comment]
Ok done, I removed the flag.

**Comment by Mecares** [comment]
The weight needs to be fixed as well 30g of Acorns should not turn into 118g without adding anything to them, also acorn meal has according to a quick google search around 500 kcal per 100g and not around 100.

**Comment by Fris0uman** [comment]
Ok let's go back to the forum discussion because my research did not deliver the same results.

**Pull request merged**
