### PR TITLE
[WIP] Trying to debug CMake test hangs

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: None

#### Purpose of change
A branch for testing the CMake tests and trying to figure out why they are hanging.

Will involve various temporary commits.

### CODE REVIEW

**Comment by reinerh** [comment]
The test hangs seem to be not only related to cmake.
They also happen on Debian build servers, and they are building with make:
https://buildd.debian.org/status/logs.php?pkg=cataclysm-dda&ver=0.C%2Bgit20181202.05d851e-2

**Comment by jbytheway** [comment]
I'm fairly sure this was because the tests are just very slow (sometimes taking more than the 10 minutes Travis uses as a timeout when there's no output).  There are a number of contributing factors:
* CMake was using a debug build
* CMake build wasn't using -Og
* The _GLIBCXX_DEBUG overhead can be considerable.
I've found various pieces of low-hanging fruit in terms of debug build performance and will be making some PRs soon.

The Debian builder timeout is 150 minutes, not 10.  Moreover, the output I see in those logs doesn't even include the message about the tests starting, so the problem must be in the pre-test init phase.  I don't think it's the same issue.

**Comment by reinerh** [comment]
I just reproduced it on my system. It seems to be related to -DBACKTRACE.
With strace I can see that it forks+execs addr2line and nm in a loop:
```
strace -e trace=fork -e trace=clone -e trace=execve -ff -p 16948
strace: Process 16948 attached
strace: [ Process PID=16948 runs in 32 bit mode. ]
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27679, si_uid=1234, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 27683 attached
[pid 27683] execve("/bin/sh", ["sh", "-c", "addr2line -i -e /lib/i386-linux-"...], 0xfffe2354 /* 99 vars */) = 0
strace: Process 27684 attached
[pid 27684] execve("/usr/bin/addr2line", ["addr2line", "-i", "-e", "/lib/i386-linux-gnu/libc.so.6", "-f", "-C", "0x1ab41"], 0x571d2eac /* 99 vars */) = 0
[pid 27684] +++ exited with 0 +++
[pid 27683] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27684, si_uid=1234, si_status=0, si_utime=0, si_stime=0} ---
[pid 27683] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27683, si_uid=1234, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 27685 attached
[pid 27685] execve("/bin/sh", ["sh", "-c", "addr2line -i -e tests/cata_test "...], 0xfffe2354 /* 99 vars */) = 0
strace: Process 27686 attached
[pid 27686] execve("/usr/bin/addr2line", ["addr2line", "-i", "-e", "tests/cata_test", "-f", "-C", "0x2b7e71"], 0x57cf9eb4 /* 99 vars */) = 0
[pid 27686] +++ exited with 0 +++
[pid 27685] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27686, si_uid=1234, si_status=0, si_utime=4, si_stime=13} ---
[pid 27685] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27685, si_uid=1234, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 27687 attached
[pid 27687] execve("/bin/sh", ["sh", "-c", "nm tests/cata_test 2>&1"], 0xfffe2354 /* 99 vars */) = 0
strace: Process 27688 attached
[pid 27688] execve("/usr/bin/nm", ["nm", "tests/cata_test"], 0x5835ff54 /* 99 vars */) = 0
[pid 27688] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=27688, si_uid=1234} ---
[pid 27688] +++ killed by SIGPIPE +++
[pid 27687] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=27688, si_uid=1234, si_status=SIGPIPE, si_utime=20, si_stime=0} ---
[pid 27687] +++ exited with 141 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27687, si_uid=1234, si_status=141, si_utime=0, si_stime=0} ---
```

And for some of the Debian builders the problem happened at a later point (not at the beginning).

**Comment by jbytheway** [comment]
I've also seen it in another place now where it doesn't make sense for it to be just slowness.  And it makes sense that it would be related to the BACKTRACE code, since that was recently enabled by default.

When you say "in a loop" do you mean an infinite loop?

**Comment by reinerh** [comment]
@jbytheway Just opened a bug with a bit more information on the hang that I observed: #26941.
Yes, I mean an infinite loop. But the issue does not seem to be related to BACKTRACE, something else is run in a loop during initialization, which again puts something in the debug log, which causes a backtrace (and therefore addr2line and nm to be executed).

**Comment by jbytheway** [comment]
Now that #27379 is merged, I can close this.

**Pull request closed without merging**
