### PR TITLE
Set turret ammo and provide defaults

### PR DESCRIPTION
**Pull request by mugling**
Usability and balance fixes
- Turrets drop casings and linkages to associated `CARGO` part if possible
- Ammunition belts are now comprised of military grade ammo
- Ammo belts are now better named
- Can specify vehicle turret starting `ammo_types` and `ammo_qty`
- Turrets can be installed at lower `mechanics` but now have ancillary skill `requirements`

### CODE REVIEW

**Comment by mugling** [comment]
Ready for now subject to review

**Comment by mugling** [comment]
Marked [CR] as the non-balance changes have been factored out as separate PR

**Comment by Coolthulhu** [comment]
I don't see a good reason for why would mounting miniguns require rifle skill.

The skill requirements for mounting non-energy weapons are also rather huge. They aren't all that useful due to their high ammo consumption.

**Comment by mugling** [comment]
> I don't see a good reason for why would mounting miniguns require rifle skill.

To set the sights? Possibly marksmanship instead?

**Comment by Coolthulhu** [comment]
Either this PR or the ammo belt one broke ammo spawns on vehicles.

Also, while you're fixing turrets, it would be a good idea to make them visible from the inside. They probably have a port or mount or whatever that is visible inside.

**Comment by Coolthulhu** [comment]
Couldn't get even a single humvee with ammo on turret to spawn.

**Comment by mugling** [comment]
Is it just the humvee?

**Comment by Coolthulhu** [comment]
Nope, APCs and infantry carriers are similarly affected.

**Comment by mugling** [comment]
I'll add some debugmsg

**Comment by mugling** [comment]
Fixed and rebased

**Comment by Coolthulhu** [comment]
Spams debugsmgs.

**Comment by mugling** [comment]
> Spams debugsmgs.

Which ones?

**Comment by Coolthulhu** [comment]
init_vehicles: non-turret part_name with ammo in vehicle_name

**Comment by mugling** [comment]
Fixed

**Comment by Coolthulhu** [comment]
Now it spawns tons of ammo

**Comment by mugling** [comment]
Fixes #17967. Ready

**Comment by Coolthulhu** [comment]
I think it's this one: I'm getting debugmsgs with Generic Guns about unused m14 mags.

**Comment by mugling** [comment]
I'll take a look

**Comment by mugling** [comment]
Not this one

**Pull request merged**
