### PR TITLE
Adds Dark Skies Above, Part 1 [MOD]

### PR DESCRIPTION
**Pull request by ephemeralstoryteller**
#### Summary
```SUMMARY: Mods "Initial commit for partial conversion mod 'Dark Skies Above'."```

#### Purpose of change
Adds a mod based around an alien invasion rather than a zombie apocalypse. Takes inspiration from sources like Half Life 2, XCOM 2, Colony, and more to present a setting based around surviving and resisting an alien occupation force. The base setting is comparatively less sci-fi than vanilla, in return for reverse engineering alien tech to achieve a similar endgame.

#### Describe the solution
For sanity, only files included in this first PR are: modinfo.json and obseletes mod, factions.json, species.json, harvest.json, and the readme.md.

#### Describe alternatives you've considered
Adding this as a third party mod. While perhaps less daunting, it's not in my interest as that sees both less exposure as well as less contribution to the project. Plus, I think it's a nice way to show people interested in contributing that these sorts of mods aren't out of reach.

#### Testing
 Played a game or two of it on a clean install of C:DDA to simulate an 'out of the box' experience. Mod works fine, though it is admittedly a bit harder than base game and requires a period of innawoods play.

#### Additional context
- Bug: Despite my best efforts, sometimes the vanilla evac shelter will spawn with vanilla graffiti and a computer that attempts to route to an evac center that doesn't currently exist in-game. It will eventually as part of a questline for finding the resistance.

DKS1
DKS2
DKS3
DKS4

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
You may want to consider adding this adding this mod bit by bit and marking it obsolete while doing so.
A 10 thousand line diff is a bit intimidating.

**Comment by ephemeralstoryteller** [comment]
Uhh good point, apologies. ^^;; What's the best way to do that?

**Comment by anothersimulacrum** [comment]
Split up files by what they do and or size and PR each individually, starting with the `modinfo.json`, of course.

**Comment by ephemeralstoryteller** [comment]
Sorry for all the questions I'll admit that I'm still getting the hang of github! What's the preferred way to get rid of files from a PR?

**Comment by ephemeralstoryteller** [comment]
Thanks to anothersimulacrum for helping me with this, the rest of the files will be released in installments soon!

**Pull request merged**
