### PR TITLE
reduce the kiltpocaplyse

### PR DESCRIPTION
**Pull request by dissociativity**
#### Summary

SUMMARY: Balance "reduce the kiltpocalpyse, balance the wardrobes"

#### Purpose of change

Kilts are absolutely everywhere lately, and while they're lovely exremely useful clothing with super low encumberance and pockets, making the classic cargo shorts largely obsolete, and keeping one's legs comfortably warm, I'm unsure that New England is quite this scottish.

Football armour, hockey masks, back scabbards, fishing waders were also absurdly common, scarves were oddly uncommon, and hats were slightly less common than they should be given the rather cold temperatures new england reaches.

#### Describe the solution

reduce appearances of kilts in itemgroups, generally rebalance domestic clothing rates

#### Describe alternatives you've considered

ponder whether scottish culture had a huge uptick in new england, make a scottish themed restaraunt variant to make this seem more normal
let new characters freeze to death due to new england inhabitants prioritizing strange fashion choices over not freezing to death

#### Testing

open game, loot around the place, find less kilts.

### CODE REVIEW

**Comment by dchieh222** [comment]
Kilts are popular with private school uniforms. Could that be a source?

**Comment by Theawesomeboophis** [comment]
It turns out that the Scottish did inhabit New England in the 1600s.
https://en.wikipedia.org/wiki/Scottish_colonization_of_the_Americas
A wikipedia article on the subject.

**Comment by dissociativity** [comment]
I have no doubt the scottish were there, it's just I'm finding kilts (plural) in almost every home, this reduction isn't actually enough from playtesting in fact!

**Comment by Theawesomeboophis** [comment]
> I have no doubt the scottish were there, it's just I'm finding kilts (plural) in almost every home, this reduction isn't actually enough from playtesting in fact!
Yeah, as far as I know, New England still shouldn't have so many kilts just lying around.

**Comment by dissociativity** [comment]
aight, this should feel about right.

**Comment by Theawesomeboophis** [comment]
> aight, this should feel about right.
> it's surprising just how common a frequency of 5 actually is!

That seems accurate, since the Scottish were only there while they were founding Nova Scotia, from the information I can gather about the period of time they inhabited that area.

**Comment by DialoMalison** [comment]
The brackets around the keyword `balance` will cause the PR validator to fail and need to be removed. I don't think the brackets around the description will also cause failure, but they are not needed.

**Comment by Theawesomeboophis** [comment]
Summary
SUMMARY: Mods "Makes Qianzhousaurus have more HP."
Use this for Summary format and just replace everything with your additions.

**Comment by dissociativity** [comment]
> 
> 
> fantastic, thanks. I was just thinking that the SUS dresser groups needed an audit for kilts. Back scabbard is another "entirely too frequent" spawn. Are you interested in expanding this beyond kilts?

any idea where they are in itemgroups? I've also noticed they're weirdly common, it seems every other person is a scottish warrior who's missing their sword.

**Comment by curstwist** [comment]
> 
> 
> > fantastic, thanks. I was just thinking that the SUS dresser groups needed an audit for kilts. Back scabbard is another "entirely too frequent" spawn. Are you interested in expanding this beyond kilts?
> 
> any idea where they are in itemgroups? I've also noticed they're weirdly common, it seems every other person is a scottish warrior who's missing their sword.

bscabbard is the item ID.

it's in both: SUS_wardrobe_mens and SUS_wardrobe_womens
https://github.com/CleverRaven/Cataclysm-DDA/blob/ee5753246748653c93cfaecbda982d63ec4210ce/data/json/itemgroups/SUS/domestic.json

I think removing it from one of those groups, and lowering it to 1 should help a lot.

**Comment by dissociativity** [comment]
apparently this is just going to be a wardrobe rebalance, less waders, back scabbards, more scarves around, slightly more hats (I found there were too little given the default start is still in a pretty cold season even since we moved the date forward, having one's face freeze off due to pre-cataclysm humans seemingly underdressing substantially is sad.

**Comment by dissociativity** [comment]
this of course is mostly a problem due to cataclysm handling body heat terribly, your torso should matter the most, some of the mouth's warmth should transfer over to preventing frostnip to the head overall, similar system for say, extremities mattering more than arm or leg warmth so long as your torso is warm enough, but that's outside the scope here

**Comment by dissociativity** [comment]
alright, enough checks don't hate me, off to bed

**Comment by curstwist** [comment]
> apparently this is just going to be a wardrobe rebalance, less waders, back scabbards, more scarves around, slightly more hats (I found there were too little given the default start is still in a pretty cold season even since we moved the date forward, having one's face freeze off due to pre-cataclysm humans seemingly underdressing substantially is sad.
> 
for what it's worth, hats are more common on coat racks, along with bags and coats.  Most houses get a coat rack.
unisex_coat_rack 

https://github.com/CleverRaven/Cataclysm-DDA/blob/2b10a30909e4b40ecb1e8911c6c8a59dabf042ba/data/json/itemgroups/Clothing_Gear/clothing.json#L2646

Feel free to add some more to the wardrobe though.

**Pull request merged**
