### PR TITLE
Replace sinkholes with pits

### PR DESCRIPTION
**Pull request by jokermatt999**
Because frankly sinkholes just aren't fun. Yes, they're avoidable if you carry around a hole rope at all times, but if you don't know about them, it's basically random fate-worse-than-death.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Good idea, but they should be masked somehow.

Also, pit traps are buggy and can't be filled. They have to be the pit terrain to work properly.

**Comment by tyrael93** [comment]
I think they're good at teaching people not to fuck around in swamps, even more than the animals they spawn. You learn the hard way and then carry that single item when you're going swamping.

Honestly I think this is a very unneded nerf, I mean if sinkholes were common on the terrain map in general sure, but they're limited to a very small portion of the map.

**Comment by Zireael07** [comment]
Sinkholes are bullshit instadeath.

The only alternative to removing them would be IMHO to allow climbing out of them, if you have rope/spiderweb mutation.

**Comment by Coolthulhu** [comment]
Sinkholes are obviously an unfinished placeholder. They place you underground, but don't actually offer any way to escape. They don't even clear the rock wall you spawn on.
Then you slowly starve to death. Not even suffocate, just starve.

Later on someone might reimplement them and make them do something sane (heavy debuff that roots you in place? spawn you in slime pits below? just break one of your legs?), but for now it would be better to just not have them than to have them.

**Comment by graysage1** [comment]
I like the idea of a sinkhole, but not if there is no reasonable way to prepare for it.  I was told even having a rope is not enough to be prepared, because the game rolls throwing and of all things unarmed skill checks?  So although I like the concept of a sink hole, provided they're avoidable by prepared people and are otherwise sane in the ways other people above mentioned, I won't be sad to see the current implementation go for now.

**Comment by vache** [comment]
I would be in favor of sinkholes being a much harder to notice, fairly damaging pit.

**Pull request closed without merging**
