### PR TITLE
Mad militia balancing with artificial dispersion

### PR DESCRIPTION
**Pull request by BioHazardSuit**
#### Summary
Balance "Too lethal accuracy"

Fixes mad militias' too lethal accuracy\, and description.
#### Purpose of change
I read that they are too lethal in accuracy.

#### Describe the solution

Made a fake ar15 with a dispersion of 3000, resulting in the mad militia being more prone to missing their shots.
#### Describe alternatives you've considered
I haven't tried making the gun skill to 0, it may also work.

#### Testing
Did multiple tests, they miss at least (If I saw it right) half of the total shots, and still do at times even when already near the character.

#### Additional context
No other additional

### CODE REVIEW

**Comment by wapcaplet** [comment]
Should help with #53707

**Comment by BioHazardSuit** [comment]
I feel like I'm missing something. Is there something more I should balance change for mad militia? Changing it here in the same Pull request sounds the efficient way to go.

**Comment by wapcaplet** [comment]
I did some playtesting - before your changes, the mad militia was able to hit most shots at around 20-25 range. After your changes, they missed most shots at that range, and became a lot more accurate at around 10 tiles away. This seems pretty reasonable to me.

> I feel like I'm missing something. Is there something more I should balance change for mad militia? Changing it here in the same Pull request sounds the efficient way to go.

Their extremely sharp accuracy was the major concern of the issues #53707 and #53824, so I think you have covered the big one.

**Comment by kevingranade** [comment]
There's an underlying problem here that this just works around, based on their stats, they should not be this accurate, I suspect there is something going on in gun actor that shouldn't be, such as not applying any kind of aim penalty.

**Comment by BioHazardSuit** [comment]
Alright

**Comment by BioHazardSuit** [comment]
Alright then, all looks good.

**Comment by AcidAntOnAMinefield** [comment]
Thank you for this. Having tested it myself, now it is actually fair to try and face/avoid them compared to previously!

**Pull request merged**
