### PR TITLE
Removed duplicate gyroscopic stabilizer

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
This was converted to a rail accessory, but the old entry wasn't removed.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
The interesting thing is that the game was using the rail version instead of the accessory version. Aren't jsons supposed to load alphabetically?

**Comment by kevingranade** [comment]
The order is indeterminate, it should work if the order is scrambled.  I.e.
anything that works for one ordering and not another is a bug.

Also duplicates should cause an error message, did that not happen here?

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade no error appeared within game; the bug was only noticeable when reading the code.

How does the game choose between different definitions? I've never seen the game use the now-deleted definition of a gyroscopic stabilizer.

**Comment by kevingranade** [comment]
As I said, it generally shouldn't pick one, it should report an error.

**Pull request merged**
