### PR TITLE
foes that regenerate in dark were regenerating in daylight

### LINKED ISSUE #67027: Monsters which "use darkness to regenerate" can regenerate in light
### Describe the bug

Monsters who regenerate in darkness, such as the unseen hunter, can regenerate in broad daylight. This is because the check for regeneration requires a light level of less than 10,000 (floodlight) which is brighter than broad daylight by a considerable margin.

### Attach save file

n/a

### Steps to reproduce

1. Spawn an unseen hunter in daylight.
2. Injure it somehow.
3. Observe it "using darkness to regenerate" despite no darkness.

### Expected behavior

They should use darkness to regenerate and can't do that under a heavy duty flashlight or whatever.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: b549de5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by db48x**
#### Summary

Balance "foes that regenerate in dark were regenerating in daylight"

#### Purpose of change

The regeneration message says that the monster uses “the darkness” to heal itself, so why does the game allow it to happen in full sunlight?

The darkness feature was balanced so that a floodlight prevents these monsters from healing in a 20–tile radius. Floodlights create a light level of 8000, which drops off as you get further away. 20 tiles away the level has dropped to about 200. Unfortunately, full daylight at noon on a clear day has an ambient light level of only around 127.5, so while the monster may work fine in underground areas with the occasional floodlight, it is not so great outdoors or in buildings with windows.

#### Describe the solution

This fix rebalances it so that the regeneration rate drops to zero at a light level of 30, the same level where the (unrelated) PHOTOPHOBIA effect kicks in. This lets the player use daylight from a window to effectively neutralize this healing ability. Unfortunately other light sources, like flashlights and floodlights, are even more effective than daylight. Rebalancing those against the light from the sun, however, seems like a rather more ambitious fix.

I also added a few additional messages for different light levels.

#### Testing

Screenshot from 2024-01-08 04-55-28

#### Additional context

Fixes #67027

### CODE REVIEW

**Comment by Maleclypse** [comment]
This isn’t the solution we are looking for unfortunately.  From Kevin
‘’’
It would be very easy and cheap to maintain a boolean "direct sunlight" flag for each tile. If anyone wants to look at that before me, all you really want to do is stick a set of bit vectors in the map cache. There's already several examples. Then in the sunlight code just also mark that as direct sunlight where appropriate. Then some kind of map method to check for direct sunlight level at a given tile
‘’’

**Comment by db48x** [comment]
So one thing that I didn’t mention is that there is also the `SUNDEATH` effect, which harms creatures in direct sunlight. It calls `game::is_in_sunlight`, which really just checks to see if they are inside or outside and doesn’t take into account windows but which could obviously check a bit in the map cache as mentioned. But, if it is changed to check for sunlight then floodlights won’t stop them from regenerating either.

As it stands, one of the two monsters with `regenerates_in_dark` also has `SUNDEATH`, meaning it will be both damaged and healed on the same turn while standing outside in direct sunlight. The sun should end up winning because the damage is twice as strong, but I bet it’s pretty funny to watch. Looks like it won't voluntarily walk outside though.

**Comment by Maleclypse** [comment]
At the moment we’d rather lose floodlights preventing regen than allowing flashlights and headlights to prevent regeneration.

**Comment by PatrikLundell** [comment]
What I read from the comments is that they don't want to fix the creatures that use "darkness to generate" to not regenerate in bright artificial light. If so, the creature description should not say they regenerate in darkness while being in a brightly (artificially) lit area, but rather refer to the lack of direct sunlight as the source of the ability to regenerate (and you should probably be able to block the regeneration with a UV light generator, should the game allow you to get/build one. Aren't there some active night vision goggles that emit UV light?).

**Comment by db48x** [comment]
The SUNDEATH effect checks the solar irradiance (in units of W/m²) rather than the ambient light level (if this is in a consistent unit it is unknown to me). It requires the sunlight to be above `irradiance::minimal`, or 87 W/m². I decided to run a test to see how that compares, and discovered that the sunlight hits this minimal level at an ambient light level just above 30. At least with this patch that becomes consistent; the player won’t see messages about it dying in the sun and also regenerating in the darkness at the same time.

I think that any other way of fixing this will require rebalancing the ambient light levels so that flashlights are not 2.3× as bright as the sun and so on. Maybe specify their brightness in terms of W/m² and then calculate an ambient light level from that to drive the graphics.

**Comment by fairyarmadillo** [comment]
> The SUNDEATH effect checks the solar irradiance (in units of W/m²) rather than the ambient light level (if this is in a consistent unit it is unknown to me). It requires the sunlight to be above `irradiance::minimal`, or 87 W/m². I decided to run a test to see how that compares, and discovered that the sunlight hits this minimal level at an ambient light level just above 30. At least with this patch that becomes consistent; the player won’t see messages about it dying in the sun and also regenerating in the darkness at the same time.
> 
> I think that any other way of fixing this will require rebalancing the ambient light levels so that flashlights are not 2.3× as bright as the sun and so on. Maybe specify their brightness in terms of W/m² and then calculate an ambient light level from that to drive the graphics.

Differentiating artificial and solar light would be really helpful for all the farming stuff I mentioned, especially if it also allowed us to designate something as a grow light. UV radiation is often used in sci fi to explain why vampires etc. burn in the sun, it seems reasonable that we could just have that kind of light hurt the monsters, and a flashlight wouldn't.

**Comment by RenechCDDA** [comment]
Hey @db48x, looks like you've got some merge conflicts and CI failures that have been sitting for a while.

**Comment by db48x** [comment]
I wasn’t going to bother fixing them because you said that you didn’t want this patch. I did #70799 instead. It fixes the bug in how much they regenerate without rebalancing how much sunlight is necessary to stop them from regenerating.

**Comment by RenechCDDA** [comment]
I apologize, I'm working on the 0.H release list and skipped over the discussion which I had previously read (and believed I remembered).

**Comment by nornagon** [comment]
Is it safe to say that given our choices with the current light level situation, given flashlights are brighter than the sun, are either:

1. dark-healing monsters can heal in sunlight but not in floodlight, or
2. dark-healing monsters can't heal in sunlight, but a flashlight can prevent them from healing?

And from these options, we prefer (1)? In which case, this PR should probably be closed.

**Comment by db48x** [comment]
> I apologize, […]

You’ve no need to apologize for that :)

**Comment by Night-Pryanik** [comment]
I'm closing this based on discussion.

**Pull request closed without merging**
