### PR TITLE
Wished for items span with full charges or ammunition

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Testing involving batteries or ammunition is a hassle because wished for batteries are uncharged and wished for guns require magazines and ammunition.

#### Describe the solution
Create items fully loaded when wished for.

#### Describe alternatives you've considered
If there's a use case where you need discharged batteries, add UI to select charge level.
~~Extra niceness would be to spawn withed for items with charged batteries already in them (and guns!).~~

#### Testing
Debug spawn a battery and stick it in a flashlight or something.
Debug spawn a collection of guns and magazines, they appear loaded.
Debug spawn various tools, they spawn with charged batteries.

### CODE REVIEW

**Comment by ymber** [comment]
I don't think this does what you want it to. This affects the batteries I added in #32141 but those aren't actually used anywhere in game yet. Current magazine type batteries won't be affected by this.

**Comment by anothersimulacrum** [comment]
This can be achieved by spawning in disposable batteries, but having it for normal batteries would be good.

**Comment by nullptr98** [comment]
maybe use ammo_type to check if its a battery and granted.ammo_set( granted.ammo_default() , -1 ) for the current magazine type batteries

**Comment by nullptr98** [comment]
maybe use ammo_type() to check if its a battery and granted.ammo_set( granted.ammo_default() , -1 ) for the current magazine type batteries

Edit1: this seems to work for the disposable batteries only, like simulacrum stated.

Edit2:
`            if ( granted.is_magazine() && granted.ammo_capacity() > 1 && ( granted.type->looks_like == "battery" || granted.type->looks_like == "storage_battery") ) {
                granted.ammo_set( granted.ammo_default(), -1 );
            }`

definetly not the best but gets the job done for all batteries exept vehicle's ones. 
adding looks like battery for them in json\items\vehicle\battery.json fixes it.

**Comment by KorGgenT** [comment]
this is a static function that i'm using in the craftnig test in #36656 
```cpp
static item tool_with_battery( const itype_id &tool, const int battery_charges )
{
    item it( tool );
    item mag( it.magazine_default() );
    item ammo( mag.ammo_default(), -1, battery_charges );
    mag.contents.insert_legacy( ammo );
    it.contents.insert_legacy( mag );
    return it;
}
```
It probably needs a bit more nuance for things like internal mags, but it should actually work for everything that has a mag that has a default ammo.

**Comment by kevingranade** [comment]
Yea my bad, I went off in a bad direction thinking the code would mean what it says :D

**Comment by kevingranade** [comment]
Thanks for the feedback all, that's what I get for trying to hack something together on my phone.

Now it's *significantly* more general, if it has ammo, it spawns loaded.

**Pull request merged**
