### PR TITLE
Prompt before oxytorch activity if you don't have enough gas

### PR DESCRIPTION
**Pull request by AlexMooney**
#### Summary
Features "Prompt before oxytorch activity if you don't have enough gas"

#### Purpose of change

With the addition of [tiny acetylene tanks](https://github.com/CleverRaven/Cataclysm-DDA/pull/78323), having insufficient gas to torch things is far more prevalent.  Since you need 112 charges to cut through a metal door and the new tanks hold 100, the player can easily waste 96 charges (8 gas per second until it runs out) if they attempt to torch a door with a full tiny tank.

#### Describe the solution

Check if the player has enough acetylene before starting the activity and prompt them if they want to start if it's not possible to finish with the current tank.

#### Describe alternatives you've considered

1. Could make the `oxy_torch` `USES_NEARBY_AMMO` so that multiple tiny tanks can do the job. This would still waste gas when there isn't enough and would also change up welding crafting to be able to squeeze every drop out of each tank.
2. Handwave steel doors to require 6 kg of steel melting requiring 96 gas instead of 7 kg requiring 112 gas, so that you can cut a door with a tiny tank.  This doesn't solve the problem of wasting gas, but at least makes the tiny tanks less punishing.
3. Increase the tiny tank to 1.25 L so that you can cut a door.  As above.
4. Empty the current tank whether or not it'll do the job.  Current behavior.

#### Testing

Prompt appears
image

Can reload and resume
image

#### Additional context

[Gas requirements in the `oxy_torch`](https://github.com/AlexMooney/Cataclysm-DDA/blob/786d9eed7d1669ad8c31047890ce921b1c9c0b58/data/json/items/tool/workshop.json#L832-L834)
[Capacity of `tinyweldtank`](https://github.com/Night-Pryanik/Cataclysm-DDA/blob/1716dbd3dca180d75f62487d7bc30755d40f9cc1/data/json/items/magazine/weldgas.json#L3-L18)

### CODE REVIEW

**Comment by AlexMooney** [comment]
Did more testing when updating the tests and now I see that you can reload the torch and resume the activity. This PR would prevent you from using multiple tanks to get the job done. I'll see about updating it with a prompt to ask if you're sure you want to start given your current tank doesn't have enough.

**Comment by Night-Pryanik** [comment]
Care to update the tests?

**Comment by AlexMooney** [comment]
> Care to update the tests?

As I mentioned in the comment above, I was working on updating the tests but I decided this change isn't correct yet.  I'm going to change it to prompt for confirmation instead of blocking the action and I'll also add a test.

**Comment by AlexMooney** [comment]
I'm thinking of adding something to `Avatar` so that I can force the `query_yn` to return `true`. Something along the lines of `dummy->set_query_yn(true)` to override the `return ::query_yn` call.

**Pull request merged**
