### PR TITLE
More requirements in recipes

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- used more requirements in recipes instead of explicit tools and qualities.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by nexusmrsep** [comment]
You removed "GLARE" reqirement in many cases. Wasn't it intended to be eye-protection (glasses when sewing wood or metal for example) but with poor implementation ( glare is always a protective eyewear, but protective eyewear  is not always glare protection)?

**Comment by ZhilkinSerg** [comment]
> You removed "GLARE" reqirement in many cases. Wasn't it intended to be eye-protection (glasses when sewing wood or metal for example) but with poor implementation ( glare is always a protective eyewear, but protective eyewear is not always glare protection)?

Good point. It makes sense to check recipes if they need to be updated with mechanical eye protection in separate PR. As for current PR - `GLARE` quality is in `welding_standard` requirement, so recipes didn't loose it.

**Comment by nexusmrsep** [comment]
In few cases you removed it from recipes that don't use welding standard from the begining. It'll be harder to identify those afterwards when glare will be gone from that. I know thats not ideal but maybe leave those few for that further PR you mentioned or maybe add a flag for eye protection preemptively?

**Comment by ZhilkinSerg** [comment]
Can you please give an example? I've reviewed changes and didn't find any recipes affected by this issue, though some recipes from `\data\json\recipes\recipe_others.json` were changed in unintended way and I will revert this.

**Comment by nexusmrsep** [comment]
Checked, and it seems I was wrong. Those I thought about just had wding standard not where I was looking for it. Sorry, my bad. But it seems its for the beetter as a new possible idea emerged this way.

**Pull request merged**
