### PR TITLE
[CR] More consistent item descriptions

### PR DESCRIPTION
**Pull request by ama0**
#### Summary
Content "Rephrase "This is a[n]" into "A[n]" at the beginning of item descriptions"

#### Purpose of change

Item descriptions have a more consistent style

#### Describe the solution

Rephrase the descriptions

#### Describe alternatives you've considered

Not changing anything 

#### Testing

Descriptions have changed ingame.

#### Additional context

I'm not sure if there is a desire to have the descriptions in a more consistent style. This is just a first batch of changes to see if I should continue.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
While it is just a slight and obvious cgange, it would require translation of 117 big strings which were already translated previously.

**Comment by ama0** [comment]
> While it is just a slight and obvious cgange, it would require translation of 117 big strings which were already translated previously.

And that is not even all the changes. So in the end it will be much more to translate.

**Comment by mlangsdorf** [comment]
Why do items need more consistent descriptions?  What's the downside to some items saying "this is an $ITEM" and others saying "an $ITEM", and why is making all of the first into the second a good solution?

This seems like a lot of churn to get some minor consistency.  The CDDA dev team would generally prefer that code be consistent, but that can be a secondary concern to not having churn.  For JSON, the concern about not churning is ranked much higher than for code.

**Comment by actual-nh** [comment]
I suggest that, if one is already editing the description in question for some other reason, that would be the time to change it to "A[n]" (which does have the merit of shortening the description).

**Comment by ama0** [comment]
Alright then. That's why it was a comment request in the first place 🙂

**Pull request closed without merging**
