### PR TITLE
Refactor item_location class [CR]

### PR DESCRIPTION
**Pull request by mugling**
1. `item_location` now requires `item *` not `const item *` as it provides an interface for mutating an `item` via `remove_item()` and `obtain()` (f019486)
2. Equality and indirection operators are provided in 3cef83c. The latter are usable for all valid locations (everything apart from an empty default constructed `item_location`)
3. `visitable<T>::has_item` is now used by each internal implementation (a16d777, 9323534, 96f199d). A separate PR will implement `visitable<T>::remove_item` and update `item_location` to use this.
4. `item_location::describe()` is extended in db99002 to append relative distance for vehicle tiles 
5. astyle and cleanup

### CODE REVIEW

**Comment by mugling** [comment]
A further PR will extend `item_location::obtain` to allow specifying a maximum number of charges to fix the problem identified by @BevapDin whereby it currently obtains the entire stack irrespective of available inventory space

**Comment by Coolthulhu** [comment]
The change fixed slings, but I got a segfault later.
Not sure what exactly caused it, but I was spamming the rivtech flamethrower in burst mode while it happened.

**Comment by mugling** [comment]
Do you have a stack trace?

**Comment by mugling** [comment]
> EDIT: Got it, it happens when a burst fire is ended prematurely due to lack of ammo, possibly only with weapons that use more than one charge per attack.

Unrelated to this PR then but I'll look into that

**Comment by Coolthulhu** [comment]
As usual, `ptr == nullptr` is better than casting `ptr` to `bool`.

**Pull request merged**
