### PR TITLE
Crude shotgun: Take 2

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

SUMMARY: Content "Add new low-level crafted firearm (makeshift shotgun)"

#### Purpose of change

This is a re-attempt at adding an early-game shotgun. Hopefully the linting etc is correct now!

#### Describe the solution

This is a gun that can be made at very low skill levels (0-1 mechanics and marksmanship). It is extremely inaccurate, with extreme recoil, as expected of a firearm made of two pipes and scrap.

#### Describe alternatives you've considered

Not make it, and leave players without any gun at all.

#### Testing

Put into game. Wish for gun. Shoot it.

#### Additional context

Speaking of other weapons, the 2-shot special might do well if renamed to "zip gun" and given the same treatment.

### CODE REVIEW

**Comment by Xenomorph-III** [comment]
If anyone knows why these still fail, I'll be glad.

**Comment by anothersimulacrum** [comment]
https://travis-ci.org/github/CleverRaven/Cataclysm-DDA/jobs/696635821#L1147-L1159

**Comment by Xenomorph-III** [comment]
Got it, thanks!

Also I accidently copy-pasted the old files from the inital crude shotgun request - my bad!
I'll close this and try again.

**Comment by anothersimulacrum** [comment]
You need to remove the merge commits.
For existing branches, you should be able to just rebase them onto upstream/master.
For your master branch, you can just hard reset it to upstream/master.

**Pull request closed without merging**
