### PR TITLE
Fix failing unit tests for vehicle_turret

### LINKED ISSUE #19024: vehicle_turret unit test failures
Using 9d41e9fd4a4c453b799faa43a60d469295cf8eff:

```
-------------------------------------------------------------------------------
vehicle_turret
  mounted flamethrower
-------------------------------------------------------------------------------
vehicle_turrets.cpp:46
...............................................................................

vehicle_turrets.cpp:62: FAILED:
  REQUIRE( tank )
with expansion:
  false

-------------------------------------------------------------------------------
vehicle_turret
  water cannon
-------------------------------------------------------------------------------
vehicle_turrets.cpp:46
...............................................................................

vehicle_turrets.cpp:62: FAILED:
  REQUIRE( tank )
with expansion:
  false
```

### PR DESCRIPTION
**Pull request by mugling**
Fixes #19024

The unit test was never updated to account for the generic tanks PR

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I realized our CodeBlocks project doesn't include tests.
MSYS2 currently segfaults, so I can't test it right now.

**Comment by mugling** [comment]
> Builds fine and vehicle_turret test case is no longer failing.

See @BrettDong's review also verifying this

**Comment by Coolthulhu** [comment]
At the moment the rules are roughly: mergetester merges after testing. I can't test this.

If you want to change the rules to allow self-merges after independent reviews, make an issue and ask others. I'd be fine with it.
Or we could add @BrettDong to devs. But I don't see myself being able to do that (or I don't know where to do that), so we'd need someone with rights to do that.

**Comment by mugling** [comment]
I'd see @kevingranade's comments in #19291 for reference.

This also alarms me that the unit tests aren't being used at all. There is no purpose in their existence if they aren't actually used.

**Comment by mugling** [comment]
Merged as per @BrettDong's review

> Builds fine and vehicle_turret test case is no longer failing.

**Comment by Coolthulhu** [comment]
> There is no purpose in their existence if they aren't actually used.

I recall you wanting buildbot doing them once in a while. Did anything come out of it?

**Comment by mugling** [comment]
> I recall you wanting buildbot doing them once in a while. Did anything come out of it?

As yet no

**Comment by kevingranade** [comment]
The problem there is as of the last time we checked, the build bot software
doesn't do any kind of sandboxing, so anyone with a GitHub account could
trigger execution of arbitrary code but opening a pr.

**Comment by mugling** [comment]
> The problem there is as of the last time we checked

This is still the case. The last discussion was to run this only for committed code as that doesn't open @narc0tiq to any (additional) risk

**Pull request merged**
