### PR TITLE
Increment decrement operators single string

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change
Apply https://github.com/CleverRaven/Cataclysm-DDA/pull/77238 to the repo. This PR is just ++ and --

#### Describe the solution
Replace
\",[ \n\r]+\"\+\+\"
with
++"
and
\",[ \n\r]+\"\-\-\"
with
--"

#### Testing
Manually reviewed changes

### CODE REVIEW

**Comment by akrieger** [comment]
Why not `\s` for 'any whitespace'? Does that catch more cases?

**Comment by Procyonae** [comment]
I just forgot that was a thing, my retention of regex stuff is abysmal '^^

**Comment by Maleclypse** [comment]
Ok so this is not ready for merge?

**Comment by marilynias** [comment]
quick search yield no additional hits (if my regex is up to par)
Screenshot from 2024-12-06 14-19-51
Screenshot from 2024-12-06 14-20-56
Screenshot from 2024-12-06 14-21-32
Screenshot from 2024-12-06 14-22-16

**Comment by Procyonae** [comment]
Ye this is good to go I think \s is equivalent to [ \t\n\r] and we don't allow tabs so what I did is just slightly uglier but does the same thing

**Pull request merged**
