### PR TITLE
Enum classes

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

#### Purpose of change

Add class to some enums (rename enum class members in the process, to remove prefixes)

#### Describe alternatives you've considered

Leave enums alone in a classless society.

#### Testing

Let it compile.

### CODE REVIEW

**Comment by jbytheway** [comment]
It would be good to remove the (now-unnecessary) common prefix from the enumerator names.

If you don't want to do that by hand, then I had a plan to implement a clang-tidy check to do it at some point.

**Comment by anothersimulacrum** [comment]
I introduce a new enumeration in #39387 should I convert it to an enum class as well?

**Comment by kevingranade** [comment]
Yes, I want to discuss with everyone, but I think this would be a good
thing to make mandatory.

**Comment by ZhilkinSerg** [comment]
> I introduce a new enumeration in #39387 should I convert it to an enum class as well?

Yes, it should not be any harder to use than plain enums in most cases.

> It would be good to remove the (now-unnecessary) common prefix from the enumerator names.
> 
> If you don't want to do that by hand, then I had a plan to implement a clang-tidy check to do it at some point.

I was thinking about renaming them too. Will do.

**Comment by jbytheway** [comment]
> Yes, I want to discuss with everyone, but I think this would be a good thing to make mandatory.

Agreed, I think it should be the default to do so, unless some unusual situation dictates otherwise.  Certainly for enums at global scope.

**Pull request merged**
