### PR TITLE
Add Hammer to toolbox recipe

### PR DESCRIPTION
**Pull request by DifferentLevelDan**
Toolbox has hammer 3 quality, but no hammer component.

### CODE REVIEW

**Comment by ifreund** [comment]
thats because there is a hammer in the basic repair kit recipe

**Comment by ifreund** [comment]
thats because there is a hammer in the basic repair kit recipe

**Comment by ifreund** [comment]
Maybe hammering 3 and fine hammering 1 should be added to the repair kit?

**Comment by Rod-Serling** [comment]
Current Components list no longer includes the basic repair kit.

```
  "components": [
    [ ["pockknife", 1], ["primitive_knife", 1], ["switchblade", 1], ["knife_steak", 1] ],
    [ [ "screwdriver_set", 1 ] ],
    [ [ "hacksaw", 1 ] ],
    [ [ "wrench", 1 ] ],
    [ [ "saw", 1 ] ]
  ]
```

Toolbox lost basic repair kit functionality and recipe in #16237

**Comment by ifreund** [comment]
Huh I was lazy and just used the item browser, who knew it would be so out of date?
http://cdda-trunk.estilofusion.com/toolbox/craft

**Pull request merged**
