### PR TITLE
new houses

### PR DESCRIPTION
**Pull request by LilShiningMan**
```SUMMARY: Content "5 new house layouts with palette"```

#### Purpose of change
To add variety to residential house layouts.

#### Describe the solution
Added 5 new house layouts, each with flavour variants. Added palette that includes a variety of item spawn lists that try to ensure items that should be rarer (ie - toolboxes, textbooks) remain so, but the variety of things that might spawn on, say, a living room table, have more variety. The spawn weight of each house and its variants are cumulatively 200.

#### Describe alternatives you've considered
There are always great new house layouts being added so I could just wait.

#### Testing
I've tested each house design and their variants to ensure loot drops are basically on par with what's currently in the game.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Some screenshots?

**Comment by LilShiningMan** [comment]
Thanks for the comments. This is my first PR so any feedback is appreciated. 

Here are some screenshots of the various houses

lsm001-1

lsm002-1

lsm004-1

lsm005-1

lsm003-1

**Comment by LilShiningMan** [comment]
This PR is too large, you should try to split it up.
Your itemgroups should be in the itemgroups directory, not shoved in with palettes.

As for the item groups in the palette, I'm happy to split them in a separate JSON. My thinking was that these groups would be called by my houses specifically, not unlike how some of the mansions builds use the mansion room lists. I believe those are a mod though(?), so maybe that's more mod-like behaviour. 

I also appreciate that the item lists are large. I actually pooled various items that might fit into multiple categories into single lists for ease when assigning them to certain furniture items in the style sheet. The reason I didn't use existing lists is that having unique lists allows me to make changes without disrupting what other people are doing. For example, I noticed in the main shower item list there's a bathroom scale. I'm not sure of the rationale of that. I removed that and also added other things that might be found in a shower to my list (rubber gloves, sponge, etc). I'm not sure what the process looks like to edit the "main" item lists. This seemed like an easy workaround.

**Comment by Night-Pryanik** [comment]
Just FYI, you could spawn clairvoyance artifact to show all the picture, without map memory and/or unseen tiles.

**Comment by anothersimulacrum** [comment]
> I pooled various items that might fit into multiple categories into single lists for ease when assigning them to certain furniture items in the style sheet.

For this, I'd suggest you have item groups that just reference existing itemgroups.

 > I didn't use existing lists as having unique lists allows me to make changes without disrupting what other people are doing. For example, I noticed in the main shower item list there's a bathroom scale. I'm not sure of the rationale of that. I removed that and also added other things that might be found in a shower to my list (rubber gloves, sponge, etc).

You're not really disrupting what other people are doing, don't worry about that. The shower itemgroup is likely used as a more general bathroom itemgroup, which is why it has those things.

> I'm not sure what the process looks like to edit the "main" item lists. This seemed like an easy workaround.

While this is an easy workaround for now, it actually increases maintenance in the long run.
You can look at these PRs #35088 and #34738 for how changes are being made to domestic itemgroups.
Again, I'd strongly suggest you use pre-existing itemgroups and make some changes, rather than making large itemgroups that are largely duplicates.

**Comment by curstwist** [comment]
hey, glad to see more houses!  

I agree with the above comments on item_groups.  Though I think some of yours could be easily added into the SUS kitchen groups file, like your cabinets for pantry items.  I'm in the process of adding some for bedrooms (dresser, wardrobe, desk/table, coat rack) that you can make good use of as well.  

For the maps themselves:
Pick different wall terrains.  Anything except unpainted default t_wall or natural rock.  I've been using brick and adobe brick and stone for the exteriors and painted walls for interiors.  Feel free to look into ones that'll work well for you.

Please add roofs, if the foundations are all identical, you only need one roof.  Make sure to add gutter access for both levels though.

The library could use some chairs, desk or something to liven it up.

If you make more houses, I'd suggest looking into the nested map chunks.  They need square rooms to work well though, so I don't think you can easily incorporate them into this batch.  There are a number you can use already, and it'd be great for more to be added.

**Comment by LilShiningMan** [comment]
****Night**-Pryanik**: I haven't come across that artifact in my playtime but will def remember for next time I take screenshots.

**anothersimulacrum**: I'm currently following your suggestion and reconfiguring my groups to reference existing itemgroups and adding the few dangling items that can't be easily added otherwise. As for changes to domestic groups, it's something I'd definitely like to contribute to, as I feel there are a few groups in my palette that don't currently have an analogue in existing groups. For example, I couldn't come up with a satisfactory substitute for my "home_display_case" list. I think in the near future I will try and submit that to main branch as a separate pull request. I'd also like to help out with arranging some of the food groups, specifically alcohol. I think it'd be beneficial to break it down into liquor, wine, beer and mixed drink categories that are all called by the main "alcohol" group. Again, its own PR.

As for my palette, it does a lot of the heavy lifting currently, but having "loose" slots for furniture that sits on different terrains goes a long way towards giving me flexibility (using concrete, multiple kinds of carpet, etc in a single design). However, I can see room for tightening up my palette so that the house files aren't quite so "busy" though.

**curstwist**: Thanks for the comment. As above, I'd like to add some of my groups to main branch as I think they can be of use to people. Specifically, "liquor_cabinet" which could just be called liquor, "display_case", maybe the "home_desk" entry as well. That may be my next move before trying to submit these houses again. Since you're currently looking at the desk, maybe I'd wait to see what you come up with first.

I've got quite a few houses that are in various stages of readiness to submit, a fair percentage of which have different kind of walls (some brick, some concrete, etc.), so I'm def interested in keeping up the variety. I also plan on doing some "variants" on the houses so that the same house design has different walls, carpet colours, etc. for some variation.

Roofs are something I've neglected. It's not a lot of additional work to do, really, so I'll make sure I do that before resubmission.

Sorry, not sure which is the "library" you mention. I do try to put a lot of furniture and detail in there, but admittedly some of the rooms look a little sparse.

I'd be interested in hearing more about the nested chunks you mention if you can point me towards something to read. It's been a while since I scanned the Docs, so it's possible I just missed something in there. 

I think I will pull this PR for the time being and work on refining my palette, item lists, etc. and then re-submit. 

Thanks for all the comments everyone.

**Comment by esotericist** [comment]
> ****Night**-Pryanik**: I haven't come across that artifact in my playtime but will def remember for next time I take screenshots.

You spawn it with the debug menu.

**Comment by curstwist** [comment]
I don't think we have much documentation on nested chunks, I'll work on fixing that.  For now you can look at #34691 and subsequent PR's for the nested houses I made.  It should give you a good idea on what is involved.

**Pull request closed without merging**
