### PR TITLE
Remove salt water from broth

### LINKED ISSUE #58818: Swamp broth
### Describe the bug

Natural swamp resources already provide both water and salt water, exposing a flaw in the recipe and potentially also shallow salt water.

Credits to @x-qq for reporting this on IRC.

### Steps to reproduce

1. Be in a swamp.
2. Be near a salt and normal water tile.
3. You now have 2 of the 3 ingredients necessary for broth, salt water (a substitute for herbs or sauce) and normal water.
4. water + salt water + cattail stalk = broth apparently

### Expected behavior

I know that survival is all about improvising but this seems cheap and unrealistic. It appears that the recipe may potentially imply that you are boiling the salt water until only salt remains but this also problematic due to the time consumed.

Secondly, although the murky swamp water full of organic material may already classify as a vegetable itself, the contamination of the water may still be an issue. Maybe we need murky salt water?

My proposal is to remove salt water from the broth recipe entirely.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-9426-gcb051eb5bae [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This might be a good first issue.

### PR DESCRIPTION
**Pull request by NetSysFire**
#### Summary
None

#### Purpose of change

Fixes #58818

#### Describe the solution

This addresses the fact that you can make a broth from the following components:
- Water
- Salt water
- Corn husk
= broth

Note the water + salt water part. One unit of salt water is 250 ml. <s>One unit of salt (also applies to pepper) is 250g and it required 4 units of it. 1 kilogram of salt for 500 ml of broth,</s>, I did not account for charges. Argh. I tweaked the other ingredients accordingly and require more wild herbs because of the missing salt. Wild herbs are also easy to get.

#### Describe alternatives you've considered

I know this was a "controversial" issue but really? Water + salt water is something that should definitely not work. If there was brine in the game I would have replaced the salt water requirement with this.
I hope the other tweaks to the ingredients will appease the folks complaining.

#### Testing

n/a since this is a trivial change.

### CODE REVIEW

**Comment by Qrox** [comment]
Actually you can make 1 salt water from 1 water and 10 (table) salt, and this makes it impossible to use that perfectly reasonable salt water in place of water + salt in this recipe. Why not just make swamps give you inedible salt water instead? It's not like they only contain sodium chloride so it's safe to assume you can't use the swamp water for cooking.

**Comment by NetSysFire** [comment]
Hmm. Another thing is that you have 500 ml of broth yet only 250 ml of water. This will not really work with some vegetables.

I certainly did not check how salty that salt water is but you would need to boil it for far longer if you want to make broth with it in order to get rid of most of the fluid so it is not that watered down.

**Comment by Qrox** [comment]
> 500 ml of broth yet only 250 ml of water

I checked in game and all broth recipes make 1 broth from 1 water which are both 250 ml.

> how salty that salt water is

1 water and 4 salt would have similar saltiness to 1 water and 1 salt water (totaling 2 water and 10 salt) and thus do not require additional boiling. However it means you lose half of your diluted salt water so the numbers could use some auditing.

**Comment by AtomicFox556** [comment]
I think it's a better idea to just remove salt water from swamps if making broth that way is a problem.

Using both salt water and non-salt water in a recipe would assume that you're diluting water that is too salty for broth as-is with non-salty water, so it should just use two actual broth ingredients, one unit of normal water and one unit of salt water to make twice the normal amount of broth.

**Comment by Zireael07** [comment]
> Using both salt water and non-salty water in a recipe would assume that you're diluting water that is too salty for broth as-is with non-salty water, so it should just use two actual broth ingredients, one unit of normal water and one unit of salt water to make twice the normal amount of broth.

Agreed

**Comment by NetSysFire** [comment]
>Dropping in to say that you can absolutely 100% make broth out of water and (dried) corn husks

I believe you but corn husks are currently 0 cal ingame. This is not the focus of this PR though.

**Pull request merged**
