### PR TITLE
Added another underbarrel slot for KSG

### PR DESCRIPTION
**Pull request by Night-Pryanik**
So it can accept forward grip like this

### CODE REVIEW

**Comment by pisskop** [comment]
can it also accept a flamethrower too now?

**Comment by Night-Pryanik** [comment]
> can it also accept a flamethrower too now?

All underbarrel mods, so yes, aux flamethrower too.

**Comment by pisskop** [comment]
So it has 7 shells, plus 7 more for the underbarrel, plus one of either 2 more shells underbarrel, 4 doses of flamthrower, or a grenade launcher attachment?

**Comment by Night-Pryanik** [comment]
> So it has 7 shells, plus 7 more for the underbarrel, plus one of either 2 more shells underbarrel, 4 doses of flamthrower, or a grenade launcher attachment?

Yeah, it seems so.

**Comment by pisskop** [comment]
I dont think thats a good idea.

**Comment by kevingranade** [comment]
It sounds like we're treating, "enough room for an underbarrel grip" and "enough room for an underbarrel weapon" as the same thing, but we shouldn't. 
Until that is adressed, preventing grip installation is less bad than allowing excessive accessory installation.
Also I notice the product page says 6+6 rounds in the magazine, why does our version have 7+7?

**Comment by John-Candlebury** [comment]
Probably meant to mean 6 rounds in the magazine plus one loaded into the barrel.

But I dont think any other shutgun does this.

**Comment by Night-Pryanik** [comment]
> It sounds like we're treating, "enough room for an underbarrel grip" and "enough room for an underbarrel weapon" as the same thing, but we shouldn't.
Until that is adressed, preventing grip installation is less bad than allowing excessive accessory installation.

I don't understand, what is the problem here? KSG has rails for underbarrel weapons, it is lengthy enough for underbarrel weapons (its barrel length is more of m4a1, for example).

**Comment by Broken-Admin** [comment]
Why don't we do something specific for under-barrel grips, a different slot?

**Comment by kevingranade** [comment]
> KSG has rails for underbarrel weapons

I did some quick reading, something I didn't realize is the underbarrel rail/grip is part of the pump action mechanism, that's a hard no to allowing weapons to be attached there.

There needs to be an adjustment to how mount points work to allow a grip but disallow a weapon before I'm ok with this.

**Pull request closed without merging**
