### PR TITLE
Improve CMake behavior on Unix and macOS

### PR DESCRIPTION
**Pull request by perryprog**
#### Summary
None

#### Purpose of change
I noticed a few build and install issues popping up after #65822 for me on macOS. Namely:
1. I was getting a linker error on compilation due to CoreFoundation being used but not linked in CMake
2. Installation locations were hecked up when using `-DUSE_PREFIX_DATA_DIR=Yes` because... okay, I'm not sure why but stuff would be installed to `/usr/local` instead of within `/usr/local/share/cataclysm-dda` as you might expect.

#### Describe the solution
1. Add CoreFoundation as a framework when building on macOS.
2. Set `CMAKE_INSTALL_DATAROOTDIR` to include the `/share/cataclysm-dda` suffix when building with `USE_PREFIX_DATA_DIR`. I'm uncertain if this is the ideal solution—@alef, do you know?
    - I also wonder if USE_PREFIX_DATA_DIR should just be on by default on Unix since I'm _pretty_ sure this is what most Unix people would want, but I'm content to leave it as is for now.

#### Testing
Stuff builds and installs in the right location. I'm hoping CI will catch any other obvious issues...

### CODE REVIEW

**Comment by perryprog** [comment]
Going to try making `USE_PREFIX_DATA_DIR` the default to see if that makes CI happy. (And because it's probably better for Unix users.)

**Comment by perryprog** [comment]
I'm confident enough that this should be good to merge despite the flaked CI failure stopping the CMake job from actually running.

**Comment by andrei8l** [comment]
> I'm confident enough that this should be good to merge despite the flaked CI failure stopping the CMake job from actually running.

The CMake job is already broken from the last CMake PR. Let's make certain it works this time

**Comment by perryprog** [comment]
> The CMake job is already broken from the last CMake PR. Let's make certain it works this time

Yeaaaaah, you're right. My impatience was just getting to me. 🙃

**Pull request merged**
