### PR TITLE
Mod list tabs for categories

### PR DESCRIPTION
**Pull request by OzoneH3**
Addition to #13763. Sorts categories into Tabs.

WIP because of a keybinding issue. For now it uses Tab, but because of that you can't leave the 'Mods to use' main tab.

How this could look like:

Change category tabs with TAB, BACKTAB. Change main tab with <, >.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Hmm. Dividing blacklist mods into a separate tab might help clean things up a bit, since these in turn can be divided into monster blacklists and item blacklists.

Assuming the keybindings can be sorted out.

**Comment by Coolthulhu** [comment]
> Dividing blacklist mods into a separate tab

You mean like they are in the screenshot or like "Mods to use" or "World Gen Options"? Because the latter would be an overkill.

Sorting their category to the bottom (or the top) would help, though. They represent a different kind of mod than additions. In fact, it would be a good idea to categorize mods by additions, deletions and conversions.

**Comment by chaosvolt** [comment]
Hmm. I was actually going off of the addition of a division between "standard" and "special" that seems...not sure what that's all about.

**Comment by OzoneH3** [comment]
Default and Special were just placeholders.

I updated the first post with new preview images of how it could look like.
I like the Blacklist tab idea, to further split exclusion mods.

Not sure what the actual final tabs will be. Any thoughts?

**Pull request merged**
