### PR TITLE
Dummy PR for bounty issue closing

### LINKED ISSUE #6824: 3-dimensional Z-level support, Core Part 5: ranged sight and attacks. [$110]
Master Ticket #6822
This will be a "bounty issue" for the development of z-line track development.

This issue concerns interaction between z-levels

This has following requirements:
Enemies with ranged weapons should be able to fire on the player from other z-levels
The player should be able to press a key to view a lower or higher z-level
The player should be able to view details on other z-levels
The player should be able to fire on other z-levels

<bountysource-plugin>
---
There is a **[$110 open bounty](https://www.bountysource.com/issues/1548692-3-dimensional-z-level-support-core-part-5-ranged-sight-and-attacks-110?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
I read #6824 and noticed that all of the enumerated requirements look fulfilled.

Those are:

> Enemies with ranged weapons should be able to fire on the player from other z-levels
> The player should be able to press a key to view a lower or higher z-level
> The player should be able to view details on other z-levels
> The player should be able to fire on other z-levels

While the FoV calculation itself isn't complete (has some bugs), it is complete enough to show that the above points are all possible:
- Turrets and NPCs can shoot up and down
- Player can look up and down
- Look command reveals details on other z-levels
- Player can target tiles on other z-levels

So, unless I'm missing something or some of the above are not done well enough

Closes #6824

### CODE REVIEW

**Comment by kevingranade** [comment]
I need a test case for having a turret target me from a different z-level and vice versa, I have z-level support enabled, and tried inter-z combat with a turret from both above and below them and couldn't get it to work.

**Comment by kevingranade** [comment]
Nevermind, I was just out of range when shooting the turret, I just need a way to get it to target me, or is it just theoretically capable and the AI won't do it?

**Comment by Coolthulhu** [comment]
> I just need a way to get it to target me, or is it just theoretically capable and the AI won't do it?

I think the turrets were bugged a week ago. I think it was the ammo bug that made them shoot blanks.

Another possible problem is the z-level vision. It is disabled by default (it is slooooow and a bit buggy in non-zlevel worlds) and the setting for 3D shadowcasting and 3D critter vision has to be a single setting (otherwise 'V' display would act weirdly).

**Comment by kevingranade** [comment]
Nada, I made a new world with the z-level option on, climbed on top of the starting shelter, made sure debug mode was on, and spawned in some turrets around the shelter, I could see them, but they didn't shoot me or go beep beep.

Just in case it was about building layout instead of the general code, I moved to an office tower and repeated the experiments, nada.

**Comment by Coolthulhu** [comment]
Was 3D vision (in debug settings) on? Debug mode enables player to see critters (for ease of testing), but everything else is explicitly hardcoded not to see anything outside own z-level if 3D fov is not enabled.

**Comment by kevingranade** [comment]
You are correct, I thought you meant the world option, I forgot there was an in-game option as well.

**Comment by Coolthulhu** [comment]
Thank you

Now it's just the FoV, mapgen, scentmap and we're full 3D. And scentmap looks easy

**Pull request merged**
