### PR TITLE
acetylene recipe no longer makes 250x more slaked lime than it should

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary
Bugfixes "acetylene recipe makes 50 slaked lime instead of 12500 slaked lime as a byproduct"

#### Purpose of change
 
I messed up in #62130, and I'm hastily correcting it (see comments on that PR)

#### Describe the solution

changed byproduct line to read `[ { "item": "chem_slaked_lime", "charges": 50 } ]` so it creates 50 individual charges instead of 50 fully charged instances.

However, the byproduct now inexplicably manifests a plastic bag when created, due to that being the default container of the item. I plan to fix that later by moving the container from the item to the spawngroup but fixing the mistake I made is my priority.

edit: I think I've fixed it now, moved the plastic bag to the itemgroup instead of the item.

#### Testing

MrDraMaster on the discord gave me this solution and even tested it on their own build, so thank you for that.
image
byproduct shows up as just a bag, but the lime is in it.

### CODE REVIEW

**Comment by Daved27hundred** [comment]
okay, so despite thinking I did twice, this branch isn't lined up properly with the master. Anyone know how to rebase a branch?

**Comment by RenechCDDA** [comment]
Unfortunately `byproducts` does not support this input. `byproduct_group` does, but 1) forces it to spawn in a container if default container is specified (specifying null just returns default container) and 2) *duplicates the container and contents*. I've been looking into these issues as part of #61874 and some C++ changes are needed to properly spawn in-container/default container items.

The straightforward path to resolving this *without* C++ changes is to remove the item's default container and change your current field to `byproduct_group`, then it should output properly.

**Comment by Maleclypse** [comment]
Please check that I fixed your conflicts correctly.

**Comment by Maleclypse** [comment]
```Error: ([slow] ~starting_items)=> Expected an array, got a 9

  {
    "result": "acetylene",
    "byproducts": [
                   ^
                    { "item": "chem_slaked_lime", "charges": 50 } ],
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",

([slow] ~starting_items)=> 23:04:51.191 INFO : Make sure that you're in the correct working directory and your data isn't corrupted.
test exited with code 1```

**Comment by RenechCDDA** [comment]
I grepped for chem_slaked_lime earlier and confirmed that is the only item group which uses it.

I've also implemented the changes locally and confirmed that they work as advertised. 50 units of slaked lime, not 12,500. The crafting gui is still wrongly reporting 12,500 but that should be resolved by my PR.

**Comment by Daved27hundred** [comment]
thank you for that renech

**Review by Maleclypse — APPROVED** [review]
Thanks!

**Pull request merged**
