### PR TITLE
Removed inappropriate books from schools

### PR DESCRIPTION
**Pull request by RarkGrames**
#### Summary
```SUMMARY: Bugfixes "Removed inappropriate books from schools"```

#### Purpose of change
School libraries spawn many books that outline practical methods and recipes for killing people. The PR removes the inappropriate books from library book item groups.

#### Describe the solution
Adding "manuals_school" and "textbooks_school" itemgroups, which are the same as "manuals" and "textbooks", except these books:

"manual_melee",
"manual_cutting",
"manual_stabbing",
"manual_knives",
"manual_gun",
"manual_shotgun",
"manual_rifle",
"manual_pistol",
"manual_smg",
"manual_launcher",
"recipe_bullets",
"howto_traps",
"manual_traps",
"textbook_gaswarfare",
"recipe_bullets",
"pocket_firearms",
"textbook_traps",

#### Describe alternatives you've considered
Leaving it as it is, as it has balance consequences.

#### Additional context
Archery and medieval armors/weapons are still in the group because archery is a sport, and medieval stuff can be historical information.
Removed the standalone dnd book from the school spawn list, it was a duplicate entry already in "manuals".

### CODE REVIEW

**Comment by TechyBen** [comment]
TBF my school did have "My ladybird first book of nuclear weapons". I went to a strange school.
(For ref: https://www.jenniferslittleworld.com/2014/11/ladybird-tuesday-story-of-nuclear-power.html Though I cannot remember if it was that exact one. It had a pic of a bomb in it IIRC anyhow)

**Comment by RarkGrames** [comment]
Yeah, mine had strange books too. But this book isn't the same as a step-by-step guide to how to build pipebombs or where to stab someone to kill him faster.

**Comment by eilaattwood** [comment]
Here should be a joke about USSR-style schools in New England.

**Comment by ZhilkinSerg** [comment]
Censure, huh?

**Comment by RarkGrames** [comment]
@ZhilkinSerg I'm not a hippie, but the first time finding a Spetsnaz knife training manual in a school was a pretty WTF moment.

**Pull request merged**
