### PR TITLE
Permanent marker weight reduction

### PR DESCRIPTION
**Pull request by Montimorency**
Permanent marker weight reduction

#### Summary
Balance "Permanent marker weight reduction"

#### Purpose of change
Permanent marker as a game item weighs a quarter-pound (113 g). It shouldn't.

#### Describe the solution
The game description divulges that these are based on the king-size Sharpie. 

Amazon has a 4-piece package of Sharpie King Size at 0.5 lb total, suggesting 0.125 lb (56.7 g/2 oz) per unit as a ceiling. The page also displays an "item weight" of 3.2 oz (90.7 g).

But this is an outlier. JetPens' detailed spec sheet assures us that the weight of one unit of the same marker, including ink and cap, is exactly 28g (~1 oz). The next supplier specifies an item weight of 0.297 lb for each 4-pack, for an individual unit weight of 33.68 g. They also list a carton of 96 (24x4) as weighing 7.59 lb, or 3442.77 g total, for a maximum of 35.86 g per unit. Uline lists their unit weight as 0.07 lb, or up to 32 grams.  Since we do have to account for packing weight, in all likelihood the exact 1 oz specification is correct.

If yet more corroboration is needed, other Amazon listings provide weight figures such as 4.16 oz for 4 markers, or even 1.37 lb for 24, which would come out to even less than 1 oz per marker. 

Perhaps some are instinctively discomfited by survivors rocking trenchcoats layered with markers, waiting to accost innocent merchants in dingy alleys. Nevertheless, I propose adjusting the weight of a permanent marker to 28 g (0.06 lb). The evidence convergently supports or permits this figure. Otherwise, reductio ad absurdum giant novelty marker.

giant-marker-pool-float-0

To compensate, I will for thorougness review the volume, which is currently 0.05 L, or just slightly barely bigger than a pen. According to the JetPens page, the grip diameter of the marker is 21 mm, while its capped length is 142 mm. By formula: 

V = πr^2h = π·10.5^2·142 = 49183.204

A good game approximation volume would thus be 0.049 liters, which is — wait a second. Whoops... maybe our pens are just too chunky?

So the volume should remain as is.  That's all for a day's work! Maybe next I'll draft-mode the PR in order to swap "permanent marker" from the Misc tool json to the Stationery tool json, if people think that's a good idea. I don't see why the marker entry shouldn't sit alongside the pen and pencil entries.

https://www.amazon.com/Sharpie-15661PP-Permanent-Marker-4-Count/dp/B0013CQ20Q
https://www.jetpens.com/Sharpie-King-Size-Permanent-Marker-Chisel-Tip-Black/pd/15854#index=1
https://www.ontimesupplies.com/san1799262-king-size-permanent-marker-broad-chisel-tip-assorted-colors-4-set.html
https://www.uline.com/Product/Detail/H-255BL/Pallet-Markers/Sharpie-King-Size-Markers-Black
https://www.amazon.com/Sharpie-15661PP-Permanent-Markers-Black/dp/B00PV19OV4
https://www.amazon.com/Permanent-Markers-Chisel-Plastic-Leather/dp/B0CPDSQ264

#### Describe alternatives you've considered
N/A

#### Testing
Markers now appear with the correct weight. 

#### Additional context
I noticed that ink is sized such that a full permanent marker contains 0.5 L of ink, despite being 0.05L in volume as a whole. Even regular pens, when full, contain 0.1 L of ink within a 0.04 L frame. Pencils are the same with graphite, but as their ammo type is not a fluid - dischargeable - the ammo volume doesn't get represented in the item description. This can't be solved by reducing the volume of permanent ink units, as they are 0.01 ml, which is the current hardcoded minimum. It's merely a trivial flaw in the math of the world, but I might as well highlight it.

### CODE REVIEW

**Comment by Maleclypse** [comment]
"permanent_marker had its density fixed, remove it from the list in data/mods/".

**Comment by Montimorency** [comment]
> "permanent_marker had its density fixed, remove it from the list in data/mods/".

I don't understand the instruction.

**Comment by Maleclypse** [comment]
> > "permanent_marker had its density fixed, remove it from the list in data/mods/".
> 
> I don't understand the instruction.

Goto this file `Cataclysm-DDA\data\mods\TEST_DATA\known_bad_density.json` and delete `permanent_marker` from the list in that file and your PR will be complete and ready to merge.

longer explanation.  We have a list of items that are known to have a bad density, that list exists so that people can fix it slowly rather than it breaking all tests until someone fixes every item on that list.  When someone fixes the density of any item on that list the test breaks until that item is removed from the list.

**Comment by Montimorency** [comment]
What have I done wrong? Was it "[Merge branch 'CleverRaven:master' into Permanent-marker-weight-reduction](https://github.com/CleverRaven/Cataclysm-DDA/pull/72117/commits/ef698484e689995c4b53f0326862af5f5dea4f75)"? 

I was just syncing to the master repository.

**Comment by Maleclypse** [comment]
> What have I done wrong? Was it "[Merge branch 'CleverRaven:master' into Permanent-marker-weight-reduction](https://github.com/CleverRaven/Cataclysm-DDA/pull/72117/commits/ef698484e689995c4b53f0326862af5f5dea4f75)"?
> 
> I was just syncing to the master repository.

I don't think you've done anything wrong.  This all looks good to me.  I've approved the test suite and once it's done if everything looks right to you as well this should be ready to merge. Thank you!

**Pull request merged**
