### PR TITLE
Turn on 3D FOV by default and combine its two options into one

### LINKED ISSUE #58601: Wasps able to hit player while player cannot hit them back due to XY mismatch
### Describe the bug

Giant wasps very often fly on the higher Z-level and attack the player from above. However when they do this they are misalligned, as they can hit the player from 1 tile diagonally or horizontally while the player can only hit from directly below a target. I assume this affects more than just wasps but they are the most common example.

in addition, the player cannot see wasps that are on a higher z-level, unlike with lower z-levels. This allows wasps to "sneak up" on the player if you're not constantly changing to the higher z-view when wasps are around since you can't normally see where they are.

Note in the screenshots how the wasp is a tile away from me in addition to above and can hit me while when I press TAB the game simply tells me no enemies are nearby. The solution is to step underneath the wasp obviously but it's very annoying that this has to happen at all.

### Steps to reproduce

1. Find wasps in the city.
2. Get attacked by wasps.
3. Observe wasps attacking from the wrong coordinate.

### Expected behavior

Wasps should only be able to attack from directly above the player since they do not have reach. 

### Screenshots

wasp1
wasp2

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 7ff3302 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

_No response_

### LINKED ISSUE #63276: Ascending a staircase on z-level 9 crashes the game
### Describe the bug

I tried to build stairs to z-level 10 to utilize the higher wind speed for wind power generation. However, aftering building a staircase on z-level 9 and ascending it, the game crashed.

### Steps to reproduce

1. Build a staircase on z-level 9 leading to z-level 10
2. Try to ascend the staircase
3. Game crashes

### Expected behavior

The game does not crash, and the player character either moves to z-level 10 or stays at z-level 9 (with a message stating 9 is the highest possible z-level).

Also, the code and comments here should be changed if the highest z-level is 9 rather than 10.
https://github.com/CleverRaven/Cataclysm-DDA/blob/bfe455e5267a8053ca9361265f31c76b727be446/src/game_constants.h#L70-L75

#60705 fixed a similar crash related to ascending with helicoptor, but that didn't seem to consider non-vehicle movement.

### Screenshots

_No response_

### Versions and configuration

c0335423ae9aed250c392a323372d0dc9170c112

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10496378/crash.log)

### LINKED ISSUE #69053: Enabling experimental 3D view cancels companion reading tasks when PC changes levels
### Describe the bug

Tasking companions to read books and then transition to another Z level causes those companions to "finish" their tasks, but only when experimental 3D view is enabled.

### Attach save file

[West Kingston-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13226439/West.Kingston-trimmed.tar.gz)

### Steps to reproduce

1. Walk downstairs and up to the companion strangely (but not relatedly) removing a bench on the level above, and note that the 3 beggars reading won't care about it.
2. Walk back up, enable experimental 3D view and return back down to the companion downstairs.
3. See that the reading beggars will stop reading.

### Expected behavior

3D experimental view should not affect companion activity, and, if it should have any effect, it should enable 3D activity, rather than kill it.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4823-g033a9b7373 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

### Additional context

Non important ramble below.

Discovered it accidentally as upgrading to a new experimental version seemed to degrade companion behavior. However, it turned out I'd forgotten to disable it after desperately trying to get out of the trap formed by a cockroach blocking the path up from a cellar (the type with a ramp, in particular a doomed future Tacoma farm (doomed because it's surrounded by fungaloids on at least 2 sides, and probably all 4)). As I couldn't move past it (warnings on) or attack it (warnings off) I tried to enable 3D view to at least be able to shoot at it, but it still couldn't be targeted. Ended up debug killing the vile critter as it wouldn't come down either.
I believe you can now try to squeeze past zombies blocking stairs (at least I think I've seen that trying to move downstairs), so maybe a similar thing is needed for ramps?

### LINKED ISSUE #71185: Terrain tiles on different z level no longer drawing.
### Describe the bug

Z-level terrain is no longer drawing graphically.  Experimental Z-levels are disabled.

### Attach save file

N/A

### Steps to reproduce

1. Create a new world at evac center with experimental z-levels disabled.
2. Climb to roof.
3. z-0 terrain tiles are 'visible' when moused over, but graphics are not revealed.
4. Peeking down will reveal the tiles, and they will be visible from memory afterwards.

Alternatively, fly around in a helicopter.

### Expected behavior

Terrain tiles graphics should be drawn, expected behavior still works in 2023-12-18-0506.  Experimental Z-levels functioning a bit oddly too, but peeking seems to be working properly.

### Screenshots

Before peeking and after peeking.  ''Below: Grass" is visible in both screenshots.
beforepeek
afterpeek

From top of apartment building, before and during peek.
zlevels odd
zlevels peek

view from z-5 in 2023-12-18-0506 with FOV off and no map memory

z5 expected

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 31e4c0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Possibly related to https://github.com/CleverRaven/Cataclysm-DDA/pull/70957 ?  Just a wild guess.

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
Interface "Turn on 3D FOV by default and combine its two options into one"

#### Purpose of change
Closes #71185. Fixes #63276. Closes #69053. Closes #58601 since I cannot no longer reproduce it (but it may have already been fixed before this PR).

3D FOV has been working fine for a while and I finally managed to fix the unit test errors caused by turning it on, so let's do it.

The old colored blocks display of the level below can be restored by setting 'Vertical range of 3D field of vision' to 0, but I don't think it is worth supporting multiple-level vision with colored blocks display because the main reason for the colored blocks display is performance and multiple-level vision is going to affect performance anyway, and fewer options make it easier to maintain the vision code.

Here's a list of previous behaviors (from my memory, didn't bother to test so do correct me if I'm wrong) and current behaviors. Most of the previous behaviors are still supported.

|                                               | FOV_3D | FOV_3D_Z_RANGE | Behavior & comments |
|-|-|-|-|
| Before multi-level rendering | On         | 0                             | Colored blocks & no z-level vision (Still supported) |
|                                               | On         | non-zero                 | Colored blocks & z-level vision (Not supported. Multi-levels are displayed instead. If performance is a concern, reduce the z-range value or change it to 0 to re-enable colored blocks) |
|                                               | Off         | 0                             | Colored blocks & no z-level vision (Still supported) |
|                                               | Off         | non-zero                | Colored blocks & no z-level vision (Changes into multi-level display) |
| After multi-level rendering   | On         | 0                             | Colored blocks & no z-level vision (Still supported) |
|                                               | On         | non-zero                | Multi-level & z-level vision (Still supported) |
|                                               | Off         | 0                            | Colored blocks & no z-level vision (Still supported) |
|                                               | Off         | non-zero                | Multi-level & no z-level vision (Not supported. Z-level vision is always enabled for consistent information.) |
| Now                                      | On         | 0                            | Colored blocks & no z-level vision |
|                                               | On         | non-zero               | Multi-level & z-level vision |

#### Describe the solution
1. Removed the `FOV_3D` option and code for `fov_3d == false`. Unified handling of `fov_3d_z_range` in the process.
2. Fixed monster attack test by only allowing monster to stumble into the player when adjacent and properly implmenting the test for `FOV_3D` enabled.
3. Fixed the player activity interruption test failure that has been haunting us, by forcing the weather to `WEATHER_CLEAR`.
4. Fixed crash when moving or shifting view outside the z-level range.

Regarding 3; Turns out if the weather is changed due to previously run tests, the seen cache will be different. In this case the weather is `mist`, which seems to cause the player character to see through a wall column for a brief in-game second, which can also be reproduced in-game, and looks like #65205. The transparency cache also doesn't look right when the weather is `clear` in the test; z-level -1 seems to be considered to have the same transparency as air, although this problem does not happen in-game. I did not bother to fix these problems in this PR though; someone with more experience with the shadowcasting code should probably look into it.

#### Describe alternatives you've considered
Not doing this; Keep the FOV_3D option.

#### Testing
Ran the unit tests and they passed. Moved around in-game and the shadows looked reasonable. Tried to move character or cursor to z-level 10, they did not move and the game did not crash.

The filter that reproduces the player activity interruption test failure is `[vehicle], activity_interruption_by_distractions`.

#### Additional context

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I believe #69053 remains a relevant hindrance.

**Comment by Qrox** [comment]
@PatrikLundell It seems the light map is only built on the player character's z level even with FOV 3D on, which caused NPCs to abort activities when the player character moves to a different z level. I worked it around by using the old behavior from non-3D-FOV mode, i.e. let NPCs continue activities when not on the same level as the player character. Building the light map for NPCs could be expensive, especially if there are multiple z levels with NPCs, so I didn't go that route.

**Comment by andrei8l** [comment]
The test `npc_light_and_fine_detail_vision_mod` can probably go. I made the wrong assumption there and it basically only checked that sunlight propagated down in open spaces.

**Comment by Qrox** [comment]
@andrei8l I changed the test to use the test cases from non-3D-FOV mode, but I think we can keep the test to ensure that no one changes `fine_detail_vision_mod` without also reworking lightmap generation.

**Pull request merged**
