### PR TITLE
Incorporate human meat and fat into existing recipes, remove dedicated recipes

### LINKED ISSUE #35621: Human lard not usable in other recipes
# Describe the bug

Human lard can't be used in other recipes. Even cannibal recipes require animal fat.

# Steps To Reproduce

1. Play as a Cannibal. Procure human lard using your book's recipe.
2. Search "c:human,c:lard"
3. Human lard can't be used in any other recipes.

# Expected behavior

Human lard should be usable like any other fat

# Versions and configuration

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2
- Game Version: 0.D-9240-g1bb08dd [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy]
]

# Additional context

Playing a creepy cannibal-type, and I've noticed that human lard can't be used in other recipes. Even cannibal recipes don't list human lard as an option, and require you to use animal fat instead. This seems like a simple oversight, a small but important tweak for players who want to go a little bit Hannibal. There's no logical reason it can't be used like any other fat.

EDIT: Human tallow shares this issue.

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
#### Summary
```SUMMARY: Balance "Incorporate human meat and fat into existing recipes, remove dedicated recipes"```

#### Note for reviewers
Only [these commits](https://github.com/CleverRaven/Cataclysm-DDA/pull/35630/files/f5ed93809c71724c207d70a06b424ec7bab52bdb..4f5fbe673749067ca21788e3b2cc36979a2d35de) are relevant, the rest of the commits are from #35711 and should disappear when it is merged.

#### Purpose of change
The goal is to eliminate the need for duplicated recipes that use human meat, using the new inheritable flags and conditional names capabilities.

Fixes #35621 
Requires #35711 

#### Describe the solution
1. Make CANNIBALISM flag inheritable, meaning anything crafted from items made of `hflesh` will also trigger effects of eating human. (9a6517b)
2. Refactor meat-related cooking components lists to reduce duplication, allowing for future commits to make fewer changes. (aca21e3 shuffles entries around, 9f0ec00 adds a few new entries)
3. Add human meat, fat, lard, and tallow to every single recipe that uses normal meat, fat, lard, or tallow, with two exceptions: Dog/cat food, and mutagen. (dc34863)
4. Fixed a conflict where dry meat and jerky would not inherit CANNIBALISM due to having NO_CRAFT_INHERIT. This flag was added to prohibit them from getting the BAD_TASTE flag when made with mutant meat. This was an addition made by myself, with pretty arbitrary justification, so I elected to just remove NO_CRAFT_INHERIT from these two items. (63cfb06)
5. Obsolete human-meat-only dishes and recipes, adding migration entries for them for save compatibility. (a6a8ddf)
6. Added conditional names (see #35711) to cannibal dishes so that the existing alliterative and punny names are preserved. (bf56b13)

#### Testing
All items were double checked in-game, and I crafted a few items using human flesh/fat to ensure nothing odd was happening to stop the CANNIBALISM flag from being inherited properly.

#### Additional context
Screenshot to show that the old names were preserved under the new system (singular and plural shown):
image

Screenshot showing how the old names combine with the mutant-meat-dish names added in #35711 (again, singular and plural both shown):
image

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Contextual names would actually be a wonderful idea, but . That would allow a lot of variable names, particularly if you allow flags *or* item IDs in the contextual bit. Then, for example, the PB&M sandwich could just be a peanut butter and honey sandwich using maple syrup as a substitute ingredient. Many recipes could be consolidated with that mechanic.

**Comment by DaviBones** [comment]
While your idea about accepting item IDs is great, after looking at peanut butter sandwiches, I don't think they're a great candidate, because they each have different material entries which can't really be consolidated in any way I can think of.

That said, I have coded it, and have a few ideas of my own for applications.

**Comment by Kodiologist** [comment]
Clearly what's needed is a fully general sandwich subsystem where arbitrary food items can be combined into a new food item and the enjoyability of the result is determined by a neural network trained on Yelp reviews.

**Comment by ZhilkinSerg** [comment]
Can you resolve conflicts please?

**Comment by DaviBones** [comment]
Ok, done.

**Comment by adamkad1** [comment]
i wonder if it would be possible to make variations need special books, like you needing 'to serve man' to use human meat where meat it needed

**Comment by Kodiologist** [comment]
I can't speak from experience, but I imagine that cannibalistic cooking doesn't require any skills above and beyond that of using ordinary meats, except perhaps an absence of shame.

**Comment by adamkad1** [comment]
> I can't speak from experience, but I imagine that cannibalistic cooking doesn't require any skills above and beyond that of using ordinary meats, except perhaps an absence of shame.

Pretty sure different meats got different properties. maybe the book could atleast give bonus fun value to food for being prepared 'properly'

**Pull request merged**
