### PR TITLE
[WIP] update retrodays+ to 16x16

### PR DESCRIPTION
**Pull request by captnblood**
#### Summary
SUMMARY: Content "update retrodays+ and conversion to 16x16"

#### Purpose of change
conversion of retrodays+ to 16x16
and general update, many tile changes.

#### Testing
i've tested playing as i modify tiles along. this will take some time to finalize but it is already usable.
it still need more clean up on some tiles that were resized badly but i'm getting there, fixing them.

#### Additional context
the goal is to make retroplus use 16x16 instead of 10x10.
the extra gain of space per tile allows to have retroplus just a little bit more detailed while also keeping it mostly true to itself and its origin (retrodays classic). 
this is a work in progress, and it will take me time to draw all the monsters one by one (see screenshots). but that being said, it works already reasonably well and is a good update over previous retroplus. i create the pull request to share the work so far, allow everyone to test and eventualy adapt their work to the new tile size. ( @Wokko1 if you read this, your hats PR was very nice and much appreciated. do you think you could update your hats tileset to 16x16 ? )

another advantage with the 16x16 size is that objects now fit nicely, in or on, furniture.
i plan to keep all objects to their original size of 10x10, but furniture will use 16x16. so for example, the cupboard will not be hidden by the objects it contains anymore.

this nothing revolutionary, but, the small gain in pixel per tile permit more character customisations
and for furnitures too. here's a quick example:
preview

and in-game:
retroplus-update
retroplus-update4

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
20x20 should be easier to transform and would provide even more space.

**Comment by captnblood** [comment]
> 20x20 should be easier to transform and would provide even more space.

thanks for telling, but i wanted to stay close to the original, and not go too high in resolution. 
i thought that 16x16 was a good standard, just increasing from 10x10 a little. enough to allow a bit more liberties and comfort when editing tiles i just needed a few more rows, but not too much.
and beside, all the work is already done and working.
this is subjective of course, but i like the result. it's like retrodays+ but a just little bit better everywhere.

**Comment by esotericist** [comment]
i think this needs to be a separate tileset.

going from 10px to 16px is not a drop-in change; because it isn't a multiple of the original tileset, you cannot maintain per-pixel proportions. this *will* have stylistic impact, making it have a different 'feel' to many people.

going to 20px would let you maintain proportions, but at that point it's a substantially higher resolution which results in a different feel anyway.

further, these tilesets are maintained in a decomposed format in another repository; editing them here isn't going to "stick" because it'll just get replaced when they're merged from upstream.

**Comment by or-or** [comment]
Agree with Esotericist. Also, you already made some significant stylistic changes away from the original, like the pillow shading, and detail and colour increase. This is not so much an "enhancement" of retrodays+ and more an entirely different take on the retrodays concept (one that breaks with the original idea at that, imo).

**Comment by ZhilkinSerg** [comment]
Yeah, let's rename it to make a new tileset, so we will have:

- Retrodays (10x10, opaque black background)
- Retrodays+ (10x10, transparent background)
- your new tileset (16x16, transparent background)

You can even name it Retrodays++ (and we will then enhance it with sharp filter and make a fourth tileset named Retrodays# ).

**Comment by I-am-Erk** [comment]
For a change of this magnitude I really need to demand that you join us over at https://github.com/I-am-Erk/CDDA-Tilesets and work with the source files. This is going to mess up compatibility between the two repositories and permanently erase any contributions on the source side that haven't been added to mainline yet.

**Comment by captnblood** [comment]
@I-am-Erk 
i went to check your repo about tilesets and i see that some work already took place there on retrodays+.
i mean work that haven't been released yet, also structural changes, file splitting, tiles additions and more.
that is nice, i didn't know that was happening there. 

hmm.. i would need to have a talk with you and the other retroplus contributors about how to proceed. i have some questions. where would it be better for me to ask them ? on discord, cdda forum, or on your github repo, by creating an issue maybe ?

i would like to ask things like: 
- should really this be made a standalone, yet another, retrodays based tileset?
- how to contribute my work to your repo, i mean, can i do it on a tile by tile individual upload/share or should i finish and make available the whole tileset in one big "contribution/share/upload" ?
 - what's the release schedule plans are ? i mean why is there some change on tilesets there (on your repo) that haven't been made available yet ? when are they supposed to be be released ? there is a something like a roadmap or release schedule that you and the others are conforming to ?
- where can i discuss ideas that are like those i implemented in this github PR, i mean like changing tileset resolution, putting faces on monsters, other characters and so on..

**Comment by I-am-Erk** [comment]
You could post an issue on the GitHub or you could come talk at https://discord.gg/kAXNZuy, those are probably the fastest ways to get in touch with your questions. I don't really do much for rd myself, better to talk to the people working with it for answers.

**Comment by captnblood** [comment]
@I-am-Erk and others

i opened a new issue on Erk's repo to discuss the thing in more details. 
for those interested, here: https://github.com/I-am-Erk/CDDA-Tilesets/issues/244

**Comment by captnblood** [comment]
> Yeah, let's rename it to make a new tileset, so we will have:
> 
> * Retrodays (10x10, opaque black background)
> * Retrodays+ (10x10, transparent background)
> * your new tileset (16x16, transparent background)
> 
> You can even name it Retrodays++ (and we will then enhance it with sharp filter and make a fourth tileset named Retrodays# ).

@ZhilkinSerg 
exactly.. that same kind of thing happened too when i created retrodays+
people wanted me to name it silly, like "retrodays_with_transparency" and things like that.
initialy, i wanted to modify retrodays itself. but i was told my work was bad because it would destroy retrodays in essense. i was told to create a new tileset, to which i complied and named it: "retrodays+". but then i was told:  "it's too similar to "retrodays", "it's useless to create a new tileset for that" ... i replied then: i had plans for the future and they should wait and see what was coming and that i would make it a worthwhile addition to the cdda tileset familly. i replied that i could understand they wanted to protect the original, and i accepted to make it a new tileset to implement my ideas that seemed too destructive to the original for people to accept it.

and now the same kind of talk are starting again..
"why do you do that ?" 
"it's not needed. leave retrodays alone"
"make a new tileset, name it xyz" .. and so on ..

and now folks want me to create yet another retrodays based tileset to implement my ideas. which seems a bit silly to me because _that_ was the very reason i had created retrodays+ for.

**Comment by kevingranade** [comment]
captnblood is a bandodging account of nsklaus.
Feel free to maintain your version of the tileset outside the main repository.

**Pull request closed without merging**
