### PR TITLE
Rebalance oatmeal json values and recipes

### LINKED ISSUE #51606: oats, oatmeal and cooked oatmeal calorie bug means haggis disobeys thermodynamic laws
### Describe the bug

Someone please double check this, but it I tried making a haggis from 16 oatmeals, 4 piece of kidney, and a stomach.  The result was a single bomb of food with 3072 calories that i have to consume all at once - one portion. I think this is because the recipe for oats and oatmeal_cooked are a bit out of whack (10 cal of oatmeal turns into 175 cal of oatmeal_cooked) , and oats used in recipes cooks_like oatmeal_cooked.

### Steps To Reproduce

Take the above ingredients and produce a haggis.

### Expected behavior

I expected the haggis to be less calories becuase of the ingredients, according to JSONs in the github these are the caloric values of the  ingredients:

stomach - 60cal x 1 = 60
kidney - 54 cal x 4 = 216
oatmeal 10 cal x 16 = 160
expected total = 436

### Screenshots

_No response_

### Versions and configuration

osx 10.11.6
version F-1
curses

### Additional context

Looking at the jsons on the github, i think the problem is the cooked oatmeal, and some other strange things about oats.

Oats  x 1  = 323 cals

the oatmeal recipe uses 2x oats (646 cals) to produce 16 charges of oatmeal at 10 cals each.
16 x 10 = 160 calories.  Ok so we lost like a 500  calories just crushing the oat grains. I doubt that is accurate.

But anyway besides that, then to produce cooked oatmeal from oats, **we need only 1 charge of oatmeal, which is just 10 calories, but it produces a portion of cooked oatmeal that's 175 calories.**  I know cooking releases nutrients and all that, but not by a  factor of 17.5! 

re: the haggis i notice that oatmeal has a cooks_like tag of oatmeal_cooked, it is benefitting from this oatmeal bug.  

now we're getting 
stomach - 60cal x 1 = 60
kidney - 54 cal x 4 = 216
oatmeal > oatmeal_cooked - 175 cal x 16 = 2800
 
=   3076 cals, which is what the haggis is!

### PR DESCRIPTION
**Pull request by Kribylet**
#### Summary
Balance "Update json values for oatmeal to fix inconsistent haggis recipe"

#### Purpose of change
Fixes #51606. Oatmeal had several calorie content inconsistencies; oats were milled into oatmeal at a ratio of 1:8 with a large calorie content loss. This was then adjusted for using a cooks_like tag to recover the calories. This calorie gain was much greater than could be justified.

>2 oats:  646 kcal, 500 ml, 172g
Processing:
>16 oatmeal, 160 kcal, 250 ml, 400g
Cooking:
>16 cooked oatmeal, 2800 kcal, 4000 ml, 3952g

#### Describe the solution
I adjusted the rate that oats are processed into oatmeal and adjusted the nutrition value of the resulting oatmeal so that 1 unit of oatmeal reasonably corresponds to one unit of oatmeal_cooked. Additionally I went through the recipes that use oatmeal and adjusted the amount of oatmeal used in them to more closely match their alternatives by weight.

>2 oats:  646 kcal, 500 ml, 172g
Processing:
>4 oatmeal, 524 kcal, 500 ml, 140g
Cooking:
>4 cooked oatmeal, 604 kcal, 1000 ml, 988g

The oatmeal requirement for the cloutie dumpling recipe wasn't adjusted. All alternatives were weight discrepant so there was no clearly correct amount:
1. Buckwheat, ~180g
2. Flour, ~65g
3. Oatmeal, 25g (previously) 

#### Describe alternatives you've considered

1. Leaving the 1:8 processing ratio, fixing the oatmeal calorie content then making oatmeal_cooked have the correct number of calories based on that ratio. Rejected because cooking/eating oatmeal seemed needlessly tedious at ~ 40 kcal portions and because this solution would also nerf world oatmeal item spawn calorie contents. 

#### Testing

1. Processing oats into oatmeal by recipe to see rough preservation of calorie content
2. Cooking oatmeal into oatmeal_cooked, slight increase in calorie content (~20 extra kcal per portion, removes raw food debuff)
3. Cooking oatmeal into granola, now more on par with dry_rice but requires more oatmeal units since oatmeal weighs less by unit.
4. Cooking oatmeal into cookies, now more on par with dry_rice but requires more oatmeal units as above
5. Cooking oatmeal into haggis, now on par with using buckwheat (~1000-1200 kcal per unit)

#### Additional context

The cooked oatmeal was adding calories on top of removing the raw tag so I assumed this was intended behavior, though it seems a little bit odd that food items should gain calories from being cooked in two different ways at the same time.

### CODE REVIEW

**Comment by Kribylet** [comment]
Windows build seems to be failing due to a JSON error in a file not changed by the pull request; please let me know if there's something I should do about that.

**Comment by Kribylet** [comment]
Seeing these test failures:

>D:\a\Cataclysm-DDA\Cataclysm-DDA\tests\comestible_test.cpp(147): FAILED:
  CHECK( mystats.calories.avg() <= upper_bound )
with expansion:
  979.0909090909 <= 676.08197f

>RecipeID: haggis, default is 441 Calories,
Current recipe range: 792-1208, Average 979.1, Stddev 117.5
Average recipe Calories must fall within this range, derived from default Calories: 206-676

>D:\a\Cataclysm-DDA\Cataclysm-DDA\tests\comestible_test.cpp(147): FAILED:
  CHECK( mystats.calories.avg() <= upper_bound )
with expansion:
  1998.1818181818 <= 1365.60986f

>RecipeID: haggis_large, default is 882 Calories,
Current recipe range: 1584-2536, Average 1998.2, Stddev 241.8
Average recipe Calories must fall within this range, derived from default Calories: 398-1366

Surely related to the change, but I am curious as to how the previous haggis recipe did not trigger a warning.

**Comment by kwl01skz** [comment]
For example, if flour has 10 calories, 5 flour = 1 bread, and bread has 50 calories.  If you change the calories of flour to 20, but do not change the calories of bread to 100, this error will be reported.

**Comment by Kribylet** [comment]
> For example, if flour has 10 calories, 5 flour = 1 bread, and bread has 50 calories. If you change the calories of flour to 20, but do not change the calories of bread to 100, this error will be reported.

That makes sense. The oatmeal variant of the haggis recipe produced haggis with 3000~ kcal, so I was confused how the default haggis calories of 441 didn't trigger this. Does the test ignore cooks_like tags for calculations?

**Comment by kwl01skz** [comment]
> > For example, if flour has 10 calories, 5 flour = 1 bread, and bread has 50 calories. If you change the calories of flour to 20, but do not change the calories of bread to 100, this error will be reported.
> 
> That makes sense. The oatmeal variant of the haggis recipe produced haggis with 3000~ kcal, so I was confused how the default haggis calories of 441 didn't trigger this. Does the test ignore cooks_like tags for calculations?

 I guess the gap between the material in the recipe is very large and the old Haggis in this interval.

**Comment by Kribylet** [comment]
> > > For example, if flour has 10 calories, 5 flour = 1 bread, and bread has 50 calories. If you change the calories of flour to 20, but do not change the calories of bread to 100, this error will be reported.
> > 
> > 
> > That makes sense. The oatmeal variant of the haggis recipe produced haggis with 3000~ kcal, so I was confused how the default haggis calories of 441 didn't trigger this. Does the test ignore cooks_like tags for calculations?
> 
> I guess the gap between the material in the recipe is very large and the old Haggis in this interval.

I can't quite make heads or tails of the testing tools despite looking at it for an hour or so but I am pretty sure no haggis recipe in the previous system was able of going below 600 kcal since all oatmeal variants would have a 16*175=2800 kcal floor from the oatmeal alone, and the buckwheat variant has a ~600 kcal floor from the buckwheat. It seems to me  that the only way the test could pass the old haggis recipe seems to be if it calculated the haggis calories based on the oatmeal without looking at the cooks_like tag for the oatmeal.

**Comment by kwl01skz** [comment]
The computer is not by my side, I will check after the holiday

**Comment by kwl01skz** [comment]
```
"id": "oatmeal",
"weight": "25 g",
"calories": 10,
"charges": 16,
"flags": [ "EDIBLE_FROZEN", "NUTRIENT_OVERRIDE", "RAW" ],
```

You see, old oatmeal only 10 calories / 100g.
16 * 25g = 400g, just 40 calories.

**Pull request merged**
