### PR TITLE
Fixed KSG

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
The KSGs' gunmod lacked weight and volume, which caused it to have inconsistent recoil and aim speed compared to the base gun. This PR divides the weight of the gun equally between the mod and gun, and add volume 7 and integral volume 0 to the mod.

### CODE REVIEW

**Comment by mugling** [comment]
Correct solution is to fix auxiliary mod recoil calculation to use base weights

**Comment by BorkBorkGoesTheCode** [comment]
Do you have a fix?

**Comment by mugling** [comment]
No, but this PR obfuscates any actual fix - it's a JSON hack in core for a non-critical issue. That's a very bad idea

**Comment by Coolthulhu** [comment]
Don't we have `integrated_weight`? If not, it could be added just for cases like this one. Though it would need a core item to use it.

**Comment by mugling** [comment]
No, but we probably should. It would still be better (and probably quite simple) to fix this problem at source. JSON hacks should be temporary solutions for critical problems

**Comment by BorkBorkGoesTheCode** [comment]
have I offended you in any way @mugling ?

**Comment by mugling** [comment]
Not at all. I've just got back from the weekend and there are ~100 notifications to wade through so I'm trying to address them all quickly in sequence.

Discussion is part of any project and inevitably focuses around PR's that have problems. Try not to generalise from that weighing though. It's the sum total of your work that counts - for example  #19148 is a welcome contribution.

**Pull request closed without merging**
