### PR TITLE
Adds batch crafting variable to lye recipe.

### PR DESCRIPTION
**Pull request by Rivet-the-Zombie**
It should have it, since it's a boil-stuff-in-a-bucket recipe.

### CODE REVIEW

**Comment by Core0verload** [comment]
What do the bath factors mean?

**Comment by Rivet-the-Zombie** [comment]
With the batch variable enabled, making a bunch of something at once is quicker than making the same amount of stuff one at a time.

**Comment by Core0verload** [comment]
No, i'm about the [80, 4] values. I know they are some sort of time multiplier, but what do they exactly mean?

**Comment by Rivet-the-Zombie** [comment]
80% time reduction, which scales as you increase the batch size, achieving the full value at four items.

**Comment by Coolthulhu** [comment]
Doesn't seem to work. Spelling?

**Comment by Rivet-the-Zombie** [comment]
@Coolthulhu, spelling? Was your comment meant for this PR?

**Comment by Coolthulhu** [comment]
Yes
I mean the tag name
Could be an extra 's' or something like that.
During testing the craft time was always `3 hours * batch size`. I double checked to make sure I merged it.

**Comment by Rivet-the-Zombie** [comment]
Odd, I just copy+pasted it from clean water's recipe. Back to it!

**Comment by Coolthulhu** [comment]
Odd, it didn't work when I was testing it.
Might be one of the debug traits?

**Comment by kevingranade** [comment]
I saw some inconsistency too, but I was able to trigger the batching
discounts eventually, so the definition is correct.
Other crafting penalties like poor lighting might eat into the projected
(and actual?) crafting time. Just a guess.

**Pull request merged**
