### PR TITLE
Jeweler profession

### PR DESCRIPTION
**Pull request by Daved27hundred**
#### Summary
Content "Adds a jeweler as a new starting profession"

#### Purpose of change

More options for characters. This profession could be considered A sidepath to the blacksmith profession, trading the useful blacksmithing proficiency for several, lesser used and more specific proficiencies.

#### Describe the solution

Adds the jeweler as a profession, which starts with fabrication 6 and a metalworking chisel. The proficiencies they start with are Metalworking, Fine Metalsmithing, Redsmithing and Gem Setting (Redsmithing is required by Gem setting, which requires metalworking.) 

#### Describe alternatives you've considered

removing some of the proficiencies they start with or not adding them altogether. I'm also open to changing the description bc I think it could use work..

#### Additional context

Gem Setting currently does nothing, I hope this gets fixed in the future.

### CODE REVIEW

**Comment by Brambor** [comment]
I saw somewhere a comment like this:

Why does the jeweller have swimming 2? Is it required? You are forcing the player to have swimming 2 if they choose the jeweller profession, which limits roleplay. It is better to let them decide if they want swimming 2.

**Comment by Daved27hundred** [comment]
@Brambor Swimming was renamed to "athletics" and made to cover various activities instead of just swimming. It's still named swimming in the code.
The blacksmith had athletics 2, so I gave them it since they work with similar tools

**Comment by Rabadash94** [comment]
The jeweler might also have some basic knowledge of chemistry.

**Comment by Daved27hundred** [comment]
how so?

**Comment by Rabadash94** [comment]
With Principles of Chemistry proficience, like the lab technician.

**Comment by Rabadash94** [comment]
If you're asking why, jewelers need basic chemistry knowledge about metals and gems, and some chemical agents, such as acids.

**Comment by Daved27hundred** [comment]
I'll probably need a more concrete source for that before people raise their eyebrows at it.

**Comment by Daved27hundred** [comment]
looked it up, Chemical etching is a thing. I'll add an applied science skill, but I think principles of chemistry is too much for them.

**Comment by Daved27hundred** [comment]
Coming back to this - I think the fact that none of the jewelry crafts require any chemistry or applied science skill to make should tell me that the profession doesn't need it. Maybe that can change in the future, when there's more jewelry crafts, but for now I'm keeping it as is.

**Pull request merged**
