### PR TITLE
Unhardcoded NPC destinations (using new class)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- NPC destination terrains for various needs can now be loaded from new json (`\data\json\npcs\npc_destination.json`).

***

Either this or #23111 should be merged.

### CODE REVIEW

**Comment by codemime** [comment]
There are now three record types which look very alike and do basically the same thing: `start_location`,  `overmap_location`, and your `npc_destination`. I suppose they'd benefit from coalescing into one. #22724 was a step towards it.

**Comment by ZhilkinSerg** [comment]
Hmm, we can add `npc_needs` node to `overmap_location`...

**Comment by codemime** [comment]
I think it should remain as narrow as possible. We essentially need to map NPC needs to the corresponding locations. The mapping can be left hardcoded for now (`need_id()` does this).

**Comment by ZhilkinSerg** [comment]
So, you mean we don't need new npc destination clads, but move what is in npc destinations json now to overmap locations json and do mapping to overmap locations via need_id function?

**Comment by ZhilkinSerg** [comment]
And we can do similar thing with start locations in separate PR.

**Comment by ZhilkinSerg** [comment]
Also mission destinations.

**Comment by ZhilkinSerg** [comment]
> I think it should remain as narrow as possible. We essentially need to map NPC needs to the corresponding locations. The mapping can be left hardcoded for now (need_id() does this).

Take a look at this #23111.

**Pull request closed without merging**
