### PR TITLE
Refactor base camp code to make it more sane, and fix translation issues

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
SUMMARY: Bugfixes "Fix text untranslated in base camp UI"

#### Purpose of change
I noticed several translation issues when fixing the static gettext calls in `faction_camp.cpp`, so I decided to solved it. Unfortunately, what was supposed to be a simple translation fix escalated into a full refactor... for sanity's sake.

#### Describe the solution
1. Fixed base camp mission name (recipe blueprint name and recipe descriptions in recipe groups) untranslated in the base camp UI.
2. It was mapping these names and description *to* the recipe id! Not only does it sound absurd, it was also causing bugs since some code wrongly used the recipe id as the key. Made it the other way around and used `recipe_id` and `translation` instead of `std::string` for better type safety.
3. Hide scrollbar if the base camp UI can show all text at once.
4. Fixed base camp mission description (recipe description) untranslated. Item type descriptions are also changed to use `translation` due to dependency on recipe descriptions. Artifact item descriptions are stored using `no_translation`, since they are generated. This also ensures that the genereated descriptions are not double-translated.
5. The code was passing untranslated direction abbreviations around for both indicating directions and composing camp mission ids/names. It now distinguishes between direction vectors, direction ids, and direction names, and mainly passes direction vectors around instead of ids. Also found and fixed a few buggy functions thanks to the improved type safety.

### CODE REVIEW

**Comment by davidpwbrown** [comment]
Yep, basecamp/faction camp code was doing a lot of stuff with strings being passed around and compared, and typos here and there caused all sorts of nonsense.
Its what we inherited though....  @mlangsdorf will probably have an opinion on this. I'll try and review what I can, though looking at the basecamp code always gives me a headache.

**Comment by mlangsdorf** [comment]
This looks fine to me if it works.  My question is whether you can send NPCs out on basecamp missions without these commits and retrieve them after these commits have been applied.  I can't tell if that was tested or not.  If that was tested and works, then I approve these changes.  If not, I don't.

**Comment by Qrox** [comment]
> whether you can send NPCs out on basecamp missions without these commits and retrieve them after these commits have been applied.

The underlying mission ids haven't been changed, so it's unlikely to cause any save compatibility issues. I tested nontheless, and missions were correct loaded from a save created without this PR, and retrieving NPCs and crafted items worked fine with no problem.

**Comment by mlangsdorf** [comment]
Thanks for the testing, and thanks for helping clean up this code.

**Comment by ZhilkinSerg** [comment]
Something is up in VS build:
```
  basecamp.cpp
c:\projects\cataclysm-dda\src\basecamp.cpp(40): error C2065: 'TAB_MAIN': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(41): error C2065: 'TAB_N': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(42): error C2065: 'TAB_NE': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(43): error C2065: 'TAB_E': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(44): error C2065: 'TAB_SE': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(45): error C2065: 'TAB_S': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(46): error C2065: 'TAB_SW': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(47): error C2065: 'TAB_W': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
c:\projects\cataclysm-dda\src\basecamp.cpp(48): error C2065: 'TAB_NW': undeclared identifier [C:\Projects\Cataclysm-DDA\msvc-full-features\Cataclysm-vcpkg-static.vcxproj]
```

**Comment by Qrox** [comment]
That sounds like a bug in VS. According to [this](https://en.cppreference.com/w/cpp/language/unqualified_lookup), under the section `Definition outside of its namespace`, unqualified name lookup should find these enums from the same namespace.

**Pull request merged**
