### PR TITLE
Color and symbol variants

### LINKED ISSUE #56814: Change color with variants
### Is your feature request related to a problem? Please describe.

You can't currently change the color of an item with a variant, but I want to make variants that are different colored versions of an item.

### Solution you would like.

To be able to change the color of an item with a variant, like we can with the name and description.

### Describe alternatives you have considered.

To create another item just for a color change.

### Additional context

I want this to add more variants to various common items, like dresses, shirts, etc.

### PR DESCRIPTION
**Pull request by Termineitor244**
#### Summary
Infrastructure "Add the possibility to change color and symbol of an item with a variant"

#### Purpose of change
Fixes #56814
Sometimes you want an extra difference for a variance of an item, to make them more unique or different from their original, generic version, but you couldn't change more than the name and description, until now.

#### Describe the solution
Implements the suggestion by @ZhilkinSerg and gave some t-shirt variants different colors and symbols as a first use.

Edit: I decided to add variant symbols and colors to all the clothing variants since I will be busy for making these changes the next week.

#### Describe alternatives you've considered
To have one same color for all t-shirts, dresses, etc.

#### Testing
Compiled and tested with all the suggested changes, it works now!.

#### Additional context
imagen
Thanks to the fix by @anothersimulacrum, it now works even if you do not define a new color or symbol for the variant (it uses the ones for the base item, as it should).

But...
Animation
<del>The items still go crazy and iterate between the possible different symbols/colors for all the possible variants, this in an old gif, but the problem its the same now.</del>

It works now! Thanks @dseguin 
imagen

### CODE REVIEW

**Review by Maleclypse — APPROVED** [review]
I can't really speak to the c++ but the json looks good and the c++ came from ZS.

**Comment by Termineitor244** [comment]
@Maleclypse sadly, there seems to be a problem/s with the c++ already in place related to item symbols/colors, namely:
1._ The game cannot decide which variant's symbol/color to use for an item with variants (I guess related to the same problem with professions/ debug spawning iterating between different variants of an item when calling the base item.)
2._ You need to manually define each variant symbol/color, or it will suffer from a lack of both (This could be addressed with changes to the c++ code introduced in this PR, but I'm not sure how to write it).

I will put the PR in draft until solutions to these problems are found.

**Review by Maleclypse — CHANGES_REQUESTED** [review]
Thanks for letting me know about the testing issues.

**Comment by Termineitor244** [comment]
> Thanks for letting me know about the testing issues.
> 
> The request changes is to offset the approval. I’ll try snd fix both when I get to a computer.

Thanks!

**Comment by anothersimulacrum** [comment]
For 2 https://github.com/Termineitor244/Cataclysm-DDA/pull/1

**Comment by Termineitor244** [comment]
@anothersimulacrum thanks!

**Comment by PatrikLundell** [comment]
Is this related to animals (notably cows, but not limited to them) randomly changing appearance between the times they enter the reality bubble? Basically an "item" ought to store what appearance it selected on creation, rather than picking one to display each time.

**Comment by Termineitor244** [comment]
> Is this related to animals (notably cows, but not limited to them) randomly changing appearance between the times they enter the reality bubble? Basically an "item" ought to store what appearance it selected on creation, rather than picking one to display each time.

Possibility related, but worse because the game cannot decide which color/symbol to use for the items on the ground.

**Comment by Termineitor244** [comment]
@Maleclypse do you have any suggestions for the remaining problem in this PR? That of changing symbols when the items are on the ground and with the ASCII tileset activated, since it seems to be from a part of the code that this PR does not touches, and I'm ignorant on how to solve it.

**Comment by Termineitor244** [comment]
> Here's a fix for the cycling tiles:
> 
> ```diff
> diff --git a/src/cata_tiles.cpp b/src/cata_tiles.cpp
> index c4e5e2407c..898041ba7f 100644
> --- a/src/cata_tiles.cpp
> +++ b/src/cata_tiles.cpp
> @@ -2099,6 +2099,11 @@ bool cata_tiles::draw_from_id_string( const std::string &id, TILE_CATEGORY categ
>              } else {
>                  tmp = item( found_id, calendar::turn_zero );
>              }
> +            if( !variant.empty() ) {
> +                tmp.set_itype_variant( variant );
> +            } else {
> +                tmp.clear_itype_variant();
> +            }
>              sym = tmp.symbol().empty() ? ' ' : tmp.symbol().front();
>              col = tmp.color();
>          } else if( category == TILE_CATEGORY::OVERMAP_TERRAIN ) {
> ```

Thank you so much! I will apply the changes and test it further them.

**Review by dseguin — APPROVED** [review]

**Pull request merged**
