### PR TITLE
More mall background tiles will match floor

### PR DESCRIPTION
**Pull request by sneeze-attack**
#### Summary
```SUMMARY: Bugfixes "More mall background tiles will match floor"```  

#### Purpose of change
Alleviates issue with mall terrain not matching surrounding floor tiles as described in #27139 

#### Describe the solution

1. Created new terrain tiles which includes these IDs:
```
t_door_red_o
t_door_green_o
t_door_white_o
t_door_gray_o
t_door_red_c
t_door_green_c
t_door_white_c
t_door_gray_c
t_door_red_b
t_door_green_b
t_door_white_b
t_door_gray_b
t_door_frame_red
t_door_frame_green
t_door_frame_white
t_door_frame_gray
t_door_glass_red_o
t_door_glass_green_o
t_door_glass_white_o
t_door_glass_gray_o
t_door_glass_red_c
t_door_glass_green_c
t_door_glass_white_c
t_door_glass_gray_c
```
2. Adjusted new terrains to have matching background tiles where possible (such as deconstructing or bashing)

3. Added new terrains to all tilesets except MSX++DeadPeopleEdition. Used same graphic for background as follows:
red = t_carpet_red
green = t_carpet_green
white = t_linoleum_white
gray = t_linoleum_gray

4. Added `t_carpet_red`, `t_carpet_green`, `t_linoleum_white`, and `t_linoleum_gray` to any tilesets that did not already have them defined.

5. Used a palette for furniture and terrain generation. Changed maps to match the new palette.

#### Describe alternatives you've considered
Making the mall floors tiles all `t_floor` but that would make the mall appearance too basic

#### Additional context
Some tilesets such as Chesthole have the wooden door background filled in which prevents you from setting a background other than `t_floor`. To fix this, the png files must be edited.

A lot of tilesets still have missing or incorrect backgrounds for items. Much of this likely needs to be fixed for the individual tileset.

### CODE REVIEW

**Comment by sneeze-attack** [comment]
I can see there is a message on this PR about conflicting files. I've looked over the conflict and I'm not sure what I am supposed to do to fix this. If there is anything I need to do on my end, please let me know, thanks!

**Comment by AMurkin** [comment]
Same Q&A: https://github.com/CleverRaven/Cataclysm-DDA/pull/27448#issuecomment-455966991

**Comment by sneeze-attack** [comment]
> Same Q&A: [#27448 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/27448#issuecomment-455966991)

Thank you again for the guidance! I had not realized I needed to remove the `<<<<<<<`, `=======`, `>>>>>>>` markers.

**Comment by AMurkin** [comment]
Jenkins says `Formatted data/json/terrain.json`

**Comment by SunshineDistillery** [comment]
Making a dozen new types of terrain is not a good way to fix this. 

There are two separate problems here.  The issue in #27139 is that the actual terrain beneath the furniture is not what you would expect.  You can see in the pics he's moved the furniture to show the spots that don't match. Where the chair spawns, wood floors spawn underneath.  That can be fixed by editing the palettes and mapgens in json.

What you're talking about is that the maptile png assumes the floor matches the bash terrain. So open doors look like there are wooden floors underneath, even if it clashes with surrounding tiles.  

If you have to multiply every type of door by every type of floor you'll have a lot of an absolute ton of different terrains.  Then do it for damaged, locked, pickable locked, one-way-locked, and peephole versions.  And also door frames.  There are too many terrain types as is, and multiplying them is a going down a path of madness.  

The bigger issue is that there need to be fewer types of terrain, but which can have various states--open damaged, floor tile underneath, etc--instead of just transforming into a whole different type.

**Comment by SunshineDistillery** [comment]
You could have done #27962 by adding a new pallete and making sure it matched the mapgen/chunk's terrain. But changing all the strconc to thconc doesn't really address the issue. 

So instead of just one lab palette you would have a few for different floors/terrains. Like:
"lab_basic": { "furniture": { "c": "f_chair" } }
"lab_strconc": { "terrain": { "c": "t_strconc_floor" } }
"lab_thconc": { "terrain": { "c": "t_thconc_floor" } }

Then depending on mapgen/chunk you would define two palettes. Either: 
"palette": [ "lab_basic", "lab_strconc"] or 
"palette": [ "lab_basic", "lab_thconc"] 
(and also the palettes that define loot)
That way the map is putting the right type of terrain under the furniture.  Also remember that palettes override each other in order, so it's okay to define the floor in lab basic and it will still get replaced correctly. 

For labs it should work pretty easy, but malls have mapgens with several types of flooring in a single map, so you'd have to fiddle with them to make sure that they're working. You might need to add further terrain and furniture entries after the palletes to catch the mistakes.

**Comment by sneeze-attack** [comment]
@SunshineDistillery I chose to create new terrain types, because I saw no other way to properly set the deconstruct and bash configurations to have the correct floor type upon destroying/deconstructing.

The method you've outlined would help, but I do not think it would fully set up the maps properly due to the bashing/deconstruction settings.

Using `t_door_c` as an example, we have these configurations:
`    "deconstruct": { "ter_set": "t_door_frame", "items": [ { "item": "2x4", "count": 4 }, { "item": "nail", "charges": [ 6, 12 ] } ] },
    "bash": {
      "str_min": 8,
      "str_max": 80,
      "str_min_blocked": 15,
      "str_max_blocked": 100,
      "sound": "smash!",
      "sound_fail": "whump!",
      "ter_set": "t_door_b",
      "items": [ { "item": "2x4", "prob": 25 }, { "item": "splinter", "count": [ 1, 2 ] }, { "item": "nail", "charges": [ 0, 2 ] } ]`

The two `ter_set` sections are what caused me to take the route of creating new terrain types. If there is a solution to this that I am not aware of (like using a variable such as `"deconstruct": { "ter_set": "%FLOOR_VARIABLE%"` ) then please let me know and I'd be more than happy to rework my changes.

I figured that although we would have more terrain types with this method, we would be given greater control over the floor types used in the mapgen as we'd be able to start specifying which floor type is going to appear (as long as terrain also is properly set in mapgen).

**Comment by SunshineDistillery** [comment]
Yeah, there are two problems: moving furniture to find the wrong floor, and bashing to find the wrong floor. Setting palettes will fix the first one.  The second one is trickier.  

I used to play modded Minecraft.  Each type of block had its own ID number. And each block had a variation for each skin. In vanilla it wasn't a problem because there were only a few blocks and terrains, but with mods it was crazy.  Every single type of fence, wedge, cylinder, pipe, whatever multiplied by every type of skin resulted in thousands of separate entries. Scrolling through search would be hundreds of pages of pointless blocks until you got to the useful stuff.  I would not want something like that to happen to cata, the jsons are already hard enough to search through.  

I thought about and I did come with a weird idea if you're willing to experiment a little.  Terrain and furniture are pretty much the same, with some exceptions.  So, you could, instead of creating multiple terrains, make alternate furnitures.  You would make a furniture called f_glass_wall with the same bash results, and set its str_min to -1 so you can't grab/drag it.  Then just place it where the terrain was.  When you bashed it, it would reveal any type of floor underneath.  That's one entry instead of a dozen. 

You could do the same with doors, because they can open/close to other types of furniture and bash to other types of broken furniture.  There is a DOOR flag so NPCs can path through it and some flag so vehicles can pass over it.  The png tile for open doors could be made partly transparent to show the terrain beneath, just like other furniture does now. There might be some weirdness with blocking/barricading doors. And I don't know if gates can work with furniture, so those might require terrain.  But it should work in theory.

**Comment by sneeze-attack** [comment]
> I used to play modded Minecraft. Each type of block had its own ID number. And each block had a variation for each skin. In vanilla it wasn't a problem because there were only a few blocks and terrains, but with mods it was crazy. Every single type of fence, wedge, cylinder, pipe, whatever multiplied by every type of skin resulted in thousands of separate entries. Scrolling through search would be hundreds of pages of pointless blocks until you got to the useful stuff. I would not want something like that to happen to cata, the jsons are already hard enough to search through.

I have to disagree here. The JSONs are really not difficult to search through, you can use various search tools to sift through the files such as a "find" in document editing software, `grep` on command line Linux, or using the `search Repository` feature Github provides.
If you keep your searches specific and don't rely on the limitations of a single tool, I think scrolling through search is a non-issue.
If the games' performance was impacted by the bloated JSON sizes, then I think it would be a cause for concern.

> I thought about and I did come with a weird idea if you're willing to experiment a little. Terrain and furniture are pretty much the same, with some exceptions. So, you could, instead of creating multiple terrains, make alternate furnitures. You would make a furniture called f_glass_wall with the same bash results, and set its str_min to -1 so you can't grab/drag it. Then just place it where the terrain was. When you bashed it, it would reveal any type of floor underneath. That's one entry instead of a dozen.
> 
> You could do the same with doors, because they can open/close to other types of furniture and bash to other types of broken furniture. There is a DOOR flag so NPCs can path through it and some flag so vehicles can pass over it. The png tile for open doors could be made partly transparent to show the terrain beneath, just like other furniture does now. There might be some weirdness with blocking/barricading doors. And I don't know if gates can work with furniture, so those might require terrain. But it should work in theory.

This was a great idea and not something I considered previously. I'm always interested in improving what contributions I am trying to submit, so I went ahead and tried this idea out. Most of the terrain features/properties seem to apply to furniture as well.
I tested by creating a copy of `t_wall_glass` and ended up with the following furniture JSON:

`      {
    "type": "furniture",
    "id": "f_wall_glass",
    "name": "furnituremodel glass wall",
    "symbol": "LINE_OXOX",
    "color": "light_cyan",
    "move_cost_mod": -1,
    "required_str": -1,
    "flags": [ "NOITEM", "BLOCK_WIND", "TRANSPARENT", "WALL", "AUTO_WALL_SYMBOL", "BLOCKSDOOR" ],
    "bash": {
      "str_min": 4,
      "str_max": 12,
      "sound": "glass breaking!",
      "sound_fail": "whack!",
      "sound_vol": 16,
      "sound_fail_vol": 10,
      "items": [ { "item": "glass_shard", "count": [ 5, 10 ] } ]
    }
   }`

The first issue I noticed has to do with the `AUTO_WALL_SYMBOL` flag. On tiles everything renders fine when I copied both the `t_wall_glass` and `t_reinforced_glass` settings within `tile_config.json` (I used the MSX++DeadPeopleEdition tileset for testing if it matters).

When I switched tiles off, it is noticeable that the `AUTO_WALL_SYMBOL` flag is not applying correctly to the new furniture glass wall created.

Example screenshots [here ](https://imgur.com/a/jdDm1zW)


@SunshineDistillery  Due to this flag not applying correctly, I don't think this method would be appropriate as we would be making the mapgen look good for tiles but making it worse for the curses version.
I don't disagree with your concerns entirely, but unless the method I am using makes a negative impact on game performance this seems to be the most thorough way to ensure all of the floors are correct under different terrain tiles that can be deconstructed/bashed.
If I knew C++ I would try to introduce changes that way that would allow us to not need variations of existing terrains, but until that happens this may be the best method we have right now.


I will however make use of the palettes in the mall and keep this open as a WIP until that's cleaned up more.

**Comment by sneeze-attack** [comment]
That should be the last change, thanks.

**Comment by ZhilkinSerg** [comment]
> 
> 
> That should be the last change, thanks.

Unfortunately there is a conflict that needs to be resolved.

**Comment by sneeze-attack** [comment]
@ZhilkinSerg conflict has been resolved, thanks!

**Comment by halfahermit** [comment]
Retrodays furnutire and terrain are all opaque, so there's no need to include a bg entry for those. Also fine to include it if that's easier.

**Comment by sneeze-attack** [comment]
> Retrodays furniture and terrain are all opaque, so there's no need to include a bg entry for those. Also fine to include it if that's easier.

Thank you for this information. Do you want me to open a small PR to remove the bg entries? Or if you want you can make the changes, I don't want to interfere if you have an existing process.

**Comment by halfahermit** [comment]
No need to remove them, just wanted to save you the effort of adding them in future PR's.

**Pull request merged**
