### PR TITLE
[DinoMod] Add S-Rex

### PR DESCRIPTION
**Pull request by LyleSY**
Skeletal Tyrannosaurus Rex

#### Summary

SUMMARY: Mods "Adds monster 'S-Rex'"

#### Purpose of change

Add variety and difficulty, reward and punish different types of gameplay

#### Describe the solution

Adds new monster based on vanilla skeletons as applied to zombie T-Rex, then makes zombie T-Rex upgrade into it slowly. No fancy loot for this one. Also minor fixes for zombie dinos.

#### Describe alternatives you've considered

There are so many horrible things a zombie T-Rex could evolve into.

#### Testing

Spawns, no errors. Couldn't get looks_like to work, looks like it will need its own tiles.
Screen Shot 2020-06-08 at 12 25 23 AM

#### Additional context

Like the cover of that one book.

### CODE REVIEW

**Comment by Resok** [comment]
I was able to get looks-like to work -

image

`    "harvest": "mr_bones",
    "looks-like": "mon_zyrannosaurus",
    "categories": [ "DINOSAUR" ]`

**Comment by ZhilkinSerg** [comment]
It is not possible - `looks-like` is not read by the code, only `looks_like` is supported.

**Comment by Resok** [comment]
That is odd, probably the copy-from probably inherited the look for it anyway and looks-like was completely ignored. My bad. Looks like the image even without the tag. Sorry for the confusion.

**Comment by ZhilkinSerg** [comment]
Yes, it should be a copy-from inheritance.

**Comment by tornikeo** [comment]
[Dear god](https://youtu.be/ItrseO_L7SA?t=2).

**Pull request merged**
