### PR TITLE
Support marking mods as broken [CR]

### PR DESCRIPTION
**Pull request by mugling**
As set out in #17157 the generic guns mods is broken. This currently results in `--check-mods` failing. Whether or not we chose to eventually drop generic guns we do need a system of marking some mods as `broken`.

Broken mods:
- Are supported for existing save games
- Cannot be used when starting new games
- Will be skipped for `--check-mods`
- Are specified via `broken: true` syntax

The issue as to whether we should drop support for specific mods remains outstanding but this PR provides a simple solution for doing so without harming existing saves.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Against

We should either support or drop mods from mainline.
There is no reason to keep broken mods around.

**Comment by mugling** [comment]
Won't dropping a mod break saves? Marking it as `broken` for a month or two allows us to phase out unpopular broken mods?

**Comment by BorkBorkGoesTheCode** [comment]
I can update most of the mods listed, if the modmakers don't object.

**Comment by mugling** [comment]
> I can update most of the mods listed, if the modmakers don't object.

I only included generic guns which doesn't have a maintainer.

For many mods it's a more complex issue than just finding a new maintainer. For the blaze mod the original author is maintaining a separate version outside of the tree so there isn't really any other option than to drop the outdated version we currently ship (but that's a separate issue to this PR).

**Comment by Coolthulhu** [comment]
> Won't dropping a mod break saves?

It will
> Marking it as broken for a month or two allows us to phase out unpopular broken mods?

It shouldn't disable `--check-mods`, though. Until the mod is dropped, it is officially supported.
> I can update most of the mods listed, if the modmakers don't object.

Would be good. Starting with generic guns, since it reports bugs at start.

Forum poll results are: 2 users, 6 would like to use but it's broken, 44 don't use. Not exactly unpopular, not really popular.
I'd keep the mod since it is a well-designed one, not just a bunch of extra crap added in because the author had more desire to create than ability to be creative.
I'd argue that generic guns are better designed than mainline guns.

**Comment by mugling** [comment]
> I'd argue that generic guns are better designed than mainline guns.

Yes, I'd agree

**Comment by kevingranade** [comment]
I don't understand how you plan to reconcile, "supported for existing save
games" and "skipped for --check-mods", which implies they can't even load.
If it's broken and fixing it isn't a high enough priority to break the
build over, remove it. We don't keep broken code or data around, if someone
wants to revive it, they can revert the commit that deleted it.

**Comment by mugling** [comment]
> I don't understand how you plan to reconcile

It's difficult.

How about dropping having `broken` mods still tested via `--check-mods` and then we can use the field as a warning that deprecation is imminent? The alternative is #17290 which isn't much more pleasant.

**Comment by kevingranade** [comment]
Valid options are #17290 or actually maintaining it. Letting it break and keeping it in the repo isn't an option.

**Comment by kevingranade** [comment]
Oops, there is a middle path, some kind of migration that lets saves load but causes all mod content to evaporate would also work.  That's more on the "remove it" side of things, but without rendering saves unloadable.

**Comment by mugling** [comment]
Both blazemod and generic guns are now in progress so I think this PR is nolonger required

**Pull request closed without merging**
