### PR TITLE
Acorn meal decay time fix and recipe change

### LINKED ISSUE #24255: Cooked Acorn Meals have no spoilage and give too much nutrition
Cooked acorn meals are currently overpowered with their 42 Nutrition and 0 spoilage. I suggest, instead of adding a spoilage we simply lower the nutrition to 9 like we have with fried seeds as this is pretty close to the same thing although I have no clue how much nutritionally they vary. It seems semi reasonable as I've gotten 50+ "meals" in the fall.

### PR DESCRIPTION
**Pull request by nexusmrsep**
Resolves #24255 (see for racionale)

- Acorn meal now has spoil time comparable to flour.
- Acorn meal recipe requires a quern or food processor to grind the acorns into meal, and extra water to remove tannin (see explanation by @Amariithynar in #24255)

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>Acorn meal recipe requires a quern or food processor to grind the acorns into meal

IRL, a chef's knife works really well.

**Comment by Noctifer-de-Mortem** [comment]
Would just like to point out that the “More Survival Tools” mod would warrant a morter and pestel varient of the recipe.

**Comment by kevingranade** [comment]
Or import the mortar and pestle into mainline.

**Comment by nexusmrsep** [comment]
> Or import the mortar and pestle into mainline.

Sounds like a new quick PR in line on my ever-expanding TODO list 👍 

> IRL, a chef's knife works really well.
For shelling - yes, but for grinding it down? At least @Amariithynar said it's needed, so I've added it.
Also: I know you can convert acorn meal into flour with quern and food processor, so in my head I imagine its a second grind to make it even more powdery. Am I wrong on this matter?

**Comment by GroeneAppel** [comment]
Doing some searching around reveals some interresting recipes concerning preparing acorns.
The tannin in acorns for example can be more slowly removed using cold water, which also results in more nutrients remaining in the acorns. In addition one can also simply use a rock in a survival situation to grind the acorns down after soaking or boiling. 
In addition when a blender is used, cold water can also be used to create a milk-like slurry which is then put in a fine-meshed bag and massaged with running water. A method both quick and which retains the most nutrients. 

This could be reflected in three recipes in Cata. One involving a blender, one very slow one that forces the player to wait a week. And one that results in less nutrient rich acorns. But perhaps that is a little too much? 

[Source ](http://wildernessarena.com/food-water-shelter/food-food-water-shelter/food-procurement/edible-wild-plants/preparing-acorns-nutritious-food-source-remove-tannin)
[Source](https://www.almanac.com/content/how-prepare-and-cook-acorns)

**Comment by Rivet-the-Zombie** [comment]
>For shelling - yes, but for grinding it down?

Yeah, you just chop them up roughly. They're not really that hard, even when raw.

**Comment by Amariithynar** [comment]
Sorry for the late reply here; github is terrible at letting you know what pulls have active conversations. 

Chopping them up roughly allows you to leach the tannins, but that's not acorn meal. Meal is when it's been ground down to a coarse grit, as with cornmeal or bonemeal. 

@nexusmrsep Technically coarse grain acorn meal isn't flour yet; it needs to be spread out and dried, then ground down even finer to get proper flour... but meal works well enough as a flour substitute, though it does suffer from a mealy mouth texture; it being a direct flour replacement is fine by me. Did this commit add (1) tannic acid (liquid) as a byproduct of the process per batch, and add tannic acid as a usable material in tanning skins?

**Pull request merged**
