### PR TITLE
Remove "pair of" from singular item names

### PR DESCRIPTION
**Pull request by Kodiologist**
### Summary
`SUMMARY: Interface "Remove \"pair of\" from item names"`

#### Purpose of change
To remove uninformative prefixes, as in #34977.

#### Describe the solution
It's a big diff for one small change: a regex replacement from `"name": "(?:pair of )?(.+?)",\s+"name_plural": "pairs of .+?"` to `"name": { "str": "\1", "str_pl": "\1" }`.

#### Describe alternatives you've considered
Perhaps some items whose pairing is not obvious, like butterfly knives, should keep the "pair of".

Items with singular and plural names that are identical are common enough that there should be a way to specify them without repeating the name (e.g., `"name": { "str_ps": "knitting needles" }`). The current system is just begging for duplicated names to get accidentally desynchronized. But perhaps that's better left for another PR.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Oh dang, this doesn't work quite as I hoped; three pairs of boots are now listed in the inventory as "3 boots", which is pretty confusing. Perhaps the plural forms should retain "pairs of", while the singular forms should have no "pair of"? What do you guys think?

**Comment by DaviBones** [comment]
Not a huge fan of that solution either.

1. Seeing `boots` on it's own with no number might make sense in the context of a list of worn items where that number is implied to be 2, but in other contexts, it could be confusing, especially to new players. Imagine looking in a dresser as a new player and seeing:
    ```
    boots
    socks
    leather gloves
    ```
    Not very descriptive or clear. 

2. It doesn't really solve anything; AFAICT, the stated goal of this is to reduce length of item names, but your new solution leaves plural forms (the longer of the two) untouched.

**Comment by Kodiologist** [comment]
1. Can't relate. For everything else in the game, the number is omitted for a single unit of an item, and the fact that the unit is one pair for something like pants or boots should be obvious, but is clarified by the many item descriptions that mention that the thing is a pair. (In the few cases where the description doesn't include a mention that the thing is a pair, perhaps we should add it.) At any rate, I find it a lot easier to remember that boots come in pairs than that [the M4A1 is a carbine, or indeed that it is a gun](https://github.com/CleverRaven/Cataclysm-DDA/pull/34547).
2. Surely getting a shorter name in the more common case is better than nothing.

**Comment by DaviBones** [comment]
> At any rate, I find it a lot easier to remember that boots come in pairs than that the M4A1 is a carbine, or indeed that it is a gun.

That isn't my complaint, I agree that the description stating that the item comes in pairs is sufficient, just like stating that the M4A1 is a carbine in the description is sufficient. My complaint is with the ambiguity of the number of pairs present in the singular case. Yes,

> For everything else in the game, the number is omitted for a single unit of an item

but your proposed change might throw that concept into question for players still learning the game.

**Comment by Kodiologist** [comment]
I have now pushed a new version that does what I just described. And now I notice that "the number is omitted for a single unit of an item" is not actually true throughout the game. You can get the messages "You see here 1 boots", "You see here 1 blueberries", and "You see here 1 SPAM". I suspect that deeper changes are needed to make the game more grammatically aware, and the interaction of that with translation will be a nasty business. I'd say that on balance this change is probably for the better, but clearly it's a judgment call.

**Comment by mkikt4743** [comment]
yeah it seems fine as it is to me boss, don't see why this needs changing, goes to a more confusing en result so far

**Comment by I-am-Erk** [comment]
I gave this some time for a good think over and I agree, while the motivation behind this is great, the result is just too awkward.

**Pull request closed without merging**
