### PR TITLE
Magic energy sources

### PR DESCRIPTION
**Pull request by Varda53**
#### Summary

SUMMARY: [Mods] [Magiclysm] "Adds hunger, thirst and pain as spell energy sources."

#### Purpose of change

To fill out the available energy types for spells to apply to the other non-fatigue needs. Pain can already be alleviated or increased via magic, so making it an energy type is a logical next step. This also allows for several new kinds of novel spell, such as a spell that creates fruit from the user's own calorie reserves, in order to store them for later use.

#### Describe the solution

Adding hunger, pain and thirst as valid power sources, in the same manner as fatigue is currently a valid power source.

#### Describe alternatives you've considered

For pain at least, you could have a secondary spell effect that increases pain alongside the primary effect. However, there would be no hard cap like there is for the fatigue power source and "Dead Tired" so you would be able to cast pain-based spells pretty much infinitely, although you wouldn't be good for much else.

#### Testing

Debug spells properly increase or decrease the values of the energy sources used, and become unavailable when a certain threshold is reached for each energy source.

#### Additional context

The inspiration for the fruit-making spell that prompted these changes originally came from this thread: https://www.reddit.com/r/cataclysmdda/comments/is8kwi/plants_get_fat_as_shit/

### CODE REVIEW

**Comment by KorGgenT** [comment]
1. it should be called calories instead of hunger.
2. calories is an absolutely terrible choice in terms of gameplay because it is a hidden stat.

pain additionally has no actual "limit" so it's not really fair to call it a "cost". 
more or less... what in-repo mechanics are being added for these?

**Comment by KorGgenT** [comment]
so i'm not sure if i was clear, but i want clear working examples that would fit in with the setting of magiclysm (not debug spells just to see that they work, actual spells players would use); either that, or a new in-repo mod (that follows the guidelines) that uses these.

**Comment by I-am-Erk** [comment]
Having any of these as side effects could be cool though, especially in the context of artifacts

**Comment by KorGgenT** [comment]
i'd have to check but pain is definitely a side effect that is available

**Comment by KorGgenT** [comment]
image
yeah so, i'd definitely take additions to this that add thirst and calories. but i'm also considering deprecating fatigue as a "cost" since it still isn't used anywhere in the repo.

**Comment by I-am-Erk** [comment]
In addition to thirst and calories as recover_energy options, radiation and focus would be good additions to the list. If we feel like digressing...

**Comment by Varda53** [comment]
> image
> yeah so, i'd definitely take additions to this that add thirst and calories. but i'm also considering deprecating fatigue as a "cost" since it still isn't used anywhere in the repo.

Noted. I'll close this PR and write up a PR to do just that. I reasoned that since fatigue didn't have any in-repo spells using it as an energy source, it wouldn't be a requirement for newly added power sources to do so either.

I would argue though that adding additional JSON moddability to the in-built spell system is worth it even in the absence of immediate in-repo content. There's a very real barrier of entry in needing to change the source code to implement your cool spell idea, that can be lowered by making more possible with only JSON.

However, some of the other issues raised make me think that this is a bad idea in the first place. The only thing that energy sources really do that negative recover_energy can't is stop you from casting the spell entirely once you hit a certain threshold. However, the QoL in not allowing you to starve/parch yourself to death through overzealous spell usage is overshadowed by those thresholds being hidden and arbitrary.

**Comment by KorGgenT** [comment]
> I would argue though that adding additional JSON moddability to the in-built spell system is worth it even in the absence of immediate in-repo content.

I don't really have a long-winded response to this, but the reason I am resisting it is because of maintenance burden for essentially dead code. this is why lua was removed, and i don't want similar dead code related to the magic code.

**Pull request closed without merging**
