### PR TITLE
Residential-Decay

### PR DESCRIPTION
**Pull request by RanikOrtega**
#### Summary
Content "Mapgen changes"

#### Purpose of change
Somehow a few days into the Cataclysm buildings are still pristine even with riots and Zombies. Dirty up residential structures with Door and window damage. Blood, bile and body spawns as well as trash and graffiti. 

#### Describe the solution
Edited house-general_pallet and aux_nested files for small chance of décor spawning. Windows and doors have a chance to generate broken versions. Floor tiles in houses have a small chance for blood, bodies or trash to spawn settings relatively conservative currently. Could be adjusted higher or lower. Houses with dozens of zombies in / around them shouldn't be pristine. 

#### Describe alternatives you've considered
Leaving the mapgen as it was. 

#### Testing
Repeatedly generated maps and tested frequency of additions. 

#### Additional context
CDDA-Decay1
CDDA-decay2
CDDA-Decay3
CDDA-Decay4
CDDA-Decay5

### CODE REVIEW

**Comment by Maleclypse** [comment]
@LovamKicsiGazsii I'd appreciate if you take a second to review this.

**Comment by LovamKicsiGazsii** [comment]
Not much objectively wrong with this, except for the absence of glass shards near broken windows. That could be solved by using a modified version of `destroyed_glass_door_wall` in nested/aux_nested. Also, glass walls could use some bashing as well.

On a more personal note, I wish not all houses got vandalized the same way.  The fact that every house gets the same amount of destruction, the same amount of blood, trash, and corpses makes things look all too artificial.  I would prefer if the solution was implemented similarly to #60275, with houses having varying stages of destruction, starting from completely intact all the way to how it is in the screenshots.

**Comment by Procyonae** [comment]
I agree, stages of destruction would be much more interesting, here's some doc links that might interest you https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md#mapgen-values https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md#place-rubble-and-smash-existing-terrain-with-rubble

**Comment by RanikOrtega** [comment]
> @LovamKicsiGazsii  Let me have a look at 60275. I'm not at all attached to the current changes as much as I am to proper implementation of wear and tear on houses ESPECIALLY in Cities which should be very damaged. If it can be done better via 60275's methods then I may move it more towards that.

**Comment by RanikOrtega** [comment]
> Not much objectively wrong with this, except for the absence of glass shards near broken windows. That could be solved by using a modified version of `destroyed_glass_door_wall` in nested/aux_nested. Also, glass walls could use some bashing as well.
> 
> On a more personal note, I wish not all houses got vandalized the same way. The fact that every house gets the same amount of destruction, the same amount of blood, trash, and corpses makes things look all too artificial. I would prefer if the solution was implemented similarly to #60275, with houses having varying stages of destruction, starting from completely intact all the way to how it is in the screenshots.

Not sure implimentation from #60275 is even working. Testing palette distribution between standard and hoarder versions isn't even working at the moment.  The following code seems to do nothing if changed. 

EX: "palettes": [
      {
        "distribution": [
          [ "standard_domestic_palette", 9 ],
          [ "standard_domestic_palette_abandoned", 280 ],
          [ "house_hoarder_palette", 40 ],
          [ "house_survivor_palette", 180 ]
        ]
      }
    ]

**Pull request merged**
