### PR TITLE
No crucibles for forging

### PR DESCRIPTION
**Pull request by Elgrosito**
#### Summary
Content "Removes unrealistic crucibles"

#### Purpose of change
The process of forging iron or steel does not include the use of crucibles, forging temperatures never reach melting point where crucibles are needed. Crucibles are more suited to non-ferrous metal recipes. 
Casting the steel would be unrealistic because 
1) It would be harder to reach such a temperature.
2) Because the end product would be inferior due to grain size and lack of strength from forging/rolling.
3) It would take much more time, effort, fuel, and oxygen.

#### Describe the solution
Essentially remove crucibles from recipes that should not need them.

#### Describe alternatives you've considered
Making this a part of a more extensive PR in the works.

#### Testing
Linted and ran the game with the code.

#### Additional context
IMG-20170928-WA0009

### CODE REVIEW

**Comment by Maleclypse** [comment]
So my main question is whether or not the crucible is used as an abstraction for the process of creating steel bars out of the scraps `, [ "steel_chunk", 4 ], [ "scrap", 20 ] ]`  as an example where the ingredients without some kind of process to combine them would not be useable to make an iceaxe.   I could see using a single steel lump but most items that requires multiple pieces of steel seems like it would require some sort merging process prior to being forged into whatever the end result is.

**Comment by Elgrosito** [comment]
Hi! when we need to "merge" several pieces of steel into a billet we do something called "forge welding". Essentially, you stack the pieces of steel, and once hot enough, you hammer them together into one piece. This has been done for millennia. To keep them together, you can use wire, a welder, or just gravity like the Japanese do. What you mentioned, would require huge amounts of heat or higher amounts of carbon to lower the melting temperature, the latter would result in a very brittle material (cast iron), but suitable for casting. Also, the grain in the material resulting from that process, even if low carbon, would make it weaker because of the temperature and would require several normalization cycles not to crumble. Steel casting was only done consistently after the industrial revolution.

**Comment by Maleclypse** [comment]
Needs linting : data/json/recipes/tools/tool.json

https://dev.narc.ro/cataclysm/format.html

**Comment by Elgrosito** [comment]
Yes, I noticed. I will get to it when I have time.

**Pull request merged**
