### PR TITLE
Remove the MR73

### PR DESCRIPTION
**Pull request by BalthazarArgall**
#### Summary
None

#### Purpose of change
While working on the Chiappa Rhino I noticed that the Manurhin MR73 was in the game, which is surprising given its rarity, after checking on gunbroker it turns out that not only is it rare but it's way below the inclusion standard.

#### Describe the solution
Migrate it and replace it with a similar revolver.

#### Testing
None.

#### Additional context
I can't access the completed listings due to not being a US citizen, maybe if you include them you meet the standards although I'd be surprised if it made much of a difference.

Gunbroker screenshot:
Untitled

### CODE REVIEW

**Comment by BalthazarArgall** [comment]
Remind me to not work on 2 PRs touching the same files at the same time again

**Comment by kevingranade** [comment]
Here the hits for completed listings
Screenshot_20240618_073853_Firefox
,  as expected...

**Comment by Griffinhart** [comment]
Why are y'all looking up MR73s on Gunbroker? (I see mention of "inclusion standard" but I don't know where/what that is.)

Beretta is the official US importer for the MR73 and they can be purchased brand-new.

https://gun.deals/search/apachesolr_search/mr73

I see listings from Eurooptic, Gunprime, and Guns dot com.

**Comment by KrunkySmokin** [comment]
> Why are y'all looking up MR73s on Gunbroker? (I see mention of "inclusion standard" but I don't know where/what that is.)
> 
> Beretta is the official US importer for the MR73 and they can be purchased brand-new.
> 
> https://gun.deals/search/apachesolr_search/mr73
> 
> I see listings from Eurooptic, Gunprime, and Guns dot com.

I don't get the removal of any of the recent guns when they have a tent gun show that spawns that could reasonably contain any of these harder to find weapons.

**Comment by BalthazarArgall** [comment]
> Why are y'all looking up MR73s on Gunbroker? (I see mention of "inclusion standard" but I don't know where/what that is.)
> 
> Beretta is the official US importer for the MR73 and it can be purchased brand-new. They're not rare, they're just an expensive (~3700USD) niche (revolver) gun.
> 
> https://gun.deals/search/apachesolr_search/mr73
> 
> I see listings from Eurooptic, Gunprime, and Guns dot com.

Unless I'm misunderstanding this is evidence of the possibility of purchase, not evidence of the item being present in New England in the minimum amount required to be represented in the game.

**Comment by BalthazarArgall** [comment]
> > Why are y'all looking up MR73s on Gunbroker? (I see mention of "inclusion standard" but I don't know where/what that is.)
> > Beretta is the official US importer for the MR73 and they can be purchased brand-new.
> > https://gun.deals/search/apachesolr_search/mr73
> > I see listings from Eurooptic, Gunprime, and Guns dot com.
> 
> I don't get the removal of any of the recent guns when they have a tent gun show that spawns that could reasonably contain any of these harder to find weapons.

Indeed the gun show is an excellent way to give players a way to access guns that both meet the requirements for inclusion and are rare. The issue with the RM73 is that it only meets one of those conditions.

**Comment by harakka** [comment]
> Why are y'all looking up MR73s on Gunbroker?

<https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GUN_NAMING_AND_INCLUSION.md>

The comments of this PR are not the place to debate this, if you have a better methodology make an issue explaining it.

**Comment by KrunkySmokin** [comment]
> > > Why are y'all looking up MR73s on Gunbroker? (I see mention of "inclusion standard" but I don't know where/what that is.)
> > > Beretta is the official US importer for the MR73 and they can be purchased brand-new.
> > > https://gun.deals/search/apachesolr_search/mr73
> > > I see listings from Eurooptic, Gunprime, and Guns dot com.
> > 
> > 
> > I don't get the removal of any of the recent guns when they have a tent gun show that spawns that could reasonably contain any of these harder to find weapons.
> 
> Indeed the gun show is an excellent way to give players a way to access guns that both meet the requirements for inclusion and are rare. The issue with the MR73 is that it only meets one of those requirements.

If you're going by that then you may as well start removing non-military/police machine guns because of how rare those are in New England. The MR73 is still currently in production and to a degree that Beretta sees it profitable to import to sell.

**Comment by BalthazarArgall** [comment]
> If you're going by that then you may as well start removing non-military/police machine guns because of how rare those are in New England. The MR73 is still currently in production and to a degree that Beretta sees it profitable to import to sell.

Indeed. We already started removing some machineguns. As for your other point, I already explained how the possibility of a sale and import doesn't equate to evidence of the weapon existing in the region the game takes place in.

**Comment by KrunkySmokin** [comment]
> > If you're going by that then you may as well start removing non-military/police machine guns because of how rare those are in New England. The MR73 is still currently in production and to a degree that Beretta sees it profitable to import to sell.
> 
> Indeed. We already started removing some machineguns. As for your other point, I already addressed it:
> 
> > [...]this is evidence of the possibility of purchase, not evidence of the item being present in New England in the minimum amount required to be represented in the game.

Maybe fix existing guns and the months long bugs where barrels on certain rifles aren't spawning there instead of removing guns, guns that could fit in at a gun show. Gun shows where _collectors_ bring their guns to show off and trade.

**Comment by BalthazarArgall** [comment]
> Maybe fix existing guns and the months long bugs where interchangeable barrels on certain rifles aren't spawning there instead of removing guns, guns that could fit in at a gun show. Gun shows where _collectors_ bring their guns to show off and trade. Having a gun show and having that "it has to be prominent enough in New England" rule for gun inclusion makes no sense.

We can both fix the bugs and remove the guns at the same time. I already explained how guns can be rare and still meet the requirements for inclusion, justifying their presence at a gun show.

**Comment by KrunkySmokin** [comment]
> > Maybe fix existing guns and the months long bugs where interchangeable barrels on certain rifles aren't spawning there instead of removing guns, guns that could fit in at a gun show. Gun shows where _collectors_ bring their guns to show off and trade. Having a gun show and having that "it has to be prominent enough in New England" rule for gun inclusion makes no sense.
> 
> We can both fix the bugs and remove the guns at the same time. I already explained how guns can be rare and still meet the requirements for inclusion, justifying their presence at a gun show.

None of what you've said above explains how they can also meet the requirements for inclusion of a gun if rare because by virtue of them _being rare_, they're being removed from the game. There is a completely viable place they could be found instead.

**Comment by BalthazarArgall** [comment]
> None of what you've said above explains how they can also meet the requirements for inclusion of a gun if rare because by virtue of them _being rare_, they're being removed from the game by you. There is a completely viable place they could be found instead.

That's because we make a distinction between "rare" and "too rare for inclusion".

**Comment by Maleclypse** [comment]
> > > Maybe fix existing guns and the months long bugs where interchangeable barrels on certain rifles aren't spawning there instead of removing guns, guns that could fit in at a gun show. Gun shows where _collectors_ bring their guns to show off and trade. Having a gun show and having that "it has to be prominent enough in New England" rule for gun inclusion makes no sense.
> > 
> > 
> > We can both fix the bugs and remove the guns at the same time. I already explained how guns can be rare and still meet the requirements for inclusion, justifying their presence at a gun show.
> 
> None of what you've said above explains how they can also meet the requirements for inclusion of a gun if rare because by virtue of them _being rare_, they're being removed from the game by you. There is a completely viable place they could be found instead.

As mentioned above completed PRs are not the place to be discussing this.  If you ignore requests to change the venue of a conversation again in the future it could result in removal of your ability to comment on this repo.

**Pull request merged**
