### PR TITLE
Make EXOTIC HWP resemble a LMG

### PR DESCRIPTION
**Pull request by SirPendrak**
#### Summary

Balance "Increase weight of HWP EXOTIC configuration and give integrated bipod"

#### Purpose of change

This thing was too light, and baisicaly unusuable at full auto

#### Describe the solution

Give it some more weight and bipod as well as threaded muzzle for mounting muzzle brake, compensator etc.

#### Describe alternatives you've considered

Ideally, this would come with build in both bipod and muzzle brake, but because of how BIPOD flag works on single gunmod, effects of muzzle brake would be lost when firing this thing from shoulder

Make the bipod foldable but that was little benefit for more work

#### Testing

Tested

#### Additional context

None

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm not following your rationale. This is a hub-designed weapons platform that has a bunch of configurations. You bring them *ammo* samples and they make you a bolt/barrel(/maybe receiver?) parts kit to convert it to the new calibre.  It seems to be positioned as a LMG in this configuration so 5-round burst makes sense to me, and I definitely don't see a reason to override BombasticSlacks' choice here.

**Comment by SirPendrak** [comment]
I understand that original author had his vision, and I try to respect that by proposing change to something I believe was an oversight. 
In robofac_gun file there is a comment saying it is based on EXODI BR, so model 71., one that has only semi and 2 burst fire mode.
You dont get this conversion by bringing just ammo, you have to bring mag and one of two rifles. Both rifles have 2 round burst mode. Only LMG model 68. has full auto.
Another topic is that HWP chambered in 12.3 ln weights only 3,7 kg when you remove sights, and 3,5kg if we dont count integrated forward grip and laser sight. It is the largest caliber avaliable to it, probably closer to .30-06 than .308. Why is it getting higher rate of fire than every other HWP configuration? How is the super-light barrel not melting? IRL guns of similar role usually weight arround 8kg (BAR) or 6kg (H-car), but thats semi-auto only.
I know that HUB scientist can sometimes get too creative, but they are not total idiots, and recoil of this caliber on such lightweight platform while full-auto is enormous, making it useless, save for bursting shoggoths at point blank range

If this rationale is not enough, I will close this PR

**Comment by SirPendrak** [comment]
Changed the dialogue mentioning it accepting standard EXODI mags. I had two options: 
1. Make it accept both EXODI and HUB mags.
2. Change the dialogue. 
Other caliber conversion of HWP always use HUB-made mags, so I chosen option 2

**Comment by kevingranade** [comment]
> Another topic is that HWP chambered in 12.3 ln weights only 3,7 kg when you remove sights,
Ok, since that's such a dominant concern maybe bump the weight up a bit. That seems far more likely to be the oversight than the rate of fire.

>IRL guns of similar role usually weight arround 8kg (BAR) or 6kg (H-car), but thats semi-auto only.
Looking over https://en.wikipedia.org/wiki/Light_machine_gun that's not what I'm seeing. If you focus on the older ones yea they're heavy as hell, but more modern stuff like the RPK are down around 5kg. Even lower for more modern intermediate cartridges, but yea that makes it hard to do apples-apples because they're losing some weight because of modern materials, design goals etc and some because they're just chasing smaller cartridges.

**Comment by SirPendrak** [comment]
Ok, so now i am semi-happy with this version, and i think bipod is something that truly transforms this gun into LMG.
I had some problems when i tried to make this one BORE gunmod include both bipod and barrel/muzzle gunmods, baisicaly they were not working when BIPOD flag was present and gun was fired from shoulder.

This conversion still fits into HWP maitenance kit, but barerly

**Comment by kevingranade** [comment]
Works for me! I think this is what they call synthesis.

**Pull request merged**
