### PR TITLE
Martial Arts Rebalance for Ninjutsu

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Balance "Martial arts rebalance for Ninjutsu"```

#### Purpose of change

Partially implements #32422
Update for the martial art: Ninjutsu

#### Describe the solution

`Ninjutsu is a martial art and set of tactics used by ninja in feudal Japan.  It focuses on rapid, precise, silent strikes.`

_Current Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Arm Block|Unarmed 3||
Ninjutsu|Unarmed 0|Static Buff|Attacks are Quiet (generate no noise)
Momentum shift|Unarmed 0|OnMove Buff|+1 Dodges, Accuracy increased by 17% of Dexterity for 2 turns
surprise attack|Unarmed 3|Melee & Unarmed Crit Tech|+40% bash damage, +100% cutting damage, Stun duration: 2 turns

**Weapons:** All weapons.

There isn't much to Ninjutsu but it's surprisingly effective. The Quiet special ability can be useful and is the closest thing in the game to stealth at the moment. Surprise attack is a powerful tech that does crazy damage and stuns as well.

_Problems and issues_
- **Ninjutsu shouldn't be able to use every weapon.** 
This is a long one to discuss so I'll cover it under rebalance goals.

- **suprise attack needs Unarmed 3 to use but also works with a weapon.** 
Surprise attack works better as weapon attack do to the high damage. Adding a second Unarmed skill technique would give the style a bit of variety.

_Rebalance Goal_
There is a lot to talk about with Ninjutsu. First, yes, Ninjutsu is real ([LINK](https://en.wikipedia.org/wiki/Ninjutsu)). It is more of a combination of strategy, tactics, espionage than a traditional martial art. However, martial arts training in unarmed combat and weapon combat is part of Ninjutsu so having it as a martial art in CDDA is still valid.

Ninjas are a common staple of fiction and are well liked by a lot of people. While everyone knows what a ninja looks like and acts in fiction. The big problem is that fiction really hypes up what ninjas can do. Legends exist that said ninjas could control the elements through magic, turn invisible, fly, walk on water, etc. While fiction will often use these sorts of things as ninja powers, real life ninja could not do these sorts of things. Heck, real ninjas didn't dress in black most of the time, they usually wore plan clothing to hide in plain sight. Therefore, the fictional parts of Ninjutsu will not be included in CDDA's Ninjutsu martial art.

On the other hand, there are also some real life things in Ninjutsu that cannot be added to the martial art. Ninja tools like smoke bombs should be useable by everyone not just those using Ninjutsu and most forms of non-combat training like Tenmon (meteorology) have no place in the martial art. 

So what does all this background mean for the rebalance? I want Ninjutsu to be realistic but I also want people to live the fantasy of playing a ninja as much as possible. What does it mean to play as a real ninja in CDDA?
1. **Ninjas are stealthy.**
This goes without saying, ninjas know how to move around without being noticed. Some times this is sneaking but often times it was walking around in plain clothes and being completely unnoticed.
2. **Ninjas are fast and agile.**
Speed is key in Ninjutsu. Get into somewhere quickly, finish the mission fast, escape and run away. 
3. **Ninjas kill by assassination.**
Ninjutsu is an "anything goes" martial art and a ninja would do anything to win. Biting, scratching, whatever works. However, ninjas are more well known for performing assassinations and I think this is a better aspect to focus on. The first hit should be the most important.
4. **Ninjas used a variety of weapons.**
In ancient Japan, the weapons used by the ninja were pretty varied. They used traditional weapons such as the katana, quarterstaff, and tanto but also repurposed farming tools such as the Kunia and Kama as weapons due to the fact farmers were extremely common and no one would think twice about someone carrying farming tools. In the case of CDDA, I will make a compromise with this. I don't think ninjutsu should be able to use every weapon (ninjas don't use Battle Axes or Shotguns) but the style shouldn't be so restrictive in weapon choice. So any sort of logical jump in weapon use from the transitional ones will be useable by Ninjutsu.

_New Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Arm Block|Unarmed 3||
Ninjutsu Stance|Unarmed 0|Static Buff|Attacks are Quiet (generates no noise), movement is stealthy (generates 50% base noise)
Sneak Attack|Unarmed 0|Static Buff|+50% damage
Loss of Surprise|Unarmed 0|OnAttack Buff|-50% damage
Momentum Shift|Unarmed 2|OnMove Buff|+1.0 Dodge skill, Accuracy increased by 20% of Dexterity for 2 turns
Swift Strike|Melee 2|Melee & Unarmed Tech|80% move cost
Escape Plan|Melee 3|OnKill Buff|+2 Dodge attempts, +10 speed. Lasts 3 turns.
Assassinate|Melee 5|Melee Crit Tech|+50% damage, Stun duration: 1 turn
Ninjutsu Takedown|Unarmed 5|Unarmed Crit Tech|+100% bash damage, Knockdown duration: 2 turns, Stun duration: 2 turns

**Weapons:** 2-by-Sword, Arming Sword*, Bionic Claws, Bokken*, Broadsword*, Calvery Saber*, Combat Knife, Copper Knife, Cutlass*, Crude Sword, Dao, Dive Knife, Firebrand*, Hunting Knife, Ironshard Quarterstaff, Jian*, Katana*, Kopesh, Kirpan*, Kris, Kukri, L-stick*, Longsword, Machete, Makeshift Knife, Monomolecular Blade, Nodachi*, Nord*, Powered Quarterstaff, Quarterstaff, Rising Sun*, RM42 Fighting Knife, Scimitar*, Shishkebab*, Sickle, Surival Knife, Switchblade, Sword Bayonet, Tanto*, Trench Knife, Wakizashi, Xiphos
*Includes all variations

_Important Changes_
- **Added Sneak Attack buff and Loss of Surprise buff.**
Assassinations are all about the initial strike. Ninjutsu mimics this but having a high damage Static Buff. However, once you make your initial attack, you lose the benefit of the surprise. In this case, an OnAttack buff will trigger after you attack and cancel out the high damage buff of the passive. Because it's an OnAttack buff, it will renew itself every time you attack. The only way to get rid of it is to not attack. Running away, waiting, etc for a few turns will allow you to gain the full benefit of Sneak Attack again.

- **Added "stealthy" attribute to Ninjutsu Stance buff.**
This new attribute will increase the stealthiness of the player. See below.

**New buff attribute: "stealthy"**
"stealthy" is a buff attribute that when set to true, causes the player to generate half as much base noise when moving. By default, players generate 6 noise when moving before any traits or effects are applied to the noise. Having a "stealthy" buff will reduce this amount to 3. 
Without any other modifiers, players will generate a very small amount of noise when walking, slightly less noise when running, and 0 noise when crouching.

- **Added Escape Plan buff.**
This OnKill buff is means to allow a Ninjutsu practioner to get away from a group or a bad situation after killing something. It helps cemment Ninjutsu as a hit-and-run style. "speed" is an attribute that isn't used in any other martial art. It works similar to the Quick trait in that it increases your available action points for the duration of the buff.

- **Added Ninjutsu Takedown.**
Assassinate is more geared towards weapon use than unarmed. As such, I added this technique to aid unarmed Ninjutsu practioners. It isn't as damaging but it can give you a moment to retreat and let Lose of Surprise wear off before you attack again.

- **Ninjutsu now uses style weapons instead of all weapons.**
Ninjutsu is trained in a number of Japanese weapons. This training can extend to any sort of weapon of similar size and function:
**Katana** - Any normal sized sword such as a Broadsword
**Nodachi** - Any larger that average sword such as a Longsword
**Wakizashi** - Any sort of short sword
**Tanto** - Any sort of knife
**Quarterstaff** - All variations of quarterstaves
**Kama** - Although not in the game, this training extends to other bladed farming tools such as the Sickle.

_Advantages_
- With the right weapon and a critical hit, you can do so much damage on your first attack that you might outright kill your opponent.
- Slient attacks and stealthy movement allow you to pick and choose your fights in areas with less light.

_Disadvantages_
- Your first attack makes or breaks how you perform in combat. Missing is going to a big setback.
- As a hit-and-run style, you are going to spend a lot of time moving around just to get in a few good hits.
- Ninjutsu is terrible at handling groups unless you pick off your enemies one at a time. The [Conservation of Ninjutsu trope](https://tvtropes.org/pmwiki/pmwiki.php/Main/ConservationOfNinjutsu) does not apply to CDDA.
- Being stealth doesn't really matter if your enemies can see you from 20 tiles away.

#### Describe alternatives you've considered

Ninjutsu is essentially an ad-hoc version of a stealth system. In the event of an actual stealth system being implemented into the game, Ninjutsu should be reevaluated to prevent the style from being too strong when paired with the stealth system. Depending on what kind of stealth system is created, it might be wise to remove Ninjutsu to prevent problems. If this is done, I recommend adding Ninjutsu back to the game in some different form to allow players to continue playing out the fantasy of being a ninja.

_If the style is too strong..._
- Reduce the damage from Sneak Attack.
- Increase the damage penalty from Loss of Surprise.
- Reduce the damage on Assassinate and Ninjutsu Takedown.

_If the style is too weak..._
- Reduce the duration of Loss of Surprise.
- Increase the duration of Escape Plan or Momentum Shift.
- Increase the damage on Assassinate and Ninjutsu Takedown.

#### Additional context

_References:_
[Ninjutsu wikipedia page](https://en.wikipedia.org/wiki/Ninjutsu)
[Ninjutsu Weapons](https://blackbeltwiki.com/ninjutsu-weapons)

### CODE REVIEW

**Comment by Hymore246** [comment]
Jenkins rebuild

**Comment by Noctifer-de-Mortem** [comment]
Any consideration for adding the bionic blade (monomolecular blade) to the weapon lists? It’s description and the profession it is included in hints at it being an assassination weapon.

**Comment by Hymore246** [comment]
> 
> 
> Any consideration for adding the bionic blade (monomolecular blade) to the weapon lists? It’s description and the profession it is included in hints at it being an assassination weapon.

Yeah, I could see the style adapting to bionics pretty fast. Also, bionic weaponry are considered to be unarmed weapons so they will work with most styles right now. But I'll add them to Ninjutsu in the off-chance that changes.

**Comment by 321nick** [comment]
> Aikido is a Japanese martial art focused on self-defense, while minimizing injury to the attacker.

minor thing, but, shouldnt this be changed too the vanilla text about ninjutso, not aikido?

**Pull request merged**
