### PR TITLE
[CR] Remove PDA

### PR DESCRIPTION
**Pull request by Cyrano7**
The cell phone is basiclly a carbon copy of the pda now. Pretty much cell phones and pdas are the same thing irl now anyways. Is the current cell phone description clear enough? Should we be changing the name to "smartphone"?

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> Should we be changing the name to "smartphone"?

Not necessarily name, but it would be a good thing to note that in the description. And maybe in deconstruction recipe.

**Comment by BorkBorkGoesTheCode** [comment]
Why not add the PDA to museums?

**Comment by Mecares** [comment]
Or change the name of the PDA to Tablet?

**Comment by Shoes01** [comment]
Would a tablet be functionally different from a cell/smart phone?

**Comment by harald921** [comment]
Just because they share functionality, it doesn't mean one has to go. Perhaps make one lighter, or smaller, etc.

**Comment by Totentag** [comment]
Does the E-Ink Tablet not fill that niche exactly already, @harald921 ?
With added functionality beyond what the PDA has.

**Comment by pisskop** [comment]
I dont know about you guys, but Im finding the flashlight app on that phone to last for hours.  should be horrendously inefficient.  not enough to grind my tailoring to level 3 before it cops out

**Pull request merged**
