### PR TITLE
Electric motor size revamp : Add tiny motor and micro motor

### PR DESCRIPTION
**Pull request by Fris0uman**
Add a new smaller type of electric motor : the tiny motor, a 0.5HP (power : 4) electric motor.
 
Replace motor_small with motor_tiny in several recipes : door_motor, drive_by_wire_controls, carver_off, cordless_drill, food_processor, makeshift_sealer and electric_hair_trimmer.

Add motor_small to deconstruction recipe of dryer and whashing machine.

Idea comes from this discussion : [washing-machine-and-dryer-not-containing-a-motor](https://discourse.cataclysmdda.org/t/washing-machine-and-dryer-not-containing-a-motor/15815/17)

There's still at least two issue that i can see but don't know how to resolve : 
- I couldn't get the volume to be smaller than 1 (without being 0)
- tiny motor might be a silly and imprecise name, maybe it'd be good to rename electric motors with a better convention ? Using HP or Voltage, I don't know how it works in real life.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> I couldn't get the volume to be smaller than 1 (without being 0)

Your motor appears to be less than 250 ml (= 1 volume)?

**Comment by Night-Pryanik** [comment]
Also `fan` item could probably yield this motor on disassemble?

**Comment by Fris0uman** [comment]
> Your motor appears to be less than 250 ml (= 1 volume)?

Yes it's the same size as the small motor, which kind of defeat the purpose of making a "smaller" motor.
But if I input a value between 1 and 0 the item is automatically 0.01L

**Comment by Fris0uman** [comment]
Yep there something weird with the sizes of motors. 
But I need to do somre research to understand what should be their real size

**Comment by Rivet-the-Zombie** [comment]
>A powerful electric motor with a volume of only 1,5 liters?

Electric motors don't have to be very large to be really powerful. Car starters are an example.

**Comment by sfsworms** [comment]
I was a bit interested in trying to correct the various motor power output, weight and size (to prevent tanks doing 300 mph among other issues). I'll try to dig up some numbers at some point.

**Comment by Mecares** [comment]
Half a horsepower is still a lot of power, we are talking about 370 Watts. Maybe power 1 would be better than 4 for most uses of a tiny motor. We could think about adding it to all manhack and turret recipes. Maybe add some tiny motors to the butchering results of robots.

**Comment by sfsworms** [comment]
Those seems to be industrial motors, presumably weight reduction isn't really a concern for those. It seems about ok for industrial electric motors. (This has good tables of size and wieght too) http://www.steelofab.net/pdf/Hindustan-Electric-Motors-Catalogue.pdf

For comparison, a Tesla model S electric motor weight about 175 kg (https://www.quora.com/How-much-does-the-Tesla-Model-S-motor-weigh?share=1) and has a power outpout of 780 HP. Looking at the equivalent power from our hindustani friends, the biggest engine they have is 420 HP, and weight a whooping two tons. 

I guess for our purpose, looking at motors of electric cars, bikes, scooter and the like probably provide the best yardstick?

**Comment by Fris0uman** [comment]
So rather than trying to fit a size to a power we decide on which engine is which and  estimate a size this way ?

`enhanced electric motor` is a like a Tesla engine : 780 HP, 175 kg and 250L [Tesla Model S Drive Unit](http://www.evwest.com/catalog/product_info.php?products_id=476)

`large lectric motor` is like one from a racing car : 420 HP, 90kg and 16L [AM Racing AMR Dual Stack 250-90 AC Motor](http://www.evwest.com/catalog/product_info.php?products_id=300)

`electric motor`  standard  electric car : 125HP, 68kg and 20L [Curtis 1238e-7621 HPEVS Dual AC-34](http://www.evwest.com/catalog/product_info.php?cPath=8&products_id=170) (I don't know if it's really "standard" or not)

`small electric motor` motrobike : 15HP , 17kg and 5L [BLDC / PMSM brushless motor HPM-10KW](https://www.miromax.lt/en/m-6/c-39/c-45-brushless_bldc_motor_with_permanent_magnet/product-507-bldc__pmsm_brushless_motor_hpm-10kw_-_nominal_power10kw13kw__134ag174ag___650cm3#to_products)

`tiny motor` electric bike : 0.7HP , 5.8kg and 0.5L [Front 500w Heavy-Duty Direct-Drive Motor](https://www.ebikekit.com/collections/wheels/products/front-500w-heavy-duty-direct-drive-motor)

It seems to fit the role of each motor correctly, but I don't really have any rational to choose those models other than that's the ones I found. 

And maybe we throw a `micro motor` on top of that for manhacks and some tools ? Could be an item just for crafting that is not a vehicle part so we don't have to assign it any power value ?

**Comment by sfsworms** [comment]
They seems about right. Maybe I just think you're overestimating the size od the tesla motor since it has that "bulge" on the side. Assuming the bulg is one third of the total size, I get 108 L. 

I also get something a bit bigger, around 30L, for the racing car.

The "micro motor" is also nice

**Comment by nexusmrsep** [comment]
"Servomotor" maybe?

**Comment by Fris0uman** [comment]
Well I thought about that, but servomotor are for precise mouvement. That doesn't seem to fit with manhack rotating blades or the motor inside a food processor. The only thing I can think of that could be using servomotor is `door_motor` but for only one object I don't think it's worth.

**Comment by John-Candlebury** [comment]
The enhanced electric engine is more like a wheel hub motor, its just that the the vehicle rework that would have allowed them to  function properly never happened to conclusion.

Notice that is both very small and lightweight and has low efficiency, the only car that includes it by the default (atomic sports car) also has them installed in the wheel tiles.

**Comment by Fris0uman** [comment]
> The enhanced electric engine is more like a wheel hub motor, its just that the the vehicle rework that would have allowed them to function properly never happened to conclusion.

If I read the jsons correclty `motor_enhanced` is currently 3L, 20Kg, 250HP and has `"epower": -60000,`
We could keep it this way, and just adjust the description to mention the wheel hub thing.  

But now I realise that I have no idea how to adjust power consuption, does anybody now how `epower` is calculated ?

**Comment by ZhilkinSerg** [comment]
Tests need to be updated.

**Comment by Fris0uman** [comment]
So after a bit of testing it turns out that a 1HP `motor_tiny` can't move a bike with the player on it. 
image

After bumping `power` to 5 HP top speed is still of only 6km/h, what I get from that is that it's pointless to tweak electric motor to be more "realistic" if it's making them useless in game.

So what do you guys think ? Is there a way to solve that only with json ? Or should I just close this PR and maybe try again one day when vehicle physics is reworked ?

**Comment by Fris0uman** [comment]
So in the end I just changed the weight and volume of the motors and added motor_micro which is a very small motor for recipes only.
Now it seems that every check is failing, how do I check what's messed up to correct it ?

**Comment by kevingranade** [comment]
This PR is pretty hosed, can you copy your changes to a new branch?  That seems a lot easier than trying to resolve it through git.

**Pull request closed without merging**
