### PR TITLE
Remove unused VORPAL flag

### PR DESCRIPTION
**Pull request by illi-kun**
> “Beware the Jabberwock, my son!
>       The jaws that bite, the claws that catch!
> Beware the Jubjub bird, and shun
>       The frumious Bandersnatch!”
> 
> He took his ~~vorpal~~ _regular_ sword in hand; 
> And simply slain it.
> 
> The End.

This PR clean up all places where `VORPAL` was left. Initially, it was hardly obtainable thing for flavor but after landing of #14052 it's become completely useless.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Butbutbut...

shwing_zpsn1mnmabp

That is admittedly the one and only time I've ever had that technique go off, but it could not have been better timed. o3o

**Comment by illi-kun** [comment]
Thank you, @chaosvolt! I missed to obvious thing: only part of `VORPAL` thing was lost and the most important part of it (=technique) is still working. Sorry for that.

Your amazing hit of unknown spirit of fire will be preserved through the centuries!

**Comment by chaosvolt** [comment]
Doh. So being able to obtain the technique with a diamond blade still works?

Though if the new holster technique had the "check for vorpal flag" thing inserted into it, that would allow not losing any of the original functions.

In any case, it's fine. Having the technique on that sword doesn't really do much. XP

**Comment by illi-kun** [comment]
I thought that the only effect of this flag was glowing  but during cleaning stuff up I removed technique with the same name and you demonstrated that this technique actually do something useful.

**Comment by chaosvolt** [comment]
Ah, I see. That said, the technique has such an immensely low weight that it likely rarely proves itself useful. And removing it from the incorruptible blade wouldn't be much of a loss. XP

**Comment by sparr** [comment]
@illi-kun a good strategy when doing something like this is to just grep the whole src directory for the flag in question to see everywhere it's used.

**Comment by illi-kun** [comment]
@sparr yeah that's typically how I do this but here I made some incorrect conclusion and it brings me to incorrect result.

**Pull request closed without merging**
