### PR TITLE
Fix attack speed test failures

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Unbreak CI
#### Describe the solution
~~slap !mayfail to test~~ block bouldering effect, also make character attack the debug mon, and not themselves

### CODE REVIEW

**Comment by mqrause** [comment]
> i can't reproduce it locally

I just went through recent PRs to look for some windows fails. You could try reproducing it with these seeds:
1712972203
1712879528
1712952697

You'll need to do a full test run, though, since the windows build doesn't use any filters.

**Comment by GuardianDll** [comment]
tried to run 1712972203, but have a lot of some mysterious errors - first error in Character_attacking_a_zombie, now in crafting_with_a_companion

**Comment by osuphobia** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8673271162/job/23784451215?pr=72987

Failed in Basic Build and Test (Clang 10, Ubuntu, Curses), randomness seeded to: 1713010785.

```
(~[slow] ~[.],starting_items)=> ../tests/enchantments_test.cpp:242: FAILED:
(~[slow] ~[.],starting_items)=>   REQUIRE( moves_spent_on_attacks == -380 )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   -446 == -380
(~[slow] ~[.],starting_items)=> with messages:
(~[slow] ~[.],starting_items)=>   Character, melee skill lvl 10, attacks with no enchantment
(~[slow] ~[.],starting_items)=>   10 attacks cost 380 moves
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> Log messages during failed test:
(~[slow] ~[.],starting_items)=> 10:00:27AM: 
(~[slow] ~[.],starting_items)=> 10:00:27AM: You eat your holy SPAM of debugging (fresh).
(~[slow] ~[.],starting_items)=> 10:00:27AM: You start walking.
(~[slow] ~[.],starting_items)=> 10:00:27AM: 
(~[slow] ~[.],starting_items)=> 10:00:27AM: You have learned a new style: Brawling!
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 4 damage.
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 0: attack cost: 38, total amount of moves: -38
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 9 damage.  Critical!
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 1: attack cost: 38, total amount of moves: -76
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 4 damage.
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 2: attack cost: 38, total amount of moves: -114
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You try to keep your balance.
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 8 damage.  Critical!
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 3: attack cost: 38, total amount of moves: -152
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You miss.
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 4: attack cost: 49, total amount of moves: -201
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 3 damage.
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 5: attack cost: 49, total amount of moves: -250
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 2 damage.
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 6: attack cost: 49, total amount of moves: -299
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 3 damage.  Critical!
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 7: attack cost: 49, total amount of moves: -348
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 2 damage.
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 8: attack cost: 49, total amount of moves: -397
(~[slow] ~[.],starting_items)=> 10:00:28AM: 
(~[slow] ~[.],starting_items)=> 10:00:28AM: You hit you for 3 damage.
(~[slow] ~[.],starting_items)=> 10:00:28AM: attack 9: attack cost: 49, total amount of moves: -446
```

After a miss, the attack cost changed from 38 to 49.

**Comment by osuphobia** [comment]
> After a miss, the attack cost changed from 38 to 49.

Missed attack is irrelevant.
The real reason should be this: `You try to keep your balance.`
https://github.com/CleverRaven/Cataclysm-DDA/blob/36578d798b731bc71ad5d890ae0c24d754384be2/data/json/effects.json#L672-L682

The avatar walked on a boulder, and got a limb_score balance penalty, which will `Modifies thrown attack speed, movement cost and melee attack rolls.` as it is said in the JSON_INFO.md.

bf
af

**Comment by GuardianDll** [comment]
why characters starts to move, interestingly 🤔 
clear_map should remove all the stuff

**Comment by mqrause** [comment]
If I interpret that correctly, because the test guy attacks themself, whenever they hit their own legs with a crit, they get a chance to apply the bouldering effect. So yes, blocking the effect should work, but also they probably shouldn't attack themselves.

**Comment by GuardianDll** [comment]
wdym attack themselves?

**Comment by osuphobia** [comment]
The attack speed test seems fine now, but the tests in iteminfo_test.cpp failed this time.
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8482270578/job/23241203488?pr=72690
I've got exactly the same failure, do you know the reason of it?

**Comment by osuphobia** [comment]
> If I interpret that correctly, because the test guy attacks themself, whenever they hit their own legs with a crit, they get a chance to apply the bouldering effect. So yes, blocking the effect should work, but also they probably shouldn't attack themselves.

The test do generate a debug monster though, you mean the test guy is not attacking the monster but themself?
Ahh, the sentence `You start walking` is misleading me, it pops up not because the guy start moving, but movement_mode set to walk?

**Comment by mqrause** [comment]
> wdym attack themselves?

https://github.com/CleverRaven/Cataclysm-DDA/blob/36578d798b731bc71ad5d890ae0c24d754384be2/tests/enchantments_test.cpp#L218

`guy` is attacking `guy` instead of the debug monster.

**Comment by GuardianDll** [comment]
I didn't know it is possible
Should it be `pseudo_debug_mon` instead of a `guy` there?

**Comment by mqrause** [comment]
Sorry, that might have been a bit of a miscommunication. You need to add the target creature as a parameter to `test_melee_attack_attack_stamina` and then adjust the calls in the `Enchantment_MELEE_STAMINA_CONSUMPTION_test` test case.

**Pull request merged**
