### PR TITLE
Add piercing and ballistic protection to mycus skin mutations due to lack of integrated armor

### PR DESCRIPTION
**Pull request by MushroomW**
#### Summary
None 

#### Purpose of change
fix it

#### Describe the solution
add protection

#### Describe alternatives you've considered
give integrated armor to the mutations instead

### CODE REVIEW

**Comment by MushroomW** [comment]
balancing. and mainly it makes sense that it would have some ballistic / stab protection since it also has cut protection

**Comment by Fris0uman** [comment]
Damage type are distinct because it takes distinct things to resist them, having cut or bash resistance does not imply resistance to pierce and ballistic or otherwise they would all just be the same damage type

**Comment by MushroomW** [comment]
this is how it works with regular clothing. why would skin material be any different. it's just a material. a good example of this is the phelloderm mutation

**Comment by Night-Pryanik** [comment]
Due to what? Pr's title is incomplete.

**Comment by MushroomW** [comment]
not sure what causes this. sorry

**Comment by kevingranade** [comment]
You haven't presented any meaningful rationale for this, and I don't expect mycus skin to present a notable amount of ballistic or piercing protection relative to human skin.

**Comment by tenehea** [comment]
But it already provides some minor increase in protection against bash and cut over human skin. Why would it not also provide a minor increase in protection against ballistic and pierce?

**Pull request closed without merging**
