### PR TITLE
Makeshift flotation vest

### PR DESCRIPTION
**Pull request by ituluwituluwzev**
Makeshift flotation vest is made of inflated animal skins, for survivors who need to swim across water with equipment and loot, but have not found a factory-made one.

### CODE REVIEW

**Comment by ituluwituluwzev** [comment]
The first commit was synchronizing my fork with the master, and is irrelevant. Is there a better way to synchronizing fork?

**Comment by Night-Pryanik** [comment]
I found this excellent tool (https://upriver.github.io/) to synchronize forks and branches.

**Comment by Leland** [comment]
It's a question of merges vs. rebasing. Rebasing is cleaner and I prefer it, but only if the PR hasn't been reviewed yet.

`git pull origin master && git rebase master` will do it (provided `origin` is this repository)

**Comment by ituluwituluwzev** [comment]
Thanks! Very useful! What's wrong with the recipe, though?

**Comment by Night-Pryanik** [comment]
You need to lint your changes - put them in http://dev.narc.ro/cataclysm/format.html.

**Comment by ituluwituluwzev** [comment]
Thanks! I think it passes the check now.

**Pull request merged**
