### PR TITLE
Code optimizations reported by static code analysis (2019-01-14)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

SUMMARY: Performance "Code optimizations reported by static code analysis"

#### Purpose of change

Cleanup code while increase performance and fix minor error.

#### Describe the solution

See commit messages.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by narc0tiq** [comment]
Err? There's no website at :80 on that host (nor at :443) -- you want http://gorgon.narc.ro:8080/. Or https://ci.narc.ro/, which is a reverse proxy for the same site.

I'm not sure what's going on with the Jenkins PR builder. Clearly it's getting some PR notifications, but not others? It's weird.

**Comment by ZhilkinSerg** [comment]
Yes, I've checked port 8080 - just copied incorrect URL here. Seems that was a temporary issue and it is fine now.

**Comment by narc0tiq** [comment]
Looking in the webhook log, I'm seeing some of this: 
image

Each of the errors is, as shown, a timeout, and all of them were able to be manually redelivered and worked absolutely fine. I imagine the build machine must be getting a little too busy to respond in a timely manner while a build is actually going on. Maybe some [nice(1)](https://linux.die.net/man/1/nice) would be required in there...

To be honest, the best solution would be to have the Jenkins front-end running on a separate machine from the build machine, but I don't expect to have the time to make that change anytime soon. However, automatic niceness is definitely something I can look into.

**Pull request merged**
