### PR TITLE
Resolves #23527 - split scrambled eggs recipe

### LINKED ISSUE #23527: Scrambled eggs recipe (regular and deluxe) requires water
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
You can craft (cook) scrambled eggs just by having a source of heat, a cooking utensil able to contain eggs like a frying pan and eggs, the way you can easily do so IRL

### Actual behavior
Both deluxe scrambled eggs (regular scrambed eggs + meat) and 'scrambled eggs' require water for crafting.

### Steps to reproduce the behavior
Attempt to craft 'scrambled eggs'.

### PR DESCRIPTION
**Pull request by gastamper**
This PR resolves #23527 by removing the requirement for water to cook scrambled eggs.

### CODE REVIEW

**Comment by Mecares** [comment]
We desperately need the ability to define A or (B + C) as ingredients.

**Comment by gastamper** [comment]
Thanks for catching that, BorkBorkGoesTheCode.

And yes, it would be very nice if we could do somewhat more logic in recipes.

**Comment by ZhilkinSerg** [comment]
There is also deluxe scrambled eggs recipe. You should change it too for consistency.

image

image

**Comment by Isaacssv552** [comment]
@Mecares, If you want to define A or (B + C) in ingredient lists I'd advise looking at the  requirement_data struct in requirements.h. However, adding that capacity would likely be non-trivial. Maybe a format like the below would work? You'd have to consider backwards compatibility as well.
`"components": [
    [ "AND", 3 ],
    [ "duct_tape", 100 ],
    [ "blade", 1 ],
    [ "OR", 2 ],
    [ "stick", 1 ],
    [ "AND", 2 ],
    [ "2x4", 1 ],
    [ "broom", 1 ]
  ]`

**Comment by DoctorVanGogh** [comment]
> We desperately need the ability to define A or (B + C) as ingredients.

This game needs the ability to define recipes as
- "Needs n units of [foo]"

Where items are not used directly but for their contained properties.

Like allowing _mixed_ fruits to be used for dehydrating.
Like allowing 5 reptile & 7 birds eggs to make 1 unit of powdered egg...

**Comment by Isaacssv552** [comment]
@DoctorVanGogh I think that would actually be easier to add, although editing the JSONs to take advantage would be a pain. Something like

`"components": [ [ "duct_tape", 100 ], [ "blade", 1 ], [ "WOOD_CAT", 3 ] ]`

**Pull request merged**
