### PR TITLE
Remove modularvest items

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
SUMMARY: Content "Remove MBR vests"

#### Purpose of change
MBR vests were a relic of old cata with inconsistent behavior and no discernible basis. They're being replaced with real plates and carriers.

#### Describe the solution
Remove `modularvest*` items. Replace with other items where appropriate.

#### Testing
Game loads correctly without errors.

#### Additional context
We may want to add survivor made hard steel plates and stab panels.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
This sounds like a great idea but should probably wait for the real plates and plate carriers to be ready, so we can swap them in to replace the mbr variants (everywhere if appropriate). I don't see how removing mbr vests from the game before them helps us much.

**Comment by SirPendrak** [comment]
"Kevlar slot" in survivor recipes had MBR before, now it has ballistic vest empty. But does it contain any kevlar at all? 

Why remove it completly right now, even if theese things wont spawn naturally anymore, maybe keep the recipes? They dont seem Scifi or harder to make than other recipes we already have, and they offer good variety for survivors that manage to gather varoius materials for their forst serious armor. And their ballance PR is already on Github

**Comment by Brian-Otten** [comment]
Keep this in in the pocket though, when we have the plate carrier system with plates fully ready this should almost definitely happen. Should cause no loss of functionality then and improve the gamefeel.

**Comment by tenmillimaster** [comment]
>"Kevlar slot" in survivor recipes had MBR before, now it has ballistic vest empty. But does it contain any kevlar at all?

Functionally speaking, an MBR and an empty ballistic vest(insert-less SPCS or similar, all the way back to interceptor era armor likely) are identical. The empty ballistic vest could be disassembled further to remove its soft armor inserts.

**Comment by tenmillimaster** [comment]
I recommend just going ahead and replacing the MBR variants with ballistic vest variants.

Kevlar insert, Bookplate, Aluminum sheet, Titanium panels, steel plating  and commercial AR500 Hardsteel plating (hard plating item is sufficiently similar, as many industrial applications use similar Abrasion Resistant steels) would all be valid options.  

- Hard plating would be the only one you'd encounter in the wild, however, (not in military service).
- Bookplate is what some law enforcement agencies are teaching these days as part of active shooter response. 
- Kevlar inserts are used sometimes as an alternative to spall liners found on plates. They would increase protection if used alone on a vest.
- Aluminum, Titanium, and mild steel would all provide little protection (to varying degrees) but would absolutely increase the vest's performance.

I also recommend, either here or at a later date, relegating the MBR items to a Post-cataclysm Survivor fabrication. In this sense, it'd be the sewing of front, back, and side pockets to accept ballistic inserts onto a kevlar vest, to increase its protection.

**Comment by Ker-Nes** [comment]
I'm against it. A rename might be good, but the MBR is a good option to represent overt bullet resistant vests with plate holders. While the ballistic vest is a good option to represent actual plate carriers (which aren't bullet resistant on their own), there are such things as the aforementioned overt vests, such as this one: https://www.marsarmor.com/products/ballistic-vests/overt/model-25/ and multiple others.

**Comment by kevingranade** [comment]
This is pretty impactful, so I want to take it a little slow.

1. Add the new ballistic vests and spawns, remove spawns of old vests.
2. Let it sit for a while and make sure nothing is breaking.
3. Migrate existing MBRs to the equivalent ballistic vest.

**Comment by Inglonias** [comment]
I'm still concerned about the absurdly high armor values of the new ESAPI vests. Are we sure that those are in line with reality? They seem extraordinarily powerful, especially if compared to other armor in the game.

**Comment by SirPendrak** [comment]
Lets increase armor of every zombie soldier type to 50b 90c to match ballistic vest almost every one zsoldier wears. 

On serious side, someone made seriously wrong assumption that IRL behavior of stopping most 7,62 rifle rounds translates to 0 dmg at our current damage system. Armor values of old Hardsteel MBR reflected it better.

**Comment by Inglonias** [comment]
It looks like the main issue is that we can't actually define those values directly. They are derived from material thickness, and with a material thickness of 20, the ESAPI plates just break the armor and damage system. It may be worth looking at how those get calculated before we replace the MBRs with these new vests.

**Pull request merged**
