### PR TITLE
Fix almost instantaneous and always successful climbing the downspouts

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Balance "Fix almost instantaneous and always successful climbing the downspouts."```

#### Purpose of change
Right now climbing downspouts is much more faster than it should be (4 seconds) and has no chance to fail (unlike climbing terrains like wire fence).

#### Describe the solution
- Increased time cost to climb terrain with `UNSTABLE` flag (like downspouts). With 500 additional moves it's total of ~7 seconds which is almost two times more slower than before, but is still way too fast than it should be.
- Added a chance to slip while climbing up these terrains (and climbing down from `ledge` terrains). The formula is taken from `chainfence` iexamine function: chance is based on player's dexterity and/or `BADKNEES` mutation. Slipping when climbing up will just cost you time for a failed attempt. Slipping while climbing down from a ledge will make your character fall off and take heavy damage from falling.

#### Describe alternatives you've considered
I wanted to make climbing up and down much more slower, probably a minute or two, but that will make player defenseless and unresponsive for all this time. This would require converting climbing to an activity.

#### Testing
Climbed up through the downspouts. Climbed down from ledges. Checked for consumed time. Observed situations when character slipped down while climbing up and down.

#### Additional context
None.

### CODE REVIEW

**Comment by jbytheway** [comment]
>     [...] The formula is taken from `chainfence` iexamine function: chance is based on player's dexterity and/or `BADKNEES` mutation.

Looks like this formula is now duplicated in three places (chainfence and your two new ones).  Could you refactor it as a function called from each?

**Comment by Night-Pryanik** [comment]
> Could you refactor it as a function called from each?

Yeah, sure.

**Comment by MirrorMorphMemories** [comment]
I know I'm a little bit late, but would it be reasonable to make traits like Parkour Expert and Bad Knees, as well as mutations like Arachnid Arms, influence your climbing speed and reliability? I know this is something that already influences climbing over fences (see https://github.com/CleverRaven/Cataclysm-DDA/blob/47bc01243222b4af43437fab3f1b9ff8559674ab/src/iexamine.cpp#L1009), so I think it's something that can be mostly copied and pasted over to clambering down drainpipes.

**Comment by Night-Pryanik** [comment]
Bad Knees is already affecting the chance to slip down while climbing the downspouts.
I'm not sure about Parkour Expert, as IMO it's helpful only when climbing over horizontal obstacles.
Arachnid and Insect Arms - sure, their effects could be added, but as for now they have minimal on climbing over the fence - both 90 and 75 moves cost for these mutations are less than one second, and player wouldn't even notice their effect.

**Pull request merged**
