### PR TITLE
make onion rings craftable

### PR DESCRIPTION
**Pull request by Cyrano7**
Makes onion rings craftable. Changes nutrition from 9 to 8. Now its (8 \* 3) 24 for the rings. 
Ingredients are maximum 25 (onion + bread) but mostly lower like 23 (cornbread + onion)

### CODE REVIEW

**Comment by Malkeus** [comment]
That oils gonna taste mighty funky after awhile ;)

**Comment by Cyrano7** [comment]
Ya one thought I had was that we could have a "dirty oil" byproduct that you could still use for other applications, just not for food anymore.

**Comment by Rivet-the-Zombie** [comment]
Fry potatoes in it; it takes most of the browned flour out of the oil. Or just [don't worry about it at all](http://www.omgfacts.com/food/4624/A-restaurant-in-Memphis-serves-burgers-that-have-been-fried-in-98-year-old-cooking-grease).

I don't think it's a big enough thing to worry about.

**Comment by chaosvolt** [comment]
It is terrifying.

**Comment by Malkeus** [comment]
Jeez, no way. Oil evaporates as you cook with it, that's one reason why fast-food workers have such shiny, pox-ridden complexions and smell like stale grease. I worked at long john silvers for awhile and we'd lose a half-inch of oil out of the fryers in a day, straight into the overhead fans and ductwork, where it eventually caught fire...Good times.

**Comment by chaosvolt** [comment]
Hmm. So a simple way would be to have frying recipes use oil as a component instead, and return a reduced amount as a byproduct. Whether it's evaporated or no longer usable, either way that method can be used to represent it in abstract.

**Comment by ejseto** [comment]
There's no such thing as an "onion_fried" in the json files, causing a debug error. I assume you meant "onion_rings".

**Comment by Cyrano7** [comment]
Your right its onion_rings. Ill fix it now. My bad.

**Pull request merged**
