### PR TITLE
Pull enemies Scorpion-style

### LINKED ISSUE #51816: Short-range attacks with pull capability
# Is your feature request related to a problem? Please describe.

Currently, there does not appear to be any way to have a mutation (e.g., a frog's tongue) or a weapon (e.g., a chain, preferably with spikes) that pulls on an opponent.

# Describe the solution you'd like

A way to do this, both for mutations and weapons; possibly a spell effect, to do as an enchantment?

# Additional context

Ping: @Maleclypse, @KorGgenT?

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
Fixes #51816.

#51630 introduced some neat new mutation lines. One thing it was missing was the ability to latch onto enemies with a tongue mutation and pull them towards you. Until now...

https://user-images.githubusercontent.com/12537966/136326921-dd92444b-3d16-4ed3-a6f6-f6424e2ae76a.mp4

#### Describe the solution
I created a new activity `ACT_PULL_CREATURE` which allows the player to select a target and pull it towards them. I've added this activity as an activation effect for these mutations:
- `LONG_TONGUE2` - Whipping Tongue
- `GASTROPOD_EXTREMITY2` - Rasping Tongue
- `GASTROPOD_EXTREMITY3` - Harpoon Tongue

There's also a new spell effect `pull_to_caster` that calls the same longpull function. This should enable other abilities to use this effect from JSON.

The ability to pull a creature depends on its weight as well as the player's strength. If a creature is seriously heavy, there's a chance the pull will fail. Here's a handy table showing the % chance to pull a creature of X kg:

| STR | 20kg | 40kg | 60kg | 80kg | 100kg | 120kg | 140kg | 160kg | 200kg | 300kg |
| ----- | ------ | ------- | ------ | ------ | -------- | ------- | -------- | -------- | ------- | -------- |
| 2      | 9% | 2%    | 1%    | 1%   | 0%     | 0%      | 0%      | 0%     | 0%     | 0%      |
| 4      | 36% | 9%  | 4%    | 2%   | 1%     | 1%      | 1%      | 1%     | 0%     | 0%      |
| 6      | 81% | 20% | 9%   | 5%   | 3%     | 2%      | 2%      | 1%     | 1%     | 0%      |
| 8      | 100% | 36% | 16% | 9% | 6%     | 4%      | 3%      | 2%     | 1%     | 1%      |
| 10    | 100% | 56% | 25% | 14% | 9%   | 6%      | 5%      | 4%     | 2%     | 1%      |
| 12    | 100% | 81% | 36% | 20% | 13% | 9%      | 7%      | 5%     | 3%     | 1%      |
| 14    | 100% | 100% | 49% | 28% | 18% | 12%  | 9%      | 7%     | 4%     | 2%      |
| 16    | 100% | 100% | 64% | 36% | 23% | 16%  | 12%    | 9%     | 6%     | 3%      |
| 18    | 100% | 100% | 81% | 46% | 29% | 20%  | 15%    | 11%   | 7%     | 3%      |
| 20    | 100% | 100% | 100% | 56% | 36% | 25% | 18%   | 14%   | 9%     | 4%      |

Here's the formula for determining the % chance (in python):
```python
for x in range(2, 22, 2):       # x = Strength
  for y in range(20, 320, 20):  # y = Creature weight (in kg)
    print("x = {0}, y = {1} -> {2}%".format(x, y, round(100.0/max(min(pow(y/(x*3), 2), 1000.0), 1.0))))
```

In order to use the target UI, I added a fake weapon which is "thrown" at the target. This is something that could use some improvement. Also, I made it so that these mutations are immediately deactivated once the target is selected, since that's the only purpose for their active effect.

#### Describe alternatives you've considered
I considered making this a mutation attack special effect, but those are not controlled by the player and could lead to undesired situations.

#### Testing
1. Get one of those mutations (You'll need to break the threshold for either frog or snail)
2. Spawn a training dummy
3. Activate the mutation with `[` and the letter assigned to it
4. Select your target (the dummy)
5. Yell "Get over here!"

### CODE REVIEW

**Comment by Maleclypse** [comment]
Side note: Spell effects work outside of Magiclysm. Lots of vanilla and other mod effects use the spell system without something explicitly saying in game that “this is a spell”. Also thank you for adding this! I really wanted these effects but they were out of my skillet.

**Comment by dseguin** [comment]
You're right about the chances. I added a table to the description showing %chance for STR over weight. I also added a python snippet to show the formula.

**Comment by hm001121606** [comment]
Why do spell effects 'pull_to_caster' report errors

**Comment by hm001121606** [comment]
My English is not good. This sentence is translated by my translation software:"Spell effect, you're wrong. It's' pull_target 'is not' pull_to_caster', I follow the DOC and keep reporting errors."I hope I didn't offend you.

**Pull request merged**
