### PR TITLE
[RDY] Update wiki URL in readme.md

### PR DESCRIPTION
**Pull request by WizardOfOoo**

### CODE REVIEW

**Comment by keyspace** [comment]
Might be better with indirection, so:

http://tools.cataclysmdda.com/wiki

**Comment by Leland** [comment]
Could someone just get http://wiki.cataclysmdda.com/ to redirect to the new URL? That's still the link that the main site's Wiki navigation anchor points to.

**Comment by WizardOfOoo** [comment]
Ok, fixing.

**Comment by WizardOfOoo** [comment]
I messed this up, redoing it.   #20240

**Pull request closed without merging**
