### PR TITLE
Drop all Chinese world names because of charset incompatibility

### LINKED ISSUE #16129: Random world name will always be "Tom" in Chinese version
Tested with zh-cn/zh-tw/ja, press \* will generate random name, and it will only be "tom" (and related translated word).

Random character name will also generate "Tom" a lot ("Tom" only, without last name),  some where around 1 in 5.

English version does not have this issue.

0.c-12763-g100d5bd ,windows

### PR DESCRIPTION
**Pull request by BrettDong**
<del>The game will use English world names in all locales.This fixes 16129 , and also solves the problem that Chinese Windows users are unable to create worlds with default randomly generated Chinese world names. Localized world names works fine in OS X and Linux, because Chinese characters in those systems are all using UTF-8 encoding, but in Windows, Chinese characters are using GB-18030 encoding, which causes problems as the file `data/names/zh_CN.json` is encoded as UTF-8.</del>

Chinese Windows users are unable to create worlds with a world name including Chinese characters. So it's very inconvenient if the randomly selected default world name is in Chinese, for the users need to manually input an English world name. In this PR, I drop all Chinese world names first to temporarily finish the inconvenience off, and in a future PR I'm going to add a new mechanism to the name generator to automatically fall back to load English world names if current locale doesn't offer any.

### CODE REVIEW

**Comment by illi-kun** [comment]
I'm not sure it's a proper fix: if it's an issue only for Chinese language only then replace Chinese world names by default ones.

**Comment by illi-kun** [comment]
Also, this PR will conflict with #19302 which is first in line for merge.

**Comment by BrettDong** [comment]
The issue is, that for a non-English locale, the random world name will
always be "Tom". The reason behind: name generator randomly choose a
available world name for current language, but if there's no world name
for current language, the name generator will return "Tom". And the
problem is, there is only English world names defined in
data/names/en.json iirc. Someone earlier added some Chinese world names, but

1. UTF-8 Chinese world name doesn't work in Windows

2. Kevin suggests in the issue post that the world names should remain
untranslated

So in this PR I load those English world names whatever current language is.



在 2016/11/23 下午6:25, Dmitry Serov 写道:

**Comment by BrettDong** [comment]
Oh sorry, misled by the description of #16129 , I mistakenly thought there are only English world names. I just discovered that there is also a huge amount of Russian world names defined in `data/names/ru.json`. I need to redesign this PR. WIP.

**Comment by kevingranade** [comment]
> 2. Kevin suggests in the issue post that the world names should remain
> untranslated

To be clear, I said each locale should have its own list of names, but they
should not be translations of the English names.

**Comment by BrettDong** [comment]
Ugh, misunderstood.

**Comment by BrettDong** [comment]
Totally changed the purpose of this PR. The only thing I did is the removal of all Chinese world names. Ready.

**Comment by illi-kun** [comment]
@BrettDong I have some issues with testing the translated version of the game (I have no proper font with Chinese symbols). Could you explain how you test your PR?

**Comment by BrettDong** [comment]
Working on a better solution.

**Comment by illi-kun** [comment]
I'm not saying this PR is bad, the issue is on my side (I don't have Chinese font), do I'm trying to understand how this fix works for you, so it can be merged if you tested this properly.

**Comment by BrettDong** [comment]
I'm now writing a more general fix to tackle #16129 , and this PR is now unnecessary.

**Comment by illi-kun** [comment]
Okay, good to know that.

**Pull request closed without merging**
