### PR TITLE
Safely deal with different line endings (fix #13952)

### LINKED ISSUE #13952: Crash trying to play Sokoban on game watch
Playing de8cf93 on Cygwin, I tried to play Sokoban on my game watch.  It crashed.

```
(gdb) bt
#0  0x0000000100d7c85c in std::_Rb_tree<int, std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > >, std::_Select1st<std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > > > >::_M_begin (this=0x0)
    at /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/bits/stl_tree.h:518
#1  0x0000000100d7b72b in std::_Rb_tree<int, std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > >, std::_Select1st<std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > > > >::lower_bound (
    this=0x0, __k=@0x242edc: 0)
    at /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/bits/stl_tree.h:927
#2  0x0000000100c8aab0 in std::map<int, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > > > >::lower_bound (this=0x0,
    __x=@0x242edc: 0)
    at /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/bits/stl_map.h:902
#3  0x0000000100c8abd8 in std::map<int, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, std::string, std::less<int>, std::allocator<std::pair<int const, std::string> > > > > >::operator[](int&&) (
    this=0x0,
    __k=<unknown type in /cygdrive/c/git/Cataclysm-DDA/cataclysm.exe, CU 0x600d413, DIE 0x6089253>)
    at /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/bits/stl_map.h:516
#4  0x00000001009a42ee in sokoban_game::parse_level (this=0x2432a0)
    at src/iuse_software_sokoban.cpp:111
#5  0x00000001009a535c in sokoban_game::start_game (this=0x2432a0)
    at src/iuse_software_sokoban.cpp:255
#6  0x00000001007762ac in play_videogame (function_name=..., game_data=...,
    score=@0x24a5bc: 0) at src/iuse_software.cpp:67
#7  0x00000001005f505d in iuse::portable_game (this=0x24a85f, p=0x6001a3610,
    it=0x605f8ac60) at src/iuse.cpp:5535
#8  0x000000010058406a in use_function::call (this=0x600e041d0,
    player_instance=0x6001a3610, item_instance=0x605f8ac60, active=false,
    pos=...) at src/catalua.cpp:1132
#9  0x0000000100a3e985 in itype::invoke (this=0x600d70430, p=0x6001a3610,
    it=0x605f8ac60, pos=...) at src/itype.cpp:75
#10 0x000000010091fe77 in player::invoke_item (this=0x6001a3610,
    used=0x605f8ac60, pt=...) at src/player.cpp:11397
#11 0x000000010091fdcc in player::invoke_item (this=0x6001a3610,
    used=0x605f8ac60) at src/player.cpp:11387
#12 0x000000010091d844 in player::use (this=0x6001a3610, inventory_position=6)
    at src/player.cpp:11202
#13 0x0000000100682f6f in game::use_item (this=0x600191dc0, pos=6)
    at src/game.cpp:7390
#14 0x000000010065cff1 in game::handle_action (this=0x600191dc0)
    at src/game.cpp:2602
#15 0x0000000100651ba7 in game::do_turn (this=0x600191dc0) at src/game.cpp:1253
#16 0x0000000100a30302 in main (argc=0, argv=0x24cb68) at src/main.cpp:439
```

### PR DESCRIPTION
**Pull request by BrettDong**
Fixes #13952 . 

#### Cause of the crash

In `iuse_software_sokoban.cpp`:
```C++
while(!fin.eof()) {
        getline(fin, sLine);
        //...
        if (sLine == "") {
            //Find level start
            vLevel.resize(iNumLevel + 1);
            vLevelDone.resize(iNumLevel + 1);
```

`sokoban.txt` separates levels by an empty line. When the program reads an empty line, it knows a new level begins, then expands `vLevel`. But using `sLine == ""` to check for an empty line doesn't work for Windows CRLF line ending. An empty line with CRLF line ending is read as a 1-character-long string `"\r"` by `std::getline` function. Therefore the `vLevel` is never expanded, causing access violation error afterwards.

#### The fix

Add a new `safe_getline` function that handles `\r`, `\n` and `\r\n`. Implementation is from [http://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf](http://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf).

### CODE REVIEW

**Comment by kevingranade** [comment]
How about we just convert the newlines to Unix style?

**Comment by BrettDong** [comment]
Git on Windows stores files as Windows style in local and push files as Unix style in remote. If I manually convert files into LF line ending, Git will throw a warning. And it's inconvenient to edit Unix style files in Windows.

**Comment by ZhilkinSerg** [comment]
So much trouble with that ancient CRLF typewriter/punchcard legacy...

**Comment by kevingranade** [comment]
bummer that there's no simpler fix, I'm merge testing now.

**Pull request merged**
