### PR TITLE
Obsolete ACRs

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Obsolete ACRs"

#### Purpose of change

The Remington ACR is an experimental firearm that saw 0 adoption anywhere, so it should be removed. I can't even find much information about it because google keeps thinking about the Bushmaster ACR.

#### Describe the solution

Removes it.

#### Testing
image
image

### CODE REVIEW

**Comment by sonphantrung** [comment]
I saw this [Wikipedia post](https://en.wikipedia.org/wiki/Adaptive_Combat_Rifle), have you taken a look at this?

**Comment by Testudo-Cultu** [comment]
The Bushmaster ACR is typically what I'd expect to be chambered in .300 BLK, so it looks a bit like the person that contributed this in the first place may have gotten the Remington and Bushmaster ACRs backwards. I don't think it's true that the Remington ACR is an experimental firearm; I believe it simply did not succeed the US Army's competition to find a replacement to the M4 and wound up flopping in this arena. I basically never see or hear about law enforcement using it, but it was sold to them and a few foreign militaries (not that it matters much in the purview of what you'd likely find in New England).

There is no Bushmaster ACR in the game, and it's already chambered like a Bushmaster ACR, so why not just rename it from Remington to Bushmaster and fix up the description?

**Comment by Holli-Git** [comment]
> There is no Bushmaster ACR in the game, and it's already chambered like a Bushmaster ACR, so why not just rename it from Remington to Bushmaster and fix up the description?

Because the Bushmaster is semi-auto only, as it's for the civilian market. Not enough hits on gunbroker.

**Comment by Testudo-Cultu** [comment]
> Because the Bushmaster is semi-auto only, as it's for the civilian market. Not enough hits on gunbroker.

I'm aware the Bushmaster isn't fully auto, I just didn't mention that because it's by far the most trivial thing to change. I didn't expect so few hits on Gunbroker, though. Fair enough to remove it on this basis alone, in my opinion.

**Comment by Maleclypse** [comment]
Conflict in the variant validator

**Comment by Holli-Git** [comment]
> Conflict in the variant validator

Should be fixed now

**Pull request merged**
