### PR TITLE
Migrate seeds from comestibles part 1

### PR DESCRIPTION
**Pull request by Cyrano7**
And change them to generic.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Would it be possible to make seeds non-comestible but just generic? It would make them not pollute the 'e'at menu.

**Comment by Cyrano7** [comment]
That's a good idea.

**Comment by Coolthulhu** [comment]
OK, I was wrong: they have to be comestibles for now, because at the moment only comestibles and ammo can be `count_by_charges`.

**Comment by Cyrano7** [comment]
Done. Caught me right before I left the house. Haha.

**Pull request merged**
