### PR TITLE
makes body pillows craftable

### PR DESCRIPTION
**Pull request by OromisElf**
#### Summary
Content "makes body pillows craftable"

#### Purpose of change

So I just learned there is a body pillow in this game and THEN I learned it isn't craftable. Which this pr is meant to change.

#### Describe the solution

You can now craft a body pillow with 1 sheet, 20 cotton balls (compared to 4 rags and 8 cotton balls for a normal, craftable pillow), some thread and 20 charges of ink from a pen.

#### Describe alternatives you've considered

Not having my own body pillow in my current save :(

#### Testing

Started the game, debugged that ingredients in and crafted a body pillow.

### CODE REVIEW

**Comment by Qrox** [comment]
We should have an artist skill and make you lose morale when sleeping with a poorly drawn body pillow character.

**Comment by Rivet-the-Zombie** [comment]
**This is my waifu. There are many like it, but this one is mine.
My waifu is my best friend. It is my life. I must master it as I must master my life.
My waifu, without me, is useless. Without my waifu, I am useless.**

**Comment by Fris0uman** [comment]
How would it actually work if you wanted to make a good quality print/pattern on the pillow though? And is it worth trying to implement that?
Also this is not very important but this recipe should make a makeshift bodypillow and not the same exact item as the pre-cataclysm one.

**Comment by OromisElf** [comment]
I thought about quite a lot of things on how to get the print on the body pillow; I am kind of ashamed I didn't think of a makeshift one but I don't think it's THAT important. After all it's just another kind of pillow in the code right? One of the things I thought of: making pre-printed sheets spawn in different kinds of shops (sex shops, clothing shops, and what I could find) and make that a component for it; but again: it's really just a fun item for flavour purposes, so I didn't feel like going the extra mile.

**Comment by Fris0uman** [comment]
It's not really important but it would be better immersion wise because the descritpion could be coherent with the recipe. Adding more tailoring supplies variety with colored and/printed sheets would be awsome.

**Pull request merged**
