### PR TITLE
[CR]Interface to iterate over points on map

### PR DESCRIPTION
**Pull request by Coolthulhu**
The typical tripoint loop requires at least 3 lines: declaring the tripoint and 2 `for`s (or 2 `for`s and constructing a tripoint). This looks rather ugly and in the later case also is quite slow.
@BevapDin in #12309 suggested that it could be solved using an iterator.

Here I implement such an iterator. It creates only one tripoint, modifies it when incremented and returns a (const) reference to it when deferenced.

This allows accessing areas of tripoints with a nice, readable syntax:

```
for( auto &&pt : g->m.points_in_radius( p, 3 ) ) {
    g->m.bash( pt, 10 );
}
```

This will iterate over all points within rectangle (p.x - 3, p.y - 3, p.z)-(p.x + 3, p.y + 3, p.z).

The code is available in a version that silently clips to map bounds (in map class) and in a form that doesn't clip (could be used for overmap and similar "unlimited" classes).

To allow testing, I changed the ammo effects in damage.cpp and the `do_blast` in game.cpp to use the new syntax.

### CODE REVIEW

**Comment by Zireael07** [comment]
Woot!

**Comment by macrosblackd** [comment]
Suggestion: Maybe add a few different iteration types? E.G. Radial, diagonal, maybe some others that might be useful? This could help where a certain search pattern is more beneficial than another.

**Comment by BevapDin** [comment]
Very nice.

- Why is the tripoint class no used instead of `{min,max}{x,y,z}`? That would also make the constructor simpler.
- `map::points_in_radius` should call `points_in_rectangle` to avoid the duplication of the range-clipping.
- It should be possible to forward declare `map_iterator` in map.h and not include the header there. It needs to be included in the cpp file that actually uses them.

Putting the code of map_iterator.cpp into the header makes the new code a tiny bit faster, leaving it in the cpp file (and therefor in a separate compilation unit) makes it quite slow (each loop iteration involves three function calls: operator++, operator* and operator==). The old code did all this without any function calls. I suggest moving at least the three iterator functions into the header.

**Comment by Coolthulhu** [comment]
@BevapDin 
> It should be possible to forward declare map_iterator in map.h and not include the header there. It needs to be included in the cpp file that actually uses them.

Didn't know you could return an incomplete type.
> Putting the code of map_iterator.cpp into the header makes the new code a tiny bit faster

Also didn't know.

I'll just move the entire class into the header. I wanted to do it at first, but I didn't because I didn't know that returning an incomplete type is doable.

@macrosblackd 
> Suggestion: Maybe add a few different iteration types?

I thought about it when implementing this, but didn't know how to do it right.
With a regular class that would be either quite slow or duplicate a lot of code. But now that I'm moving the class to the header, I could easily make it a template with custom incrementor. This would allow different shapes and orders.

With a good algorithm, a triangle-shaped, circle (sphere) shaped and line-shaped generation would all be quite easy.

**Comment by kevingranade** [comment]
I'd hold off on a grab-bag of shapes unless they're used somewhere, what
needs a triangle after all?
I'd also prefer not to have the entire class in the header, just the parts
that really need to be, there are good reasons to have things defined in
separate compilation units.

**Comment by Coolthulhu** [comment]
> I'd also prefer not to have the entire class in the header, just the parts
that really need to be

The class itself is quite tiny and the header would be only included in .cpp files.

> I'd hold off on a grab-bag of shapes unless they're used somewhere, what
needs a triangle after all?

Just saying what could be done. Circle could be useful though - we still have that euclidean distance thing and it isn't adequately supported in most cases (many effects are still square).

**Comment by Zireael07** [comment]
I can imagine laser fields or something using the triangle function btw.

**Comment by Coolthulhu** [comment]
Removed the header inclusions from headers, added to .cpp where applicable.

Moved operators to header.

Added an explicit move constructor from 2 tripoints. I am not sure if I wrote this one right.

**Comment by BevapDin** [comment]
> Added an explicit move constructor from 2 tripoints. 

I think moving from tripoints is the same as coping them. There is nothing to "move", the original remains anyway as the tripoint is just some `int`s. Through it's certainly not wrong.

**Comment by BevapDin** [comment]
Works fine, no objections from me, @kevingranade shall it go in?

**Comment by kevingranade** [comment]
I haven't had a chance to review it yet, so no opinion either way.

**Pull request merged**
