### PR TITLE
Use long stick for polearms with wooden handles

### PR DESCRIPTION
**Pull request by cake-pie**
Long stick (`stick_long`) was introduced #24017 to justify spears having a further reach (i.e. `REACH_ATTACK`).

Previously:  
1 heavy stick (`stick`) -saw-> 1 two by four (`2x4`)  

Now:  
1 long stick (rough) -saw-> 1 two by four (approx same length, squared cross section)
1 long stick (rough) -cut/break-> 2 heavy sticks (shorter, still rough)

#24059 implemented it in the following recipes:
`pointy_stick`, `spear_wood`, `spear_copper`, `spear_forked`, `spear_knife`

For consistency, we should do likewise for other polearms with wooden handles.  
I surveyed the json data, below is an exhaustive list of items with `REACH_ATTACK`.

Already done a couple of the most obvious ones.  
Proposed changes listed for the others, will leave open for comment for a couple days before proceeding.

## Not applicable
Fake item: `halberd_fake`  
Not craftable: `pitchfork`  
Not wooden: `spear_rebar`, `spear_pipe`, `spear_survivor`, `bullwhip`

## Single stick
Same treatment as #24059 i.e. one-for-one replacement of heavy stick with long stick.
* makeshift glaive `makeshift_halberd`
* stone spear `spear_stone` (More_Survival_Tools)

## Multiple sticks
The general formula for these is currently to require twice as many heavy sticks as two-by-fours.  
(That conversion almost seems reasonable, but no, these recipes haven't actually been updated yet.)

~Proposal: substitute heavy sticks with half as many long sticks (i.e. equal count as two-by-fours)~
Needs more extensive rework, see below.

### DDA

item | components
---|---
awl pike `pike` | [  [ "2x4", 4 ],  [ "stick", 8 ] ]
steel spear `spear_steel` | [ [ "2x4", 3 ], [ "stick", 6 ] ]
`qiang` | [ [ "2x4", 3 ], [ "stick", 6 ] ]
`halberd` | [ [ "2x4", 4 ], [ "stick", 8 ] ]
`glaive` | [ [ "2x4", 3 ], [ "stick", 6 ] ]
`naginata` | [ [ "2x4", 3 ], [ "stick", 6 ] ] + steel + fur/leather
`naginata` | [ [ "2x4", 2 ], [ "stick", 4 ] ] + katana

### Medieval_Stuff

item | components
---|---
`ji` | [ [ "2x4", 4 ], [ "stick", 8 ] ]
dory `spear_dory` | [ [ "2x4", 4 ], [ "stick", 8 ] ]
`fire_lance` | (uses qiang)

## Other
homemade halfpike `spear_homemade_halfpike` is made with [ [ "stick", 2 ], [ "2x4", 2 ] ]

~~Probably substitute 2 long sticks instead of 2 heavy sticks.~~
Change to 1 long stick (= 1 two by four) per Xhuis

Seeing as @Xhuis added this recently (#24120) -- written the day before #24059 was merged, in fact -- pinging in case they might want to chime in on this.

### CODE REVIEW

**Comment by Xhuis** [comment]
Halfpike was made before long sticks. I'd personally make it take one long stick. Halfpikes in real life are similar to normal pikes, but shorter, so one long stick should be fine for that.

**Comment by DracoGriffin** [comment]
From [kevin](https://github.com/CleverRaven/Cataclysm-DDA/issues/24017#issue-332914941):
> Replace "heavy stick" in spear recipes with "long stick".

So looking at the Multiple Sticks category, 1 `long stick` can be crafted into 1 `two by four`, and a `long stick` could potentially be broken into 2 `heavy sticks`, so I'd hazard that I'd change the stick requirement to long stick and at half quantity, as you determined initially.
>Proposal: substitute heavy sticks with half as many long sticks (i.e. equal count as two-by-fours)

**Comment by sfsworms** [comment]
Not sure it's a good idea. When fitting a long stick to serve as the handle, you would carve and discard a lot of the wood. Adding "splintered wood" as a by-product would be a good idea if you feel the need to adjust weight/volumes.

**Comment by Mecares** [comment]
In that case dissembling them should not yield a long stick again. Polearms are per definition not small and short items.

**Comment by RadHazard** [comment]
I'm not sure how many of these recipes even warrant having more than one long stick in them.  A single long stick is supposed to be something like a 6' pole, and I don't think anything except the awl pike is longer than that.

**Comment by cake-pie** [comment]
A couple balance/realism considerations have been raised re: the more complex recipes.

I had originally hoped to keep this a narrowly-scoped PR focused on pure heavy stick -> long stick replacement with minimal/no balance changes, but having looked over the points raised, digging a little further, and thinking on it, this might need to be a bit more involved than orignally planned.


Stuff so far:

#### Issues already inherent in the pre-existing recipes

DracoGriffin elaborated on why it seems reasonable to change heavy sticks to half as many long sticks in the Multiple Sticks category.  But, as I alluded in the OP, this is more of a fluke than actually intentional.  If you consider the recipe in the context before long sticks were introduced, it didn't really make sense to require twice as many heavy stick as two-by-fours, when it used to be that each heavy stick is crafted into one two-by-four.

If the recipes were already wonky to begin with, we should probably fix them rather than simply convert some numbers.


#### Change in understanding re: what the various wood pieces represent

Before long sticks entered the picture, the polearm recipes probably envisioned "assembling" the wood pieces in some way to attain the required length.  RadHazard points out, quite reasonably, that a single long stick should now suffice in (almost) all cases.

Thinking about it, that is precisely the raison d'etre for the long stick!  And the corollary to that should be: cobbling shorter pieces of wood together is no longer considered adequate;  i.e. the result is certainly not sturdy enough for the higher end polearms we're looking at in the "multiple sticks" category.

So, since the available raw materials have changed quite fundamentally, it may be better to reconsider from scratch, rather than blindly mapping from the old recipes.


#### Weight / Volume

Mecares reminds to re-rationalize weight/volume as needed based on changes to raw material input.  
This will definitely be necessary as a consequence of the previous two points.

Furthermore, after looking into the overall pipeline for wood resources, there are some weight/volume inconsistencies there that we may want to address first.  (Will file a separate issue.)


#### Fitting / Reshaping / Disassembly

For the sturdier, non-makeshift items, it makes sense flavor-wise that the crafting process involves some reshaping of the wood.  sfsworms suggests this could be implemented as splintered wood byproduct; Mecares correctly cautions re: parts being recovered from disassembly

I checked, of all the polearms, currently `spear_copper`, `spear_knife` and `makeshift_halberd` recipes are currently marked as `"reversible": true`.  

One thing we can do for consistency is to allow disassembly only for the makeshift "weapons of desperation" that are essentially "tape/tie X to Y" -- namely `spear_knife`, `spear_forked`, `makeshift_halberd`. And *maybe* `spear_homemade_halfpike`

We could also take a further step and introduce the intermediate item `pole` as per originally envisioned in #24017 which would be carved/smoothed from the long stick (with byproduct splinters).   Whereas makeshift weapons are allowed to use the long stick in its rough form, the better quality weapons would require the use of the `pole`.  This would allow logical disassembly without the problems that Mecares cautioned against, e.g. taking apart a copper spear and crafting a steel spear in its place = reasonable workaround for spear "upgrading" mechanics.

**Comment by cake-pie** [comment]
Moving forward under the premise that
> a single long stick should now suffice in all cases

Remaining recipes are now updated.  
Due to lack of input / interest in #24632 , #24633 item stats, volume, weight remain unchanged.
This maintains status quo for the weapons' performance vs portability.

**Pull request merged**
