### PR TITLE
Tweak booby trap recipe.

### PR DESCRIPTION
**Pull request by Rail-Runner**
Allows using aluminum can and empty canister to make booby trap.

### CODE REVIEW

**Comment by KA101** [comment]
OK, how exactly do you propose to fit the grenade in the drink can w/o any cutting implement?

(Empty canisters can be used to *make* grenades last I checked, so a bit of a same-size problem there.)

**Comment by Darkyhard** [comment]
Okay, I'll add a cutting quality as a requirement when I get some free time.

As for components used, they may come in different shape to fit each other. For example, a survivor could make a canister which is used for grenade, and then another one which is wider than the first but still has the same volume..

**Comment by kevingranade** [comment]
Except it shouldn't need cutting for the food can, since that one is open already.
Sounds like a job for an alternate recipe (or wait until the new recipe format that was proposed is added, that could handle it in one recipe.)

**Comment by DavidKeaton** [comment]
New proposal? Where?

**Comment by kevingranade** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/11052

**Comment by narc0tiq** [comment]
Re: new recipe format, note that I'm not promising to work on it at this time; I know someone else was also poking at changing things up on that front, but I think they've stalled out (or at least I haven't heard anything recently -- but I also haven't been paying as much attention).

**Comment by KA101** [comment]
I'll see about adding one in the merge.  Hopper clean-out time.

**Pull request merged**
