### PR TITLE
Fix float-keying activity level problem

### LINKED ISSUE #49178: Activity diary is not accounting for per-turn activity levels
# Describe the bug

avatar::log_activity_level is now getting fed (floating-point) numbers
that don't match the exact activity levels, due to #45316 making the
activity level per-turn then averaging activity over each 5-minute
period. The activity diary test (in tests/char_biometrics_test.cpp)
was not spotting this since it was still using times in multiples
of 5 minutes; the linked PR fixes **_this_** part, resulting in a test failure.

# Steps To Reproduce

See #49179.

# Expected behavior

Intermediate activity levels should be assigned to the closest *_EXERCISE activity level. (Doing the activity diary once every minute might also be a good idea.) Additionally, the activity diary test should spot when this is not working properly.

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary

None

#### Purpose of change

avatar::log_activity_level is now getting fed (floating-point) numbers
that don't match the exact activity levels, due to #45316 making the
activity level per-turn then averaging activity over each 5-minute
period:

avatar.cpp (activity_levels is a `std::map`):
```
void avatar::log_activity_level( float level )
{
    calorie_diary.front().activity_levels[level]++;
}
```

character.cpp: `log_activity_level( activity_history.average_activity() );`

The activity diary test (in tests/char_biometrics_test.cpp)
was not spotting this since it was still using times in multiples
of 5 minutes.

Fixes #49178.

#### Describe the solution

This PR first moves around 1 minute of NO_EXERCISE in the test, keeping the same total number of minutes of each activity level; this detects the problem. Second, in avatar::total_daily_calories_string, intermediate-valued 5-minute intervals are now classified with the closest activity level.

#### Testing

Test code included.

#### Additional context

Ping @jbytheway - possibly a clang-tidy test could be done to check for the use of a floating-point variable as a map key? (Admittedly, this PR does not actually remove this source of bugs in this particular instance.)

I spotted this in the process of looking at adding a SLEEP_EXERCISE activity level, for the weariness improvements discussed in #48409.

### CODE REVIEW

**Comment by kevingranade** [comment]
With a brief look, I don't think an "ugly" or "slow" fix for this would actually be a problem, as the only consumer of this is a very intermittently accessed UI element.

A quick fix is to walk the log and throw them in "buckets" based on exceeding the next level, so if the value is less than LIGHT_EXERCISE it counts as NO_EXERCISE, if it's less than MODERATE_EXERCISE it counts as LIGHT_EXERCISE, etc.
To get a bit fancy you could try and make those thresholds more representative, like the midpoint between the values or something.

Regardless, if you don't feel like doing it, you did the most valuable part already.

**Comment by actual-nh** [comment]
> With a brief look, I don't think an "ugly" or "slow" fix for this would actually be a problem, as the only consumer of this is a very intermittently accessed UI element.

I was wondering why it hadn't been noticed before on the player side of things... that explains it. Ah. I had been thinking of something processing the floats into categories at the time of _gathering_ the data, not when the info was _accessed_ (including saved?), if I'm understanding your suggestion below.

> A quick fix is to walk the log and throw them in "buckets" based on exceeding the next level, so if the value is less than LIGHT_EXERCISE it counts as NO_EXERCISE, if it's less than MODERATE_EXERCISE it counts as LIGHT_EXERCISE, etc.
> To get a bit fancy you could try and make those thresholds more representative, like the midpoint between the values or something.

For purposes of debugging weariness, I'd like to do the fancier one.

> Regardless, if you don't feel like doing it, you did the most valuable part already.

Well, thank you; barring something unexpected coming up, I should be able to do it a bit later this weekend.

**Comment by jbytheway** [comment]
> Ping @jbytheway - possibly a clang-tidy test could be done to check for the use of a floating-point variable as a map key?

That certainly seems like an unwise thing to do in most cases, so yes, such a check might be warranted.  I even feel like I've seen some static analysis tool have such a check, but looking at clang-tidy I guess it wasn't there.

**Comment by actual-nh** [comment]
Well, my first try didn't work, probably because of some embarrassing C++ error. (I also need to remember to alter the expected Gained/Spent/Total calories, likely from roundoff.)

```
 CHECK( condensed_spaces( dummy.total_daily_calories_string() ) == string_format( "<color_c_white> Minutes at each exercise level Calories per day</color>\n" "<color_c_yellow> Day None Light Moderate Brisk Active Extra Gained Spent Total</color>\n" "<color_c_light_gray> 61 60 45 30 20 15 10 %d %d</color><color_c_light_blue> %d</color>\n", expect_gained_kcal, expect_spent_kcal, expect_net_kcal ) )
with expansion:
  "<color_c_white> Minutes at each exercise level Calories per day</color>
  <color_c_yellow> Day None Light Moderate Brisk Active Extra Gained Spent
  Total</color>
  <color_c_light_gray> 61 10 10 10 10 15 5 1282 730</color><color_c_light_blue>
  552</color>
  "
  ==
  "<color_c_white> Minutes at each exercise level Calories per day</color>
  <color_c_yellow> Day None Light Moderate Brisk Active Extra Gained Spent
  Total</color>
  <color_c_light_gray> 61 60 45 30 20 15 10 1283 732</color>
  <color_c_light_blue> 551</color>
  "
```
Likely part of whatever error I made is that I'm needing a nap; rectifying that now.

**Comment by actual-nh** [comment]
Never mind, I just figured it out (I think).

**Comment by actual-nh** [comment]
Well, almost:
```
./tests/char_biometrics_test.cpp:472: FAILED:
  CHECK( condensed_spaces( dummy.total_daily_calories_string() ) == string_format( "<color_c_white> Minutes at each exercise level Calories per day</color>\n" "<color_c_yellow> Day None Light Moderate Brisk Active Extra Gained Spent Total</color>\n" "<color_c_light_gray> 61 60 45 30 20 15 10 %d %d</color><color_c_light_blue> %d</color>\n", expect_gained_kcal, expect_spent_kcal, expect_net_kcal ) )
with expansion:
  "<color_c_white> Minutes at each exercise level Calories per day</color>
  <color_c_yellow> Day None Light Moderate Brisk Active Extra Gained Spent
  Total</color>
  <color_c_light_gray> 61 60 45 30 20 20 5 1282 730</color><color_c_light_blue>
  552</color>
  "
  ==
  "<color_c_white> Minutes at each exercise level Calories per day</color>
  <color_c_yellow> Day None Light Moderate Brisk Active Extra Gained Spent
  Total</color>
  <color_c_light_gray> 61 60 45 30 20 15 10 1283 732</color>
  <color_c_light_blue> 551</color>
  "
```

**Pull request merged**
