### PR TITLE
Add "PALS_LARGE" to "single_sling"

### PR DESCRIPTION
**Pull request by PlutusPleion**
#### Summary
None

#### Purpose of change

1. **Player choice**: Give the player the customization and choice of attaching the sling to their vest
2. **Realism**: We attach [single point slings to vests](https://camo.githubusercontent.com/44b777e1e994b9860d57a7d98e7c36ab767827aa04c4613ca95203c22503e30e/68747470733a2f2f7777772e746163746963616c6c696e6b2e636f6d2f6173736574732f696d616765732f70726f64756374696d616765732f696e666964656c736c696e672f73756c2e6a7067)
3. **Balance**: Currently the survival harness is by far the most efficient holder since most long guns can only be holstered to single point slings and survival harness. Single point slings can be used in conjunction with PALS holders but at the cost of much more encumbrance. This has the added benefit of freeing up "hang from front" strapped slot, while limited, adds to making pals/molle vests competitive.

#### Describe the solution
Allow single point slings to be attached to PALS/MOLLE capable gear such as load bearing vests and ballistic vests.

Chose the tag variant which takes up the most space(3) PALS_LARGE instead of medium or small for balance.

#### Describe alternatives you've considered
- Nerf survival harness by adding more encumbrance to be in line with single point slings used with PALS gear

#### Testing
- Check to see if it attaches (pass)
- Check to see if it can detach (pass)
- Check to see if a player can place a gun in the pocket (pass)

### CODE REVIEW

**Comment by PlutusPleion** [comment]
Okay thanks, changed it to None

**Comment by bombasticSlacks** [comment]
The single point sling can already be worn with these vests with no conflict. The single point sling hangs off the front, the vest is on the torso. 

A single point sling does usually integrate with tac vests but it doesn't attach to the molle and take up vest space it's still a gun hanging off your front.

**Comment by PlutusPleion** [comment]
> The single point sling can already be worn with these vests with no conflict. The single point sling hangs off the front, the vest is on the torso.
> 
> A single point sling does usually integrate with tac vests but it doesn't attach to the molle and take up vest space it's still a gun hanging off your front.
> 
> And to be clear the "integration" mentioned above isn't necessary since they already don't conflict.

In the same regard many of the current "PALS" items don't already conflict with with the vests, it's to help clear up that spot for another strapped gear.

For example a sheath covers the hips so there is no conflict with vests. Yet it is still attachable.

I don't think that argument invalidates it.

**Comment by bombasticSlacks** [comment]
PALS is a thing. The items that attach to the vest have molle straps to attach to vests. The logic isn't "you can wear it elsewhere" it's "this is designed to attach to these vests"

Some nylon and a connector don't have straps to attach to the front of a vest. Even if they did the gun would still be hanging off your front a seperate location.

I understand the photo you are showing. I referenced that above but that doesn't mean it's attached to the molle rigging on the front

**Comment by PlutusPleion** [comment]
If the argument is just that "single point slings can't attach to PALS" then here's two quick ones that explicitly say they're PALS compatible:

https://www.thecorpsshop.com/index.php?route=product/product&product_id=164

https://picclick.com/Elite-Ops-Quick-Release-Single-Point-Sling-For-321751233368.html

**Comment by bombasticSlacks** [comment]
While we are being pedantic that's the same sling twice. 

I've said my piece. This would be a silly addition and require a pile of special code to handle appropriately for no benefit.

**Comment by PlutusPleion** [comment]
I see the single point sling in the same regard as any of the other current PALS tagged containers. I do appreciate the feedback because it made me also realize that the current PALS/MOLLE attach system is incomplete. Simply adding the PALS_LARGE tag to the single point sling has the same missing feature of not inheriting "use_action": { "type": "holster" } . I'm trying to figure out how to do that but my coding knowledge is pretty basic.

**Comment by bombasticSlacks** [comment]
I wasn't talking about that. 

The code that would need to be handled is anything incorporating a single point sling would need to also be promoted to the "hanging_front" sublocation since it now has a gun hanging off the front of you. That's a lot of custom code. 

Also adding the sling to a PALS vest gives the exact same encumbrance as just wearing it. So if it still hangs off the front and still gives between 0-16 encumbrance based on volume stored there isn't any point if your "min-maxing" to have it take up PALS slots. 

I think fixing that issue with holsters is a valid idea but this PR is a lot of work so that players can do something inefficient.

**Comment by PlutusPleion** [comment]
> The code that would need to be handled is anything incorporating a single point sling would need to also be promoted to the "hanging_front" sublocation since it now has a gun hanging off the front of you. That's a lot of custom code.

I will refer again to any of the current pals tagged gear. None of them have custom code to change coverage even though they occupy other slots from the vest they're attached to. The only exception being adding a blanket "strapped" layer to the ballistic vest variations.

I don't know why you're thinking single point sling as a special exception or edge case for some reason. Or really why there is such aversion to add this minor change.

> Also adding the sling to a PALS vest gives the exact same encumbrance as just wearing it. So if it still hangs off the front and still gives between 0-16 encumbrance based on volume stored there isn't any point if your "min-maxing" to have it take up PALS slots.

Good point and I've downgraded the "balance" aspect to being the lowest purpose to this change. I still kept it as balance because this change frees up the hangs off front strapped slot while has limited competition is still a freed up slot. While not the initial intended encumbrance benefit, gives a new alternative to the player if they want to say wear a 2.5L canteen while having a gun slot.

> I think fixing that issue with holsters is a valid idea but this PR is a lot of work so that players can do something inefficient.

Out of scope for what already works in my test and that achieves the current goals.

**Pull request closed without merging**
