### PR TITLE
Adjust damage of unarmed weapons

### LINKED ISSUE #65630: Balance Pass for Unarmed Clothing
### Is your feature request related to a problem? Please describe.

Currently, the unarmed clothing items (6 varieties of Knuckles, Studded Gloves and Cestus) have a rather strange power curve, where many are flat-out terrible, yet Skewer Knuckles are amazingly good. Impact Knuckles used to be good (slightly too good re: armor damage, probably), and the nerf made them pretty much terrible again. The slowest of various, cheaper craftable unarmed items with only 1 more bash.

What I'm proposing is to condense the power curve from 1-10 which now has many items on the low end and an easy 10, down to a 3-8. Weak items get buffed, Impact Knuckles get buffed (though not as much as it used to be before the nerf), and Skewer Knuckles get a small nerf. Even then, Skewer Knuckles take the highest aggregate score of DPS and Damage-per-Stam easily. It's the only weapon in the list with +1 to-hit. Which is fine.

I have taken into account the difficulty to craft these items as a rough guideline of which tier they're sitting in. The buff to these items is roughly proportional with their current damage.

Now, the general buff to Bashing damage and how that relates to armored enemies is the most important thing here. I can say that on a late-game munchkin with 20 DEX and 20 STR, max melee and unarmed skills, using Impact Knuckles with 9 Bashing, killing a Kevlar Hulk with your fists is still a *tedious affair* and something like Pankration throwing damage will be far more reliable than using another martial art with perfect equipment. But critical damage does proc actual low-digit damage to the Hulk. I am not sure if this was possible with Impact Knuckles at Bashing 5. Frankly, I took one look at them and thought they were reasonably nerfed but to an unreasonable amount. These, along with Skewer Knuckles, make up the top two unarmed items for Martial Artists, both in utility and in difficulty to craft them, yet Impact Knuckles were reduced to 5, while still being the slowest of the bunch at speed 77. Compared to a 73-speed 12 total-damage item. That's a dead item.

Anyway, here's my table for proposed changes, and what that breaks down to in numbers. Keep in mind that these numbers are with a munchkin character, and are only intended as being very close-to-maximum of what's attainable in CDDA. Look at them as relational power numbers more so than discrete. And notice that after the proposed nerf, Skewer Knuckles are *still* easily the best. The slight nerf subtracts more points from the first 2 columns than what it gives to vs. Armored.

This also makes a point that adding piercing damage to the unarmed attack is massively useful (see Damage-Per-Turn vs. Unarmed and Fast) just because so many enemies aren't very much armored, that it's almost out-of-line to the rest of the unarmed lineup.

### Solution you would like.

A general buff to most Unarmed Clothing items, and a slight nerf to Skewer Knuckles to bring it closer in line.

Cestus: Bash 2 -> Bash 5
Brass Knuckles: Bash 4 -> Bash 6
Nail Knuckles. Bash 2 Pierce 3 -> Bash 4 Pierce 4 
Scrap Knuckles: Bash 4 -> Bash 6
Steel Knuckles: Bash 4 -> Bash 7
Studded Gloves: Bash 2 Pierce 1 -> Bash 2 Pierce 4
Impact Knuckles: Bash 5 -> Bash 9
Skewer Knuckles: Bash 2 Pierce 10 -> Bash 3 Pierce 6

The weights and therefore Speed ratings remain unchanged. This leaves Skewer Knuckles as the DPS and Stamina King and gives Impact Knuckles (and arguably, Steel Knuckles) a place in the lineup.

Let me know what you think. This is what would make sense to me after having played the game for a very long time - but I make no claims to be right.

### Describe alternatives you have considered.

It's possible I am undervaluing damage vs. armored. But consindering the amount of squishy, dangerous enemies now in the game and the amount of armored ones that do more than play "be a wall" with you, I find it hard to see this point. One of those Shell Muntants will still require a rifle to make a dent, Kevlar Hulks are killable in that it's a chore and you get thrown around plenty because of general killing speed being about 1/3rd to half that of an armed survivor, I think. So about where it's supposed to be. Equipping the same survivor with a decent rapier, even without martial arts he's a much more capable killing machine. The DPS aggregate (three DPS calculations added together) for a tempered rapier is around 280. Even higher since I haven't tested this with a character of max Piercing skill. Skewer Knuckles, still being the highest of the bunch, get 160 post-nerf. With the upside that Unarmed fares well in the Stamina department, which just the DPS aggregate excludes. But then, unarmed fights take up that extra amount of time.

### Additional context

unarmed clothing 2

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Balance "Adjusts damage of unarmed weapons"

#### Purpose of change

https://github.com/CleverRaven/Cataclysm-DDA/issues/65630 laid out a very good case for adjusting the damage of unarmed weapons. As it was, it was pretty much not worth using anything except the skewer knuckles, which doesn't reflect how brass knuckles etc. are most commonly designed in the real world.

#### Describe the solution

As outlined in the attached issue, the following adjustments were made:

Cestus: Bash 2 -> Bash 5
Brass Knuckles: Bash 4 -> Bash 6
Nail Knuckles. Bash 2 Pierce 3 -> Bash 4 Pierce 4
Scrap Knuckles: Bash 4 -> Bash 5 Cut 1
Steel Knuckles: Bash 4 -> Bash 7
Studded Gloves: Bash 2 Pierce 1 -> Bash 2 Pierce 4
Impact Knuckles: Bash 5 -> Bash 9
Skewer Knuckles: Bash 2 Pierce 10 -> Bash 3 Pierce 6

I also noticed that none of these weapons except for the skewer knuckles had a to_hit set, and the skewer knuckles had theirs set incorrectly. I've given them values according to GAME_BALANCE.md, it now works out that they're all +0 except for the studded, nail, and skewer knuckles, which are -1 owing to their different striking surface.

This is a minor downgrade to the skewer knuckles, which were previously on top of the heap in every respect, but I feel that's appropriate - commercially available real-life unarmed weapons almost always take the form of a cestus or brass knuckles. Cases where people have put short spikes or blades on these kinds of weapons have never been successful enough to achieve mainstream use (katars and patas are not considered unarmed weapons in CDDA), so we can assume that the cestus and brass knuckles are the most effective form factor.

Weight, attack speed etc. remain the same.

#### Describe alternatives you've considered

Piercing damage in general feels like it's too strong now that weak points exist. I think we should discuss adding piercing armor to many types of monsters, specifically anything that doesn't have internal organs, or whose internals are diminished (decaying zombies, skeletals, robots) to give bash and especially cut damage some room to shine. This has already been done in some cases (most of the skeletals, specifically), but it hasn't really dethroned the combat knife.

#### Testing

I spawned into the world and checked all the weapons to make sure they were still roughly hitting the 10 DPS mark that the tests suggest. I will propose adjustments if this method fails the DPS tests on build.

#### Additional context

closes #65630

### CODE REVIEW

**Comment by Nebnis** [comment]
Pierce damage doesn't exist? Am i confusing something or did  you or that pr just mean stab? Because monsters got that :P

**Comment by Tharn** [comment]
It used to be called Piercing, afaik. Yes, it means Stab. Damage types weren't changed, just the individual values.

**Comment by Nebnis** [comment]
> It used to be called Piercing, afaik. Yes, it means Stab. Damage types weren't changed, just the individual values.

Oh oki i thought you were confused too because most monsters afaik like skeletons already have insane amount of cut and piercing resistance, since you can't really cut/pierce bones or kevlar. I.e "https://cdda-guide.nornagon.net/monster/mon_skeleton"

**Comment by fairyarmadillo** [comment]
> Pierce damage doesn't exist? Am i confusing something or did you or that pr just mean stab? Because monsters got that :P

The terms are used interchangeably in various places and mean the same thing in this context. 

Stab armor is generally automatically calculated as 80% of cut armor, unless otherwise specified. Way before we had weak points, this was deemed a good way to show that stab weapons could precisely penetrate armor in ways that the long edge of a cutting blade could not. Stab weapons also had a variety of drawbacks, namely low damage, slow attacks, and the potential to sometimes get stuck in enemies, which wasted turns.

Over the years, stab damage has crept up to be pretty much the best in almost every case, which is one reason the combat knife is the dominant meta. This has left cutting weapons in an unhappy place as they don't really have a field in which they outperform bash and stab.

Now that we have weakpoints, stab is essentially double dipping on its bonus against armor. This could be offset by manually adjusting the armor values of enemies such as skeletals, robots, and other things that don't have easily pokable internal organs.

**Comment by Nebnis** [comment]
Well this is more of an issue about combat knife being overturned with eskrima specifically. It is much easier to bring combat knife in line than going on buffing every monster with piercing armor since that would also make every other knife that isn't combat knife to be specially awful more than they already are now for a lot of a scenarios. I don't see how combat knife is better than a survival knife or the tanto for that matter(which is also a combat oriented knife). I would bring combat knife down to that range of damage and remove the "to -1 hit" to 0 or something to compensate since that doesn't make a lot of sense either. Sorry if i got offtopic about the pr btw.

**Comment by fairyarmadillo** [comment]
> Well this is more of an issue about combat knife being overturned with eskrima specifically. It is much easier to bring combat knife in line than going on buffing every monster with piercing armor since that would also make every other knife that isn't combat knife to be specially awful more than they already are now for a lot of a scenarios. I don't see how combat knife is better than a survival knife or the tanto for that matter(which is also a combat oriented knife). I would bring combat knife down to that range of damage and remove the "to -1 hit" to 0 or something to compensate since that doesn't make a lot of sense either. Sorry if i got offtopic about the pr btw.

That's OK. I expect this PR is sort of an uncontroversial change so we may as well use the comment space for off-topic discussion lol.

You're right that the combat knife is specifically a problem. I'm especially confused at how it's so much better than a kukri even though both are highly respected fighting knives. I know partially this will be fixed by the someday-maybe changes to weapon damage - if it was doing cut damage half the time like it should, it'd be a lot less OP. I have just noticed a pattern of stabbing weapons (rapier, estoc, combat knife, skewer knuckles) often being best in class, mostly for the reasons stated above.

**Comment by Nebnis** [comment]
Late game cutting weapons usually have huge amount of bash throw in, which usually makes them better than knifes in a lot of situations. Plus the high block ability. Pair that with a good martial and they feel pretty stronger, but I'm totally not against cut getting another niche like how stab penetrate some armor by default. 

Rapier/estoc is often used because of the stunlock chances ability, and skewer was because how AWFUL the other unarmed weapons were compared to it, they were basically nothing(which this PR is trying to fix but i don't think it will be merged to be frank with you as you said :P)

I remember talks about bringing combat knife down a peg from some dev(it was aerin i think?) So you could probably talk to them about how to approach the nerf.

**Comment by fairyarmadillo** [comment]
> they were basically nothing(which this PR is trying to fix but i don't think it will be merged to be frank with you as you said :P)

I didn't say that. I said it will not be controversial, meaning it will probably get merged.

**Comment by Tharn** [comment]
Yes, Rapier and Estoc are best-in-class because they're the only serious contenders for temper-able, stabbing damage, martial arts-able weapons. Pairing something like a tempered combat machete with Eskrima or Silat is still going to yield pretty great DPS as well, so it's not so much that stabbing is the "secret ace" in the weapons category as that a lot of cutting weapons aren't up to snuff.

I have a whole table for Temper-able weapons, comparing them to bludgeons, if you're looking for inspiration inspired for future changes. The change was a bit too big for me and I haven't gotten enough experience with the various melee weapons for a fair comparison. Just the numbers. Also, after having watched a video on the Falx, I would argue that with the forward curved shape it has, it might actually be an around-the-shield stabbing weapon more than a cutting weapon. That might also give it some lustre with how meh it does stat-wise at the moment. Zweihänder could use a touch more speed.

At a glance, War Hammer and Rapier are probably a little too strong as well. Estoc to a lesser degree.

**Comment by fairyarmadillo** [comment]
@Jarewill made some suggestions in the issue that spawned this PR. I have adjusted scrap knuckles to have 5 bash and 1 cut. This makes them a bit worse than brass knuckles (6 bash 0 cut), which are a factory-made item that has been popular for this purpose for centuries, while scrap knuckles are basically trash and rags.

**Comment by Tharn** [comment]
Is the failure to build something to do with those values or is that an unrelated error?
How can we help get this merged?

**Comment by fairyarmadillo** [comment]
All tests are passing. A couple of recent additions, specifically the monster corpse and grab changes, appear to be making a bunch of PRs display errors in testing, but it's a false alarm and won't get in the way of merging.

Since this is a balance change and not just content, bombasticalacks or somebody probably wants to give it a look first, and they're pretty busy. Give it a week or two.

**Comment by Tharn** [comment]
Can we get eyes on this, pretty please?

**Pull request merged**
