### PR TITLE
Stop strapped and waist items from making player wet

### LINKED ISSUE #21693: Wearing non-WATERPROOF gear over WATERPROOF ones makes character loses their waterproofing
Wearing duffel back over nomad gear shouldn't make character wet under the rain.

0.C-6700, Windows XP SP3, curses.

### PR DESCRIPTION
**Pull request by Theundyingcode**
Should Fix #21693

Couldn't find anywhere else that covered_with_flag was used but made it only effect waterproof just in case.

Still will cause player to get wet if layered cloths weirdly. But that should reflect wearing soggy cloths and I see no reason to change unless player is forced to "properly" layer their cloths.  However, for the most part, wet strapped and waist items should cause negligible effects to a player wearing rain gear.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
What you're doing is pretty much flagging all belted and waist items as waterproof, except in the wrong place, in a way that isn't relayed to player, in a way that isn't generalizable to other items.

The proper way to solve this is to add waterproof flag to relevant items.
The less proper way is to hardcode waist and belted items to get the flag on finalization, in item_factory. This would still be wrong, but it would be less work. I wouldn't excuse it in this specific case, though - water morale isn't good enough of an excuse to hardcode things like that.

**Comment by Theundyingcode** [comment]
I was thinking changing the is_waterproof method would be the simplest/easiest and would prevent issues with items added latter.  However, it's just
` bool player::is_waterproof( const std::bitset<num_bp> &parts ) const
 {
     return covered_with_flag("WATERPROOF", parts);`

So I edited the covered_with_flag method.

Options:

1. I haven't spent any time looking at the item factory so changing that is out for me.

2. Adding the Flags to everything would be quick thanks to find and replace. Where dose the Flag for worn guns go though? Potentially recreate problem with every new item 

3. revert is covered and rewrite player::is_waterproof to be smarter. (possibly move up to character.cpp)

**Comment by Coolthulhu** [comment]
> Where dose the Flag for worn guns go though? Potentially recreate problem with every new item

Guns get all the flags from their gunmods by default. So if the shoulder strap mod is waterproof, the gun will be waterproof. It won't be the "gun waterproofing" (being able to fire in water), so no problem here.

Recreating the problem with every new item is lesser evil here. Hardcoding weird layer behaviors is out of question - it would only be excusable for something major, not a minor annoyance.

There is a rather complex option that would solve it for longer, but it would have a larger cost up front:
Creating abstract item definitions and having items copy them. This would allow specifying data for large sets of items (for example, all waist layer items). If you're interested, check out data/json/items/comestibles/carnivore.json - it has a set of entries defined by copying.

**Comment by Theundyingcode** [comment]
The set doesn't seem very complicated... I should be able to do that fairly quickly... Things don't get heavier when wet right?  I'll make a couple categories for the sake of future tweaks.

**Comment by Coolthulhu** [comment]
> Dose this then create a problem with have a gun on your back protecting your hoodie from getting wet?

Now that I think about it, it may actually do this.
A new flag may be necessary here.
Or possibly a redesign of the whole wetting function.

The simplest way would be to use the WATER_FRIENDLY flag instead. It's not a perfect solution, because there are bags that are explicitly supposed to be just water friendly backpacks, but it's simple enough and this little problem doesn't warrant redesigning things too much.

**Comment by Theundyingcode** [comment]
I tries doing it to a smaller file dose it look right? I can't figure out how to add to pull requests...

Also, when you copy-from and then have a "flags" element are you adding or overwriting?  

[ammo_pouch.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/1326970/ammo_pouch.txt)

**Comment by Coolthulhu** [comment]
It's not right: the use action is overwritten, not loaded partially. It needs to be fully defined each time.
The abstract class shouldn't include things that you will want to overwrite, only things shared by instances of it. For example, material thickness.

The abstract class shouldn't be "ammo_belted", but something like "leg_bag", "torso_bag", "belt" etc.
Those in turn could be copies of some more generic thing, like "accessory_belted", "accessory_waist".

With copy-from, you add new flags like this:
```
"extend": { "flags": [ "BELTED" ] }
```

If you don't do that, you redefine things instead.

**Comment by Coolthulhu** [comment]
I read the functions you're changing.

Since `is_waterproof` is the ONLY user of `covered_with_flag`, it would be OK if you inlined `covered_with_flag` in `is_waterproof` and removed `covered_with_flag`.
The problem with your implementation was that you special cased it in a general function - this behavior was unacceptable. If `is_waterproof` was the only user of this code, it would be tolerable (although not perfect) to have a special case there.
That would still leave the problem of communicating it to player, though. Which adding the flag solves just fine.

**Comment by kevingranade** [comment]
I'm fairly certain all you need to do is add the water friendly flag to the items you want to behave like this,  and if that doesn't do exactly what you want, add a new flag and apply that one.

**Comment by Theundyingcode** [comment]
This code isn't going to be going in so I''ll close the PR now that I have the info I need to properly change stuff.

I like the abstract copy from fix the most because as a by-product you also end up creating item templates.

**Comment by kevingranade** [comment]
Just add flags to the items you want to act like this.  There is no reason to make an item template based on waterproofing behavior.

**Pull request closed without merging**
