### PR TITLE
Remove Raging Judge, A180, KSG-25, PPSH

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary
Bugfixes "Remove some guns"

#### Purpose of change

PPSH, KSG 25, Raging Judge, A180 don't exist in enough quantities.

#### Describe the solution

Removes their spawns and moves their defs to an obsoletion file. None have any good migration targets so this is the best I can do. 

#### Describe alternatives you've considered

Leaving em

#### Testing
image
The guns still exist, but shouldn't spawn. Unsure how GG will react though.

#### Additional context
Originally removed the 12 gauge gatling gun, but Renech pointed out it was wanted, so I just removed the spawns
N/A

### CODE REVIEW

**Comment by KeremBabaG** [comment]
Will we have any guns left after all these prs or will I have to actually try out archery for once

**Comment by Holli-Git** [comment]
> Will we have any guns left after all these prs or will I have to actually try out archery for once

Many. The 180 already didn't spawn, this is just removing the magazines, KSG 25 and PPSH already had an astronomically low chance of spawning, and who actually crafts the 12 gauge gatling gun

**Comment by KHeket** [comment]
I think there is a lot of collectors of different weapons, and such type of guns can be met in America, but with extremely low chance. May be create itemgroup named "Super rare weapon", where we include such rare weapon with very low spawn chance? 
Because its realistic and make funny situation happens. And also obsoleted rpg can be readded in this item group

**Comment by Holli-Git** [comment]
> I think there is a lot of collectors of different weapons, and such type of guns can be met in America, but with extremely low chance. May be create itemgroup named "Super rare weapon", where we include such rare weapon with very low spawn chance? Because its realistic and make funny situation happens. And also obsoleted rpg can be readded in this item group

If you'd like to do all the math and research to make sure the spawn numbers aligns with IRL values, go right ahead.

**Comment by KeremBabaG** [comment]
I agree with the other guy (except the RPG part). Correct me if I'm wrong but from what I understand these guns are removed based on the amount (as in official figures) of them people have in New England and US in general. I see why you would remove stuff like survivor revolvers and 12 gauge gatlings but I think that the the rarity of the other guns (such as raging judge or lemats) don't really warrant their removal as collectors like this stuff and from what I gather there are plenty of those in US. Putting them in rare chances in a rare weapon groups which itself spawns extremely rarely would be better imo.

Also I would like to add that official figures on guns such as PPSH might be misleading as these are brought by expats or smugglers who have no reason to register their smuggled firearms.

**Review by Maleclypse — CHANGES_REQUESTED** [review]
Gunbroker results don’t seem valid on a gun that is still produced today and has been for 13+ years. KSG, looking online I can buy them from multiple retailers brand new. Which suggests that low sales on gunbroker.com may have more to do with people that own one not parting with it. I’ll come back and look at the others later when I’m not on my phone but I’d like to restate that I don’t believe we should be removing guns due to low gunbroker hits that can be purchased brand new for a similar price to the used market. That suggests a very popular gun. Also please try to add pictures showing the gun broker hits justifying adding or removing any guns other than the pc crafted one.

**Comment by Holli-Git** [comment]
> Gunbroker results don’t seem valid on a gun that is still produced today and has been for 13+ years. KSG, looking online I can buy them from multiple retailers brand new. Which suggests that low sales on gunbroker.com may have more to do with people that own one not parting with it. I’ll come back and look at the others later when I’m not on my phone but I’d like to restate that I don’t believe we should be removing guns due to low gunbroker hits that can be purchased brand new for a similar price to the used market. That suggests a very popular gun. Also please try to add pictures showing the gun broker hits justifying adding or removing any guns other than the pc crafted one.

KSG-25 is a specific variant of the normal KSG with a much longer barrel and magazine. It's a whole lot less common than the regular KSG. And newer guns that have already been added, like the KelTec CP33 (released 2019) has enough hits on gunbroker. 
image

**Comment by DoctorBoomstick** [comment]
My two sense when it comes to these gun removals, they make good, logical sense, however, there must be a but in the equation, and that but comes on behalf of automatic weapons. I’ve always felt a tad weird using gun-broker as a source to determine the common merits of NFA items, and that’s mostly cause, if we had to follow the notion of removing anything that doesn’t get a hundred hits on Gun Broker, we can remove:
- MAC-10s.
- MAC-11s.
- MP-40s.
- AKMs.
- Browning Automatic Rifles.
- Tomson submachine guns.
- M3 submachine guns.
And basically all automatic weapons that aren’t used by military or police forces because they don’t get the needed numbers, when guns such as MP-40s and PPSH-41s, and even Kalashnikovs to a limited extent, have good provision for being bring-back guns in a time and age where such guns did not require registration in the States. Also, in my completely personal opinion, I feel like machine gun numbers would be better sourced from dedicated past auction house listings, unless we can get a hold of the NFA database for registered machine guns, which 10 minutes of admittedly non-exhaustive googling failed to turn up. As I see it, collectors, speaking as one myself, are far less likely to put up a machine gun that they bought for sail, unless they acquired the firearm as an investment. For reference and likely deemed irrelevant, I live in a country with pretty comparable gun laws to the United States but with 500,000 people. I have, in the past 2 months of attending meetings, encountered at least 10 different people who own PPSH machine guns because they are such a mass-produced gun. Is this relevant to CDDA? No, but I thought I’d present it as an example that just because people aren’t parting with it doesn’t mean that people don’t have it.

**Comment by Holli-Git** [comment]
> My two sense when it comes to these gun removals, they make good, logical sense, however, there must be a but in the equation, and that but comes on behalf of automatic weapons. I’ve always felt a tad weird using gun-broker as a source to determine the common merits of NFA items, and that’s mostly cause, if we had to follow the notion of removing anything that doesn’t get a hundred hits on Gun Broker, we can remove:
> 
> * MAC-10s.
> * MAC-11s.
> * MP-40s.
> * AKMs.
> * Browning Automatic Rifles.
> * Tomson submachine guns.
> * M3 submachine guns.
>   And basically all automatic weapons that aren’t used by military or police forces because they don’t get the needed numbers, when guns such as MP-40s and PPSH-41s, and even Kalashnikovs to a limited extent, have good provision for being bring-back guns in a time and age where such guns did not require registration in the States. Also, in my completely personal opinion, I feel like machine gun numbers would be better sourced from dedicated past auction house listings, unless we can get a hold of the NFA database for registered machine guns, which 10 minutes of admittedly non-exhaustive googling failed to turn up. As I see it, collectors, speaking as one myself, are far less likely to put up a machine gun that they bought for sail, unless they acquired the firearm as an investment. For reference and likely deemed irrelevant, I live in a country with pretty comparable gun laws to the United States but with 500,000 people. I have, in the past 2 months of attending meetings, encountered at least 10 different people who own PPSH machine guns because they are such a mass-produced gun. Is this relevant to CDDA? No, but I thought I’d present it as an example that just because people aren’t parting with it doesn’t mean that people don’t have it.

Alright, fair enough. I'll put this in draft for now before removing the PPSH from this PR

**Comment by Kantonine** [comment]
The only thing i can really say on this is that maybe plenty of these should be moved to the gun bank? I made this point about the Lemat, but we have the Pistola PRESSIN, which is rare irl, AND custom-made, so i think having stuff like that is fine with the current model. I wouldn't be really able to check what gunbroker has to show cuz im in the UK

**Comment by Holli-Git** [comment]
@DoctorBoomstick Alright, PPSH re-added!

**Comment by Holli-Git** [comment]
> The only thing i can really say on this is that maybe plenty of these should be moved to the gun bank? I made this point about the Lemat, but we have the Pistola PRESSIN, which is rare irl, AND custom-made to include a switchblade in it, so i think having stuff like that is fine with the current model. I wouldn't be really able to check what gunbroker has to show cuz im in the UK

I'd rather not do that. I don't want the artisans to be the faction that has a butt load of rare guns because someone didn't want them removed.

**Review by Maleclypse — APPROVED** [review]

**Comment by Maleclypse** [comment]
After looking further while there are listings for new ones for sale and talking with Kevin and Holli those new listings are not evidence of extensive inventory in the wild.

**Comment by kevingranade** [comment]
`I think there is a lot of collectors of different weapons, and such type of guns can be met in America, but with extremely low chance. May be create itemgroup named "Super rare weapon", where we include such rare weapon with very low spawn chance?`
In theory I'm not totally against this, but I don't think you appreciate _how low_ of a chance we're talking about here.
This would result in the chance of you finding a particular "super rare gun" being _substantially lower_ than a one in a million per playthrough.  Yes, in the vast majority of playthroughs you would never see a "super rare" gun at all, and even when you did it would almost never be one you're interested in.
That gets us to practicalities, no I don't want to commit to spending non-trivial amounts of effort keeping around "super rare" guns that you would practically never see.  Do feel free to expend that effort yourself and make a "super rare gun" mod. (no it doesn't go in the main repository either)

`there must be a but in the equation, and that but comes on behalf of automatic weapons`
Sort of but as it turns out not really.
`I feel like machine gun numbers would be better sourced from dedicated past auction house listings`
One, get that source, don't just handwave.  We're using the best sources we have available, if you have a better one, we can look into it, but if you want to hypothesize that there's a better source without providing one, that's not helping.
`unless we can get a hold of the NFA database for registered machine guns`
The database itself isn't available AFAICT, but summaries of it are, and it doesn't look good for civilian machine guns.
https://www.atf.gov/firearms/docs/report/2021-firearms-commerce-report/download
Here's the Massachusetts row from the NFA registry for 2021 (reasonably recent)

State | Any Other Weapon | Destructive Device | Machinegun | Silencer | Short Barreled Rifle | Short Barreled Shotgun | Total
--------|--------------------|----------|---------|------------|---------|---------|----
Massachusetts | 969 | 19,571 | 7,070 | 10,409 | 6,079 | 1,040 | 45,138

Yep that's a total of 7,070 machine guns registered in the whole state. That's going to be dominated as usual by the more common stuff, leaving everything but the top 10 or so in the single digits. This is not an appearance rate worth bothering with.

**Review by RenechCDDA — DISMISSED** [review]
I do not think the gatling gun should be removed as **crafting recipe**. It is [specifically mentioned in the FMS as one example of a craftable automatic firearm](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FREQUENTLY_MADE_SUGGESTIONS.md#craftable-automatic-weapons-mostly-no) and previously had consensus from [Kevin](https://discord.com/channels/598523535169945603/598607195021508638/809472400370565190), [mlangsdorf](https://discord.com/channels/598523535169945603/598523535169945607/860999323646951456), and [tenmillimaster/Tonkatsu](https://github.com/CleverRaven/Cataclysm-DDA/pull/34638). (Has that changed?)

I see no problem with removing it from the spawns.

**Comment by a-chancey** [comment]
Just to throw in some more context for gun ownership in Massachusetts, circa 2022, being summarized from here: https://www.boston25news.com/news/local/gun-ownership-ma-number-licenses-carry-handguns-rifles-shotguns-state/RU5XN4TEFBFWBJJYPINVCFEMPI/

Only ~7% (roughly 14.7% adjusted for adults only) of the population are licensed to carry (497,237 licenses vs ~6.982mil total population, ~3.383 mil adults) which includes handguns, shotguns and high capacity rifles. 

~.3% (24,215 people) have a Firearms ID Card, which allows them to buy shotguns and low capacity rifles 

Only .02% (1,989 people) have active licenses for machine guns. 8% of those are registered to MA State Police, meaning as an average, each licensee owns 3.55 machine guns, though I imagine it's heavily weighted towards the police vs private owners. 

From what I've seen elsewhere - though I'm not confident on the reliability of the numbers so I'll not directly use it as a source - it appears the per capita gun ownership in MA is the lowest in the U.S., tied with New Jersey. 

A [2020 study by the RAND Corporation](https://247wallst.com/state/how-the-gun-ownership-rate-in-massachusetts-compares-to-other-states/) actually estimated lower total ownership - only 9% of adults actually owned guns in MA in 2020, suggesting a lot of folks are licensed but don't carry. 

Now the military deployments would certainly skew the machine gun numbers, but they'd only be using a select group of weapons

**Comment by I-am-Erk** [comment]
A quick moderation note, if you're here because reddit told you to be angry, please make sure to read and understand the PR and context before hopping in to complain, and only comment if you have some real, actionable ideas for how we could better manage the problem of having to keep the amount of guns in the game manageable from a maintenance perspective. As Kevin has said, we're open to ideas, they just have to be ideas we can work with. This PR is probably also not the best place for extended and ongoing discussion about project policy in general (if someone has a link to a better issue for it feel free to post, I don't have time to hunt it down right now).

**Comment by KnifeFightBears** [comment]
Guys the raging judge is common as it gets as far as revolvers go, they have ten of them at nearly every pawn shop in america, please read a book or go outside, touch grass, please stop submitting PRs like this. Stop antagonizing the community. Stop pretending like huge throngs of people shouting about your ivory tower changes based on awful information don't have a point.

**Comment by KnifeFightBears** [comment]
The Taurus Raging Judge is available in GENERAL STOCK at Bass Pro in .410; Anyone in america can have one ordered to their local store or direct to their home address in under a week for under $600. You can likely go into your local bass pro and just buy it over the counter. This is a hilariously common firearm. They're everywhere. I just went into a pawn shop last week and saw ten of them.

https://www.basspro.com/shop/en/taurus-judge-stainless-double-action-revolver

I deleted another comment I made because it was getting a bit rude, but I'm gonna be honest with y'all: these changes are awful and they make this project look poorly managed. If you're going to say something is too rare to exist in the real world, you could at least try to verify that's correct first. If the team is really this far away from reaching a real understanding on guns, maybe it's time for you guys to start looking for an information specialist in this area. Anyone who knows guns could have told you this was wrong.

**Comment by kevingranade** [comment]
You realize that the *Raging* Judge literally does not exist on the market, right?
From Wikipedia:
`On March 27, 2011, Taurus International President and CEO Bob Morrison stated on the Gun Talk radio show that the Taurus Raging Judge XXVIII was still under development.[[9]](https://en.wikipedia.org/wiki/Taurus_Judge#cite_note-9) Ultimately, the firearm never made it into production and no official statement was made by Taurus about it again.`
A quick check on the official website of the taurus judge https://www.taurususa.com/revolvers/taurus-judge shows a distinct lack of the word "Raging".

I was auditing gun appearance rates and discovered this with a tiny bit of research, I brought it up on discord and it was IMMEDIATELY brought to my attention that while the Raging Judge is literal vaporware that has never been on the market, the Judge line is incredibly popular, so I went cool, thanks for correcting me, it needs to be be a swap instead of just a removal.

Oh look, it already happened two weeks ago #74115
Turns out it's a pain to migrate directly from one to the other because the cylinder capacity is different, so we can't migrate them, but instead we just have a Judge now and we're removing Raging Judge.

> maybe it's time for you guys to start looking for an information specialist in this area

We're happy to work with anyone that isn't an asshole, we don't exactly have the resources to go out and *recruit* people with particular skillsets, so our hands are tied WRT what skills are available on the team.
If you have a pointer to a better source to use, I'm all ears, but "go visit a pawn shop (on the wrong side of the country)" isn't exactly a workable solution, so I'll have to wait for something else.

**Comment by KnifeFightBears** [comment]
He's talking about the Raging Judge 28. You can find raging judges online (with "raging" in the name) in great abundance. If they had never been released that would not be true.

Edit: Circling back around to this, from the wikipedia article you linked:

In 2010 Taurus introduced the Raging Judge which is chambered for [.454 Casull](https://en.wikipedia.org/wiki/.454_Casull) as well .45 Colt and 3" .410 shot shells.[[6]](https://en.wikipedia.org/wiki/Taurus_Judge#cite_note-Lee2013-6)

In 2011 at [SHOT Show](https://en.wikipedia.org/wiki/SHOT_Show) in [Las Vegas, Nevada](https://en.wikipedia.org/wiki/Las_Vegas,_Nevada), Taurus introduced the Raging Judge XXVIII chambered for 28 gauge shot shells. The 67 ounce revolver held five shells in the cylinder and had a 6.5" barrel. The cylinder used a double lock-up similar to the Raging Judge chambered in .454 Casull.


-

The 28 is meant for 28 gauge shot shells, which would have likely run against ATF restrictions and gotten the weapon labeled a destructive device. The Raging Judge itself is a higher end variant of the Judge; TRJ is the only Judge that can be chambered in 454

**Comment by esotericist** [comment]
> https://www.basspro.com/shop/en/taurus-judge-stainless-double-action-revolver

@KnifeFightBears in addition to this being a poor reference for telling what the regional availability volume is for the guns they actually list, they _do not claim to have the raging judge_. they have some judge models, they have a couple 'raging hunter' models, but not raging judge.

to reiterate from earlier discussions: the criteria here we're after is not "it ever existed", but "it was in this region in sufficient volumes to land in randomized loot tables". this is COMPLETELY distinct from placed instances; we are willing to have rare guns that get deposited in a distinct special when there's interesting story attached (see the artisans plot line for an example), but if there isn't plausible reason to believe enough of them are around then they shouldn't be in the procgen item groups.

lastly, if "this is wrong, do better" posts keep turning up but without anything _actually actionable_ in them, then we'll be forced to lock the conversation to organization members. we don't like doing that, because it stifles things. please don't contribute to that happening.

i beg of you, take the time to understand the criteria under question, then actually give us something to work with. if you can't do that, please don't post.

**Comment by KnifeFightBears** [comment]
Sorry; I was definitely confused WRT the raging judge vs the judge and I didn't add much to the conversation here. _I_ need to do better and I'm sorry for derailing the conversation with some really bad posts.

**Comment by tenmillimaster** [comment]
> The only thing i can really say on this is that maybe plenty of these should be moved to the gun bank? I made this point about the Lemat, but we have the Pistola PRESSIN, which is rare irl, AND custom-made to include a switchblade in it, so i think having stuff like that is fine with the current model. I wouldn't be really able to check what gunbroker has to show cuz im in the UK

I'd like to note that the pressing we have in game isn't a pressing, made pre-cataclysm, it's a tribute, made post cataclysm.

**Pull request merged**
