### PR TITLE
Properly obsolete Railroad Station

### LINKED ISSUE #68397: Persistent invalid overmap special id after updating
### Describe the bug

Emits the following after updating from a ~Aug 20 build to one from yesterday. Does not go away after saving. Does not appear happen on a new character in a new world.

```
 DEBUG    : invalid overmap special id "Railroad Station"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = overmap_special]
 FILE     : src/generic_factory.h
 LINE     : 478
 VERSION  : d48717d
```

and

```
 DEBUG    : invalid overmap special id "railroad_city"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = overmap_special]
 FILE     : src/generic_factory.h
 LINE     : 478
 VERSION  : d48717d
```

### Attach save file

[Copper Canyon-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12771883/Copper.Canyon-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.

### Expected behavior

No error.

@ZhilkinSerg added a railroads mod which replaced(?) the no railstations mod in #67713.
Maybe some migration stuff was missed?

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: d48717d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #68397
#### Describe the solution
use overmap_special_migration
#### Additional context
i don't know should railroad_city be obsoleted also, as it's city_building, but i think there is no harm to have it

### CODE REVIEW

**Comment by Maleclypse** [comment]
```(all_mods)=> (continued from above) ERROR : src/overmap.cpp:549 [void overmap_specials::check_consistency()] Overmap special id railroad_city has been removed or migrated to a different type.
(all_mods)=> 22:06:48.501 ERROR : src/overmap.cpp:549 [void overmap_specials::check_consistency()] Overmap special id Railroad Station has been removed or migrated to a different type.```

**Comment by GuardianDll** [comment]
Well shit
Does it mean we can't migrate maps if they are moved to the mod instead of being removed?

**Comment by Procyonae** [comment]
Guess we'll have to add perfect railroad for 0.H /s
Can't you just rename the mods version?

**Comment by GuardianDll** [comment]
i can, but then i assume i need to migrate it also, now inside the mod itself, yes?

**Comment by Procyonae** [comment]
I don't think so, it's not very convenient to test tho

**Comment by Maleclypse** [comment]
Thank you for all the contributions you’ve been making lately. You’ve really been on a roll.

**Pull request merged**
