### PR TITLE
Leavening audit

### PR DESCRIPTION
**Pull request by onura46**
#### Summary
None

#### Purpose of change
Adds baking powder and other leavening agents and recipes for some non-yeasted baking recipes

#### Describe the solution
This PR adds a baking powder item and recipe, a cream of tartar item (used to make baking powder), and adds both baking powder and baking soda to appropriate recipes: brown bread, cake, sponge cake, donut holes, pancakes, waffles, and cookies. 😄 

#### Describe alternatives you've considered
For gameplay purposes, baking powder and cream of tarter don't need to be added. Baking soda could be used for everything, ignoring realism. I'm open to this for ease of gameplay, even though it doesn't match reality.

#### Testing
Loaded up a new character, debugged good cooking skills, checked the relevant recipes to make sure they changed.

### CODE REVIEW

**Comment by onura46** [comment]
This is a draft for the moment because I want to make sure I've got every recipe. Also, I'm not 100% sure people won't be annoyed by it or make a case for adding baking powder, so I wanted to leave room for that.

Also note: 1 unit of baking soda = ~8 grams = ~2 teaspoons, which should be more than enough for most things. The only recipe that takes more than 1 unit is cake.

**Comment by tenmillimaster** [comment]
Because of the chemical utility of baking soda (making sodium carbonate, for example), I think adding baking powder is a good idea.

**Comment by onura46** [comment]
Alright, now that baking powder is in, do I add cream of tartar as a suitable acid to craft it? XD That could wait for a hypothetical future PR, though, because there's a lot of nuanced possibilities for further household chemistry and cooking that goes too deep for me...

**Comment by onura46** [comment]
It seemed prudent to add a way to craft baking powder, so cream of tartar is also in, albeit in slightly rarer spawns. I'm not messing with the chemistry of making _that_, but it might be worth adding a buttermilk recipe, since that already exists. Noted for later...

**Pull request closed without merging**
