### PR TITLE
Fix crash when npcs want to wield a weapon from a wielded container

### LINKED ISSUE #44196: Crash in item assignment operator called from npc::wield_better_weapon()
# Describe the bug
The game crashes.

# Steps To Reproduce
Load this save
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5226364/crash.zip)
Don't interrupt the in-progress waiting, just keep waiting.
Game crashes.

# Expected behavior
Game does not crash.

# Versions and configuration
- OS: Linux
    - OS Version: Arch Linux, kernel version 5.8.5
- Game Version: 0.E-5975-g0fc6ebb6e7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:823
    log_crash(char const*, char const*)
    crash.cpp:?
    signal_handler(int)
    …/src/crash.cpp:117
    ??
    ??:0
    addr2line: DWARF error: could not find variable specification at offset 18bb06
    favorite_settings
    …/src/item_pocket.h:75
    item_pocket
    …/src/item_pocket.h:38
    void __gnu_cxx::new_allocator<std::_List_node<item_pocket> >::construct<item_pocket, item_pocket const&>(item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/ext/new_allocator.h:150
    void std::allocator_traits<std::allocator<std::_List_node<item_pocket> > >::construct<item_pocket, item_pocket const&>(std::allocator<std::_List_node<item_pocket> >&, item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/alloc_traits.h:512
    std::_List_node<item_pocket>* std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_create_node<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:637
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_insert<item_pocket const&>(std::_List_iterator<item_pocket>, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1912
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::emplace_back<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1227
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_initialize_dispatch<std::_List_const_iterator<item_pocket> >(std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>, std::__false_type)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1840
    list
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:738
    item::item(item const&)
    ??:?
    item
    …/src/item.cpp:489
    addr2line: DWARF error: could not find variable specification at offset 12818f
    addr2line: DWARF error: could not find variable specification at offset 18e4da
    addr2line: DWARF error: could not find variable specification at offset 18e23e
    addr2line: DWARF error: could not find variable specification at offset 1ea297
    std::_List_node<item>* std::__cxx11::list<item, std::allocator<item> >::_M_create_node<item const&>(item const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:641
    void std::__cxx11::list<item, std::allocator<item> >::_M_insert<item const&>(std::_List_iterator<item>, item const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1912
    void std::__cxx11::list<item, std::allocator<item> >::emplace_back<item const&>(item const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1227
    void std::__cxx11::list<item, std::allocator<item> >::_M_initialize_dispatch<std::_List_const_iterator<item> >(std::_List_const_iterator<item>, std::_List_const_iterator<item>, std::__false_type)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1840
    list
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:738
    item_pocket
    …/src/item_pocket.h:38
    void __gnu_cxx::new_allocator<std::_List_node<item_pocket> >::construct<item_pocket, item_pocket const&>(item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/ext/new_allocator.h:150
    void std::allocator_traits<std::allocator<std::_List_node<item_pocket> > >::construct<item_pocket, item_pocket const&>(std::allocator<std::_List_node<item_pocket> >&, item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/alloc_traits.h:512
    std::_List_node<item_pocket>* std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_create_node<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:637
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_insert<item_pocket const&>(std::_List_iterator<item_pocket>, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1912
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::emplace_back<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1227
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_initialize_dispatch<std::_List_const_iterator<item_pocket> >(std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>, std::__false_type)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1840
    list<std::_List_const_iterator<item_pocket>, void>
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:806
    std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::empty() const
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1056
    std::_List_iterator<item_pocket> std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::insert<std::_List_const_iterator<item_pocket>, void>(std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/list.tcc:138
    item::operator=(item const&)
    ??:?
    item_contents::operator=(item_contents const&)
    …/src/item_contents.h:35
    item::operator=(item const&)
    …/src/item.cpp:492
    npc::wield(item&)
    …/src/npc.cpp:1164
    npc::wield_better_weapon()
    ??:?
    npc::move_pause()
    …/src/npcmove.cpp:2699
    npc::execute_action(npc_action)
    ??:?

Way down the line, it crashes calling and item_pocket::favorite_settings::favorite_settings

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary

SUMMARY: Bugfixes "Fix crash when npcs want to wield a weapon from a wielded container"

#### Purpose of change

Fixes #44196

#### Describe the solution

Previously `npc::stow_item` invalidated the reference to the item the npc wants to wield if it was contained in the currently wielded item. To avoid that, I reordered the logic of `npc::wield` to first remove the item if it's on the npc and then free their hands.

#### Testing

Load the save from the issue and watch it not crash.

### CODE REVIEW

**Comment by kevingranade** [comment]
It looks like there's an item duplication bug in here:
NPC with no inventory wields a golf bag with a golf club in it.
NPC attempts to wield golf club.
    npc_wield()
        makes a copy of the golf club.
        stow_item( golf_club )
            removes golf club from golf bag and drops it on the ground, and returns a reference to it.
        overwrites that copy with a copy of an item returned by stow_item()
        stow_item( golf_bag )
            wears the golf bag I think?
        character does not have this item, so it triggers the else and wields the golf club.

Result, one golf club wielded, one on ground at feet.

**Comment by mqrause** [comment]
Oh yeah, looks like the else case didn't even have the pick up from ground situation before. It was just used for items given by the player, which were removed on the player side.

**Comment by mqrause** [comment]
I'm honestly not super happy with this now. It can still duplicate items if it overflows on a nearby tile when dropping. Using a map_selector with a radius 2 like in the overflowing code doesn't feel too good either, though. Ideas appreciated.

**Comment by mqrause** [comment]
I'm kinda low on time right now, so it might take a bit until I work on this again. Best case on the weekend, worst case at the end of the year.

**Comment by mqrause** [comment]
Turned out it didn't even work before. Fixed and tested it so npcs will properly drop and wield items from wielded containers without duplication now. Still no good solution for the case of the dropped item overflowing to a nearby tile, though.

**Comment by mqrause** [comment]
With a bit of time to actually think about what I'm doing there I realized there was a much simpler solution. Reverted everything and implemented that. This is done and fully functional now.

**Pull request merged**
