### PR TITLE
Replace "two-by-four" with "plank" in user-facing strings

### PR DESCRIPTION
**Pull request by Musteval**
#### Summary
None

#### Purpose of change
2x4s have been called "plank", not "two by four", for at least a year - not sure exactly when the change was made, but I know it was recent enough that the wiki still has some references to two-by-fours. But there are still a bunch of places in the code that use the old name. In particular, the search popup on the item crafting screen uses the old name on the fifth example:

twobyfour

#### Describe the solution

I basically just did `sed -i 's/two by four/plank/'` across the codebase, except that I replaced it with `2x4` in doc/VEHICLES_JSON.md because `2x4` is still the item ID of planks.

I dunno how the translation files work, I can revert them if they're not meant to be edited by hand like this.

#### Describe alternatives you've considered
N/A

#### Testing
I'm compiling it right now, in like an hour hopefully that'll be done and I can confirm that the game starts and the item crafting popup no longer refers to two-by-fours. If there's anything high-risk in here I'm happy to revert it rather than testing it in a more complicated way than that.

### CODE REVIEW

**Comment by actual-nh** [comment]
Do revert the translation files, please.

**Comment by MarlossCDDA** [comment]
Okey dokey, 05793e7cbb24247a1ed80354b7ca675301bafe4d

**Comment by actual-nh** [comment]
The "General Build Matrix" error isn't you - see #47706.

**Comment by MarlossCDDA** [comment]
Tested locally:

compiled

Hope that was the last CI issue 🤞

**Comment by MarlossCDDA** [comment]
is there a better way to rerun CI than merging in master? 😬

**Comment by anothersimulacrum** [comment]
If the failure is not your fault (it's not), don't worry about it.

**Pull request merged**
