### PR TITLE
Tweaked bank cells loot spawn list

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Content "Tweaked bank cells loot spawn list."```

#### Purpose of change
Bank ain't supposed to be a dungeon in the end of which a lucky survivor can find a treasure chest with a rare high-level loot.

#### Describe the solution
Removed most of the nonsense stuff from the bank cells loot spawn list, such as power armor, minireactors or holocloaks. Now they store only jewelry, money, precious metals, confidential or classified documents, and occasional weird or sentimental things like a straw doll or a holy symbol.

#### Describe alternatives you've considered
~Leave rare CBMs as they could be stolen from military or scientists through the industrial espionage. But in the end decided to remove them as well. If you think they do belong to bank cell loot spawn list, ping me.~

### CODE REVIEW

**Comment by glenmack** [comment]
This could actually work well with a suggestion I just posted that would give old world money more "value" to the survivor. #32635

**Comment by chaisawlajatang** [comment]
I suggest adding collector_book group, they're pretty valuable accoring to descriptions.

**Comment by Night-Pryanik** [comment]
> I suggest adding collector_book group, they're pretty valuable accoring to descriptions.

Valuable, but not to the extent that they should be kept at the bank.

**Comment by chaisawlajatang** [comment]
Some of them state they worth a whole fortune.

**Comment by Human-Shield** [comment]
It makes cities even more worthless mid-game. 

Would need more lore around strange temple and cult hidden cabin. The rich could be storing artifacts.

**Comment by Night-Pryanik** [comment]
> It makes cities even more worthless mid-game.

So what? In an effort not to make cities worthless let's leave all the inappropriate stuff in the banks?

**Comment by Zireael07** [comment]
Some CBMs could be made to spawn? Not the cloak tech or other ridiculously OP stuff, but the average CBMs would probably be costly enough to be stored in a bank safe while making more sense than e.g. power armor or cloak.

**Comment by curstwist** [comment]
I agree this stuff shouldn't be in bank vaults, but I hope we can find/create some stuff that will be worthwhile to loot there.  With the security bots, there are very good reasons not to go to banks anymore.

**Comment by John-Candlebury** [comment]
Can you consider keeping the "standard_template_construct" aka Nanofabricator templates, in that list?

There aren't many other places that spawn them, and they are rather, of similar to confidential documents, in that they let you craft high tech stuff.

**Comment by Night-Pryanik** [comment]
Returned three CBMs (with a 2.5 times lower chance to spawn) and a nanofabricator template with a slightly lower chance to spawn.

**Comment by Night-Pryanik** [comment]
> There aren't many other places that spawn them,  and [...] they let you craft high tech stuff.

I returned their spawn, but not because of their rarity and not because they are a high-level loot (these both are weak rationales), but because it indeed feels appropriate to spawn in a bank cell.

**Comment by faefux** [comment]
Hah, I just did this on my offline machine and was about to upload.  Bank loot was crazy!  Thanks for saving me a job @Night-Pryanik ! :)

**Pull request merged**
