### PR TITLE
Fixed broken Android build due to missing FreeType library

### PR DESCRIPTION
**Pull request by katemonster33**
#### Summary
Build "Fixed broken Android build due to missing FreeType library"

#### Purpose of change
Android build broken since FreeType integration, fixing the build

#### Describe the solution
Since freetype static library is already included in SDL_ttf, just needed to add include statement to the compiler

### CODE REVIEW

**Comment by katemonster33** [comment]
@db48x I opened the build on android and it doesn't seem like freetype is enabled. Is this expected?

**Comment by db48x** [comment]
The default font (Roboto Medium) doesn’t have any Japanese characters so it’s falling back to asking SDL to render something (`cata_imgui.cpp:451`). You can edit your `config/fonts.json`  to include a Japanese font and it will use it for the Japanese characters while building the texture atlas.

**Comment by katemonster33** [comment]
@db48x seems like at the default terminal size used in the android build (80x24) the fonts all look real bad. With larger values it looks better. And yeah, English looks better.

**Comment by db48x** [comment]
Better, but still not as good as it should look. Can you open the ImGui Demo window, open the Style Editor, and show me the Fonts tab? What metrics are we using for the first font?

**Comment by katemonster33** [comment]
@db48x is this what you need? Looks like Roboto 16pt? Is that expected? It looks fine I think, I just wanted to be sure I've really fixed the android build.

**Comment by katemonster33** [comment]
I don't think I can do that on the Android build, unfortunately, because on Android the app hijacks the touch screen and doesn't allow you to click points on the screen using your finger.
I think that unfortunately the reason it looks like this is that Android draws at a resolution based on the terminal width and height and then simply up scales it to the phones screen size. I think the fonts just aren't going to look good on Android as long as we do it like that.

**Comment by db48x** [comment]
Ok, that’s fun. At least you’ve fixed the build.

**Pull request merged**
