### PR TITLE
Make soldering iron not able to repair metals with high melting point

### LINKED ISSUE #33109: A soldering iron should not be able to repair materials that has a far higher melting point than it can reach.
# Describe the bug

A soldering iron should not be able to repair materials that has a far higher melting point than it can reach. 

# Expected behavior

A soldering iron can currently repair aluminum, copper, hard steel, iron, kevlar, plastic and steel, of those only plastic is realistic.

The tip of a typical small battery-powered soldering iron reaches about 350-500 ºC. This is below the melting point of most metals.

A soldering iron should probably also not be able to repair kevlar either as it's a woven synthetic fibre. 

I would suggest letting a simple needle/sewing kit/tailor kit be able to repair kevlar as it's just a matter of attaching kevlar plates.

# Additional context

For reference:

Material | Melting point (ºC)
--- | ---
plastic (polyethylene) | 115-135
solder |  180-185
tin | 231.9
lead | 327.5
aluminium | 660.3
silver | 961.8
gold | 1064
copper | 1084
stainless steel | 1510
iron |  1538

Material | Decomposition temperature  (ºC)
--- | ---
neoprene | 200+
nomex | 400
kevlar | 450-500 

Some powered soldering irons:

* https://www.pcbtoolexpert.com/best-battery-powered-soldering-iron/

### PR DESCRIPTION
**Pull request by ampersand55**
#### Summary

```SUMMARY: Bugfixes "Make soldering iron not able to repair metals with high melting point```

#### Purpose of change

A soldering iron can currently repair aluminum, copper, hard steel, iron, kevlar, plastic and steel, of those only plastic is realistic. 

Repairing works by attaching scraps/patches of the same material onto the item. The tip of a typical small battery-powered soldering iron reaches about 350-500 ºC ([reference](https://www.pcbtoolexpert.com/best-battery-powered-soldering-iron/)), which is below the melting point of most metals.

A soldering iron should probably also not be able to repair kevlar either as it's a woven synthetic fibre.

Fixes #33109.

#### Describe the solution

Simply remove soldering irons ability to repair everything except plastic. 

You can still repair metals with welder or acetylene torch.

#### Additional context

For reference:

Material | Melting point (ºC)
--- | ---
plastic (polyethylene) | 115-135
solder |  180-185
tin | 231.9
lead | 327.5
aluminium | 660.3
silver | 961.8
gold | 1064
copper | 1084
stainless steel | 1510
iron |  1538

Material | Decomposition temperature  (ºC)
--- | ---
neoprene | 200+
nomex | 400
kevlar | 450-500

### CODE REVIEW

**Comment by LaVeyanFiend** [comment]
No tin or lead repair?

**Comment by Moonsabrt** [comment]
'w')
Keep in mind if you remove the soldering irons ability to repair kevlar.
Players who update the game will be unable to repair any kevlar items at all I believe. 'w')/

**Comment by John-Candlebury** [comment]
Hmm shouldn't you actually be able to repair most metal stuff if you used solder instead of chunks from the same material?

**Comment by ampersand55** [comment]
> 
> 
> No tin or lead repair? Those both melt below the low end of your soldering iron temp source, and tin is an actual material now.

You're right. I had that in mind when I made the issue, but it slipped my mind to add it.

Should I also add those it to welder and acetylene torch? The info will get a little cluttered.

**Comment by Moonsabrt** [comment]
> Hmm shouldn't you actually be able to repair most metal stuff if you used solder instead of chunks from the same material?

*nods*
I believe the purpose of this as discussed in the issue is that soldering irons can't weld two things together or put them into place 'w')
but yeah that does bring the point...why can't you just use solder to attach two pieces together instead of directly bonding it into place...

**Comment by Petethegoat** [comment]
Soldering stuff together makes sense in the context of certain crafting recipes, but I don't know that you should be able to fix a pipe spear by soldering the two halves back together.
I feel like most things that will actually take damage aren't really the things that are meaningfully fixable by just adding a lil solder joint.

But I'd like to see Kevlar repair added to the tailoring kit, at least.

**Comment by Moonsabrt** [comment]
> Soldering stuff together makes sense in the context of certain crafting recipes, but I don't know that you should be able to fix a pipe spear by soldering the two halves back together.
> I feel like most things that will actually take damage aren't really the things that are meaningfully fixable by just adding a lil solder joint.
> 
> But I'd like to see Kevlar repair added to the tailoring kit, at least.

This my friend this 'w') Kevlar should be added to the  tailoring kit as an alternative so players can repair their stuff and not have to rush the welder. Plus it is fiber so you should be able to repair it with a tailoring kit in theory.

**Comment by ampersand55** [comment]
> 
> 
> > Soldering stuff together makes sense in the context of certain crafting recipes, but I don't know that you should be able to fix a pipe spear by soldering the two halves back together.
> > I feel like most things that will actually take damage aren't really the things that are meaningfully fixable by just adding a lil solder joint.
> > But I'd like to see Kevlar repair added to the tailoring kit, at least.
> 
> Yeah...okay you have a point with that I concede on that point 'w')
> And yeah it is "fiber" so you should be able to repair it with a tailoring kit in theory.

It's not a fiber that can be penetrated by a needle. It's a kevlar fiber _plate_.

Repairing kevlar should be a matter of replacing and attaching new kevlar plates. The question is what holds them in place. 

I think most kevlar plates are held in place by a pouch of some kind, and it would make sense for the tailoring kit to repair it, but I wanted to keep the scope of this PR to just the soldering iron.

Also a matter for another pull: I'm thinking about having a pseudo material called ELECTRONICS which is repaired by solder (and electronic scraps?) using the soldering iron.

**Comment by tenmillimaster** [comment]
> > > Soldering stuff together makes sense in the context of certain crafting recipes, but I don't know that you should be able to fix a pipe spear by soldering the two halves back together.
> > > I feel like most things that will actually take damage aren't really the things that are meaningfully fixable by just adding a lil solder joint.
> > > But I'd like to see Kevlar repair added to the tailoring kit, at least.
> > 
> > 
> > Yeah...okay you have a point with that I concede on that point 'w')
> > And yeah it is "fiber" so you should be able to repair it with a tailoring kit in theory.
> 
> It's not a fiber that can be penetrated by a needle. It's a kevlar fiber _plate_.
> 
> Repairing kevlar should be a matter of replacing and attaching new kevlar plates. The question is what holds them in place.
> 
> I think most kevlar plates are held in place by a pouch of some kind, and it would make sense for the tailoring kit to repair it, but I wanted to keep the scope of this PR to just the soldering iron.
> 
> Also a matter for another pull: I'm thinking about having a pseudo material called ELECTRONICS which is repaired by solder (and electronic scraps?) using the soldering iron.

That's not completely true. Things like a PASGT helmet or Kevlar plates for plate carriers are, as you describe, layers of kevlar that cannot be penetrated by a needle, due to their being held together by a resin.
OTOH, things like soft armor plate carriers (the MBR vest), kevlar door panels, and kevlar vests do not need to be compressed and held together by resin- they absolutely would be repairable, to some degree, by kevlar.

That issue isn't whether *kevlar itself is repairable*, but rather a lack of distinction between layered kevlar cloth armor and kevlar plates. Both are relevant, but only one should really be repairable.



As far as the intent of your PR goes; Soldering doesn't require that the base material of the item being repaired melt at all. It's more of a 'metal glue' sort of application- Heat the two things to be joined and apply a lower melting point metal, such as lead/tin or silver, and it will hold the two things together. The problem here is that the bond isn't *usually* that mechanically strong. Jewelry can absolutely be repaired via soldering- they're typically very low stress items. As other say, a pipe spear could not, as one of the seams would be a weak point.
An electronics style soldering iron is also typically not powerful enough to heat large metal objects to get good results, as the rest of the item tends to wick away the heat, preventing the joints from getting proper adhesion.


As such, I suggest leaving soldering as a valid repair method for items made of lead, copper, gold, and tin. And any other such materials items with low stress usages are likely to be made of.

Proper soldering for larger, more stressed items would need to be done with a blowtorch and a more mechanically sound soldering material, e.g. silver.

**Comment by ampersand55** [comment]
You make some good points and I agree with your suggestion.

**Pull request merged**
