### PR TITLE
Rebreathers rework and general revisit

### LINKED ISSUE #66110: Rebreathers rework
### Is your feature request related to a problem? Please describe.

Currently rebreathers do not work how they are supposed to work IRL. They use charges refillable at any time (instead of switcheable cartridges that can be refilled) and the scrubbing compound is entirely unrealistic, requiring abstract oxidizer powder that can only be made with essentially impossible to produce liquid ammonia. The breathing times per full load are really short, too, at 30 minutes for normal and 60 for survivor diving mask.

IRL rebreathers can be made on two principles: air scrubbing and addition of oxygen/air (basically scuba tank with extra steps) or total oxygen regeneration.

What one needs for each of those methods IRL:

1. CO2 scrubber with air feed, semi-closed: CO2 is filtered out through cartridge with slaked lime and potassium/sodium lye and then diluted with your usual air crammed into a tank (in game rebreather mask has electronics, so air control should be covered). Longer diving times than simple air scuba tanks per volume, but heavy. Main advantages: no requirement for pure oxygen and cheap consumables.
2. CO2 scrubber with oxygen feed, closed cycle: same as previous, but after scrubber air is diluted with pure oxygen. Long diving times. Main advantages: straight upgrade to option 1 if there is access to oxygen concentrator.
3. Oxygen regenerator: CO2 is turned into O2 through cartridge with potassium superoxide. May have a kickstarting oxygen tank. Main advantages: LONG breathing times, compact and light, does not require oxygen concentrator.

### Solution you would like.

How that could be implemented in game:

Make rebreathers only accept magazines of "rebreather cartridge" type (already being implemented in https://github.com/CleverRaven/Cataclysm-DDA/pull/66057). The magazines will have next varieties: 
Scrubbing cartridge - crafted out of a can for scrubbing compound, rubber hoses, small scuba/medium oxygen/pressurised chemical tank.
Extended/double scrubbing cartridge - bigger and bulkier scrubbing cartridges, recommended to be carried in mask because of size. Two tanks, bigger scrubbing compound can.
Regenerator cartridge - regenerator powder can, rubber hoses.

The ready cartridges:

1. Rebreather scrubbing cartridge with compressed air: filled with compound made out of slaked lime and lyes (powdered), requires compression 1 (hand pumps can produce up to 4500 psi/300 bar, so it is enough) to fill the tank with air. Scrubber works for about 2-3 hours with 2-2.5 kg scrubber, air tank duration - about 1.5 hours if using pressurised air (3 liter air tank at 200 bar has effectively 600 l of air, which means about 120 l of oxygen, and 200 l of oxygen lasts for about 3 hours). Dive length is limited by amount of replenishing air. Reloading is done by unloading scrubber mix and recrafting the filled cartridge out of empty cartridge, scrubber mix and with application of pump.
2. Rebreather scrubbing cartridge with oxygen feed: refillable with slaked lime and lyes (powdered), requires oxygen concentrator or makeshift water electrolyzer to fill tank with oxygen. Such cartridge can be used for full capacity of scrubber (2-3 hours). Refillable in same way as air feed: through recrafting.
3. Extended/double rebreather scrubbing cartridges have (almost) double weight and volume, but extend working time by factor of 2x compared to normal ones. Otherwise the same as normal scrubbing cartridge.
4. Oxygen regenerator cartridge: here the fun stuff begins. Potassium superoxide can be made by heating up potassium, the recipe may be made quicker and in bigger batches if survivor has a source of pure oxygen (in form of pressurised tank), Potassium can be made through electrolysis of potassium lye/powder (it was first done in 1807 with voltaic pile, should be possible with modern battery tech, same recipe as sodium essentially). 2 kg of KO2 can release up to 0.676 kg = 473.06 l of oxygen (at atmospheric pressure), giving about 6 hours of diving time. Refilled using a quick recipe (i don't want it being refilled underwater for reasons of KO2-H2O reaction).

### Describe alternatives you have considered.

Stopping suggesting new ideas and begin to work on ones I already suggested (I have got one (or more?) more issue to make now, actually).

### Additional context

Basic rebreather info:

https://en.wikipedia.org/wiki/Rebreather

https://en.wikipedia.org/wiki/Diving_rebreather

Potassium superoxide and data on amount of oxygen 1 kg can produce (replace oxidizer powder with it?):

https://en.wikipedia.org/wiki/Potassium_superoxide

Making KO2 in home conditions:

https://www.youtube.com/watch?v=DrVZrOPkLvM

Exact part of article where it writes how pure potassium was obtained:

https://en.wikipedia.org/wiki/Potassium#Metal

Rebreather dive duration, info given for one tank filled with O2 and other filled with inert gas:

https://www.apdiving.com/en/rebreathers/new-to-ccr/dive-duration/

How much pressure a hand pump can produce:

https://www.airgundepot.com/vault/articles/how-much-psi-can-a-hand-pump-produce/

### PR DESCRIPTION
**Pull request by randomtyper**
#### Summary
Content "Reworks rebreathers"

#### Purpose of change

Resolves #66110.

Fixes inconsistencies/broken stuff regarding rebreathers and rebreather masks.

#### Describe the solution

See relevant issue for more info.

Adds 3 new magazines: 
- [x] 2 soda lime scrubber cartridges;
- [x] Potassium superoxide regenerator cartridge.

Adds 3 new chemicals:
- [x] Soda lime for scrubber cartridges;
- [x] Potassium superoxide for regenerator cartridge;
- [x] Pure potassium for KO2 production.

- [x] Recipes to craft all of those.

Small tweaks to coverage and materials of survivor dive mask. It now covers the whole face, like these masks: https://www.divein.com/diving/full-face-diving-mask/

#### Describe alternatives you've considered

Having rebreathers underwhelming and unrealistic (especially after last gas mask rework, that cut their capacity in half and made the cartridges impossible to refill).

#### Testing

None for now, the PR is not ready yet.

#### Additional context

See relevant issue.

### CODE REVIEW

**Comment by Drew4484** [comment]
Thank you for taking this on! My knowledge was fairly limited for rebreathers, glad to have someone who knows more pick it up.

**Comment by randomtyper** [comment]
> Thank you for taking this on! My knowledge was fairly limited for rebreathers, glad to have someone who knows more pick it up.

I have to say thank you for making the mask cartridges separate. Helps a lot with what I intend to do. Now I gotta finish this PR ASAP, because there was some unfinished stuff in your PR that will directly affect my save.

**Comment by randomtyper** [comment]
@anoobindisguise, can you help with chem crafting recipes? In terms of reviewing them and advising on crafting requirements. I feel like my estimates are really off. And take a close look at sodium recipe if you can, it has some nonsensical stuff in its comments, like 1100 u of lye powder weighing 30 grams. Seems like a VERY old recipe.

**Comment by randomtyper** [comment]
@Maleclypse, sorry for ping, but here I may need your help with this error:
"for material kevlar_layered, 1.000000 isn't a valid multiple of the thickness the underlying material comes in: 4.400000."

Does that mean that if I specify material thickness per part, layered kevlar should be at least 4.4 mm thick?

**Comment by Drew4484** [comment]
> @Maleclypse, sorry for ping, but here I may need your help with this error:
> "for material kevlar_layered, 1.000000 isn't a valid multiple of the thickness the underlying material comes in: 4.400000."
> 
> Does that mean that if I specify material thickness per part, layered Kevlar should be at least 4.4 mm thick? This error did not emerge until I specified protection for survivor divemask to be 2 mm of plastic on eyes and 1 mm of plastic + 1 mm of layered Kevlar for mouth.

You've got the right answer. Any reason to not change it to standard kevlar?

**Comment by randomtyper** [comment]
> > @Maleclypse, sorry for ping, but here I may need your help with this error:
> > "for material kevlar_layered, 1.000000 isn't a valid multiple of the thickness the underlying material comes in: 4.400000."
> > Does that mean that if I specify material thickness per part, layered Kevlar should be at least 4.4 mm thick? This error did not emerge until I specified protection for survivor divemask to be 2 mm of plastic on eyes and 1 mm of plastic + 1 mm of layered Kevlar for mouth.
> 
> You've got the right answer. Any reason to not change it to standard kevlar?

Honestly, not much besides some bash protection. But I think a survivor would add some neoprene there as padding and insulator.

Okay, I think these changes will be reasonable: 
1. Adjust crafting cost and thicknesses of Kevlar to 2 mm (about 36-48 Kevlar sheets);
2. Change layered Kevlar to simple Kevlar;
3. 3 mm plastic for eyes, increase polycarb sheet cost to 6-10;
4. 50% 1 mm neoprene coverage with about 20-30 neoprene patches added as craft requirement;
5. 0,5 mm 75% aluminium from rebreather for mouth (it was used in the craft, where did that metal go?).

Do the similar stuff to the other survivor masks, modernizing them too.

**Comment by anoobindisguise** [comment]
You can technically do "ignore_sheet_thickness": true
But one 4.4mm layered kevlar panel is 16 layers of regular kevlar, ergo one kevlar sheet is 0.275mm. I usually did multiples of 1.1mm, but you could easily round one layer of kevlar to 0.25mm.
No clue about the sodium recipe that's pretty new actually.

**Pull request merged**
