### PR TITLE
starting profession item audit

### PR DESCRIPTION
**Pull request by KeremBabaG**
#### Summary
Balance "profession item audit"

#### Purpose of change
For some while I've been bothered by some oddities regarding the items of starting professions. Stuff like EMTs having 5 painkiller bottles with one aspirin in each of them, or Bride wearing random stockings(like purple polka dot). This is presumably due to the charge removals and extensive addition of variants with this experimental cycle. This aims to solve the singular item cases and make some starting clothing more "appropriate".

#### Describe the solution

- Gave every profession that starts with rolling tobacco a full bag of them. Same thing with marijuana. Lowered the amount of rolling paper to 20 to accomodate it.
- Professions that start with aspirin now do so with a bottle of 20 pills. Something similar with antibiotics for the combat medic. 
- Adjusted the amount of cornmeal(1 to 4) and salt(1 to 100) of the reenactor. 
- Professions that started with cigs now do so with a pack full of them.
- Specified the variant of stockings for some professions that used them.
- Hacker now has a bottle of 10 caffeine pills and 3 caffeine gums, instead of one for both.
- Grenadier has a m4 instead of a m17 as well as a mag pouch and 2 magazines for it, because they do have rifles appearently.
- Hobo and vagabond have a can of two canned beans instead of one.
- Motorized police officers have now additional vehicles(4) and mechanics(2) skills, as well as a driving proficiency. Their description and name states as such.
- Removed basic engines proficiency from RV hunter and heist driver, I did not exactly now what that proficiency entailed when adding them.
- Crazy cat lady now has all of her cat food in a single bag. Increased K-9 officer's amount of dog food(1 to 2). Dog lover now has his dog food in a single bag, and has more(2 to 4).
- SWAT units and riot cop has completely black tactical pants, instead of random colors.
- Student has jeans instead of black cotton fabric pants. And removed their crop top as well (which was there along with t-shirt for some reason?).
- Increase the amount(1) of both pizzas of the pizza boy to 4, as they were a victim of the charge removal as well. Change his description as well, since that cryogenics lab thing doesn't fit the current lore.

#### Describe alternatives you've considered
Remove the weed pack group and give the professions concerned a singular blunt instead, like with the musician profession.
Other than that idk.

#### Testing
Professions indeed start with more sensible clothing and item quantities

#### Additional context
Sorry liberals no more pansexual stockings for your assasin

### CODE REVIEW

**Comment by KeremBabaG** [comment]
Also grenadiers seem to lack a rifle. Idk how it is in america but grenadiers here get a launcher AND a rifle. I assume it is the same over there?

**Comment by Kantonine** [comment]
Noooooooooo not the pride stockings for my reenactors! /Jk

As for the Grenadier, that is definitely a valid point, I doubt that the Vietnam war method of having a seperate guy with the bloop tube still applies

**Comment by Hyperseeker** [comment]
> Also grenadiers seem to lack a rifle. Idk how it is in america but grenadiers here get a launcher AND a rifle. I assume it is the same over there?

The [US Army grenadier guide](https://usacac.army.mil/sites/default/files/publications/17965.pdf) does indeed mention the M4, calling it a secondary weapon to the M320 launcher. It also discouraged mounting the M320 under the barrel of the rifle, instead encouraging the standalone, buttstock-equipped configuration.

**Comment by Cormac1991** [comment]
the park ranger spawns with nothing but the pistol now even though it still shows all the items as before.

**Comment by KeremBabaG** [comment]
> the park ranger spawns with nothing but the pistol now even though it still shows all the items as before.

are you sure? just botted up the game and started with the park ranger and he had all the items listed.

**Comment by KeremBabaG** [comment]
And that's it for now. I wanted to give medical professions some hospital scrubs, but it seems that they are not in the game. Maybe I can add those in a future PR? :)

**Pull request merged**
