### PR TITLE
Best

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
I have moved many of the guns and ammo entries into their own JSON files.

### CODE REVIEW

**Comment by kevingranade** [comment]
Commit error, you added files but they're empty.  It's always good to look over your PR diff before clicking the "create PR" button.
Also, are we really doing one ammo type per file?  Aren't most of them going to have a single entry?

**Comment by BorkBorkGoesTheCode** [comment]
Which files are empty? Most of the files on my end have at least one entry.

**Comment by karols146** [comment]
I just see only one empty line too.
Git can be tricky sometimes.

**Comment by BorkBorkGoesTheCode** [comment]
Oops. I PR'd the wrong branch.

**Comment by mugling** [comment]
Does this PR produce output consistent with the other migrations I've done involving those items?

**Comment by BorkBorkGoesTheCode** [comment]
Was it the ammo/9x18.json?

**Comment by mugling** [comment]
All of the files are empty

Currently the split between `ammo.json` and the `ammo/` subdir also identifies which items still have to be migrated (added to item groups etc). There's a lot more to it than copy/paste.

Ideally the guns should for each ammo type should be updated concurrently. This has even more migration details (adding magazines, dropping obsolete flags and fields).

**Comment by BorkBorkGoesTheCode** [comment]
Which flags are obsolete?

**Pull request closed without merging**
