### PR TITLE
Change the color system from strings to enum

### PR DESCRIPTION
**Pull request by Coolthulhu**
As @BevapDin pointed out in #12097 the color system uses strings for color ids, which slows down drawing considerably.

Since the colors are hardcoded anyway, there is no gain from using strings here.

Another really bad practice in color drawing system was lookup for a map key by iterating the entire map. This happened whenever an inverted or highlighted color was to be drawn.

Here I rewrite pretty much the entire color system except for the custom color manager gui. Colors can be addressed in 3 ways: by name (slow), by color value and by id (which is also an index to array). The defines on top of `color.h` have been rewritten to use the id. Highlights are precalculated.

This is WiP because I haven't fully implemented custom colors, but it works properly with the default ones.

### CODE REVIEW

**Comment by kevingranade** [comment]
colors not right

**Comment by Coolthulhu** [comment]
Are those on default settings? I tested only on Windows where it worked, but maybe I'll need to test independently on Linux if the colors are somehow represented differently enough for it to matter.

**Comment by Coolthulhu** [comment]
If not default, can I get a test config? I'd compare it against how current master branch renders it.

**Comment by kevingranade** [comment]
Almost certain it's default for linux, I'll double-check when I can.

**Comment by Voker57** [comment]
Colors are fine on linux here.

**Comment by kevingranade** [comment]
Whoops, my settings from originally testing custom colors were still there, after resetting them I'm not seeing any problems.

**Comment by kevingranade** [comment]
I'll pull this with my next batch, waiting until you're done with your current batch.

**Comment by Coolthulhu** [comment]
Done with my batch for now

**Comment by Rivet-the-Zombie** [comment]
colors not right

These colors make my teeth itch. I'm guessing this PR also allows for color combinations that don't make us colorblind folks feel like we're going blind?

**Comment by Coolthulhu** [comment]
The PR does not change color display, only the speed of displaying and internal structures used for display.

**Comment by DavidKeaton** [comment]
is the game Breakout?

**Pull request merged**
