### PR TITLE
Increased accuracy of Rivtech guns

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Increased accuracy of Rivtech guns

#### Summary

SUMMARY: Balance "Increased accuracy of Rivtech guns"

#### Purpose of change

By my obseration on Rivtech guns I've noticed few things:
1) Rivtech guns, despite of being futursitic prototypes has same accuracy or sometimes even less accurate than modern counterparts. Look for examples here: https://github.com/CleverRaven/Cataclysm-DDA/pull/26573
2) Players have tendency to use modern non futuristic guns  even for endgame. If it gets job done why bother with Rivtech guns with special and harder to find ammo?

So now I propose to give player one more reason to bother about Rivtech guns- now they are more accurate than modern counterparts.
Also there is no extreme craziness. Rivtech wepons still less accurate than laser rifle.
But now Rivtech wepons will not only more damaging and reliable but also noticable more accurate than modern analogs. With few exceptions.

I've tried to set logic:
comparable  modern loaded gun dispersion -60. Sometimes this rule is broken than it is too hard to find analog or than accuracy become too insane for weapon class. But mostly difference is 60. 
It is enough to be noticable but at the same not overhelming. After all I don't want to break logic like making Rivtech AR more accurate than laser rifle or making Rivtech pistols more accurate than modern rifles e.t.c.

So let us go.
gun_duspersion+ammo_rispersion=total_dispersion->new_gun_duspersion +ammo_rispersion=new_total_dispersion **VS** Comparsion gun data.

Here is dispersion changes:
Shotguns. Base ammo has 0 dispersion.
* RM120c shotgun: 345+0=345->285+0=285 **VS** Remington: 870 345+0=345 . Now it is most accurate pump action shotgun in the game.
* RM20 autoshotgun 390+0=390->335+0=335 **VS**  Saiga-12: 395+0=395. Compared to saiga becacuse ingame non futuristic heavy automatic shotgun is modifed custom monstosity.

Gunmod shotguns:
* RM121 aux shotgun: 400+0=400 -> 320+0=320 VS masterkey shotgun: 330+0=330. Now it has a tiny better accuracy than masterkey shotgun. I dont won't to put its accuracy higher. But it certnatly should be upped since it is using rare Rivtech ammo.

Pistols. Base ammo has 60 dispersion.
* RM216 SPIW 260+60=320-> 220+60=280 **VS** Calico M960: 280+60=340.  Now it is most accurate light  carbine in the game.
* RM232 IDW 440+60=500-> 280+60=340 **VS** L39 (Leadwork) 340+60=400.  Now it is most accurate autopistol in the game. Change is so dramatical because of existance of Leadworks 9mm autopistol that is quite accurate. I know that Leadworks autopistol is not exacly modern weapon but it is using normal ammo and it is only comparable pistol. Also Leadworks do not provide that futuristic wepons as Rivtech.
* RM228 PDW: 450+0=450-> 400+ 0 = 400 **VS** 12 gauge pistol:  600+0=600. Hard to compare, because there is only one non futuristic shotgun pistol in the game and it is hand made.

Rifles (and occasionaly Magnum and SMG). Do not forget that base 8x80 ammo has 75 dispersion.
* RM11B scout rifle - not changed. 10 +75 = 85 -> NO CHANGE  **VS** Remington 700: 90 +10= 100. It is already most accurate marksman rifle in the game. No change.
* RM88 battle rifle 50 +75=125 ->30+75=105 **VS** M14 EBR-RI: 110+15= 125  **VS** FN SCAR-H: 150+15=165  . Now it has accuracy is comparable with modern sniper rifle. And now it is more accurate than m14 ebr.
* RM51 assault rifle 90 +75 = 165 ->50 +75 = 125 **VS**  Steyr AUG: 140+30 = 170. Now it is noticable more accurate than any AR in the game.
* RM614 LMG: 140+75=215-> 70 +75=145 **VS** M249: 200+30=230. Original accuracy was better than Rivtech HMG. Let it be that way.
* RM298 HMG: 180+75 = 255 ->90 +75=165  **VS** M240: 200+15=215 . Compared to medium machine gun.
* RM2000 submachine gun 120 +75 = 195 -> NO CHANGE **VS** TDI Vector: 280 +50 =320. It is indeed smg not carbine. Very accurate for SMG already.
* RM103A automagnum 200 +75=275->175+ 75= 250 **VS** S&W 500: 280+30= 310. It was still most accurate magnum in he game. Accuracy was increased a little.

Flamethrowers:
* RM451 flamethrower: 240+0 = 240 -> NO CHANGE  **VS** flamethrower:300+0=300. It has better accuracy than usual flamethrower and using non rare ammo. So there is no change.

Grenade launchers:
* RM802 grenade launcher: 150 +30 =180 - > 140 +30 =170 **VS** Mark 19 grenade launcher: 180+30=210 **VS** M79 launcher: 150 +30 =180.   I don't want to tranform it to sniper grenade launcher or something. But accuracy increased a tiny bit to make it slightly more accurate than M79 launcher.

.22 guns:
* RM360 rotary carbine: 280+60=340-> 220+60=280 VS American-180: 280+60=340 .  American-180 and RM360 both SMG. But at the same time RM360 rotary carbine  has same accuracy. Accuracy increased despite of using common ammo.

Laser weapons:
No change. They are using UPS. it is not rare ammo. And they are very very accurate already.

**Do not forget that you should compare dispersion of guns with loaded ammo. It shuffles things a lot. All types or Rivtech ammo has quite high dispersion values. Especially 8x80.**

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
@ZhilkinSerg 
It is definetely not bugfix. Rebalance mostly.

**Comment by ZhilkinSerg** [comment]
You've selected Bugfixes category for summary line.

**Comment by Firestorm01X2** [comment]
>You've selected Bugfixes category for summary line.

Sorry. Fixed.

**Comment by Mecares** [comment]
What are their weaknesses now? I hope they are not  superior in every aspect now.

**Comment by AskaHope** [comment]
They are futuristic guns, an endgame feature, the latest of technology, so yeah... They must be superior

**Comment by Mecares** [comment]
I would not go for better than the currently best, maybe they could use a buff to be as precise as the current very precise guns but making them better would make them an absolute no brainer choice.

**Comment by Firestorm01X2** [comment]
>I would not go for better than the currently best, maybe they could use a buff to be as precise as the current very precise guns but making them better would make them an absolute no brainer choice.

It is uncommon guns with uncommon ammo. It not something you get from gun store (in fact sometimes you get it there but it is civilian guns, not rifles).

In that case laser rifle is no-brainer too.

**Comment by Firestorm01X2** [comment]
Ok. I've updated my cheat sheet. And in fact it bring new question.
How to read it. Digints is dipersion. Lower it is - higher weapon accuracy
Base weapon dispersion + ammo dispersion = gun dispersion

In fact Rivtech wepons are not that innacurate if we making comparsion more precisely.

**Comment by Firestorm01X2** [comment]
Anyway. Overall idea of incrasing accuracy of Ruvtech gun still make sense to make this guns much more usefull and worth using.

**Comment by Firestorm01X2** [comment]
I need to somehow standrtize changes. Let's say it should be calculated by formula:
loaded modernd gud dispersion - 50.
There will be few exceptions. But mostly I''ll try to aim at something like this.

**Comment by Firestorm01X2** [comment]
I've tried to set logic:
comparable  modern loaded gun dispersion -60. Sometimes this rule is broken than it is too hard to find analog. But mostly difference is 60.

**Comment by Firestorm01X2** [comment]
No still WIP. I should look into few ithers rivtech guns.

**Comment by Firestorm01X2** [comment]
In fact accuracy superirority of Rivtech guns  will not be as big as you may expect. But now Rivtech guns are truly superior. So you have more reasons to use rare Rivtech ammo.

Ready.

**Comment by Xion350** [comment]
Considering you can't handload Rivtech guns its a good idea.  I don't think the Bootleg 8x40mm Caseless is available anymore.

**Comment by Firestorm01X2** [comment]
Jenkins rebuild

**Pull request merged**
