### PR TITLE
turn bare materials into objects

### PR DESCRIPTION
**Pull request by TheGoatGod**
#### Summary

Infrastructure "JSON: turn materials represented by a string into objects"

#### Purpose of change

some materials are still bare this script fixes them

#### Describe the solution

run the script

#### Describe alternatives you've considered

leave as is, currently still works

#### Testing

none needed as this is seen all over.

### CODE REVIEW

**Comment by int-ua** [comment]
Do you plan on trying to merge scripts with #46964 and #47015 ?

**Comment by TheGoatGod** [comment]
> Do you plan on trying to merge scripts with #46964 and #47015 ?

how do you mean merge? if you mean 1 py no

**Comment by int-ua** [comment]
> > Do you plan on trying to merge scripts with #46964 and #47015 ?
> 
> how do you mean merge? if you mean 1 py no

Ok, then can you please move these 3 scripts into a separate PR? I think they should be reviewed together and not with the JSON data changes. It would be fine if it was only one script but since you are adding scripts that are just a slightly different copies of each other I believe they should be grouped in one PR.

**Comment by actual-nh** [comment]
> Ok, then can you please move these scripts into a separate PR? I think they should be reviewed together and not with the JSON data changes. It would've been fine if it was only one script but since you are adding scripts that are just a slightly different copies of each other I believe they should be grouped in one PR.

It would be easier to review the JSON data changes if the likely-final version of the script had already been run (no worries about getting overwritten). For items, I've already spotted at least a few that could use "str_sp" instead of "str", for instance.

**Comment by TheGoatGod** [comment]
> > > Do you plan on trying to merge scripts with #46964 and #47015 ?
> > 
> > 
> > how do you mean merge? if you mean 1 py no
> 
> Ok, then can you please move these scripts into a separate PR? I think they should be reviewed together and not with the JSON data changes. It would've been fine if it was only one script but since you are adding scripts that are just a slightly different copies of each other I believe they should be grouped in one PR.

yeah I don't mind them being different, they do diffrent things, only part you really have to look at is below, then yeah i would say they are the same, but if you only look at this part, and compare. they are not the same.

```
# We only want JsonObjects
            if type(jo) is str:
                continue
            if type(jo.get('material')) == str:
                material = jo['material']
                jo['material'] = [material]
                change = True
            if type(jo.get('ammo')) == str and jo.get('type') == 'ammo':
                ammo = jo['ammo']
                jo['ammo'] = [ammo]
                change = True

**Comment by TheGoatGod** [comment]
> > Ok, then can you please move these scripts into a separate PR? I think they should be reviewed together and not with the JSON data changes. It would've been fine if it was only one script but since you are adding scripts that are just a slightly different copies of each other I believe they should be grouped in one PR.
> 
> It would be easier to review the JSON data changes if the likely-final version of the script had already been run (no worries about getting overwritten). For items, I've already spotted at least a few that could use "str_sp" instead of "str", for instance.

i think this is a reply to my bare name pr #46964

**Comment by TheGoatGod** [comment]
the py here need edited/updated to actually do only ammo but I don't think it matters

**Comment by int-ua** [comment]
The summary line should be
```
Infrastructure "turn bare materials into objects."
```

**Comment by TheGoatGod** [comment]
don't believe that its on my end why continuous-integration/travis-ci/pr is failing

**Comment by actual-nh** [comment]
It isn't; see #47022.

**Pull request closed without merging**
