### PR TITLE
Nyctophobia

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Content "Added nyctophobia trait"

#### Purpose of change
AKA fear of dark. Add trait for RP and gameplay.

#### Describe the solution
- Players with nyctophobia can enter tiles with `cloudy` and `dark` light levels. Tiles with `very dark` light level are off-limits to them, unless player character is running or took a xanax.
- Players have a chance to see monsters (represented as hallucinations) in very dark tiles in 5-tile radius around the player, even if players themselves are standing in lit tile. The chance to spawn hallucinations is 2% per turn if player is standing in lit tile, and 10% if player is standing in very dark tile.
- Players have a chance to hear auditory hallucinations while staying in very dark tiles. The chance is 50% every 30 seconds.
- Players suffer several mental and physical effects if they are standing in very dark tiles. 2% chance per turn for every effect, i.e. they can happen all at once. Among them:
- - shaking hands (penalties to dexterity and strength);
- - trembling legs (player will fall down);
- - sudden suffocation attack (loss of stamina);
- - paralyze by fear (loss of turns).
- All negative effects are alleviated if player has taken xanax.

#### Describe alternatives you've considered
- Instead of strict blocking of entering very dark tiles, use a chance.
- Add more effects.

#### Testing
Got nyctophobia. While standing in lit tiles, looked at very dark corners. Eventually hallucinations monsters appear in these corners. Tested the same while standing in very dark tiles.
Walked over very dark tiles. Eventually was knocked down, got shaking hands, lost some stamina, got paralyzed for few turns.

#### Additional context
None.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
@Venera3 done in [c97e8ff](https://github.com/CleverRaven/Cataclysm-DDA/pull/59061/commits/c97e8ffe66cec5cb7ad46ba9de7e39984c8a79ff).

**Comment by NetSysFire** [comment]
I like this, it has a good amount of potential but I am unsure about the point cost. Raiding houses at night becomes much more dangerous this way and the dark is present almost everywhere.
I do not have a strong opinion on this but I would potentially increase the points you gain from taking this trait.

Also, can you work in the dark (e.g making flour) by wearing a blindfold? This seems like a fun edge case.

>it would work great as an on-attack effect from shadows and such.

Or portal storm effects, e.g when the sun is snuffed out like a candle and you fail an int check.

**Comment by Night-Pryanik** [comment]
> I do not have a strong opinion

Me neither. I'm open to suggestions.

> Also, can you work in the dark (e.g making flour) by wearing a blindfold?

Yes, when you're wearing a blindfold, the tile you're standing on has the same light level as your surroundings have.
изображение

**Comment by x-qq** [comment]
In my opinion this is incomplete if added without:
* ways to alleviate the effects temporarily: anti-depressants, diazepam, beta-blockers
* ways to eventually treat the effect permanently: meditation, therapy (+others implant/mutation/etc-based ?)

**Comment by Night-Pryanik** [comment]
> ways to alleviate the effects temporarily: anti-depressants, diazepam, beta-blockers

I'm not a doctor, I'm not sure which in-game medication should be used. Is it feasible IRL to alleviate the effects at all? @I-am-Erk ?

> ways to eventually treat the effect permanently: meditation, therapy (+others implant/mutation/etc-based ?)

In short, I'm not interested in implementing it. We have tons of traits which should be "curable" in theory (the most known example is Illiterate trait), and I don't want to be the one who breaks the current situation.

Personally I consider this trait as a "challenge" and "game changing" trait which should be left with character for all his game duration with no way of removing it permanently.

**Comment by x-qq** [comment]
> > ways to alleviate the effects temporarily: anti-depressants, diazepam, beta-blockers
> 
> I'm not a doctor, I'm not sure which in-game medication should be used. Is it feasible IRL to alleviate the effects at all?


```
Most phobias are curable, but no single treatment is guaranteed to work for all phobias. In some cases, a combination of different treatments may be recommended. The main treatment types are:

self-help techniques
talking treatments
medication
```

```
There are 3 types of medication recommended for treating anxiety:

antidepressants
tranquillisers
beta-blockers
```

https://www.nhs.uk/mental-health/conditions/phobias/treatment/

**Comment by NetSysFire** [comment]
Perhaps by getting a night vision bionic or pair of nv goggles.

**Comment by liminalRoar** [comment]
This sounds really fun. Makes me think of a feature. Sanity. This could be in base game or perhaps better suited for a mod. A sanity meter would track the characters mental state (could be an unseen value but probably best left visible to the player). A loss of sanity would accumulate from confrontation with phobias - fears the character can start with (or develop and even possibly cure).

Fears could include arachnids, cockroaches, the dark, water, heights, wild animals, zombies, driving, etc. Fear levels could range as well, from "slightly scare of _x_", "scared of _x_", "terrified of _x_", "deathly afraid of _x_". The sanity meter would drop with exposure to fears, falling faster if more afraid of them. If a character is afraid of spiders and gets attacked by one, this can cause their fear to worsen while killing spiders could have a small chance of lowering this fear.

A character would not normally develop fears while playing. These would be chosen at character creation. Certain enemies in game would be able to lower your sanity. Some ethereal monsters would even be able to put fears in the character that would wear off over time (could last 5 min or hours).

The sanity meter would in general be split into multiple sections with worsening effects likely a meter of 0-100 sanity.

- 100% would be great - no effects.
- 80-99% would be good - no effects. possibly occasional auditory illusions (slight paranoia).
- 60-80% would be okay sanity - some auditory and visual hallucinations. 
- 40-60% would be bad sanity - frequent hallucinations, panic attacks, loss of focus,
- 20-40% terror - things are getting worse.
- 0-20% pure insanity - loss of touch with reality. Nothing can be trusted, not your map, most of your HUD would be questionable. It is crazy as we have it now turned up to 11. Possibility of hurting yourself in actions (movement, attacking, etc).

Example for the fear of dark: the character CAN enter the dark unless their sanity is already low. The sanity meter will fill up in darkness (slowly with regular dark, very fast with extreme dark). Being in lit areas will raise their sanity meter slowly but faster in bright light. (even better would be that sanity raises faster when the character cannot see the dark, if they are in a basement with just a phone light, the dark tiles around them keeps sanity from rising much).

**Comment by RelMayers** [comment]
What about performance? Does this affect it?

**Comment by Night-Pryanik** [comment]
> What about performance? Does this affect it?

I didn't notice any impact on performance.

**Comment by Night-Pryanik** [comment]
Ok, I added Xanax as a medication to fight the nyctophobia.

**Comment by Inglonias** [comment]
I like the concept, but it seems a little excessive for two points. Being completely incapacitated in the dark is a really big deal. Either tone down the debuffs or bring up the point cost.

**Comment by Night-Pryanik** [comment]
While I don't agree that you become "completely incapacitated" in the darkness with the addition of way to alleviate the debuffs with xanax (take one pill - and you're completely protected from all debuffs), as I said, I can  increase the cost to any value - just name it.

**Comment by AtomicFox556** [comment]
I don't think completely preventing characters with this trait from entering dark tiles is a good idea.

First problem is that it often can be circumvented in many ways, such as closing all the windows if the trait prevents you from going into a dark basement, or turning off your sources of light if you're unable to go outside at night.

Second problem is that this can potentially create weird edge cases such as 1-2 tiles between light sources placed in an otherwise dark place being impassable. Unlikely to be a problem right now

Third problem is that the character can *potentially* actually have a very good reason to enter the darkness, such as fleeing from fire that is consuming the building if the character happens to have both nyctophobia and pyrophobia (in case the latter is ever implemented as well).


I'd also add a severe morale penalty that starts right when the character enters a dark tile, and ends once they enter a non-dark tile.

Regarding using a blindfold to circumvent this: I'd apply the same effects as well if the character is blind no matter the actual light level, which can represent them being afraid of their light source going out if they can't see any light (yes, even if they're outside during the day; phobias aren't a rational fear after all).

**Comment by I-am-Erk** [comment]
I'd suggest making hallucinatory sounds more common than visual monsters, because that will tend to mess with players more directly.

**Comment by Night-Pryanik** [comment]
> I'd also add a severe morale penalty that starts right when the character enters a dark tile, and ends once they enter a non-dark tile.

Adding morale penalty was my first intention, but I quickly discarded this idea. Morale mostly matters for skill gaining, and in the darkness you simply can't do most things to raise your skills. Morale penalty which works only in darkness is useless.

@AtomicFox556 all in all, if not direct ban on moving into very dark tiles, what do you suggest to replace it with?

**Comment by Inglonias** [comment]
> > I'd also add a severe morale penalty that starts right when the character enters a dark tile, and ends once they enter a non-dark tile.
> 
> Adding morale penalty was my first intention, but I quickly discarded this idea. Morale mostly matters for skill gaining, and in the darkness you simply can't do most things to raise your skills. Morale penalty which works only in darkness is useless.
> 
> @AtomicFox556 all in all, if not direct ban on moving into very dark tiles, what do you suggest to replace it with?

Cut speed in half, perrhaps?

**Comment by Night-Pryanik** [comment]
> Cut speed in half, perrhaps?

This might be good for gameplay reasons, but I simply cannot imagine why would character suddenly starts moving two times slower after entering darkness? Because he's afraid and tries to move slower in order not to accidentally bother monsters living in darkness?

**Comment by Inglonias** [comment]
I'm apiphobic IRL,, and I'm quite hesitant to go into areas with bees. That said, if I absolutely have to, I'm in and out as fast as possible.

So maybe forbid walking through very dark areas, instead forcing you to run? I'm just spitballing here.

**Comment by AtomicFox556** [comment]
> Adding morale penalty was my first intention, but I quickly discarded this idea. Morale mostly matters for skill gaining, and in the darkness you simply can't do most things to raise your skills. Morale penalty which works only in darkness is useless.

Well, it's in addition to the current effects, even if it ends up being a very minor effect. And it may indeed matter, in that you're going to learn fighting skills much slower if you actually try to fight in darkness. Negative morale by itself can give stat penalties as well.

> @AtomicFox556 all in all, if not direct ban on moving into very dark tiles, what do you suggest to replace it with?

Probably just a warning that requires player to confirm moving into a dark area. If you're talking about more severe effects in general, then rarely, actual fainting involving loss of consciousness (rather than just falling down) could also happen.

**Comment by I-am-Erk** [comment]
I agree that fully blocking movement in the dark isn't in the spirit of the game. I think forcing the player to sprint is a really fun idea actually.

**Comment by Night-Pryanik** [comment]
> Negative morale by itself can give stat and speed penalties as well, last I checked.

Wow, that's new to me. Could you point me to direction where to check this?

**Comment by AtomicFox556** [comment]
> Wow, that's new to me. Could you point me to direction where to check this?

I've just checked it myself. Well, the effect of negative morale is there but it turns out to be very difficult to get major debuffs from it. For instance, this is the result of a character with Bad Temper and no Cannibal or Psychopath traits eating four misshapen fetuses in a row. In fact it probably should be stronger, but that's not relevant for this PR.

image

image

**Comment by liminalRoar** [comment]
Not to promote my ideas too much, but i do think my solution regarding phobias could be a relatively realistic but fun one. Made a separate issue for it (#59074) but i will summarize the main points here that relate.
-A new (possibly hidden) player value for sanity. This will trend and remain 100% usually but will lower when engaged with a fear.
-As sanity drops a new status effect, _panic_, will develop. Panic can lower accuracy, focus, and many other effects. It will go away pretty quick as sanity returns.

The distinction between sanity and panic is important because panic is just 1 effect the loss of sanity brings, but it is a very important one with fears. In this case being in the dark would lower your sanity and returning to light would raise it. When sanity worsens auditory and eventually visual hallucinations can happen, with increasing strength. In the very worst cases with no sanity left, self injury could possibly happen.

My main reason for wanting a system like this is it can be applied to other things. Adding new fears, like the fear or heights or water would work great where sanity drains up high or as you are swimming. This could also work when certain creatures, like spiders are seen or engaged with. And certain otherworldly enemies should probably drain sanity slowly. Certain places could even have this effect as naturally being terrifying.

Also proposed a couple traits - afraid and fearless - which would affect how quickly sanity drains or could lessen or worsen effects. (along with a lot of other proposals i wont go into here)

I do like most of the ideas here though, just my thoughts on how this could be expanded to work with other ideas.

**Comment by Night-Pryanik** [comment]
Ok, now restriction to enter very dark tiles is only applicable to `walk` movement mode. To force yourself to move into very dark tiles, players must switch to `run` movement mode (and face with dire consequences of staying there).

**Comment by AtomicFox556** [comment]
> Ok, now restriction to enter very dark tiles is only applicable to `walk` movement mode. To force yourself to move into very dark tiles, players must switch to `run` movement mode (and face with dire consequences of staying there).

From reading the code, I think it still wouldn't prevent player from switching movement mode to running, and then immediately switching it to something else (such as walking) right after they enter the darkness.

**Comment by Night-Pryanik** [comment]
Fixed. Now you can only run through very dark tiles (or take a pill). Walking through very dark tiles if forbidden.

**Pull request merged**
