### PR TITLE
Mods "Craftable Weapons Pack - Fixed Red Dot Sight recipe"

### PR DESCRIPTION
**Pull request by Xpyder**
Summary
SUMMARY: Mods "Craftable Weapons Pack - Fixed Red Dot Sight recipe"

Purpose of change
an error in the code made it require BOTH Integrated toolset and plastic mold

Describe the solution
Now it requires EITHER integrated toolset or plastic mold

Describe alternatives you've considered
It's possible it was intended to require both, but IRL the recipe isn't that hard (if you have access to a laser pointer) and based on the layout of the section it seems like it was intended as an Or not an And but had misplaced brackets.

Mod owner can feel free to refuse/revert if my assumption is incorrect.

Additional context
Here's example of real makeshift red dot sight: https://www.youtube.com/watch?v=03j7lLSN82s

Note: it's been a while since I did one of these, if I messed it up let me know what I did wrong and how to fix it (kindly please)

### CODE REVIEW

**Comment by Fris0uman** [comment]
But integrated toolset and plastic mold are completly different ...
I mean as far as I understand plastic mold is used to mold plastic that you have "melted" first by using hotplate or integrated toolset, no ?

**Comment by Rivet-the-Zombie** [comment]
Heat is a separate requirement in the recipe already.

**Comment by Fris0uman** [comment]
True, sorry I missed that part.
But then I don't get what is the integrated toolset for ? 
`"Surgically implanted in your hands and fingers is a complete tool set - screwdriver, hammer, wrench, hacksaw, wood saw, boltcutters, drill and heating elements.  You can use this in place of many tools when crafting."`
What part of that can be used instead of a platic mold ?

**Comment by Xpyder** [comment]
> What part of that can be used instead of a plastic mold ?
No idea.  I was just fixing what seemed to be a coding mistake on the part of the developer, not contest the tools they chose.
There's a bunch of other issues with that mod I'm not interested in fixing, I was mostly just cleaning my coding talons so they don't rust.

On a side note I would be interested in seeing an adjusted makeshift red dot sight added to the makeshift items mod, it doesn't seem like it would be terribly unbalanced, just make it slightly worse than the real one.  I'm not even positive RDS needs a laser, you might be able to manage with an led since a properly polished sight would be semi reflective and should achieve the same thing.

**Pull request merged**
