### PR TITLE
Add science card reader to open Lab from inside

### PR DESCRIPTION
**Pull request by Gabriel-SE**
There are plenty of creative ways to get out from Challenge-Lab but I think most players are expecting to find a science id card and use it to open the locked lab from inside.

### CODE REVIEW

**Comment by KA101** [comment]
Hmm.  Makes sense from the realism angle (though would people then want to swipe a card to close the doors?), though I'm kinda fond of the sealed door.  Any other opinions?

**Comment by Gabriel-SE** [comment]
> though would people then want to swipe a card to close the doors
I'm thinking about that too, but science card reader consume player's science id card, and since it's quite rare, player will want to conserve that resource.

**Comment by KA101** [comment]
>player will want to conserve that resource

Known, though some folks have had 10-20 of 'em and far less labs than cards.

**Comment by Rivet-the-Zombie** [comment]
I like this.

**Comment by Gabriel-SE** [comment]
If we want player to open / close the lab's metal door at will, I think it's better if we make the card reader change the terrain from t_door_metal_locked to t_door_metal_c.

**Comment by KA101** [comment]
That's a reasonable option, but I'm OK merging this more-or-less as is.

**Comment by Gabriel-SE** [comment]
I'll make a separate PR for the metal door issue.

**Comment by kevingranade** [comment]
One question, do science ids usually turn up inside the lab? If so this seriously undermines the "trapped in a lab" scenarios.

**Comment by KA101** [comment]
IME, no, they don't, but I haven't been seriously lab-diving in a while.

**Comment by Gabriel-SE** [comment]
Well, I make this PR in a hurry, but here's another placement alternative for science card reader.

Image of Lab

A = add another science card reader, original position
B = no additional card reader, but moves the position from the original

**Comment by KA101** [comment]
After review, this'd break the Lab Challenge so not mergeable.  Sorry, Gabriel-SE.

**Comment by kevingranade** [comment]
I'm fine with this approach, but the scenario itself needs to be adjusted to take this change into account.
If you just make this one change, the trapped scenario suddenly becomes much easier on average.
Either access to science id cards needs to be regulated somehow, or getting to the exit needs to be more involved, or both.

**Pull request closed without merging**
