### PR TITLE
[CR] Sugar Recipes Overhaul

### LINKED ISSUE #74547: Allow Fruit Sugar Refining using Potassium Hydroxide
### Is your feature request related to a problem? Please describe.

While looking at the recipe for refining sugar from various fruits, i noticed that the recipe uses sodium hydroxide lye powder only, with no option to use potassium hydroxide powder instead. This makes the acquiring of sugar from fruit difficult.

### Solution you would like.

Allow Potassium Hydroxide to be used in place of Lye powder, possibly needing more to achieve the same results

### Describe alternatives you have considered.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pabblusansky**
#### Summary
Balance "Sugar recipes changes"
#### Purpose of change
Based on #74547 suggestion and @AudBobb enormous contribution. Fixes #74547 
Two sugar recipes overhaul, and the minor fixes for other methods.
Now refining sugar from sugar beets or from sweet fruits doesn't involve using lye powder (and of course it doesn't need the chemical proficiency anymore). The idea of removing lye powder is making the recipe more post-apocaliptic friendly, as we aren't going to whiten the sugar in the home conditions. (@AudBobb: The hydroxide is mainly for the cosmetic whitening of the sugar, and the removal of impurities that actually affect the sugar quality comes from the incredibly fine filtering of the sugar water that industrial facilities are capable of. At home, sugar is going to have some impurities due to this, but should be a perfectly valid substitute for factory-produced sugar. Other changes involve minor tweaks for old recipes (changed charge value) however, at this moment,  I don't touch them because I think the player still needs some low-grade recipes to obtain sugar: from processed items, from candies.  **Now,** refining sugar creates an intermediate item, and the player could obtain the sugar after 2 weeks of the active process of crystallizing!

#### Describe the solution
The math of changes is from real-life example of refining sugar (described in my previous PR: #77126):"From 5lbs of beets he started with, he produced around 1lb of sugar.", we have a yield rate of 1:5. 
Other important changes are:
- Now both recipes to refine sugar are not auto-learned but read from the "Food Fashions for Young Moderns" book.
- Refining sugar using fruits now requires 5 lvl of cooking. Added juice pulp byproduct. (3 u*0.10 L = 0.30 L, because from 0.5 kg(2 units of some fruit), approximately 0.3 kg of pulp would remain (~60% of the input weight), ).
- "The crystallization process takes around 2 weeks." ---> Now the recipe creates an intermediate item named "crystallizing sugar", which upon activation after 2 weeks gets us the sweet, sweet sugar.
- Added the cut proficiency for both fruit and sweet beets recipe because it would fasten the processing of fruits and the sweet beets at the start of the recipe
- Added the tool quality requirements for both recipes: 1 lvl of container, 2 lvl of cut, 2 lvl of boil, 2 lvl of filter, **screw press**
-  Added fruit juice as a component for fruit sugar recipe
- Minor tweaks
#### Describe alternatives you've considered
At the current moment - none.

#### Testing
I compiled the game and tested every new recipe. Everything is smooth.
#### Additional context
At the moment i'm leaving [CR] prefix, so feel free to share your opinions.

### CODE REVIEW

**Comment by Karol1223** [comment]
> "The crystallization process takes around 2 weeks." ---> Increased recipe time from 24 minutes to 1 hour and 30 minutes, because 24 minutes is a short time period for the crystallization process in the compressed timeframe of the game.

I do not see any logic in this? How are these numbers connected?

If it takes 2 weeks to crystallize irl, it should have the player waiting 2 weeks for it to crystallize in game, should it not?

**Comment by AudBobb** [comment]
The recipe should craft an intermediary item, something like 'crystallizing sugar', akin to how tanning leather works. This intermediary item should have the use action, something like

`  "use_action": {
    "target": "sugar",
    "msg": "You break up the crystallized sugar into a coarse powder.",
    "moves": 30000,
    "type": "delayed_transform",
    "transform_age": 201600,
    "not_ready_msg": "The sugar is still crystallizing.",
    "//": "2 days"
  },`

That (should) work out to 5 minutes to break up the sugar, probably should take longer, but that's up to you. And if I did my math right, thats 2 weeks for the transform age? I'm not sure if that's right, but the tanning hide claims 2 days to transform with a value of 28,800, or 14,400 per day. I have *no* idea where that number is coming from.

**Comment by Pabblusansky** [comment]
> That (should) work out to 5 minutes to break up the sugar, probably should take longer, but that's up to you. And if I did my math right, thats 2 weeks for the transform age? I'm not sure if that's right, but the tanning hide claims 2 days to transform with a value of 28,800, or 14,400 per day. I have no idea where that number is coming from.

Time Duration is in the JSON_INFO.md. 1 second in game = 1 turn. The hide is tanning in game in 8h, which is 28800 seconds, or 28800 turns. 
image
However, real-life tanning needs different time depending on the method, but it's usually from 2-3 days to weeks. This fact makes me think that all the actions from the old piece of code take place in a more compressed timeline...
But let's get back to our topic. I'll try to implement the intermediate item with appropriate time transformation.

**Comment by AudBobb** [comment]
>Time Duration is in the JSON_INFO.md. 1 second in game = 1 turn. The hide is tanning in game in 8h, which is 28800 seconds, or 28800 turns.

Yeah, and that's what I originally was assuming, just was confused because there is a comment in the block for tanning hide that says two days, so wasn't sure if that comment is just outdated, or if the delayed_transform function uses some weird math.

**Comment by Pabblusansky** [comment]
Added the intermediate crystallizing sugar item. Everything tested. However I observed that the description shows that the item "will be done in 1 week" which is wrong, after 1 week elapsed, it changes to "will be done in 7 days", (1 week + 7 days = 2 weeks) which is a bit weird
image

**Comment by CLIDragon** [comment]
Are there actually any tools with a filter level of 2? A search of the repo reveals only water filters and filter masks, neither of which relate here.

**Comment by Pabblusansky** [comment]
> Are there actually any tools with a filter level of 2? A search of the repo reveals only water filters and filter masks, neither of which relate here.

Yeah, that's a good question. Forgot to point it in the initial text, but yes, we do not have a normal filter tool that could be used in the process of crystallizing sugar, so yes, I _assumed_ that we can... use qualitative filter paper, which is used for cannabis craft? >:D. However, as an alternative, I thought to change the filter requirement with the concentration requirement and the microcentrifuge specifically. However, I really need more opinions on this topic because it sounds very controversial.

**Comment by CLIDragon** [comment]
I think the linked issue @AudBobb mentioned an example of using a cheese cloth to filter the juice. You could probably just add that to the game, with corresponding spawns where appropriate.

**Comment by PatrikLundell** [comment]
Comment on the duration confusion: Not sure if it has been resolved already.

If it takes two weeks in the real world it should take two weeks in the game, unless there's some special reason for why time should be compressed. One such case would be for a long duration passive activity that's part of an active recipe, but the correct handling of such a case should be to introduce an intermediate object, as is done here.

Duration remaining confusion: These times are not very user friendly, as they seem to truncate the unit used, so if the unit is weeks and the value is 1, the actual remaining time would be anywhere from one week to a second short of two, with the same for days, hours, months, etc.

**Comment by Pabblusansky** [comment]
> I think the linked issue @AudBobb mentioned an example of using a cheese cloth to filter the juice. You could probably just add that to the game, with corresponding spawns where appropriate.
> 
> It could then be used for other recipes, though that is definitely out of scope for this PR.

Wholeheartedly agree, definitely out of scope for this PR, because cheesecloth is a whole other story with a lot of usages, and I could not just add this item for only one recipe; that would be very unfair for other cooking recipes.

**Comment by Pabblusansky** [comment]
>If it takes two weeks in the real world it should take two weeks in the game, unless there's some special reason for why time should be compressed. One such case would be for a long duration passive activity that's part of an active recipe, but the correct handling of such a case should be to introduce an intermediate object, as is done here.

It is, indeed, 2 weeks; I did not compress the time of the crystallization process. The problem is, the game misrepresents the transformation time (it shows 1 week, and after 1 week has passed, it shows another time period: 7 days).
> Duration remaining confusion: These times are not very user friendly, as they seem to truncate the unit used, so if the unit is weeks and the value is 1, the actual remaining time would be anywhere from one week to a second short of two, with the same for days, hours, months, etc.

I used the turn unit(not the weeks and etc. as used in based recipes, because it is the use_action), because turn = seconds. However, it is shown incorrectly as I stated below. The easiest solution to fix it is to state in the description of the intermediate item that crystallization of sugar will take place 2 weeks.

**Comment by PatrikLundell** [comment]
I'm saying the UI is doing a lousy job at showing remaining time (i.e. I agree with you). It can't be fixed in the JSON, because it's caused by the UI using unsuitable logic to display remaining time. It has to be fixed in the UI (and thus is out of scope of your PR).

**Comment by Pabblusansky** [comment]
Looks like all changes were listed. I'm changing the status of PR to review

**Comment by Maleclypse** [comment]
Should molasses be created as a byproduct?  https://sugar.ca/sugar-basics/purification-of-sugar

**Comment by Pabblusansky** [comment]
> Should molasses be created as a byproduct? https://sugar.ca/sugar-basics/purification-of-sugar

Thanks a lot for the reminder, implemented this right away. I totally forgot about the byproduct of molasses for the sugar beet recipe because I was more focused on the fruit-based recipe.

**Pull request merged**
