### PR TITLE
Add abstract fish bait and use it for all baits

### PR DESCRIPTION
**Pull request by illi-kun**
Reduce number of lines in JSON data of all fish baits using abstract generic fish bait.

No rebalance, pure cleanup (that's why I didn't touch `count` value, not sure if this difference of veggy bait is intended).

Also, linting / sorting entries / moving these items in separate file are postponed to further PR.

### CODE REVIEW

**Comment by mugling** [comment]
Two options for abstracts:
* Inline in a file
* In `data/json/items/classes`

Given there are only few baits creating a new file with an inline abstract is probably best here; perhaps `data/json/items/misc/baits.json` or an equivalent.

As this PR isn't huge and you have drawn attention to it I don't see a problem in updating `count`. That looks like an omission more than anything.

If you want to lintify the new file that would also be reasonable due to the size. Be sure to add it to `json_whitelist`. It's your choice if you want to sort by `id` but for inline abstracts I've generally chosen not to and instead put the abstract at the start of the file.

Anything that gets unrelated content out of `ammo.json` is a welcome change. On that subject now that we have proper volumes we might consider making a lot of stuff that was `AMMO` become `GENERIC`

**Comment by illi-kun** [comment]
OK, I'll keep working on this in the current PR if you want so. I have to go for now, so I'll continue this tonight or tomorrow.

**Comment by mugling** [comment]
Sounds good

**Comment by Rivet-the-Zombie** [comment]
Why do we even need four types of fish bait in the first place? Couldn't we have a recipe with four possible input materials that all result in the same generic 'fish bait' item?

**Comment by illi-kun** [comment]
I dunno, I never used it in the game so I have no idea about its purpose and distinction.

**Comment by mugling** [comment]
> Why do we even need four types of fish bait in the first place? Couldn't we have a recipe with four possible input materials that all result in the same generic 'fish bait' item?

This is a good idea. @illi-kun apologies for not making this suggestion earlier.

**Comment by illi-kun** [comment]
np and agree that this can be a reasonable simplification.

**Comment by illi-kun** [comment]
Which material would be the best choice for such generic fish bait?

**Comment by illi-kun** [comment]
I reopened this for discussing the further vector of changes.

**Comment by mugling** [comment]
Ideal use case for `data/json/migrations.json`

**Comment by illi-kun** [comment]
@mugling could you expand your idea?

**Comment by mugling** [comment]
Define a single item `fishbait`. Delete all the other types. Then add to `data/json/items/migrations.json` the appropriate entires.
```
  {
    "id": "fishbait_bread",
    "type": "MIGRATION",
    "replace": "fishbait"
  },
```
It works just as you think it does - on next load all `fishbait_bread` are converted to `fishbait`

**Comment by illi-kun** [comment]
OK, got it, thanks for clarification.

Anyway, I still don't know which material should I assign to new item and important is it (I guess it's just question of consistency because you're not able to eat it).

**Comment by Rivet-the-Zombie** [comment]
>Which material would be the best choice for such generic fish bait?

I'm not sure how much it would really matter, since it's not actually food or anything. Heck, you could probably use `null` material and it would be fine.

**Comment by illi-kun** [comment]
@Rivet-the-Zombie thank you, I'll try to implement it.

**Pull request closed without merging**
