### PR TITLE
Knit cowl covers head instead of mouth, moved cowls to hoods.json

### PR DESCRIPTION
**Pull request by Zupercharged**
### Summary

SUMMARY: None

#### Purpose of change

Knit cowl covers just the mouth when it should cover the head

The item data for Knit cowl is wrongly located in the scarfs.json while the item data for Nomad cowl and Scavenger cowl are wrongly located in helmets.json when they should all be located in hoods.json

#### Describe the solution

Knit cowl now covers head instead of mouth

Item data for Knit cowl, Nomad cowl and Scavenger cowl has been migrated to hoods.json

#### Describe alternatives you've considered

None

#### Testing

Linted changed .json files and checked if the knit cowl now correctly covers the head in game.

#### Additional context

None

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
There is no error. Knit cowl is this thing - https://i.pinimg.com/736x/7d/21/7c/7d217cf4b0acedaba984b7b7ee05d606.jpg.

**Comment by Zupercharged** [comment]
It is, but they are designed the be something you can pull up over your head like so - https://img1.etsystatic.com/009/0/7836223/il_fullxfull.441921041_6i35.jpg
hence why its called a cowl. Generally speaking its too loose to cover the mouth without being held so for it to cover the head is more appropriate.

**Comment by ZhilkinSerg** [comment]
Regular knit cowls are just glorified scarfs - they cover mouth and neck, but ot head.

Your image is showing a different thing - a hooded cowl which covers head.

**Comment by I-am-Erk** [comment]
My wife knits cowls pretty regularly. Depending on the design they *definitely* cover your neck, they *might* cover your mouth but not closely enough to encumber, and they *might* cover your head.

Ideally it should be a piece of neck clothing that covers the head optionally if your head is free, like a good on a rainjacket. 

Knit cowl: https://irepo.primecp.com/2018/01/361734/Timeless-Knit-Cowl_Medium_ID-2605870.jpg

**Comment by Zupercharged** [comment]
there isnt a specified neck coverage value, but right now it adds 20 encumbrance to the mouth for 40 warmth. Would it be more appropriate to move it to cover the head as ive done or just reduce encumbrance on the mouth?

**Comment by ZhilkinSerg** [comment]
We can add neck body part soon too.

**Comment by Zupercharged** [comment]
Isnt that overcomplicating the current body damage system though? I cant see any useful functionality behind that aside from making a problem for scarves to solve.

**Comment by I-am-Erk** [comment]
I forgot we didn't have necks. I'd revert them to using mouths then.

**Comment by Ichthysdekilt** [comment]
Necks would not necessarily be such a bad thing.  Granted, it's more to keep track of, but it makes sense for necklaces/amulets/collars to be there instead of the head or the torso, and allows some neck armoring.

https://images-na.ssl-images-amazon.com/images/I/41RzG32oX8L._AC_SX425_PIcountsize-2,TopRight,0,0_SH20_.jpg
https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRIP-Ali3A_U3wMlvw_UeX7T58UT5jrntixfiNK8iPQ4Cxl4s8YhGBhtGdTqsPwCL4z2k_1GpPS3b3NX7lHAoXXzpaSv9EpqKD1-eBNCtAN&usqp=CAY

**Comment by Zupercharged** [comment]
Ok so i reverted the change to the knit cowls coverage. I noticed its flagged as a hood though, and its encumbrance is still 20.

**Comment by ZhilkinSerg** [comment]
There is no need to move it to hoods file then.

**Comment by Zupercharged** [comment]
Well i guess this Pull request is a bit pointless then, thanks for considering it.

**Pull request closed without merging**
