### PR TITLE
Make printf-format checking non-optional.

### LINKED ISSUE #22051: Internal Furnace CBM message log
Game version: 6815 experimental (Also tested in 6817)

Operating system: Windows

Tiles or curses: Tiles

Expected behavior: Reliable information in the message log.

Actual behavior: Everything claims to have restored 35123440 points of energy.

Steps to reproduce the behavior: Activate the Internal Furnace CBM and then eat something flammable that is otherwise non-edible.

Note that the amount restored is properly listed in the Consume Item menu, it simply isn't properly recorded into the message log seen in the normal view screen.

Additionally some things seem to give inordinate amounts of power, for example a Television can be eaten to provide 2512 power, which is slightly less than eating 5 entire logs.
Chopping down a tree usually drops 2-4 trunks which can be chopped up into 4-10 logs.

### PR DESCRIPTION
**Pull request by BevapDin**
It was introduced as optional and needed explicit activation, but apparently nobody used it at all. When I activated it, gcc complained about its usage in "ret_val.h" (specifically: attributes can not be added to function definitions, only to their declarations, and the format string parameter must be a `const char*` type). "ret_val.h" was added by #21774, and at least since that time, nobody has run the printf checks (or they have run it but neglected to complain about the errors).

So now it's mandatory. If required it could be disable for specific circumstances (e.g. compiler, os, ...) via macros in printf_check.h. For now it's only enabled if `__GNUC__` is defined.

I added a few more attributes "format_arg" to the source. They are already used by the glibc "libintl.h" file.

And I fixed most of the warnings. Some are still there:

- `-Wformat-zero-length` (format string is an empty string, but this is correct in out usage, for example with `mvwprintz`, which has other side effects beside printing).
- Other warnings about unused parameters (e.g. when calling `Creature::add_msg_player_or_npc`, the parameters are sometimes only used by the player message, but not by the npc message).

And this fixes #22051.

----

And the build fails because the Makefile has changed.

### CODE REVIEW

**Comment by kevingranade** [comment]
Also failing because of
```
In file included from src/item.h:22:0,
                 from src/map.h:13,
                 from src/activity_handlers.cpp:4:
src/activity_handlers.cpp: In function ‘void activity_handlers::vehicle_finish(player_activity*, player*)’:
src/debug.h:67:94: error: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘std::vector<int>::size_type {aka long unsigned int}’ [-Werror=format=]
 #define debugmsg(...) realDebugmsg(__FILE__, STRING(__LINE__), __FUNCTION_NAME__, __VA_ARGS__)
                                                                                              ^
src/activity_handlers.cpp:1386:9: note: in expansion of macro ‘debugmsg’
         debugmsg("process_activity invalid ACT_VEHICLE values:%d",
         ^
```

**Comment by kevingranade** [comment]
Considering the number of warnings, I'm not at all sure this was ever totally clear.

**Comment by kevingranade** [comment]
Also, there are a ton of warnings that appear in debug builds that might not occur in release builds.

**Comment by ZhilkinSerg** [comment]
Marking as Stalled. Feel free to reopen it.

**Comment by kevingranade** [comment]
Merged, but conflicts are confusing github.

**Pull request closed without merging**
