### PR TITLE
matchbook can reload and unload it's matchess

### LINKED ISSUE #56070: Allow matchbook to unload or reload it's matchess
### Is your feature request related to a problem? Please describe.

I am not sure why matchbook cannot unload or reload it's matchess in the game but in real life you can do it to organize matchbook, for example you have 2 matchbook first matchbook has quarter matchess, and the second matchbook has half matchess and probably you want to unload the first matchbook and fill the second matchbook so you can toss away the first matchbook.

### Solution you would like.

Remove the matchbook flags `"NO_RELOAD", "NO_UNLOAD"`.

### Describe alternatives you have considered.

Leave the matchbook as is.

### Additional context

issues

### PR DESCRIPTION
**Pull request by UnknownRori**
#### Summary
None

#### Purpose of change

Fixes #56070

#### Describe the solution

Removing the matchbook's flags `"NO_RELOAD", "NO_UNLOAD"` in data/json/item/tool/fire.json.

#### Describe alternatives you've considered

Leave the matchbook as is

#### Testing

Create new world, debug matchbook and try to unload, reload and try to use the item to burn something.

#### Additional context

issues

### CODE REVIEW

**Comment by haveric** [comment]
I'm pretty sure these are meant to represent tear off matches from a cardboard matchbook, so I'm not sure how you would be able to put them back into the matchbook. Perhaps it would be better to create a new item that represents a matchbox instead?

**Comment by Maleclypse** [comment]
> I'm pretty sure these are meant to represent tear off matches from a cardboard matchbook, so I'm not sure how you would be able to put them back into the matchbook. Perhaps it would be better to create a new item that represents a matchbox instead?

I came here to say this as well. Match box yes. Match books no.

**Comment by UnknownRori** [comment]
Oh i see, sorry for my lack of proper knowledge, but why the matchbox haven't added in the game yet, is it because it's because they never use the matchbox or because it's haven't added yet?

**Comment by haveric** [comment]
> why the matchbox haven't added in the game yet?

Usually the answer to this question is that nobody has done it yet, which makes it a perfect opportunity for you if you want to try to add it.

**Pull request closed without merging**
