### PR TITLE
Door hinges

### PR DESCRIPTION
**Pull request by barsoosayque**
#### Summary

```SUMMARY: Content "Adds door hinges for new and existing doors"```

#### Purpose of change

Making high-quality doors of planks and nails seems a bit unrealistic. "Makeshift doors" kinda might work this way,  but these manufactured doors in houses (and mansions, mind you) should be installed with hinges.

#### Describe the solution

Added hinges as a slightly modified `"sheet_metal_small"`.

Doors installation (last step of door construction) now requires hinges. Also, doors deconstruction or destruction spawns hinges, but only when there will be nothing or a frame after this process. (for example, bashing closed door to broken door won't spawn hinges).

Player can also craft hinges, and deconstruct them to `"sheet_metal_small"`.

Also, hinges will spawn in hardware stores, but the primary source for them is just doors.

#### Describe alternatives you've considered

I just though that maybe there should be some "makeshift" hinges recepies that utilize both survival and fabrication skills, but I couldn't come out with something meaningful. Maybe screws and bolts somehow might be a solution, but I doubt it.

### CODE REVIEW

**Comment by faefux** [comment]
Wondering, can this be abstracted away with 'scrap', 'steel_chunk' or 'sheet_metal_small'. Just a thought. :)

**Comment by I-am-Erk** [comment]
There are lots of ways to make makeshift hinges, I think the simplest is to make one out of a piece of leather though

**Comment by barsoosayque** [comment]
> <...> might be reasonable to add a makeshift door terrain

I saw that there is, in fact, a [makeshift door](https://github.com/CleverRaven/Cataclysm-DDA/blob/ff714b2fb909da9736c5e559fc2f0521c8d62308/data/json/terrain.json#L2764) in the game, and it's [constructable](https://github.com/CleverRaven/Cataclysm-DDA/blob/6384b4884cfcb6d9977c3c9c72022c9e3d0bc34c/data/json/construction.json#L108) using ropes.

I meant that, perhaps, there should be recipes for steel hinges out of some metal scrap, like:
*HAMMER 1* + *SAW_M 1* + *small metal sheet* + *wire*

**Comment by ZhilkinSerg** [comment]
I would bump up metal door requirement to 3 hinges as metal doors are much heavier.

**Comment by I-am-Erk** [comment]
I'd also suggest adding a third hinge to the requirements to reinforce a door actually. Three hinges are common on exterior doors and other sturdy doors, and really would help reduce zombies ripping it down.

**Comment by eilaattwood** [comment]
> 
> 
> > <...> might be reasonable to add a makeshift door terrain
> 
> I saw that there is, in fact, a [makeshift door](https://github.com/CleverRaven/Cataclysm-DDA/blob/ff714b2fb909da9736c5e559fc2f0521c8d62308/data/json/terrain.json#L2764) in the game, and it's [constructable](https://github.com/CleverRaven/Cataclysm-DDA/blob/6384b4884cfcb6d9977c3c9c72022c9e3d0bc34c/data/json/construction.json#L108) using ropes.
> 
> I meant that, perhaps, there should be recipes for steel hinges out of some metal scrap, like:
> _HAMMER 1_ + _SAW_M 1_ + _small metal sheet_ + _wire_

IMHO, proper hinges should require a forge or at least a welder to make. They need quite fine work.

**Comment by barsoosayque** [comment]
> I'd also suggest adding a third hinge to the requirements to reinforce a door actually. Three hinges are common on exterior doors and other sturdy doors, and really would help reduce zombies ripping it down.

Nice idea !

> IMHO, proper hinges should require a forge or at least a welder to make. They need quite fine work.

Yep, there is a forge recipe already. But I think that it would be really nice to have another one as an alternative. Welder recipe is actually a great idea, too. I guess it should be more expensive in resources, like small metal sheet + some scrap +  a lot of instruments; but rather low fabrication skill level.

**Comment by TechyBen** [comment]
Should they uncraft into small sheet metal? With the holes drilled in them, and the folds, IMO it'd be scrap that then needs rebeating/forming into a sheet.

**Comment by barsoosayque** [comment]
> Should they uncraft into small sheet metal? With the holes drilled in them, and the folds, IMO it'd be scrap that then needs rebeating/forming into a sheet.

Ain't `sheet_metal_small` and `sheet_metal` just generalisation ? Because if it's true, then hinges that flattened with a hammer should be ok since those holes aren't that big. Otherwise, yes, for sure.

**Comment by I-am-Erk** [comment]
I think small sheet metal or scrap are both pretty ok. I wouldn't worry about it too much.

As for crafting, having a forge recipe is probably enough. The main way people are going to be getting hinges is by scavenging them, the forge recipe is just for innawoods games and they won't likely have access to a welder anyway

**Comment by TechyBen** [comment]
> I think small sheet metal or scrap are both pretty ok. I wouldn't worry about it too much.
> 
> As for crafting, having a forge recipe is probably enough. The main way people are going to be getting hinges is by scavenging them, the forge recipe is just for innawoods games and they won't likely have access to a welder anyway

Yeah, making them by hand would be a slightly different size/quality to manufactured ones, but they should not be hard. I've seen ancient ones in museums on doors as big as a house. Plus there is a small traditional forge around here, they make gates and tools. :)
Also: https://youtu.be/g-SuUZDzaJM

**Pull request merged**
