### PR TITLE
Xedra Evolved spell audit

### PR DESCRIPTION
**Pull request by TimPollard**
#### Summary
Mods "Auditing various Xedra Evolved spells for sanity"

#### Purpose of change
Some of the Xedra Evolved spells seemed to have missing values for `spell_class` or `energy_source` and/or weird values for the various `_increment` values.

I made a quick and dirty Ruby script to check those values, and then manually had a look at anything that it outputted.

There's a more complete list of changes below, but basically:

1. Any spell that was in a class specific file (eg: `dreamer_spells.json`) but didn't have `spell_class`, got one.
2. Any spell that had `energy_cost`, but no `energy_source` was set to use MANA.
3. If the `_increment` would result in one of the variable values never reaching it's `final_` or `max_` value I changed that.

In addition while I was testing this I noticed that the Classless "Blur" spell was summoning `obfuscating_aura` from Magiclsym, instead of the equivalent `blurred_aura` from Xedra Evolved.

I've changed it to use `blurred_aura`, which was already in Xedra Evolved (but apparently unused) and appears to be identical to Magiclsym's `obfuscating_aura` except made of `dreamstuff` instead of `magical_material`.

#### Describe the solution

<details>
<summary>Classless spells</summary>

`night_sight`:

* Changed `duration_increment`

`dread_weight`:

* Changed `aoe_increment`

`blur`:

* Changed `duration_increment`
* Changed it to summon `blurred_aura` instead of `obfuscating_aura`

</details>

<details>
<summary>Dreamer spells</summary>

`spell_summon_twin_flood`:

* Removed `PERMANENT_ALL_LEVELS` so that the summons don't last forever
* ~~Increased `duration_increment`~~

`spell_dreamer_clairvoyance`:

* Added `"spell_class": "DREAMER"`

`spell_dreamer_clairvoyance_eff`:

* Added `"spell_class": "DREAMER"`
* ~~Changed `energy_increment`~~

</details>

<details>
<summary>Dreamsmith spells</summary>

No changes
</details>

<details>
<summary>Dream Eater spells</summary>

`banish_nether_monsters`:

* Added `"energy_source": "MANA"`

`banish_dark_monsters`:

* Added `"spell_class": "EATER"`
* Added `"energy_source": "MANA"`
* Changed `energy_increment`

</details>

<details>
<summary>Inventor spells</summary>

No changes
</details>

#### Testing

I played around with using the debug menu to give my character all of the
changed spell at various levels and checked that they had classes, actual costs,
and that the variable values where producing expected results.

### CODE REVIEW

**Comment by GuardianDll** [comment]
Too much interchanges with #65737

**Comment by TimPollard** [comment]
@GuardianDll, ah, I hadn't noticed that you had another pull request open that was working on the same stuff.

There's a few things I fixed that you didn't though, so I'll put this into draft until after your pull request is merged.

**Comment by TimPollard** [comment]
I merged master including @GuardianDll's changes from #65737 into this.

I undid my changes to the increments for `spell_summon_twin_flood` and `spell_dreamer_clairvoyance_eff`, but otherwise it's the same as what I submitted initially.

**Review by Maleclypse — APPROVED** [review]
Good catches! Thank you!

**Pull request merged**
