### PR TITLE
Martial Arts Rebalance for Brawling

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Balance "Martial arts rebalance for Brawling"```

#### Purpose of change

Partially implements #32422
Update for the martial art: Brawling

#### Describe the solution

`You're used to hand-to-creature fighting.  You know how to fight when unarmed or with any weapon to a certain extent.  It's not stylish or sporting, but it gets the job done.`

_Current Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Autolearn|Unarmed 2||Martial art is automatically learned
Arm Block|Unarmed -1||
Leg Block|Unarmed 7||
Feint|Unarmed 3|Melee & Unarmed Tech|Feint
Power Hit|Unarmed 4|Melee & Unarmed Crit Tech|Knockback duration: 1, Knockback spread: 1, Stun duration: 1
Hit Them Back|Unarmed 5|Melee & Unarmed Block Counter|
Trip|Unarmed 5|Unarmed Tech|Down duration: 2

Style Weapons: All weapons.

Brawling is pretty good to be honest. It gets some of the "basic" stuff of the martial arts system like a Feint and a counter.

_Problems and issues_
- **Style works both unarmed and armed techniques require Unarmed skill to learn.** 
Brawling needs to cater to both styles of combat.

_Rebalance Goal_
Brawling's closest real world analog is street fighting. Both have no defined structure of how to fight and their techniques are a bunch of random stuff "that works". For the most part, brawling has got this theme down correctly. I used the following guidelines to reblancing brawling:

**1. Brawling is the "default" fighting style.**
Any person that has thrown a few punches or swung a weapon a few times knows how to brawl. Just like in real like, if you don't know how to use something to fight with you will use the most common attacks you can think of or have seen to fight. "No style" is not the default fighting style. The player is intentionally holding themselves back when using "No style".

**2. You can use any weapon to brawl.**
You can brawl with anything. A chair, a cup, a pipe will all work to hurt someone. In truth, the player is just "winging it" when it comes to weapon use in general if they are not using a martial art associated with it. They have no training and are just using whatever works best to win a fight.

**3. It takes a while to "get good".**
Unlike other styles that have long legacy of use and tradition, brawling players are literally figuring out the style as they go. Other styles will have all their buffs and techniques by Melee/Unarmed 5 but brawling will not. Brawling has a broader move set but everything takes longer to learn.

Brawling should be a style everyone can use and should be the ultimate "fallback" martial art. If all else fails, try brawling!

_New Buffs, Techniques, and Special Abilities_

Name | Level Available | Type | Effect 
--- | --- | --- | --- 
Autolearn|Melee 1||Martial art is automatically learned
Arm Block|Unarmed 1||
Leg Block|Unarmed 7||
Feint (unarmed)|Unarmed 3|Unarmed Tech|Feint
Power Hit|Unarmed 4|Unarmed Crit Tech|Knockback duration: 1, Knockback spread: 1, Stun duration: 1
Hit Them Back (unarmed)|Unarmed 5|Unarmed Block Counter|
Trip|Unarmed 5|Unarmed Tech|Down duration: 1
Grab Break (unarmed)|Unarmed 6|Unarmed Tech|Grab Break
Disarm (unarmed)|Unarmed 8|Unarmed Tech|Disarms
Feint (melee)|Melee 3|Melee Tech|Feint
Hit Them Back (melee)|Melee 5|Melee Block Counter|
Grab Break (melee)|Melee 6|Melee Tech|Grab Break
Disarm (melee)|Melee 8|Melee Tech|Disarms

_Important Changes_
- **Brawling is automatically learned at Melee 1.**
This change allows melee characters to learn brawling without needing to spend time using unarmed attacks. Regardless of how you fight in melee combat, your Melee skill will always increase. Unarmed characters will learn the style faster but because it takes longer to learn the techniques, the style will not be any stronger than it would be at Unarmed 2.

- **Lots of duplicate techniques.**
In order to allow brawling to be usable for both unarmed and melee characters, I've created copies of most of the techniques and changed them to use melee instead of unarmed. This means you can freely use brawling without needing to level the Unarmed skill.

- **Added Grab Break and Disarm.**
These two techniques are some "basic" techniques that brawling was missing. With them, brawling becomes a "go-to" style for situations where a player needs a specific technique. However, you learn them MUCH later than other styles.

- **Power Hit is no longer a melee technique.**
This was done due to the way the game handles weapon techniques. If you are not using a style that has melee techniques, the game will use the weapon's techniques (if any) instead. If a style has at least one melee technique, that technique will always be used and the weapon's techniques will NEVER trigger. By changing Power Hit to unarmed only,  brawling no longer has any melee techniques and weapons will use their own techniques instead. This makes the most sense for brawling because you are not trained to use weapons and would lean more heavily on a weapon's natural strengths when fighting.

- **Fighting unarmed is weaker.**
While I didn't nerf anything, this is something that should be expected from a style that lets you use a Battle Axe with it. However, unarmed brawling gets the benefit of Power Hit and Trip while the melee side doesn't. Try to use unarmed brawling to control opponents instead of doing damage. It may not always be necessary, but it's still a worthwhile option to have.

_Advantages_
- Automatically learned at Melee 1.
- Can be used with any weapon.
- Gains a wide variety of techniques.

_Disadvantages_
- It takes a long time to learn all of the techniques.
- You will need to train in Unarmed to get the entire set of techniques.
- A lacks of buffs and other bonuses leaves it behind in terms power compared to other styles.

#### Describe alternatives you've considered

_If the style is too strong..._
- Remove Disarm.
- Remove Grab Break.
- Change Autolearn to Melee 2 or Unarmed 2.

_If the style is too weak..._
- Increase the damage on Power Hit to +25% Bashing damage.
- Add a unarmed only Rapid technique.
- Add a unarmed only, +20% Bash damage technique.

#### Additional context

_References:_
[Street fighting wikipedia page](https://en.wikipedia.org/wiki/Street_fighting)

### CODE REVIEW

**Comment by nexusmrsep** [comment]
Your PR descriptions are very informative. Would you consider transferring core parts to the CDDA Wiki for future reference after each part gets merged?

**Comment by Hymore246** [comment]
My plan was to do a full update to all the wiki pages related to martial arts once I finish with the rebalance.

**Comment by Poldraunic** [comment]
Reading your posts is always so satisfying. I especially love your takes on nerfing/buffing stuff. Thank you for the hard work!

**Comment by Hymore246** [comment]
I'm planning on changing Krav Maga too. That change will happen in once I get to it.

**Pull request merged**
