### PR TITLE
Remove "dig a pit" option from construction list

### LINKED ISSUE #33618: different minig byproduct
# Describe the bug
When mining from "%"-action menu (directly beneath) there are some byproducts like rocks, clay and so on.
But when digging pit from "*"-building menu no byproducts appear

# Expected behavior

There should be byproducts when "*" digging pit.

# Versions and configuration

0.D-7024-ga16c90f

### PR DESCRIPTION
**Pull request by RedShakespeare**
#### Summary

SUMMARY: Bugfixes "Remove 'dig a pit' option from construction list"
#### Purpose of change

Fixed #33618 - Different mining byproducts
#### Describe the solution

Deleted the "dig a pit" options from "*" list since it had already been moved to the activation lists of digging tools, which could work well.
#### Describe alternatives you've considered

Add byproducts to the digging constructions (but since cutting trees had also been removed for the same reason there's no need to do extra work)

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Isn't this necessary for calculating faction camp expansion requirements?

**Comment by RedShakespeare** [comment]
It's the digging mechanism that influence this, not the digging options if I didn't get it wrong.

Cutting down trees also matters when it comes to camps but it has been out of the construction list for quite a long time,isn't it?

**Comment by anothersimulacrum** [comment]
I'm talking about the blueprint_autocalc added in #31115

> add support for basecamps being able to autocalculate their upgrade build time and requirements. For that to happen, all common terrain constructions need to have a construction definition, but some constructions, like deep and shallow pits, are not meant to be selectable by the user. add the concept of a hidden construction, and add definitions for the shallow pit and deep pit construction.

**Comment by RedShakespeare** [comment]
Ah...sorry, I got it.
So maybe these options should be hidden instead?

**Comment by anothersimulacrum** [comment]
Okay, the relevant PR is actually #31209
Looks like `"on_display": false` isn't working properly.

**Comment by anothersimulacrum** [comment]
Looks like a one line PR to fix it - 
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/construction.cpp#L143
should be
```cpp
        if( it.on_display && ( !hide_unconstructable || can_construct( it ) ) ) {
```
Something that was done in #31209 and reverted at some point.

**Comment by RedShakespeare** [comment]
Yes...failed to notice that problem had been solved in latest versions(since the issue was raised yesterday). My bad..

**Pull request closed without merging**
