### PR TITLE
Fix item_info_str( test_belt, pockets ) test error

### PR DESCRIPTION
**Pull request by actual-nh**
#### Summary

None

#### Purpose of change

The test belt's maximum item length was not changed by #47605, but the test's expectation of it was. This is resulting in failures as seen in #47701, #47703, #47702, and others.

#### Describe the solution

Revert the `iteminfo_test.cpp` change.

#### Describe alternatives you've considered

Editing the test belt instead; this would admittedly have the advantage of making it more consistent with the rest.

#### Testing

Already has a test.

#### Additional context

Ping: @Lamandus, @ZhilkinSerg. Sorry I didn't notice this earlier when I gave #47605 a 👍  (altered to a ❤️  now).

### CODE REVIEW

**Comment by actual-nh** [comment]
The failure for the General Build Matrix MacOs is from the fields test that keeps causing problems; the GCC 7 one came through fine.

**Comment by Lamandus** [comment]
yikes, I really messed stuff up the last few days *cough* not the best time of mine.

**Comment by actual-nh** [comment]
> yikes, I really messed stuff up the last few days _cough_ not the best time of mine.

Everyone has bad days/periods - especially given current RL stresses...

**Comment by actual-nh** [comment]
I'm starting to think the better fix is to edit the test belt - in `data/mods/TEST_DATA/items.json` - so it matches the other toolbelts, to make sure things can fit. Thoughts? @anothersimulacrum?

**Comment by anothersimulacrum** [comment]
I think it would be good to make it match the other toolbelts.

**Comment by Lamandus** [comment]
*in a very faint voice behind some corner* yes, would be an idea...

**Comment by actual-nh** [comment]
> I think it would be good to make it match the other toolbelts.

Done for test_tool_belt; changing test code back now.

**Pull request merged**
