### PR TITLE
Chocolate Bars Updated

### PR DESCRIPTION
**Pull request by Grubleafeater**
Changed chocolate bars to have vitamins based on a Hershey's, and similarly changed their weight and caloric content to match a Hershey's bar.

#### Summary
Balance "Gives chocolate the stats of a Hershey's bar"

#### Purpose of change

Both realism and also balancing with the vitamin update.

#### Describe alternatives you've considered

Rebalancing chocolate to match a hershey's bar, but at unchanged mass--IE 170 calories and 6% calcium/iron.

#### Additional context

https://smartlabel.hersheys.com/00034000870332-0001

### CODE REVIEW

**Comment by NetSysFire** [comment]
It appears @KorGgenT rebalanced it 5 years ago at #27582. I dont know where they got the data from though since its not in the spreadsheet.

**Comment by Grubleafeater** [comment]
> It appears @KorGgenT rebalanced it 5 years ago at #27582. I dont know where they got the data from though since its not in the spreadsheet.

_shrug_ it's not like it had vitamin info anyway, so i'm using hershey's chocolate as a baseline for both vitamins and calories.

**Comment by SirPendrak** [comment]
250ml for 43g seems wrong

**Comment by Grubleafeater** [comment]
> 250ml for 43g seems wrong

No no because there are 3 charges, that's actually for 129. The code there honestly confuses me, too.

**Review by Maleclypse — APPROVED** [review]

**Pull request merged**
