### PR TITLE
Fuel rework

### LINKED ISSUE #29890: Wrong alternative fuel types in engines.
**Describe the bug**  
Diesel engines offer ethanol, methanol and denatured alcohol as alternative fuel type. Gasoline engines offer no alternative fuel types.

**To Reproduce**  
Examine engine tweaking menu and json files :)

**Expected behavior**  
IRL, ethanol is more similar to gasoline than to diesel fuel, and actually gasoline, not diesel engines can accept it as alternative fuel with minimal to no tweaking. [Actually, many gasoline cars run on mixed fuel that consists of gasoline and ethanol nowadays.](https://en.wikipedia.org/wiki/Ethanol_fuel) Lamp oil should be left for diesel engines as it is more similar to diesel than gasoline.

Also, It makes sence to add mixed ethanol-gasoline fuel and biodiesel fuel to the game. (There is a book that allows player to create diesel from fats in the game, but that is actually NOT the diesel fuel, it's [biodiesel](https://en.wikipedia.org/wiki/Biodiesel), another substance with another efficiency values.)

And, finally, It would be right to add a chance for a vehicle to spawn with biodiesel/bioethanol in the tanks instead of diesel/gasoline. And add biofuel pumps to gas stations.
**Screenshots**  
None

**Versions and configuration(please complete the following information):**
 - OS: Any
 - Game Version: 0.D-2175-gdd04a6b
 - Graphics version: Any

**Additional context**  
Fuel efficiency graph

### PR DESCRIPTION
**Pull request by eilaattwood**
#### Summary
```SUMMARY: Balance "Fixes wrong alternative fuel types in engines."```
#### Purpose of change
Fixes #29890 - Wrong alternative fuel types in engines.
#### Describe the solution
Added biodiesel definition.
Changed diesel fuel recipe from 'textbook_biodiesel' to yield biodiesel instead of diesel.
Changed diesel engine to accept diesel, biodiesel and lamp oil as a fuel and not to accept ethanol-like fuels anymore.
Changed gasoline engine to accept gasoline, ethanol, methanol and denatured alcohol as a fuel.
#### Describe alternatives you've considered
None
#### Additional context
None

### CODE REVIEW

**Comment by kevingranade** [comment]
To the best of my knowledge, gasoline engines encountered in the US only take a gasoline/ethanol blend, not pure ethanol or methanol.
AFAIK all the diesel engine changes are reasonable.

**Comment by eilaattwood** [comment]
> 
> 
> To the best of my knowledge, gasoline engines encountered in the US only take a gasoline/ethanol blend, not pure ethanol or methanol.
> AFAIK all the diesel engine changes are reasonable.

Actually, diesel engines also cannot accept pure biodiesel or especially lamp oil as a fuel without regulation and/or modification. Modern diesel engines are lot more capricious about fuel quality than gasoline engines. I've thought about that and actually thought about adding fuel blends like E75 and B20 like I tried to explain in the corresponding issue. I can add that blends, but I thought that would be unnecessary complication. I think, switching fuel type implies engine regulation.

As alternative, it would be nice to add recipes for E75 and B20, add corresponding biofuel pumps to the gas stations, and add a chance for any vehicle to spawn with biofuel in the tanks instead of regular fuel. But unfortunely, the last change lies beyond my programming skill level and understanding or the project.

**Comment by eilaattwood** [comment]
Ah, as an option, what about making fuel type switch require mechanics skill of certain level?

**Comment by kevingranade** [comment]
> Actually, diesel engines also cannot accept pure biodiesel or especially lamp oil as a fuel without regulation and/or modification. Modern diesel engines are lot more capricious about fuel quality than gasoline engines.

Ok, so back those out too and we can add support for it later.  I'm not clear on what is implied by "regulation".

> I can add that blends, but I thought that would be unnecessary complication. 

Unnecessary complication is a reason to not add something, not a reason to add a version of something that shouldn't work.  Either ethanol blending is worth adding to a reasonable level of detail, or it's not worth adding.

**Comment by Reclusive-reptile** [comment]
Biodiesel with trace methanol content can dissolve rubber seals in a diesel engine, but a side from that biodiesel will function in a diesel engine with no modifications if you are willing to accept voiding your warranty.

**Comment by kevingranade** [comment]
I'm rolling back the gasoline change because the biodiesel change is totally uncontroversial.

For gasoline to burn ethanol, it needs to either be a blend or have a reasonable adjustment process to switch the engine over.  Keeping in mind that in the US, almost all available gasoline is now an ethanol blend.

**Pull request merged**
