### PR TITLE
Make lab walls concrete

### LINKED ISSUE #12144: Science Lab overmap walls upgrade, underground Z levels fix
Science labs are a very interesting place, especially now that the Labstart challenge has been introduced, but there are still some small problems that require a quick fix from someone more competent at coding than I am. As you all remember, before concrete walls we only had regular "walls" that worked for every building in the game, science labs too. They can be smashed with a weapon with at least 20 bashing and give splintered wood, nails and sometimes some rocks. You can light them on fire with a single lighter charge, as you would with a skewer. Now, there's a weapon, the homewrecker, that requires fabrication 0 to craft and that is very simple to do on your first or second day of the challenge.  Before it was the quarterstaff but after I addressed the problem someone changed the damage output from 20 bashing to 19 bashing, with some screenshots of a character "winning" the challenge repeatedly by just taking two points in fabrication and two in bashing weapons, quarterstaff, bash, out.

Getting out of the lab after not even a day is extremely underwhelming and in my opinion not worth 8 points at character generation, plus more mutations than with a regular character at chargen, especially when you count that you can just throw chuks of steel or two by fours at the turret around midnight, standing just outside of its line of sight, to make it explode without being shot back. 

I propose to upgrade the science lab's overmap walls to concrete,  and also to fix these random drywall-hallways in the underground levels (shown in the picture), with priority to the overmap walls.
screenshot from 2015-04-23 20 42 29

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11900100-science-lab-overmap-walls-upgrade-underground-z-levels-fix?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #12144

Also moved the card reader into the wall, so that it's accessible both from the inside and the outside. It is more resistant than the surrounding walls (it was written for metal walls) so it doesn't pose a security risk here.
Except when you have an electrohack, but in this case I think it's a good thing.

### CODE REVIEW

**Comment by tyrael93** [comment]
You wonderful, wonderful person.

**Comment by BevapDin** [comment]
It looks fine, except the card reader is accessible from the room, not just from the corridor:
```
----  ---
---6++---
  @|  |
   |  |
   |  |
```
The character can access the reader. How about mvoing the read (and the doors) one tile to the outside:
```
---6++---
----  ---
   |  |
   |  |
   |  |
```

Or maybe this isn't a problem?

**Comment by Podesta** [comment]
@Coolthulhu did you end up adding the id cards for the loot pool or just replaced the walls?

**Comment by tyrael93** [comment]
I think I found some science cards in the lab after this PR, plus I see something about cards in the code changes.

**Comment by Coolthulhu** [comment]
Currently just the walls. During all of my runs of labstart I always found teleporters quite early.
With plentiful teleporters, the only thing missing is a guaranteed solution (that works at 0.01 item spawn).

**Pull request merged**
