### PR TITLE
Craftable wind turbine to place on vehicles

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Content "Adds new vehicle part : a wind turbine'"```

#### Purpose of change
Somebody mentioned in the Discord they had made their own personal wind turbine mod, using perpetual motion. I wondered if it were possible to make a part that was similar to the solar panel, but checking intensity of e-power from the windpower instead of sunlight.
So here it is.

#### Describe the solution
Adds a new item and vehicle part , imagined to be a human-sized-ish wind turbine, that can be crafted fairly easily.
It is a simpler concept than a solar panel, and installed fairly easily, but its very fragile, will have a lot of aerodynamic drag ( mlangsdorf said he would add the drag code  ) and has less power production than a solar panel - seems on average it would take around 40 hours to fill a car battery.
I welcome feedback on the recipe, stats etc of the item, and the windpower calculation.

#### Describe alternatives you've considered
Having feedback on the current RPM of the turbine would be useful, but I'm not sure how to implement that.
I want to perhaps add a wind-powered quern at some point, using this.

#### Additional context
It goes without saying, this is a Mickey Mouse operation of me bodging together code that hopefully isn't totally broken. It seems to work, but I expect and welcome criticism.

### CODE REVIEW

**Comment by darktoes** [comment]
I'm curious why the recipe requires a small motor as well as alternators. Would it perhaps make more sense, if the turbine is man-sized, to require some sheet metal for fins and perhaps a few 2x4s to make a bracket to hold it up in the air?

That said, a little research suggests that commercial wind turbines with blades around 1.2-1.5m in diameter are rated at around 400W. I suspect increasing the power from the turbine would be reasonable, and welcomed by players. That said, if you wanted to include both a smaller, low power turbine and a larger, much heavier turbine, that would be really neat.

**Comment by mlangsdorf** [comment]
I recommended 40W, as a 0.5m diameter blade assembly being 1/3rd the size of that 400W assembly and producing 1/10th the power.  I'm assuming that power production scales with the square of blade diameter, but someone should do some research.

Small sheet metal for the fins, though the reference design used sections of 8" PVC pipe.

**Comment by DracoGriffin** [comment]
Suggestions for makeshift versions: [Malawian-made with no formal education](https://www.ted.com/talks/william_kamkwamba_how_i_harnessed_the_wind?language=en#t-203196) - the book is also super interesting ("[The Boy Who Harnessed the Wind](https://www.amazon.com/Boy-Who-Harnessed-Wind-Electricity/dp/0061730335)"). I can't locate where the output is when he finished (he did several equipment test versions), but the dynamo he used had an output of 12 V with him muscle generating and he mentions the windmill was much higher and he had to figure out how to reduce it to avoid surging the radio and other stuff (all this starts from Chapter 11 and on).

**Comment by davidpwbrown** [comment]
If it's made slightly better than a solar panel in output, yet easier to craft, should I bump up the crafting requirements?

**Comment by paulenka-aleh** [comment]
I suppose some RVers use wind turbines IRL. Not while driving of course :)

Example which has at least some stats: http://www.truckcamperadventure.com/2014/05/review-of-windwalker-250-rv-wind-turbine/

**Comment by darktoes** [comment]
Wind is flatly more space efficient than sun. Solar panels are easily found, whereas a turbine has to be made from scratch with some skill. I'd say make it decent sized with a realistic crafting recipe and vehicle part weight (hauling one around should be nearly impossible) and call it good.

**Comment by davidpwbrown** [comment]
Changed epower to 17, which in testing, produces a bit better than solar panel, given average wind
when windspeed goes above 40, the turbine becomes twice as good as solar panel.
Made it bulkier and heavier.
Changed recipe to need either alternator or motor, not both, to use small sheet metals, and require fabrication in addition to electronics.

**Comment by Vasyan2006** [comment]
But still it will not stop me from installing turbines on every tile.
Make installation impossible if there is another turbine in 10 tiles radius? Turbines far away from each other will not interfere so using two of them on long vehicle will be acceptable. And something like this should be done to solar array, because it requires a lot of free space around.

**Comment by paulenka-aleh** [comment]
> Make installation impossible if there is another turbine in 10 tiles radius?
It won't prevent you from putting 4 vehicles with wind turbines adjacently. They'd rather should interfere reducing overall efficiency.

You already have to craft them, have to install / uninstall each time you want to benefit from them, they don't work indoors, might be unreliable if they're tied to real wind speed, fragile and produce only a little energy output in compare to solar power or alternators. I doubt I would ever use them in the current state, I'd just move from alternators to solar panels skipping it completely or maybe would put one at a stationary base as a backup in case of, say, nuclear winter... Nay, I'd stick to diesel generator at a stationary base, much easier even in such a case and kore effective.

I'd say it needs a buff rather than a nerf. The fact you cannot drive with it is already major inconvenience. If they will interfere they surely need a buff in power.

**Comment by kevingranade** [comment]
> But still it will not stop me from installing turbines on every tile.

That's fine, if you look at http://www.truckcamperadventure.com/2014/05/review-of-windwalker-250-rv-wind-turbine/, it makes it clear the generator needs to be mounted on a big pole anyway.  If you want to mount a bunch of turbines, you just need to mount them at slightly different heights so they aren't in each other's wake.  I don't think it's a particularly productive thing to do, but if you want to you can make it work.

**Comment by davidpwbrown** [comment]
After conversation in Discord, I have made the requirements to install and remove very low ( like on the RVs that have them - you just remove them and erect them very easily )
I have added a steel boom to the crafting requirements.

**Comment by darktoes** [comment]
Why is the steel boom a component? Should it be an installation tool requirement perhaps? It seems excessive for a wind turbine of this size, considering it's apparently rated to lift 20 metric tonnes.

**Comment by darktoes** [comment]
I was under the impression that the 2x4s were acting as a pole to hold it up in the air? That said, I think separate pipes is the way to go, steel booms are far too massive and expensive for a turbine of this size.

**Comment by mlangsdorf** [comment]
compiled but not tested code for adding drag:
```diff
diff --git a/src/vehicle.cpp b/src/vehicle.cpp
index e2c095ba87..a5e8ee9af7 100644
--- a/src/vehicle.cpp
+++ b/src/vehicle.cpp
@@ -3140,6 +3140,7 @@ struct drag_column {
     int shield = minrow;
     int turret = minrow;
     int panel = minrow;
+    int windmill = minrow;
     int last = maxrow;
 };
 
@@ -3154,6 +3155,7 @@ double vehicle::coeff_air_drag() const
     constexpr double aisle_height = 0.6;
     constexpr double fullboard_height = 0.5;
     constexpr double roof_height = 0.1;
+    constexpr double windmill_height = 0.7;
 
     std::vector<int> structure_indices = all_parts_at_location( part_location_structure );
     int min_x = 0;
@@ -3218,6 +3220,7 @@ double vehicle::coeff_air_drag() const
                          !pa.info().has_flag( "SOLAR_PANEL" ) );
             d_check_max( drag[ col ].roof, pa, pa.info().has_flag( "ROOF" ) );
             d_check_max( drag[ col ].panel, pa, pa.info().has_flag( "SOLAR_PANEL" ) );
+            d_check_max( drag[ col ].windmill, pa, pa.info().has_flag( "WIND_TURBINE" ) );
             d_check_max( drag[ col ].exposed, pa, d_exposed( pa ) );
             d_check_min( drag[ col ].last, pa, pa.info().has_flag( "LOW_FINAL_AIR_DRAG" ) ||
                          pa.info().has_flag( "HALF_BOARD" ) );
@@ -3247,6 +3250,8 @@ double vehicle::coeff_air_drag() const
         c_air_drag_c -= ( dc.last == min_x ) ? c_air_mod : 0;
         // turrets severely worsen air drag
         c_air_drag_c += ( dc.turret > minrow ) ? 3 * c_air_mod : 0;
+        // having a windmill is terrible for your drag
+        c_air_drag_c += ( dc.windmill > minrow ) ? 5 * c_air_mod : 0;
         c_air_drag = std::max( c_air_drag, c_air_drag_c );
         // vehicles are 1.4m tall
         double c_height = base_height;
@@ -3260,6 +3265,8 @@ double vehicle::coeff_air_drag() const
         c_height += ( dc.turret > minrow ) ? 2 * roof_height : 0;
         // solar panels are better than turrets or floodlights, though
         c_height += ( dc.panel > minrow ) ? roof_height : 0;
+        // windmills are tall, too
+        c_height += ( dc.windmill > minrow ) ? windmill_height : 0;
         height = std::max( height, c_height );
     }
     constexpr double air_density = 1.29; // kg/m^3
```
a single wind turbine increases c_air_drag by 0.5 (minimum value is about 0.25, maximum is around 1.5, so a fairly large jump ) and increases vehicle height by 0.7m (minimum height is 1.4m, max used to be about 3.5m).  Adding a wind turbine to a car would increase the net air drag coefficient from ~0.5 to 2+ and reduce top speed by about 40%.

**Comment by kevingranade** [comment]
> Why is the steel boom a component?
This is my fault, I mentioned it needed a steel boom since the RV mounted wind turbine used that phrase, but I didn't think of it sharing a name with an in-game item.  It just needs to be a metal pole or pipe of some kind

**Comment by darktoes** [comment]
Perfectly understandable. Like I said, based on the size and makeshift nature of the thing, a few pipes and/or some 2x4s should be able to fulfil that purpose nicely.

You might even consider requiring a chain or rope, implying that only the blades are held up and a drive belt leads to the alternator, in which case it would be lighter and wouldn't need too much support.

**Comment by davidpwbrown** [comment]
Remove steel boom, replace with 5 pipes. 
no welding as requirement, as with a metal saw and a hammer you can make pipes fit in each other.
@mlangsdorf  thanks for that code, I'll test it.

**Comment by davidpwbrown** [comment]
Tested that code, put a wind turbine on an RV, it's top speed dropped from 108 to 90.
Put three turbines on it, it hardly went above 70.
Is this not severe enough ? or too severe ? or just right?

**Comment by darktoes** [comment]
It's arguable that they would make much difference considering their size. It's probably about right. If you really want to get technical with it, consider calculating the amount of energy that would be generated by the wind turbine from the windspeed due to the velocity of the vehicle, and compare that to the lost extra energy spent accelerating the vehicle due to the drag. In theory, they should be roughly equivalent to satisfy conservation of energy.

**Comment by mlangsdorf** [comment]
Wind turbines aren't 100% efficient and secondary effects can be weird.  For instance, the turbulent air past the turbine is going to affect the vehicle's aerodynamics, but obviously can't be converted to energy by the turbine.

The stock RV weighs around 2000 kgs, so dropping the top speed from 108 mph to 90mph is roughly a 50 kW drop in effective power.  That seems not-crazy.

**Comment by darktoes** [comment]
Unless I've misread/misunderstood something, wouldn't that make the wind turbine ~1000 times more effective as an airbrake than as a wind turbine? That seems somewhat high to me, although I've honestly never tried driving an RV around with a wind turbine attached.

**Pull request merged**
