### PR TITLE
NPCs will try to run away for at least 10 tiles from dangerous items such as armed explosives

### LINKED ISSUE #22770: Friendly NPCs will walk towards live grenades I throw
Game version:
7054
Operating system:
Windows (WINE)
Tiles or curses:
Tiles
Mods active:

### Expected behavior
NPC does not move towards the live grenade I just threw even if there are targets for them to melee, moves away if the blast radius might catch them. Anything intelligent enough to recognize a live grenade or other explosive should begin moving away from the potential blast radius once it's thrown.
### Actual behavior
NPC moves towards the live grenade in order to engage in melee combat with monsters I'm trying to blow up, tries to get blown up along with the monsters.
### Steps to reproduce the behavior
Throw a live grenade at monsters your friendly NPC would advance to fight in melee.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #22770.

### CODE REVIEW

**Comment by codemime** [comment]
The current implementation probably won't work as expected in case of two (or more) explosives in the area. NPCs would run away from the first dangerous item they encounter (`points_in_radius` scans starting from the upper left corner) probably towards their certain deaths from the other items which they would ignore completely. Instead, they should run away from a "center-of-mass" (calculated over all the dangerous items) heading in the least dangerous direction.

**Comment by boydkr** [comment]
Solution would be good enough if it found the closest dangerous item to move away from.  That would greatly simplify the calculation compared to what codemime is suggesting, and probably perform the same is most cases (expect where the NPC is caught exactly between two items)

**Comment by codemime** [comment]
The calculations I was talking about are extremely simple and fairly fast. You basically need to sum up the vectors pointing at each dangerous item, then normalize and negate the resulting vector. It's now pointing at the least dangerous adjacent tile. If the resultant vector happens to be zero, simply take any non-zero vector and move sideways. If no such vector exists, all the dangerous stuff is right under the feet => run anywhere.

**Comment by Night-Pryanik** [comment]
@codemime do you have a working implementation of what you are proposing? I could close this PR in that case, because I'm afraid I don't have enough experience with all that vector stuff.

**Comment by AMurkin** [comment]
Take a look at rl_vec2d struct. That should be easy. Iterate over explosives, sum vectors from directions to them from player.

**Comment by codemime** [comment]
Good point.

**Comment by boydkr** [comment]
Invert as in 1/distance

**Comment by Coolthulhu** [comment]
The expected safe distance of an explosive varies. Maximum force at distance `d` is `power*(distance_factor)^(d/1.1)` and safety is when force is `<1`. NPCs don't need to run from explosives at safe distance.

Note that this iteration over items is potentially very expensive in safe player bases: it happens every turn, checks all nearby items (including those giant piles of craftables), and can't be turned off, unlike NPC pickup.

**Comment by Night-Pryanik** [comment]
> NPCs don't need to run from explosives at safe distance.

I assumed that NPCs ain't no explosives experts. They don't necessarily know exact explosion force or radius of shrapnel, so I thought their behavior should be like "I see armed explosive at a distance I find dangerous - I run!"

**Comment by boydkr** [comment]
> Note that this iteration over items is potentially very expensive in safe player bases: it happens every turn, checks all nearby items (including those giant piles of craftables), and can't be turned off, unlike NPC pickup.

Isn't there a way to short-cut / speed this up by only checking active items?

**Comment by Night-Pryanik** [comment]
To determine if this item is active, you still need to iterate through all the items, right?

**Comment by Coolthulhu** [comment]
> I assumed that NPCs ain't no explosives experts.

The problem is, at the moment NPCs will run in panic from all sorts of weak explosives like makeshift gas bomb or pipebomb. Though my formula wouldn't really prevent running from pipebombs, as I made it overly generous (12 tiles for a pipebomb).

The `move_away_from` function does not consider any dangers in the way. It's a bad function to use for NPCs who have anything to do, as they will get blocked on things easily. I bet you've seen NPCs do the leg melt dance in acid.

Consider the following situations:
* Player throwing a grenade while standing next to a NPC who is supposed to stand ready with a spear. The NPC will then run away, even though the player knows the grenade to be safe at current distance.
* Player laying down a C-4 with huge timer. The NPC may panic and get blocked on a wall until player picks the C-4 up and relocates it.
* Player throwing a pipebomb next to a hostile NPC. The hostile NPC gets blocked on a wall instead of actually running towards the player, where the blast will not reach.

Consider the following alternatives:
* Storing the positions of known explosives. When picking items for pickup or targets to melee (or just doing `move_to`), don't go towards explosives, but still allow going away and standing still.
* Making NPC talking take no time, so that the player can shout "don't attack, stand still" to NPCs.

**Comment by Night-Pryanik** [comment]
All your points are right, of course. 
I just had a feeling (when created this PR) that my (obviously incomplete and imperfect) realization is better than nothing.

**Comment by Coolthulhu** [comment]
Depends on what you want it to achieve. For now I'd keep the status quo, even if just because of the possible performance problems. NPCs running away from explosives in panic can be argued to be better  than NPCs unaware of explosives, but NPCs scanning all items in 121 tile block every turn sounds like it would lead to slowdown in crafting bases.

There was a time when active items had to be scanned for every turn - just checking `bool active` on all items. This did slow the game down heavily when the player had a big stash of items. Checking for `is_dangerous` is more expensive than checking for activeness.

Because of its similarity to active item problem, the same optimization method could be used: noting which items are dangerous when they are added to the map and keeping a set of dangerous items. But implementing that would be rather complex.

**Comment by Night-Pryanik** [comment]
Okay, this seems to be more complex issue that I thought. Potential big performance problem rising is more important, so for now I'd better close this PR.

**Comment by Soyweiser** [comment]
Would a better solution be to only trigger the check for 'if active' when an object is thrown? Throwing happens rarely, and normally you throw stuff like explosives etc. Then as an added bonus you could even make it possible for the game to 'trick' NPC's by throwing grenades etc who are not active yet. (If somebody throws a handgrenade at you, you don't check if the pin is out before ducking).

**Comment by Soyweiser** [comment]
Ideally we prob need a function like 'move out of line of sight of location' right? Compared to the 'move_away_from' function.

**Comment by Night-Pryanik** [comment]
> Would a better solution be to only trigger the check for 'if active' when an object is thrown?

Some explosives such as C4 are usually placed (dropped) rather than thrown.

**Comment by Soyweiser** [comment]
Yes, those will then still explode NPC's. Perhaps if we then also include a 'RUN!' shout command (which if you don't have to much mouth enc, makes friendly NPC's run away). And add a check for 'is dangerous' every time an npc walks onto a square. (which makes it run away next turn). So that way if an NPC walks onto an active explosive it still runs away, but it isn't that computationally expensive. (could still be excessive with a high number of npcs and items around btw).

**Pull request closed without merging**
