### PR TITLE
Fix incorrect color definitions

### PR DESCRIPTION
**Pull request by illi-kun**
This PR fixes the following issues reported in debug.log:

------
1)
```
23:42:16.569 : couldn't parse color: i_dark_gray
```

Fixed by removing of double underscore from ```src/color.cpp```

--------
2)
```
23:42:18.95 : couldn't parse color: c_dgray_brown
```

Fixed by changing railroad tie color in ```terrain.json```

-----------
3)
```
23:42:18.712 : couldn't parse color: c_gray
```

Gray is not a valid color, replaced by ```light_gray``` in ```chemicals_and_resources.json```

------------
4)
```
23:42:22.795 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
23:42:22.795 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
23:42:22.796 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
23:42:22.796 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
```

Fixed by replacements of ```ltgray``` by ```light_gray``` in ```/magazine/9mm.json```

-----------
UPD: expanded description added.

### CODE REVIEW

**Comment by Leland** [comment]
Part of #14808, presumably

**Comment by illi-kun** [comment]
Totally no. Current fix do nothing with color manager at all, it's a fix of some particular issues with color definition in json (excluding fixing of double underline in code, but this issue appears after #14808 was created).

**Comment by ZhilkinSerg** [comment]
Duplicate underscore was introduced by me in #22572.

**Comment by illi-kun** [comment]
>(if not all)

Take a look on changes of ```items/magazine/9mm.json``` in current PR, it fixes the rest of old-format colors.

**Comment by illi-kun** [comment]
I've updated the initial message for more details, if it helps.

**Comment by ZhilkinSerg** [comment]
> I've updated the initial message for more details, if it helps.

Thanks!

**Pull request merged**
