### PR TITLE
[MoM] Update everglow matrix lighting recipes

### PR DESCRIPTION
**Pull request by Standing-Storm**
#### Summary
Mods "[MoM] Update everglow matrix lighting recipes"

#### Purpose of change

When I initially made these recipes, electrokinesis wasn't in the game yet. However, electrokinetic crystal makes much more sense than pyrokinetic crystal if we're talking about electrical power efficiency. 

Also, the power draw needed to be updated to account for power draw changes in flashlights and electrical lanterns.

#### Describe the solution

Change the refined pyrokinetic crystal in the recipes into refined electrokinetic crystal. Change the power draw to match the new power draw values (1/4th the non-matrix versions). 

#### Testing

Changes reflected in-game.

### CODE REVIEW

**Comment by emixa-d** [comment]
Perhaps they could require some photokinetic dust as well? Since it is about electric->light conversion efficiency, both the 'electric' and 'light' part might play a role I think.

**Comment by Standing-Storm** [comment]
I thought about that, but there's a snippet about these items:

<details>  <summary>Spoilers</summary>
They were a prototype that never went furher becuase the director of researcher's response was "Do you know how expensive matrix crystals are? Do you know you can go to Home Depot and get some LED bulbs and they'll last for 15 years? What the hell are you all doing?" 
</details>

...so they were never really refined.

**Comment by emixa-d** [comment]
> I thought about that, but there's a snippet about these items:
>[...]
> ...so they were never really refined.

So, their efficiency could in theory be increased even further?

If my sloppy calculations are correct (it's surprisingly hard to find good numbers on the wall-plug efficiency of flashlights, of the type 'light output(watt)/energy input(watt)')

), then they already produce more light than energy gets in. Now hook it up to a solar panel, and you have infinite power, _without_ using a matrix crystal

Reasoning:
 * modern flashlights are made with LEDs
 * modern LED lamps convert 40% of the input energy in light (60% is heat)  (https://lamphq.com/led-heat-generation/)
 * -> output normal flashlight = input normal flashlight /0.4
 * I assume the different shape of flashlights / lamps doesn't cause losses (good positioning of optics and LEDs?)
 * a matrix flashlight requires 1/3 times the input power for the same light intensity (computed by dividing statistics of cata flashlights: 1/3 = (390 mW/225 cata light unit)/(1560 mW/300))
 * (equivalently: 3 times the light intensity for the same input power)
 * -> output matrix flashlight = input matrix flashlight * 3/0.4
 * -> a total efficiency of 750%: 3/0.4=7.5 
 * even after accounting for inefficiency of solar panels, that's still a lot and >1

While I recall a lore snippet that uses a crystal for infinite power (cars IIRC, also laser rifles), I don't think a little bit of dust is meant to be that powerful.

**Comment by Standing-Storm** [comment]
> While I recall a lore snippet that uses a crystal for infinite power (cars IIRC, also laser rifles), I don't think a little bit of dust is meant to be that powerful.
> 
> Edit: it would get even worse/better if this research was continued (e.g. by using photokinetic dust).

Both of these are actually true--it is possible to use matrix technology for infinite power generation (though PHAVIAN never got it working without serious problems on anything more than a small scale), evident in the laser rifle, the shield belts, and Project COBALT RAIN, and with further research (with appropriate facilities and a team of scientists) you might be able to make a flashlight that lasts forever and is brighter than a standard flashlight.

That said, these have a lower draw on the battery but the amount of power used by the light to produce its illumination is nearly the same, with the refined electrokinetic crystals making up the shortfall (that was the initial logic of using pyrokinetic crystal--they produce some power themselves, and the battery was included to cover what was left).

**Pull request merged**
