### PR TITLE
Keffiyeh covers head too

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Its `HOOD` flag already allows it to automatically cover your head when needed.

**Comment by Night-Pryanik** [comment]
> Its `HOOD` flag already allows it to automatically cover your head when needed.

Yeah, but it will work only if your head is unencumbered, yet it maybe needed to wear keffiyeh and other headgear and sum their warmth.

**Comment by kevingranade** [comment]
If you make it cover head always, that removes its most distinctive element which is it's flexibility.
Is there a more nuanced way we could handle this?

**Comment by Night-Pryanik** [comment]
Honestly I'd remove the `HOOD` flag as I think the "normal" way to wear it is to put it on head (I could be wrong, though). That's the simplest way.
More complex way is to add something like `Keffyeh (full)` to make it similar to scarves (loose and tight) and add possibility to player to manually change the form and characteristics of it.
The most complex way is to add game mechanics to unbutton or fasten (or analogues of these actions) almost all types of clothing and armor at will.

**Comment by kevingranade** [comment]
I think Rivet' s comment really sums it up, AFAICT it's intended to be worn alone, so the HOOD flag is a perfect fit.

**Pull request closed without merging**
