### PR TITLE
opaque hatches

### PR DESCRIPTION
**Pull request by valuial**
Add opaque hatches.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
It should become craftable or be part of some existing vehicles.

**Comment by valuial** [comment]
hatches - and in the mod heavy duty hatches - are already attached to vehicles using frames. I did the same with the opaque hatches - you just have to have a frame/heavy duty frame nearby to create them on the vehicle.

If you mean you should first craft an item, then this should be done in an extra PR as that would not just add the opaque version of hatches but also change the behavior is it is at the moment..

About adding opaque hatches to vehicles... I don't know that much about military vehicles irl, so I leave that to someone else. I don't see me making the decision where existing hatches should be changed to opaque ones. Just building the foundation to be able to.

**Comment by Night-Pryanik** [comment]
You just create some content, but there's no way to see it ingame. I think that's not very good practice.

**Comment by flitvious** [comment]
I always thought that hatches on military vehicles (armored ones) should provide limited field-of-view from the inside, and be totally opaque from the outside.

For example, these back doors on BMP-1. The round thing in the center is a firing port, two things on top of the door are periscopes.
http://www.tanks-encyclopedia.com/coldwar/USSR/photos/BMP-1_reardoors_Compt_Panzermuseum_Munster_2010.jpg

**Comment by Coolthulhu** [comment]
Pretty sure that vehicle parts don't need a recipe. Since those use frames, they can be built with the same parts as regular hatches.

There is no reason for the opaque hatch to have better durability than the regular one, though.

**Comment by valuial** [comment]
@Night-Pryanik thats simply not true. It is no Item I made it is a vehicle part, created simply with frames. Using my changes I can already use them ingame.

@flitvious For hatches to be a one-way see through there would be some additional changes needed... I don't think thats inside the scope of my current abilities.

@Coolthulhu I thought that see-through parts would be either some form of glass or slits, which would decrease the durability by creating weak points - if only very slightly (less than 10%?). Then again I can easily change that back...

What I wonder about in hindsight is rather why I put the heavy duty version into the mod. Was that changed recently?

**Comment by valuial** [comment]
git blame indicates it didn't change for years... Must have been a bad dream then. - all hatches back into the game proper then.

now another one to pick if same-value durability is really what's desired...

**Pull request merged**
