### PR TITLE
Merge Aftershock and Bright Nights, add new Fast Healing mod

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: Mods "Merge Aftershock and Bright Nights mod"

#### Purpose of change
Aftershock and Bright Nights are incompatible, and I sought to rectify that in #30859. Kevin said that I should instead merge the mods instead of making them compatible, and so I did that here.
I added the fast healing mod to have the fast healing from Bright Nights, without forcing that on players who did not want it. 
I also deleted the old rechargeable batteries from Bright Nights in favor of the ones in the base game now. The recharging station was removed for the same reason.

#### Describe the solution
Merge the files of Bright Nights and Aftershock. Add Bright Nights to replacements.json, where it is replaced with Aftershock. Replace the batteries from Bright Nights with heavy batteries in existing savegames using `data/json/items/migration.json`.

#### Describe alternatives you've considered
Merge Aftershock into Bright Nights, or make one dependent on the other.

### CODE REVIEW

**Comment by tinukedaya** [comment]
So.... it's going to be After Nights now? Or Brightshock?

**Comment by Night-Pryanik** [comment]
Aftershock of the Bright Nights.

**Comment by YukariMindGap** [comment]
AfterBright sounds better imo

**Comment by ifreund** [comment]
Pretty sure it'll just be Aftershock, up to @Ilysen though really.

**Comment by Ilysen** [comment]
I'm a tad against this due to reasons I've outlined before. In general, I don't think Bright Nights' very prevalent sci-fi like municipal reactors, common nuclear-powered cars, and homemade laser guns fits the atmosphere I was aiming for with Aftershock. Not adding my changes to BN was a deliberate choice, because I felt that the two mods aimed for different atmospheres, and Aftershock's clashes with that.

I'm okay with those things, though, if the majority outweighs my thoughts here. If people really like atomic cars, then I'm fine with keeping them, for instance. My only main request is that the name Aftershock be kept because it's neat and I like it and don't hurt my baby *cough*.

I suppose this could also serve as an excuse to finally spurn me to start doing a little more work on the mod, if nothing else.

**Comment by kevingranade** [comment]
The options are delete one or merge them, we don't need two abandoned scifi mods.
If someone decides to take up maintenance they can do whatever they like with their actively maintained mod, including splitting out whatever content they don't feel fits with their desired theme.
For what it's worth I think Aftershock is the better name.

**Comment by Ilysen** [comment]
I've had some time to think about my stance and how my paranoia influences things, and I think I could probably do more work on it. I have some work on my hard drive I've never bothered to update, so I could possibly adapt that.

**Comment by dissociativity** [comment]
Is the faster healing really necessary when you can already recover from near-death overnight pretty well on vanilla values?

**Pull request merged**
