### PR TITLE
Death drops

### PR DESCRIPTION
**Pull request by Reclusive-reptile**
Updates the tank drone to drop the correct ammo for its M4 carbine, and updates the survivor zombie's death drops so the firearms have magazines.

### CODE REVIEW

**Comment by Reclusive-reptile** [comment]
So apparently I don't understand how forks work. Those first 2 commits were my attempt to keep the fork up to date and they are not supposed to be in this pull request.

**Comment by DaliTimelord** [comment]
You are updating your fork (Death-Drops) you plan to merge with the upstream master (CleverRaven). You'll have to make another fork from Death-Drop, and update separately. Or, you could make another fork off of your local master (Reclusive-Reptile).

**Comment by Reclusive-reptile** [comment]
So I should not have pull requested the CleverRaven/master into my Reclusive-reptile/master and then created the death drops fork?

**Comment by Soyweiser** [comment]
Which command do you use to update your master? I think you need to fast forward or something. I use (while working in my local master branch) `git pull --ff-only upstream master` with upstream being the cleverravenCDDA repository.

**Comment by DaliTimelord** [comment]
Reptile you want to keep your master clean. You use your master to keep up to date with the origin master (CleverRaven). Your then make forks off of your own master, edit those forks, then when done have a merge request between your fork and origin master (CleverRaven). 

Once your own fork and master are separated, you don't want them to merge again. However, feel free to commit personal changes to your fork. This usually means you don't update your fork when trying to update your master.

**Comment by Soyweiser** [comment]
I think where you say fork you mean branch right?

**Comment by DaliTimelord** [comment]
Ah yes, fixing now.

**Comment by Reclusive-reptile** [comment]
Okay, thank you for the advice. Closing this pull request while I "git good", as it where.

**Pull request closed without merging**
