### PR TITLE
Snow Cones For Alcoholics

### PR DESCRIPTION
**Pull request by TheMurderUnicorn**
#### Summary
Content "Add Alcoholic Snow Cones"

#### Purpose of change

I added snow cones in #73916 and said I would add alcoholic versions of snow cones, so I did that.

#### Describe the solution
I made an alcoholic snow cone item, which is weak alcohol but made from strong alcohol (because it makes 3, so it would be diluted so to speak).  I added a recipe for this snow cone, allowing for a variety of juices/sodas to be used as flavoring and various hard alcohols to be used for the alcoholic component.
#### Describe alternatives you've considered
Allowing beer, but my reasoning was as follows: I did not add beers/ales/similar brewed alcohols to the list because one, it would be disgusting to make a beer strawberry snowcone or whatever.  But also two, that the alcohol content in a beer is much lower than liquor/the other alcohols, and so the resulting alcoholic snowcone would end up basically tripling your drunkenness potential despite watering down the booze with ice and other drinks and making 3 snowcones from one portion of booze.  This is also why mead doesn’t appear, despite being sweet, the weak alcohol part sort of messes things up.

#### Testing
I tested the names extensively.  Some of them are not perfect but our control over the order is extremely limited.  Additionally, there's no way to search ALL components of ALL ingredients for a specific id, it instead searches for anything containing that string.  IE: "apple" can be specified if its the core ingredient.  BUT you can't search ALL components for apple, because instead of using anything with the id of apple, it would instead accept anything that contains the word apple, so it would catch pineapple, crabapple, etc, despite them not having the exact string.  That might not make sense in text... but it just doesn't work the way you want it to, basically x_x

Anyway, point is, some of the names are wonky, specifically apples, I mentioned this as well in that original PR of #73916 as snow cones have the same issue.  Most of the names print perfectly, some get a bit complicated with long ingredient names (looking at you solomon's seal triple sec snow cones) and blah blah.  But it's not anything problematic in my opinion.

On another testing note, I finished this like a week ago but didn't submit it, and although I did a final testing pass, it's possible I missed something because I walked away and forgot something.  Let me know if you see any glaring issues.

#### Additional context
I guess I sort of added most of the additional context in the above sections.  Again, check the original PR for additional information.

On another note: I did not add fruit wine to possible list of alcohols, due to this being player-crafted from various fruits, this will break the contextual naming and cause duplicate fruit names to appear.  IE: it would output something like grape grape wine snow cone.

"Why wasn't [insert alcohol or mixed drink] added to the list?" - Basically anything that's weak alcohol is not viable, as mentioned above, because it would let you take one portion of weak alcohol, and convert it to something that's 3 portions of weak alcohol.  As we only have two flags for alcohol, there's not much I can do about this other than exclude those things from possible components.

Screenshots: 
image
image

### CODE REVIEW

**Comment by Maddremor** [comment]
Why are not requirement groups used here? (Applies to the original snow cone PR too, but I was not present for that.)

**Comment by TheMurderUnicorn** [comment]
> Why are not requirement groups used here? (Applies to the original snow cone PR too, but I was not present for that.)

I'm not sure what you mean by requirement groups, can you elaborate?

**Comment by TheMurderUnicorn** [comment]
Also as mentioned I had to hand pick/avoid certain liquors, so I do think actually having a liquor group would be applicable to other recipes/useful, in this case certain alcohols had to be left out.  IE: I can't have a group that contains all wine, because this recipe can't use the player-crafted wine without breaking the contextual naming.  So even though having a wine or liquor group would be useful for the project, this recipe should have them manually chosen.

**Comment by TheMurderUnicorn** [comment]
Updating this to use sweet_juice has now opened the door for the naming convention being broken if someone were to add other things to that list in the future.  I also left kompot out for a reason, I thought, though I don't recall why now.  I do not understand this change being made when I had offered a rebuttal on why I didn't change it and it effectively would only save a few lines in the json.  You also removed a large number of sodas?  it looks like?  without any discussion or reason why? I am confused, now.

**Comment by Maddremor** [comment]
IMO, it's less about saving a few lines than it's about not having to track down this specific recipe and update it if more sodas were added.

**Comment by TheMurderUnicorn** [comment]
That's fair.  And I guess it's like, well, if it breaks someone can fix it.  I'll make a PR to update the basic snow cone when I have some time

**Comment by Maddremor** [comment]
Eh, I'm just a lowly Discord moderator. This is just my opinion.

**Comment by Maleclypse** [comment]
> Updating this to use sweet_juice has now opened the door for the naming convention being broken if someone were to add other things to that list in the future. I also left kompot out for a reason, I thought, though I don't recall why now. I do not understand this change being made when I had offered a rebuttal on why I didn't change it and it effectively would only save a few lines in the json. EDIT: I did not see that you also converted to use a soda group, that is my mistake. EDIT 2: I guess I didn't offer much rebuttal previously, so okay. I do think this opens the door to breaking the naming to basically save a few lines, which to me isn't worth it but idk

Are you sure you left out kompot?   I may have miscounted but I literally only did those two lists and not the alcohol lists because I was handing matching every item in the list as already existing in the recipe.  One second I can go check the commit history.

**Pull request merged**
