### PR TITLE
Changes ant egg nutrition

### PR DESCRIPTION
**Pull request by Dozed12**
Lowers ant egg nutrition, it was way too much, sure is a giant egg but is it more than twice as nutricious than a royal beef?

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Well it does contain all the stuff necessary for the baby (gigantic) ant to grow, so I'd say it should probably be *positively overflowing* with nutrition.

**Comment by Dozed12** [comment]
I probably exagerated with the change but a royal beef is 80 and an ant egg is 200. Maybe 100 would be better.

**Comment by kevingranade** [comment]
How about comparing it to some non-fake food? The only reason royal beef
exists is to let carnivores consume a critically important item.

**Comment by Frost-wood** [comment]
Rivet does have a point.  Raw eggs should have a chance of a poison effect through due bacteria, because of the lack of pasteurization.

**Comment by Dozed12** [comment]
You do have a point.

http://www.safeeggs.com/blog/eating-raw-eggs-look-for-the-word-“pasteurized”-on-your-egg-carton/

**Comment by kevingranade** [comment]
Yes, someone feel free to add salmonella... from giant ants.

**Comment by DavidKeaton** [comment]
Sal-Mound-Nella (such bad joke)

**Comment by kevingranade** [comment]
Also I just can't help myself, you notice the complete and utter lack of figures that have any bearing on the risk of salmonella infections on that website?  There's a reason for that, if they give the numbers along with the warnings, people have a tendency to ignore the warnings, because the chances of getting salmonella from eggs is freaking astronomically small.  I really hate this scare tactic bullshit.

**Comment by DavidKeaton** [comment]
Salmonella tends to be most common in meats iirc

**Comment by kevingranade** [comment]
The salmonella-egg thing is because chickens are carriers for it, so eggs
laid by carriers are inoculated with it, ants wouldn't be carriers, so ant
eggs wouldn't have it.  This also causes issues with chicken meat of
course.  Both risks are rather overblown though.
We could have salmonella from appropriate sources, but I'd insist on the
infection rates being realistic, i.e. it would hardly ever happen.

**Pull request closed without merging**
