### PR TITLE
Add script for autogenerating mutation documentation to tools/

### PR DESCRIPTION
**Pull request by UmbralReaper**
#### Summary
None

#### Purpose of Change

#51697 

#### Describe the solution

A python script which generates documentation for mutations in the form of a markdown file.

#### Alternatives you have considered.
Properly handling mods with duplicate ids. Currently, if two mods are discovered with the same id, the latter will overwrite the former.

#### Testing
While it should be handled properly, I have not tested the case where a mod is inside another mod.

```sh
$ python tools/auto_doc_mutations.py data/ -o autodoc/mutations.md --include-mods
```
<details>
    <summary>Output (truncated to 150 lines)</summary>

# Table of Contents
- Categories
  - [ALPHA](#alpha)
  - [BATRACHIAN](#batrachian)
  - [BEAST](#beast)
  - [BIRD](#bird)
  - [CATTLE](#cattle)
  - [CEPHALOPOD](#cephalopod)
  - [CHIMERA](#chimera)
  - [ELFA](#elfa)
  - [FELINE](#feline)
  - [FISH](#fish)
  - [GASTROPOD](#gastropod)
  - [INSECT](#insect)
  - [LIZARD](#lizard)
  - [LUPINE](#lupine)
  - [MARLOSS](#marloss)
  - [MEDICAL](#medical)
  - [MOUSE](#mouse)
  - [MYCUS](#mycus)
  - [NONE](#none)
  - [PLANT](#plant)
  - [RABBIT](#rabbit)
  - [RAPTOR](#raptor)
  - [RAT](#rat)
  - [SLIME](#slime)
  - [SPIDER](#spider)
  - [TROGLOBITE](#troglobite)
  - [URSINE](#ursine)

### Dextrous
src: `dda`
id: `DEX_UP` 
categories: `ALPHA`, `INSECT`, `SLIME`
Description: You are a little nimbler.  +1 Dexterity.
### Disintegration
src: `dda`
id: `ROT3` 
categories: `ALPHA`
Description: Your body is slowly wasting away!
### Fast Metabolism
src: `dda`
id: `HUNGER` 
categories: `ALPHA`, `BEAST`, `CHIMERA`, `ELFA`, `MEDICAL`, `MOUSE`, `RABBIT`, `RAPTOR`, `RAT`, `SLIME`
Description: You require more food than most people, but recover stamina slightly faster.
### Good Hearing
src: `dda`
id: `GOODHEARING` 
categories: `ALPHA`, `ELFA`, `MOUSE`, `RABBIT`
Description: Your hearing is better than average, and you can hear distant sounds more easily.
### Junkfood Intolerance
src: `dda`
id: `ANTIJUNK` 
categories: `ALPHA`, `BEAST`, `ELFA`, `GASTROPOD`, `RABBIT`, `RAPTOR`
Description: Something in those heavily processed foods doesn't agree with you.  It's possible for you to eat them, but you will suffer morale penalties and obtain less nutrition from them.
### Less Sleep
src: `dda`
id: `WAKEFUL` 
categories: `ALPHA`, `ELFA`
Description: You need less sleep than the average person.
### Nausea
src: `dda`
id: `NAUSEA` 
categories: `ALPHA`
Description: You feel nauseated almost constantly, and are more liable to throw up from food poisoning, alcohol, etc.  You can, if desired, think yourself into vomiting, too.
### Pretty
src: `dda`
id: `PRETTY` 
categories: `ALPHA`, `FELINE`, `LUPINE`, `RABBIT`
Description: You are a sight to behold.  People who care about such things will react more kindly to you.
### Prime Dexterity
src: `dda`
id: `DEX_ALPHA` 
categories: `ALPHA`
Description: You're perfectly coordinated.
### Prime Intelligence
src: `dda`
id: `INT_ALPHA` 
categories: `ALPHA`
Description: You understand almost everything about which you think, with minimal effort.
### Prime Perception
src: `dda`
id: `PER_ALPHA` 
categories: `ALPHA`
Description: Your senses are keenly honed.
### Prime Strength
src: `dda`
id: `STR_ALPHA` 
categories: `ALPHA`
Description: Your muscles are perfectly developed.
### Robust Genetics
src: `dda`
id: `ROBUST` 
categories: `ALPHA`, `FISH`, `MEDICAL`, `SLIME`
Description: You have a very strong genetic base.  If you mutate, the odds that the mutation will be beneficial are greatly increased.
### Smart
src: `dda`
id: `INT_UP` 
categories: `ALPHA`, `SLIME`
Description: You are a little smarter.  +1 Intelligence.
### Very Little Sleep
src: `dda`
id: `WAKEFUL2` 
categories: `ALPHA`, `BATRACHIAN`, `ELFA`
Description: You don't sleep often.  But when you do, you need very little of it.
### Very Perceptive
src: `dda`
id: `PER_UP_2` 
categories: `ALPHA`, `BATRACHIAN`, `CHIMERA`
Description: Your senses are keener.  +2 Perception.
### Very Strong
src: `dda`
id: `STR_UP_2` 
categories: `ALPHA`, `CATTLE`, `LIZARD`, `PLANT`
Description: Your muscles are stronger.  +2 Strength.
### Weak Scent
src: `dda`
id: `WEAKSCENT` 
categories: `ALPHA`
Description: Your scent is quite weak.  Animals that track your scent will do so with more difficulty.

### Addiction Resistant
src: `dda`
id: `NONADDICTIVE` 
categories: `BATRACHIAN`
Description: Whether due to a lifetime of exposure or through simple willpower, it's harder for you to become addicted to substances, and easier to rid yourself of these addictions.
### Amphibian Pheromones
src: `dda`
id: `PHEROMONE_AMPHIBIAN` 
categories: `BATRACHIAN`
Description: Your body produces low-level pheromones, identifying you as a friend to many species of amphibian.  Amphibians will attack you much less.
### Amphibious
src: `dda`
id: `AMPHIBIAN` 
categories: `BATRACHIAN`, `FISH`
Description: You're as comfortable in water as on land, and your body has adapted around that fact.  Your base swimming speed is greatly increased, and weight will hinder you much less while swimming.
### Aquatic Sleeper
src: `dda`
id: `WATERSLEEPER` 
categories: `BATRACHIAN`, `FISH`
Description: You always sleep better underwater.
### Aqueous Repose
src: `dda`
id: `WATERSLEEP` 
categories: `BATRACHIAN`, `FISH`
Description: Falling asleep underwater is easy for you, and you spend less time asleep when you rest there.  You can also eat underwater, though you can't drink.
</details>

<details>
    <summary>DarkSkies</summary>

# Table of Contents
- Categories
  - [NONE](#none)

### RP: Combatant
src: `darkskies`
id: `DKS_COMBAT` 
categories: `NONE`
Description: You've seen your fair share of scruffs and scrapes, and when the Cataclysm hit, you fought the Occupiers and managed to survive to tell the tale.  Has no direct skill benefit, but allows you to present yourself as a fighter to certain NPCs.  Some might even recognize you.
### RP: Leader
src: `darkskies`
id: `DKS_LEADER` 
categories: `NONE`
Description: Whether or not you like it, you've always had a knack for managing people and have some hard-won skill in doing so.  During the arrival and the ensuing chaos, you helped lead people around you to safety.  Has no direct skill benefit, but allows you to present yourself as a leader to certain NPCs.  Some might even recognize you.
### RP: Medic
src: `darkskies`
id: `DKS_MED` 
categories: `NONE`
Description: Your job or experiences had you seeing all sorts of trauma, both physical and mental, and you were trusted during the Cataclysm to provide life-saving care.  Has no direct skill benefit, but allows you to present yourself as a healer to certain NPCs.  Some might even recognize you.
</summary

### CODE REVIEW

**Comment by UmbralReaper** [comment]
@Maleclypse What would be the best way to support mods? DinoMod, for example, has a lot of mutation entries which are the same mutations, just extended to include new categories.

**Comment by Maleclypse** [comment]
> @Maleclypse What would be the best way to support mods? DinoMod, for example, has a lot of mutation entries which are the same mutations, just extended to include new categories.

Ideally, I think it would pull markdowns into each mod like they have their own readme and even if it's not showing the changes it at least let's someone looking at it know that mutation x has been edited in this mod. But if that's not easy to make happen then I would suggest ignoring mods.

**Comment by UmbralReaper** [comment]
> Ideally, I think it would pull markdowns into each mod like they have their own readme and even if it's not showing the changes it at least let's someone looking at it know that mutation x has been edited in this mod. But if that's not easy to make happen then I would suggest ignoring mods.

So, create a separate markdown file for each mod? Or create a separate category in the one, huge, markdown file, that includes mods?

**Comment by Maleclypse** [comment]
> > Ideally, I think it would pull markdowns into each mod like they have their own readme and even if it's not showing the changes it at least let's someone looking at it know that mutation x has been edited in this mod. But if that's not easy to make happen then I would suggest ignoring mods.
> 
> So, create a separate markdown file for each mod? Or create a separate category in the one, huge, markdown file, that includes mods?

Separate markdown file for each mod.  Again if feasible.  If not feasible better to focus on the baseline DDA.

**Comment by UmbralReaper** [comment]
What is the difference between `allowed_category` and `category`?

**Comment by Maleclypse** [comment]
Kinda weird `"allowed_category": [ "ALPHA" ], // List of category you can mutate into. (default: empty)` So interestingly this function is only used by third party mods.

**Comment by nexusmrsep** [comment]
Any plans to add info on post threshold status of mutation in relevant category?

**Comment by Maleclypse** [comment]
It looks like it's requesting python linting? Which I hadn't seen before but I guess I shouldn't be surprised.

**Comment by ZhilkinSerg** [comment]
Some lines are too long:

```
Error: ./tools/auto_doc_mutations.py:19:80: E501 line too long (81 > 79 characters)
Error: ./tools/auto_doc_mutations.py:179:80: E501 line too long (152 > 79 characters)
Error: ./tools/auto_doc_mutations.py:185:80: E501 line too long (162 > 79 characters)
Error: ./tools/auto_doc_mutations.py:189:80: E501 line too long (89 > 79 characters)
Error: ./tools/auto_doc_mutations.py:231:80: E501 line too long (81 > 79 characters)
```

**Comment by UmbralReaper** [comment]
> Any plans to add info on post threshold status of mutation in relevant category?

Not currently, no.

**Pull request merged**
