### PR TITLE
Rewrite magnet bionic, add move costs to other bionics

### PR DESCRIPTION
**Pull request by Coolthulhu**
Magnet bionic code was quite horrible and unreadable, now it's OK.
Also displays neatly where do the items come from.

Added move costs (100) to most combat-related bionics so that you can't, for example, EMP a tank drone to death without spending any time.

### CODE REVIEW

**Comment by Vidiveni** [comment]
I think the lighter cbm `bio_lighter` should have the same move cost as matches and lighters for consistency. Ordinary lighters have 15 move cost atm if I read the code correctly.

**Comment by Coolthulhu** [comment]
`bio_lighter` allows spawning a fire of any level, not just starting it.

Also, regular lighters will most likely get a significant nerf to speed in some foreseeable future.

**Comment by Vidiveni** [comment]
Fair enough. The burning bush tactic could use the the change.

**Comment by Chezzo** [comment]
Does it work for pulling guns out of NPCs hands now? I always thought it was a shame that zombies could do that to you but you couldn't do that to anyone.

**Comment by Vidiveni** [comment]
Would prefer to not have batteries explode as I feel there are a bit many explosions already in some situations, which slows down the game if playing with animations. It's extra noticable when playing with your (great) soundpack.

**Comment by Rivet-the-Zombie** [comment]
The sort of batteries used in flashlights don't explode with enough force to be truly dangerous when they're burned.

**Pull request merged**
