### PR TITLE
Magic mod [don't merge]

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Mods "Added magic infrastructure: Spellcasting, Spell learning, Spell loading. (Magiclysm)"```
#### Purpose of change

I like magic. I wanted to put it in the game. This was a fun project.
#### Describe the solution

- Implemented generic_factory for a new "SPELL" type, along with spell and spell_type classes mimicking item and itype
- implemented a new spellcasting action and activity that allows you to "cast" a spell with various effects.
this involved making a new targeting function, since the range function prints a lot of stuff to the screen.
- added a new iuse so items can act as spellbooks in order to learn spells
- added "mana" (sidebar panel enabled by external option)
- added documentation for modders to be able to add their own spells into the game
- added Magiclsym - a mod that I will be maintaining that is largely the test bed of these new features.

My brain is tired. I've been working on this for weeks but this is all i can come up with to say about it right now. I will perhaps be able to add more text about it later.
As always, it's a work in progress. The UI may need some work, but the functionality is something I wanted reviewed before I got too much farther.
#### Additional context

Some screenshots of the menus:
image
image
image

image

### CODE REVIEW

**Comment by Vasyan2006** [comment]
Pony mutants will be able to study and cast friendship magic?
Finally!

**Comment by KorGgenT** [comment]
image
most recent version of the casting window

**Comment by KorGgenT** [comment]
i am going to be going through the branch i have and split it up into much smaller portions, probably outlined by the bullet points in the OP.

**Comment by KorGgenT** [comment]
yeesh. this PR is totally messed up with the files. the summary is still valid for reference, though. i am going to close the PR however, as it's going to be split up into many parts.

**Pull request closed without merging**
