### PR TITLE
Adjust Hub 01 environmental suit values

### PR DESCRIPTION
**Pull request by DziugasPraninskas**
### Summary

```SUMMARY: Balance "Adjust Hub 01 environmental suit values"```
#### Purpose of change

Hub 01 environmental suit is:
1. Significantly less encumbering than the hazmat suit.
2. Provides 15 liters of storage, while the hazmat provides none.
3. Has the sturdy tag.

This leads to many players wearing the environmental suit (sometimes reinforced with kevlar) majority of the time, which trivializes radiation hazard.
#### Describe the solution

To bring Hub environmental suit more in line with the hazmat suit:
1. Encumbrance increased from 7 to 20.
2. Removed all storage capacity.
3. Made the suit a bit lighter than the hazmat.

Being an advanced suit created by top-level lab personnel, it still has distinct advantages over the hazmat suit - lower encumbrance and the sturdy tag.

Also fixed the typo: "Hub 01 enviromental suit" changed to "Hub 01 environmental suit".
#### Describe alternatives you've considered

Different encumbrance, protection and storage values.
Not changing the suit at all.
#### Testing

1. Loaded up a game.
2. Spawned a suit.

### CODE REVIEW

**Comment by Maleclypse** [comment]
@John-Candlebury, resident Hub01 expert.

**Comment by Brian-Otten** [comment]
I would try to match the suit more to a customized level B hazmat suit rather than matching it to the current ingame hazmat suits which need some work themselves.

image

I would suggest light encumbrance (8-15 ish), low to zero storage volume, and perhaps ditch the sturdy tag (this depends on how advanced hub 01 is supposed to be)

**Comment by Dziugaske** [comment]
I don't exactly want to give the suit 15 encumbrance, because that's what the cleansuit has. Keep in mind that the Hub 01 suit gives the same radiation protection as the hazmat, while the cleansuit only gives partial protection.

I agree with the warmth value, going to change it.

**Comment by Brian-Otten** [comment]
It being similar to a cleansuit but having the proper/full protection makes sense to me, its what comes from making the suit fully airtight and being high grade.
I'll go with candlebury here and say it having encumbrance 8-10 seems right to me.

I have questions about the storage capacity though candlebury, where/how is the storage integrated into the suit and why don't they just wear external bags/backpacks? I can see where you're coming from with "balancing" it versus survivor gear, but i would go with keeping the encumbrance 8 and then the player can easily wear a backpack over the suit if need be. having the suit have 3-5 L of storage in various pockets seems about the logical limit to me.

**Comment by John-Candlebury** [comment]
Yes keeping the 7 encumbrance and reducing capacity to 5 liters would also be fine.

**Comment by Dziugaske** [comment]
Encumbrance and warmth values are now the same as before. Storage reduced to 5 liters.
I really appreciate the idea of making the suit harder to obtain. Acquiring it on the first mission seemed a bit disappointing to me. I changed the field researcher spawn to a scientist, if you have a better way of changing the first mission to exclude the environmental suit, let me know,

**Comment by Brian-Otten** [comment]
I would tone encumbrance down to 7-8 now that the storage volume has been brought in line, a really thin (but environmentally sealed) outerwear layer of nomex should not be all too encumbering, while it is now still at metal armor levels of encumbrance.
Warmth value should probably still be lowered, 40 seems way too high to me.

Seems good to me otherwise.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I would tone encumbrance down to 7-8 now that the storage volume has been brought in line, a really thin (but environmentally sealed) outerwear layer of nomex should not be all too encumbering, while it is now still at metal armor levels of encumbrance.
> Warmth value should probably still be lowered, 40 seems way too high to me.
> 
> Seems good to me otherwise.

15 seems about right - it is equal to that of duster or raincoat.

**Comment by Brian-Otten** [comment]
Right, just remembered the 15 shown here is unfitted, becoming 7 when fitted.

**Pull request merged**
