### PR TITLE
Butchery requirements 3

### PR DESCRIPTION
**Pull request by souricelle**
#### Summary

SUMMARY: Bugfixes "Jsonize butchery requirements update from https://github.com/CleverRaven/Cataclysm-DDA/pull/42372"

#### Purpose of change

This change adds optional surface requirements to butchery.json and butchery_requirements.json that will make "clean surface" tools non-mandatory for butchering. Instead, work speed will merely be a bit slower if the player does not have a clean surface tool.

#### Describe the solution

As stated above, plus a small error was fixed in the older butchery_requirements.cpp which had caused it to look at the butchery speed values in the wrong order.

#### Describe alternatives you've considered

N/A

#### Testing

After consulting with Snup and bugfixing the butchery_requirements error, I spawned a new survivor and several corpses as well as a scalpel and some surface items and determined that the change reliably functions as intended.

#### Additional context

Currently butchery speed is set in the jsons as 1.2 without a surface and 1.0 with. This means that with a surface, the player will have butchery speeds in line with what they had been prior, and without a surface the actions will be a bit slower. This can be adjusted by changing them to 1.0 and 0.8 respectively, which would make butchery surfaces add a speed bonus rather than penalizing the player for not having them.

### CODE REVIEW

**Comment by I-am-Erk** [comment]
So the main thing I see is that, for at least most of the field butchery, we need a couple cases.

- dismemberment should just not care
- field dressing should care a tiny bit, it should be a bonus not a penalty to have a surface.
- dissection should matter a fair bit because of the ergonomics
- quick butchery should care, but it should be a choice. Either a hanging tool *or* a surface should give you full speed, and having both might offer a tiny speed boost. Having neither would be a slowdown.
- full butchery should be the same as above but not as extreme.

The speed penalty should be more pronounced the larger the corpse. Small corpses should benefit from hanging or having a surface, but not so much so that most players are going to care. Butchering a pig without hanging or laying out on a table is where it should start getting tough.

**Comment by KorGgenT** [comment]
not yet but i can follow up this PR with it, i've got to do some minor alterations with the json loading and having this in place will help me more than hurt me

**Comment by I-am-Erk** [comment]
Fair, let's just leave this one to fix the basic problem of the surface requirement then

**Comment by KorGgenT** [comment]
image

**Comment by souricelle** [comment]
I believe I've fixed the lingering issue thanks once again to Snup. Let me know if it needs anything else.

**Pull request merged**
