### PR TITLE
Adds a missing upwards staircase to the collapsed tower

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
Bugfixes "The collapsed tower's lower level now has an upwards staircase"

#### Purpose of change

There is a downstair in part of the collapsed tower that leads to a small, enclosed room. It seems like there's meant to be a staircase there, but because an upstair doesn't exist in the mapgen, it instead has a sheer drop. This also means that it is possible to softlock and trap yourself on the lower floor forever if you fall down or don't bring a way up.

#### Describe the solution

Added an upstair to the collapsed tower's palette and inside of the room, which lets players climb to the lower level as well as escape it if they fall into it through one of the holes in the ground on the top floor.

#### Describe alternatives you've considered

N/A for the issue at hand. There are some other problems with the collapsed tower mapgen that appear to be caused by the `bash` runs (like a bunch of empty tiles in the floor), or the deliberate holes not being ones you can climb down even though they're only one z-level down, but this is fine for now.

#### Testing

1. Create a debug world and spawn in a distant collapsed tower.
2. Jump to the tower and find the downstair near the trapped tendrils. Observe that it warns about a sheer drop, and the lower level has no way out.
3. Quit out, apply changes, and try again. You can now freely climb to and from the lower level without breaking your legs.

#### Additional context

N/A

### CODE REVIEW

**Comment by haveric** [comment]
I assumed this was by design when I went through it, since the tower has collapsed, forcing you to use an alternative means of getting down and back up safely (grappling hook, ladder, building stairs back up), but if not, then this is a nice change.

**Comment by Ilysen** [comment]
That's something that'd come to mind for me, too. I ultimately figured that it was probably a missing stair rather than a deliberately excluded one, just due to the enclosed room and the downwards staircase being present just above it. I think that'd make it the only place in the game that would have a deliberate downstair with no corresponding upstair; I figure that if it was intended to be deliberate, there'd be a ledge or open space there, instead of a staircase.

@John-Candlebury You made this locale; is the missing stair intentional, or unintentional? I'm totally fine closing this PR if it's actually intended

**Comment by John-Candlebury** [comment]
Hmm so the intention is that you should need to find a way to climb back, 
Im not sure why the grappling hook cant be deployed under the elevator shaft, the overgrown floors probably count as indoors by mistake

**Comment by Ilysen** [comment]
gotcha; I'll close this then! for the record, the elevator shafts *do* appear to work, but the many holes that exist on the ground floor all over the place do not. I'm not sure those holes are actually intended to exist, but due to the `bash` uses, they appear all over the place. I think that's a recent thing; they appear in other places like the vandalized library too, where I *know* they shouldn't exist.

**Pull request closed without merging**
