### PR TITLE
Migrated combo gun

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
A note: I cannot use the ci.narc.ro linter due to a possible GitHub website issue connected to the web editor.

**Comment by BorkBorkGoesTheCode** [comment]
Well that is over.

**Comment by BorkBorkGoesTheCode** [comment]
I'm being trolled.

**Comment by mugling** [comment]
Alters too many unrelated lines. Please resubmit as a new PR in a single commit.

**Pull request closed without merging**
