### PR TITLE
Nutrition as calories [WIP]

### PR DESCRIPTION
**Pull request by Zireael07**
Bringing nutrition closer to what Kevin imagined in https://github.com/CleverRaven/Cataclysm-DDA/pull/13847#issuecomment-152223236

One step at a time.

:eyes: necessary because I don't really understand how nutrition and charges work. Help?

Also missing data for some of the foods, i.e. spezi, the Japanese cuisine, sauerkraut...

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It would be good if you used a "calories" tag instead of "nutrition" tag.
That way we could easily tell apart "old nutrition" from "new nutrition" when loading the items, add some sort of scaling and prevent the cases where some forgotten items now have nearly 0 caloric value.
This new tag isn't implemented, but that isn't much work (unlike manually finding entries with old or new values).

Charges in food work like this:
When an item is charged, its volume is divided by default charge number and multiplied by current charge number. Weight is multiplied by charge number but not divided.
So 4 units of granola (8 charges, 2 volume, 86 weight) will have 1 volume and 344 weight.
Each charge is consumed for full nutrition, so if you had say, jerky with 10 charges and 10 nutrition, that's 100 nutrition total.

Some charged items (stuff like popcorn) ended up with uselessly low calories here. If they get below 100, it's sometimes a good idea to "normalize" them by dividing charges by some number and multiplying nutrition by that number.
When "normalizing" them like that, their morale and health effects should be multiplied too, but not as much as nutrition (say, halfway there - when halving charges, bump morale by 50%).
Though items mostly useful as ingredients or drugs shouldn't get that treatment.

**Comment by Zireael07** [comment]
@Coolthulhu: I can move the calories to a new tag but don't expect it today - I spent half the day on it and my eyes and brain are tired :(
Also, if we used a new tag, someone else would have to write the C side of things - I can only do JSON stuff and bounce ideas.

**Comment by kevingranade** [comment]
My comment was super vague, sorry.  What I was trying to say is that
nutrition should be directly related to Calories, e.g. 1 nutrition == 25
Calories, but I don't know what that equivalence should be offhand*.
That having been said, having 1 nutrition == 1 Calorie would be pretty much
ideal if you want to tackle it.
I agree with Coolthulu that we need a new label for it in json so we can
manage the transition, if you're not up to making that change I can whip up
a PR for adding the new label and you can build on top of that.

*I've thought about it a bit more, and the equivalence should probably be
something like 1:25 to 1:30, because IIRC the player burns through 100
nutrition a day, and the caloric equivalent of that is 2,500 - 3,000
Calories (for someone being very active, which is what we assume until we
start factoring in additional energy expenditure for exertion).

**Comment by Zireael07** [comment]
@kevingranade: That would be very welcome - once the code for a new label is in, I could pick this idea back up. And the 1:30 equivalence sounds good.

**Comment by Coolthulhu** [comment]
Having the calorie tag always have the IRL values and only dividing them inside code would make it more clear to modders (and easier to copy+paste stuff).
Even more: we could have the calorie tag always have value per 100 grams and multiply it (by weight, charges etc.) on the code side. That would make it very intuitive, without making it much harder to implement.

**Comment by Zireael07** [comment]
@Coolthulhu: Good points :)

So this is put on a back burner now, waiting for the label + code PR first.

**Comment by kevingranade** [comment]
I'm not a fan of the value being 'Calories per gram' or similar, just look
at the confusions around charges.  'Calories per serving' is IMO more
likely to be set to the right value.

**Comment by Zireael07** [comment]
Well, if we have 'calories per serving', the value of 'serving' should be standard - is it 250 ml for liquids (except alcohol)? What's the standard for non-liquid stuff?

**Comment by Coolthulhu** [comment]
> What's the standard for non-liquid stuff?

There isn't one. Junk food has much lower serving sizes than bread, which in turn has a lower serving size than cooked meat.
For solid foods, the serving size is equal to weight.

> is it 250 ml for liquids (except alcohol)

Currently it's `250 ml / default charges`. Most "thin" liquids have default charges equal to 1, but alcohol, chemical stuff, vinegar, oil etc. have more.

**Comment by Zireael07** [comment]
Net problems mean I can't get around to rebasing this and continuing work... :(

**Comment by Zireael07** [comment]
My internet still sucks. If anyone is interested, feel free to grab the data and submit a PR.

**Comment by Zireael07** [comment]
A ton of PRs went in, making this unmergeable.

My net still sucks.
Anyone interested can grab the databases and work on it :)

**Pull request closed without merging**
