### PR TITLE
Barbaran Montante martial art and WBLOCK_1 on heavy sledge

### PR DESCRIPTION
**Pull request by MylieDaniels**
#### Summary
Content "Adds new heavy weapon based martial art, Barbaran Montante, and adds WBLOCK_1 flag to heavy sledge hammers."

#### Purpose of change
This adds a new martial art entirely based on the 16th century writings of Luis Barbaran II and the subsequent style of heavy weapon fighting that countered heavy armor, primarily because there was a notable lack of engaging melee styles for this group of weapons (heavy blades and hammers) and niche of combat (countering heavy armor via one-on-one combat).  In addition, while testing, the heavy sledge was found to lack a blocking tag, and adding that tag allows it to block before the slow attack finishes and prevent constant interrupts, allowing a very niche use as a slow high-bash weapon (useful but not too powerful against Skeletal Juggernauts, for example).

#### Describe the solution
Barbaran Montante uses heavy weaponry in an engaged fashion, allowing the player to choose their techniques by either moving or pausing.  It does not deal well with multiple enemies, unless dealing with lined-up enemies in chokepoints (based on original real world text), by lacking additional blocks/dodges but having an impale technique.
The style focuses on armor penetration and either movement into knockback or pauses into heavy armor piercing strikes, depending on the situation and player preference.

Name | Level Available | Type | Effect
--- | --- | --- | ---
Barbaran Represa | Melee 0 | Static Buff | +75% Str armor penetration
Reversing Destreza | Melee 1 | OnBlock Buff | -5% movecost, Stacks: 2, Duration: 3
Impaling Estocada | Melee 2 | Melee Tech | +10% Cut & Stab, +20% movecost, Impale only, Min 8 Cut
Swift Atajo | Melee 2 | Melee Tech | -33% damage, -50% movecost, Disarm only
Ricasso Step | Melee 3 | OnMove Buff | Blocked damage reduced by 40% of Str, Stacks: 3, Duration: 3
Vulgar Preparation | Melee 4 | OnPause Buff | +15% of Str to accuracy, +225% Str armor penetration, Duration: 1
Movimiento Natural | Melee 5 | OnKill Buff | +1 Block attempts, Duration: 5

**Barbaran Represa** (Barbaran Footwork) represents the Represa footwork style of Barbaran's teachings.
This is admittedly a very focused static buff, which solely grants armor penetration and nothing else.

**Reversing Destreza** (Reversing Dexterity, or Reversing Stance) aims to replicate the heavy blocks that are used in Barbaran Montante, representing them throwing the opponent off-balance by speeding up the player slightly.

**Ricasso Step** (Flourish/Guard Step) is focused on a powerful block, but the style has only one block (conditionally 2, see Movimiento Natural), representing the style's lack of options for being surrounded but good coverage against a duelist.
This buff reduces blocked damage (from the style's single, weapon-dependent block) by 120% when fully stacked.

**Impaling Estocada** (Impaling Thrust) represents the style's usage of thrusts.  This technique provides an option for impaling when properly chokepointing enemies, which is the style's only way of countering groups of enemies.

**Swift Atajo** (Swift Disarm/Counter) provides a Disarm option (I found references to "atajo", or "the short interception", in Iberian fighting manuals), which doubles as a rapid attack- however, it can only trigger once per enemy and only if they were wielding a weapon, and is not a substantial buff despite it's technical increase in DPS.

**Vulgar Preparation** (Common Preparation) represents less of a pause and more of a slow swing that is beginning during the pause.
Rather than enabling powerful techniques, this buffs existing techniques.

**Movimiento Natural** (Natural Movement) aims to provide a unique buff that is not out of the scope of reality- a practiced sword fighter's confidence after reducing the number of enemies to deal with could theoretically provide (admittedly only a bit, not this much, but it is a game) a performance increase.

The style may be selected as part of Melee Weapon Training, or a training manual may be found, generating very rarely in the exotic_books pool or moderately rarely in the mansion_books pool (to represent the manual's status as a historical artifact).

#### Describe alternatives you've considered
Include underutilized "lategame" weaponry in other styles, such as Medieval Swordsmanship or Fior de Battalegia.

#### Testing
Four days testing at various stat and skill levels versus various enemies or groups of enemies with a variety of armor, encumbrance, and weapons split over three iterations of the style.
Overall findings are that the style is highly effective in one-on-one combat with brutish melee attackers and helps when dealing with high armor "miniboss" enemies, but falters rapidly when either faced by multiple enemies, not taking advantage of all the techniques, or simply outclassed by enemies that should not be fought in melee (such as a shoggoth).
I would rate it as most closely comparable to Niten Ichi-Ryū.

#### Additional context
The following is a Spanish research paper on the fighting style, which includes in the documentation the most complete manuscript of the original training manual I can find.  For IP sake, I am linking the entire paper rather than screenshotting the training manual.  The title translates approximately to "The Nine Rules of the Two Handed Sword, and the Practice of Fencing near Saragossa in 1526".
[LAS NUEVE REGLAS DE LA ESPADA DE DOS MANOS, Y LA PRÁCTICA DE LA ESGRIMA EN ZARAGOZA HACIA 1526](https://gladius.revistas.csic.es/index.php/gladius/article/view/300/303)

### CODE REVIEW

**Comment by actual-nh** [comment]
Ping: @Hymore246?

**Comment by QuintusAquila** [comment]
Could you format the techniques/buffs like this:
https://github.com/CleverRaven/Cataclysm-DDA/pull/34017
It makes it much easier/clearer what the style does at a glance. If you don't know how to make a table, here's the documentation on that:
https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

I can't say much for the nitty gritty of the style, but it looks like you get everything at melee 3-6. It'd be worthwhile smoothing it out so you at least get something at the lower levels. The buff durations seem weirdly long. You'll more or less only have to think about the move buff since the other two will almost always be refreshed before they expire. I don't know if you saw what Hymore on arpen said on my swordsmanship rewrite, but its probably relevant here. Its also kind of weird that the book description implies the player knows something about archaic spanish. I'm also a touch concerned on how well a book on greatswords would apply to mass weapons like flails and the one handed broadsword.

All that said, I'm excited to have another HEMA style in the game.

**Comment by Hymore246** [comment]
I agree with what QuintusAquila said. The style's buffs and techniques needs to shown in your PR along with your reasoning and play style for the martial art. Having to sift through the JSON to find the specifics is annoying and I could easily miss something.

I don't speak Spanish so I can't comment on that paper you linked. I don't trust Google translate enough to help either. Any chance their is a translation somewhere? On a similar vain, characters don't have an automatic understanding of archaic Spanish.

Before I even look at the style, you need to remove the counters and adjust accordingly. [Since Kevin said counters are going away](https://discord.com/channels/598523535169945603/598535827169083403/883552286939435028), you need to make sure your style can function without them. I will be looking into adjusting a lot of the styles due to this decision. 

Lastly, your martial art focuses on the strongest weapons in the game. It is very hard to create a style that doesn't make already powerful attacks even stronger. This is why Medieval Swordsmanship turned out to be subpar and is being rewritten (#50073). You need have some sort of theme or gimmick in the style to prevent the player from being given "free damage" 24/7.

**Comment by andrei8l** [comment]
This appears to be a sword style so why does it work with bludgeons too? Swords and war hammers are balanced very differently. The sledges in particular would not work at all for such flowery antics, even for super strong mutants.

The linked paper only talks about the history of "The nine rules(...)", which appears to be just the strange poem in appendix 1?

**Comment by Mikenyes** [comment]
> I can't say much for the nitty gritty of the style, but it looks like you get everything at melee 3-6. It'd be worthwhile smoothing it out so you at least get something at the lower levels.

Didn't think about that, will fix.
> Could you format the techniques/buffs like this: #34017 It makes it much easier/clearer what the style does at a glance. 

> I agree with what QuintusAquila said. The style's buffs and techniques needs to shown in your PR along with your reasoning and play style for the martial art. Having to sift through the JSON to find the specifics is annoying and I could easily miss something.

Will fix, my apologies.
> I don't speak Spanish so I can't comment on that paper you linked. I don't trust Google translate enough to help either. Any chance their is a translation somewhere?

Unfortunately, both the primary studies and the original texts are all in Spanish, and I couldn't find a translation.  I can link some interviews with HEMA fighters who follow these teachings and basic tutorials from them, however, and will link an interview with sources at the bottom of this post.
> On a similar vain, characters don't have an automatic understanding of archaic Spanish.

> Its also kind of weird that the book description implies the player knows something about archaic spanish.

That was 100% my mistake in putting together the PR, I meant to imply that the character understood that it was partially a poem from the notation and punctuation.  Will fix.
> Before I even look at the style, you need to remove the counters and adjust accordingly. [Since Kevin said counters are going away](https://discord.com/channels/598523535169945603/598535827169083403/883552286939435028), you need to make sure your style can function without them. I will be looking into adjusting a lot of the styles due to this decision.

Can do, will fix.
> Lastly, your martial art focuses on the strongest weapons in the game. It is very hard to create a style that doesn't make already powerful attacks even stronger. This is why Medieval Swordsmanship turned out to be subpar and is being rewritten (#50073). You need have some sort of theme or gimmick in the style to prevent the player from being given "free damage" 24/7.

Makes a ton of sense, will fix and add more interesting mechanics and less free damage.
> I don't know if you saw what Hymore on arpen said on my swordsmanship rewrite, but its probably relevant here.

This style is supposed to focus on combating heavily armored opponents with the detriment of suffering against hordes or health tanks, and I believe the amount of armor penetration gained by critting with high melee skill will act as incentive to use this style to fight the way it was used in the real world, in duels against foes with plate armor and other heavy armor.  This is the one thing I'd like to keep more than anything else, even if other facets must be reworked.

> The buff durations seem weirdly long. You'll more or less only have to think about the move buff since the other two will almost always be refreshed before they expire.

In my testing, the heavy weaponry used by this style often led to a 5 turn duration only lasting 2-3 inputs in practice, but I will happily change it.  Will fix.
> I'm also a touch concerned on how well a book on greatswords would apply to mass weapons like flails and the one handed broadsword.

> This appears to be a sword style so why does it work with bludgeons too? Swords and war hammers are balanced very differently. The sledges in particular would not work at all for such flowery antics, even for super strong mutants.

The teachings of Luis Barbaran II expanded into a style of fighting that focused on blades as well as bludgeons, though I could certainly split this into two styles.  My second attempt will reword and refocus techniques and buffs to make it clearer that bludgeons are a possible choice, though less optimal.  I could also rename the style to "Destreza Vulgar", the later term for the styles and teaching methods that included bludgeons.

> The linked paper only talks about the history of "The nine rules(...)", which appears to be just the strange poem in appendix 1?


The Nine Rules are the original writing that led to the development of this variant of medieval melee fighting, though it would be more apt of me to include some modern sources about the applications and uses in HEMA.
This interview and the linked sources were very valuable to me in researching this style.
[Iberian Montante](https://thespadoneproject.com/2020/03/14/iberian-montante-an-interview-with-ton-puey/)

**Comment by Shodan14** [comment]
It's a bit weird to include one-handed stuff like longswords and maces in the style as well. I'd limit it only to two-handers.

**Comment by QuintusAquila** [comment]
> It's a bit weird to include one-handed stuff like longswords and maces in the style as well. I'd limit it only to two-handers.

Longswords are two handed. I'm pretty sure the mace is too.

**Comment by Mikenyes** [comment]
I have reworked according to feedback and edited the PR accordingly- my only concern right now is that certain weapons, particularly the Zweihander, are too slow to prompt Saragossa Final.  However, I don't think that's actually an issue, as it prompts the player to wear light armor to increase their speed, as was typical with this fighting style.

**Comment by QuintusAquila** [comment]
I'd recommend throwing a cut damage requirement on the Saragossa Impale so it doesn't trigger when using a mace or other blunt weapon. 

And do you mean that you can only trigger Saragossa with slow weapons if you have low encumbrance?

**Comment by Mikenyes** [comment]
While nude save for socks (to prevent barefoot slowdowns), I can manage to attack, move, and pause in 3 turns to activate Saragossa Final with a Zweihander.  It doesn't take much more to prevent that: a Zweihander cannot use Saragossa Final (due to the timing) while wearing full light survivor gear, as an example.  I'm unsure if this is a good thing, but for now I'll leave it as is pending further feedback.
I like the idea of removing Saragossa Impale from bludgeoning weapons, will implement immediately.

**Comment by Hymore246** [comment]
I've had some time to review your style. Here is my input:

First, I understand you want your martial art to be a "late game style" but you are falling into the same problem that Niten had. It was a powerful late game style and require players to pick the weapon trait at chargen and then wait until mid-late game to find a weapon to use it. People hated this because for as strong as Niten was, you spent more time looking for a weapon to use than actually using the style. Aside from cleaning up Niten, I added the 2-by-sword to the style weapons JUST so people could use it at the start of the game. It was better to let the style scale with weapons rather than forcing it with techniques and buffs. This style is also a bit complicated. It took me awhile to figure out how it worked due to all the techniques and required buffs.

**Beginner's Represa** - Lets assume a new character picks your style and then finds a style weapon for it (like a fake mace). Using your style at low melee is actually a disadvantage. At Melee 0, they get a -2.0 Dodging skill penalty in exchange for +50% strength armor penetrations (+5 with 10 strength). This is a terrible trade. Bad enough that it would be better to use no style at all. 

**Overextended** - I REALLY don't like this buff. I get what you are going for but this is bad. Not only does it punish earily game players with no benefit in return, it also makes the move cost penalties of the techniques much worse. The weird thing about it somehow implies that by using Barbaran Montante, you are automatically slower with no benefit. Compared to using No Style, I am somehow swinging my Broadsword 30% slower for no reason at Melee 0? 

**Represa Momentum** - This buff exists just to offset Overextended. It just a bandage that only helps after hitting 3 times in a row. Pray you never miss because you WILL get slower.

**Ricasso Step** - I like Ricasso Step. A stacking OnMove buff that gives better blocking is a nice way to approach enemies instead of waiting for them to come to you.

**Thrusting Revesas** - This seems seems ok. I can understand a move cost increase for performing an impale AoE and it has minor damage increases. However, requiring Ricasso Step is bad. Setting up an Impale AoE is much harder than setting up a Wide or a Spin AoE. Remember that AoE techniques will never trigger unless their conditions are met. You can never use a Wide tech against a single target, there MUST be an enemy adjacent to them. So getting the conditions meet with an OnMove buff seem really hard.

**Vulgar Preparation** - I know the intent here is to recoup some of the move cost penalty but I can't think of a good reason to sit still for 3 turns for -15% move cost bonus. It competes with Represa Momentum so you are still going to be at a lose for move cost. Also, the time spent doing this is damage lost. You could have just hit the enemy more and ended the fight faster by doing more damage overall.

**Advancing Empuje** - You want this to be a setup move but I feel like this attack does more harm than good. Knocking an enemy away 2 spaces is going to cause you to lose one or more of your stacks of Represa Momentum, Ricasso Step, or Vulgar Preparation. All of these buffs compete with each other to exist and you can't maintain them if your opponent is out of range. Being a normal technique, you run the risk of ruining Saragossa Final by having this trigger.

**Saragossa Final** - This requires a lot of setup to work. An OnMove buff and OnPause buff are usually exclusive and I don't think the technique is worth setting up. As I mentioned above, you could just hit the enemy twice and do more damage than using this. You are using end-game weaponry after all. The move cost penalty is harsh considering Overextended is going to be up and get this move off without a significant penalty is going to be very hard. 

**Saragossa Impale** - Everything I said about the Thrusting Revesas applies here but now you need somehow get the OnMove buff and OnPause buff too. By the time you get both it is very likely the enemies will have moved out of position to trigger this attack. It also competes with every other attack in the style and even with +300% weighting, you only have 57% chance of this attack going off. The stars would need to align for this technique to trigger.

**Duelist's Represa** - I personally prefer to only go up to level 5 for skill requirements and avoid having more than one stat bonus in a style but those are nitpicks. My real concern is that this doesn't fully offset Beginner's Represa. You are still at -1.0 Dodging and the Armor Penetration doesn't make up for it.

Lastly, the style weapons are a bit odd. Can you really impale someone with a flail? I think you can with a blunt weapon (ouch) but that might not be realistic to the techniques in this style.


I apologize for being so harsh on your style. There is a lot of work that needs be done on it and I am trying to help you fix the problems now. The community will not be as nice and they will completely disregard a style that has noticeable flaws. Best of luck, keep at it.

**Comment by Mikenyes** [comment]
Thank you for the input, I think I see the trap I fell into.  I was so focused on avoiding excess buffs and simplicity that I overtuned and went to "weak and complicated".  I'll make changes and iterate slowly over a couple days until I reach something that will work better than this version, is it alright if I ping you when I'm done?

**Comment by Hymore246** [comment]
> 
> 
> Thank you for the input, I think I see the trap I fell into. I was so focused on avoiding excess buffs and simplicity that I overtuned and went to "weak and complicated". I'll make changes and iterate slowly over a couple days until I reach something that will work better than this version, is it alright if I ping you when I'm done?

Sure. No problem.

**Comment by Mikenyes** [comment]
Ping: @Hymore246 
Thanks for the feedback, here's my third attempt.

**Comment by Hymore246** [comment]
> 
> 
> Ping: @Hymore246
> Thanks for the feedback, here's my third attempt.

Getting better. Much cleaner now. I am still iffy about Crushing Empuje. I feel like players are going to trigger it a lot by accident  unless they stop to use Vulgar Preparation. Looking over your techs, you might want to just forgo bonus damage and focus completely on armor penetration. I think that was the basis of the style from what I read. If you do decide to go that route, you can add the armor penetration to Vulgar Preparation and get rid of Saragossa Estocada and Impaling Estocada since Thrusting Revesas can cover the impale AoE. Also, good idea using Min cut 8 to keep blunt weapons from using the impale. I would also recommend using str scaling for the armor pen instead of the 4 * existing since it is confusing to calculate (75% * 4 is 300%). Keep it up. I think your vision for the style is becoming clearer.

**Comment by Mikenyes** [comment]
Ping: @Hymore246 
Hopefully this is the last time I have to ping you for this PR!  I've tried to simplify and diversify the technique, replacing the knockback with a disarm and removing overcomplicated buff requirements.

**Comment by Rabidweasel** [comment]
I'm not sure that the cut restriction really does much if the idea is that it restricts the impale attack to only function with weapons where it makes logical sense. I can't see how this would work with a battleaxe for example.

Looking at the raw numbers on this style it doesn't have much going for it other than armour penetration and block power, which both require significant setup - but it also has excellent weapon variety, giving access to the battle axe, broadsword, zweihander, mace and warhammer which between them covers almost any situation you could want.

It's much less of a "stand and fight" style than the other HEMA arts but it's also the only one which lets you blast through armour like it's not there so the balance is probably fine. If you're free to move around and tactically pause to maximise the output of the buffs then it seems strong, but if you get swamped you're likely to have a bad time.

**Comment by QuintusAquila** [comment]
I still disagree with giving it the broadsword. It's lighter than the arming sword. It fits better with the lighter swords of fencing than the heavy weapons this style uses.

**Comment by Maleclypse** [comment]
@Hymore246 Is this in merge ready shape?

**Comment by Termineitor244** [comment]
@Mikenyes The style is supposed to use heavy weaponry, right? That's the only condition for a weapon to be used by the style? I'm implementing the weapon categories to the martial arts in #51867 so I would like to know before hand about this style and how it should be categorized.

That said... Is the dao heavy? And I'm not sure if the broad sword is exactly "heavy" for the standards of this style...

**Comment by Hymore246** [comment]
Reversing Destreza can never be stacked to 3 since Movimiento Natural can only give a single bonus block. Reduce the stack amount of Reversing Destreza to 2 stacks.

**Pull request merged**
