### PR TITLE
[Magiclysm] Parabolan wool gambesons

### PR DESCRIPTION
**Pull request by rty275**
#### Summary
Content "Adds parabolan wool armors"

#### Purpose of change
Parabolan wool is an incredibly bullet resistant material, it'd be a bit silly if nobody'd ever made armor out of it. And wool gambesons are right there to copy.

#### Describe the solution
Adjusted parabolan wool mass/volume based on a discord conversation, then created copies of wool gambesons based on that adjusted mass. Created recipes for those gambesons again based on the mass/volume adjustment of the patches. Added spawns for those gambesons in the Forge of Wonders shop, as per messages on discord. Also added a material for quilted parabolan wool, made equivalent to quilted wool proportionately. 

Parabolan wool used to be 1/10th the mass of cotton, and is now 6/10ths the mass. Parabolan felt patches used to be the size of cotton sheets and are now the size of cotton patches, to match regular felt patches. Recipes for existing parabolan wool garments were changed appropriately. 

#### Describe alternatives you've considered
Not adding these. Adjusting the material to be worse at ballistic protection and thus not make sense to make armor out of.

#### Testing
Clothes were wearable and craftable. Clothes protected more than adequately but not 100% completely from a CROWS turret, as expected. Clothes spawned at the Forge of Wonders and were on sale. Clothes were cut into appropriate amounts of patches. 

#### Additional context
While this isn't my *first* first PR, it is absolutely the first that adds anything on this scale. I hope I have done things correctly.

### CODE REVIEW

**Comment by rty275** [comment]
Shoot, I probably should have made those one big commit. That's my bad.

**Comment by rty275** [comment]
But the Clang test said I needed spaces there! Fine, back to how it was before

**Comment by Maleclypse** [comment]
I am behind but I will try and look at this today :)

**Comment by rty275** [comment]
Sounds good, there's no hurry!

**Comment by Maleclypse** [comment]
Thank you for doing this!

**Pull request merged**
