### PR TITLE
Move it! 1 (Start moving player.h stuff to Character.h)

### PR DESCRIPTION
**Pull request by i2amroy**
Since these are pretty high PR-use files I'm doing it in smaller chunks. This moves a chunk of player+npc attributes (mostly mutation, bionic, and inventory stuff) to the Character level instead of the Player one as a precursor to getting NPC's to not depend on the player files and functions.

### CODE REVIEW

**Comment by BevapDin** [comment]
It might be better to keep the functions in src/mutation.cpp and just make them proper members of Character. The same "system" is used for ranged and melee combat withing the ranged.cpp and melee.cpp files. It seems a good way to make the character.cpp / player.cpp files less cluttered.

**Comment by i2amroy** [comment]
Good idea, I'll look into that.

**Comment by KA101** [comment]
OK, so should I close this?

**Comment by i2amroy** [comment]
Just hold off for now, I'll see about getting the move stuff into the PR tonight. (Don't let it keep you up though, it can always wait till tomorrow and I might not get a chance till late).

**Comment by kevingranade** [comment]
Tip for shifting things around like this (or a similar exercise, consting things).
Pick something that should be moved, move it, build.
Fix the resulting compile errors by moving more stuff, repeat.
When you move something and it does NOT cause compile errors, commit just that change.

If you end up not being able to move some of your target methods over, you can just do git reset (or git stash if you might fix it later) to back it out, but the things you committed along the way you can go ahead and PR.

**Comment by i2amroy** [comment]
>Tip for shifting things around like this (or a similar exercise, consting things).
Pick something that should be moved, move it, build.
Fix the resulting compile errors by moving more stuff, repeat.
When you move something and it does NOT cause compile errors, commit just that change.

That was pretty much what I did, it's just that the mutation/bionic/etc. stuff is *really* interwoven in a lot of places, so there was a lot of "sweet, down to just one more function to move!" "shoot, that function requires me to move 5 others over".

Also sorry about letting this sit for so long, real life in the form of homework and various other college stuff has reared it's ugly head and is cutting huge chunks out of my free time.

**Comment by KA101** [comment]
.>_<

Syntax again.  Bloody bash and exclamation points.

**Comment by narc0tiq** [comment]
Backslashes and single quotes are your best friend when working with bash.
Or perhaps with shells in general.

I've never gotten along with exclamation points (nor needed them), and this
just prompted me to look up how to disable that feature. According to
http://unix.stackexchange.com/a/19257, it's just a simple "set +H". I'm
totally shoving this into my .zshrc now -- you'll probably want it in your
.bashrc, @KA101.

**Pull request merged**
