### PR TITLE
Sample fixes, adds human samples to purifier

### LINKED ISSUE #53256: Harvesting mutagen samples is extremely stingy
### Describe the bug

The odds of getting a sample while dissecting animals are much too low. Even with health care 10 and a scalpel, I've spent several days dissecting all ~10 cows in a dairy farm and received only a single bovine sample. With a single dose of mutagen requiring 3, that's pretty rough.

This renders even what should be relatively easily acquired mutagens, such as cattle, functionally unattainable, and rare samples like molerat are just complete pipe dreams.

### Steps to reproduce

1. Give yourself health care 10 and a scalpel
2. Dissect a bunch of cows (or other sample-carrying animals)
3. Despair

### Expected behavior

Recipes should have ingredients that are possible to acquire in practice. Here are a few suggestions for how to adress the problem:

- Drop the recipe requirement to 1 sample
- Increase the drop rate, probably all the way to 100%
- Actually, increase it beyond 100%. The rarer monsters especially could stand to drop multiple samples.
- Increase the number of monsters that drop samples. Bovine samples could become "ungulate samples" and be dropped from deer and moose, lupine samples could be dropped by every kind of dog, etc. This might include mutant and/or zombified versions of animals.
- Courtesy of @Venera3: make samples a non-consumable tool when making mutagen, consume it only when crafting serum.

Probably we need to implement multiple of these. 100% drop rate and 1 sample per mutagen would make cattle possible, but molerat samples would still be too rare for troglobite to be remotely practical.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 40e9432 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
Balance "Increase sample dissection rates, redistribute sample usage, adds human samples"

#### Purpose of change
Partially fixes #53256.

#### Describe the solution
Adds human samples for purifier, adjusts sample utilization,  increases sample drop rates.

#### Describe alternatives you've considered
Letting other people do it.

#### Testing
Tested and it seems to be working better than previously.

### CODE REVIEW

**Comment by Paprika-H** [comment]
Are... we gonna have to butcher people for our purifier now?

**Comment by Photoloss** [comment]
When was Purifier stated to be "human mutagen" and why does it not act as such if that is the lore? No threshold, no member traits appropriate for the species, basically it acts as "anti-mutagen" and somehow has access to a memory of what your character was like at creation instead.

**Comment by Maleclypse** [comment]
> When was Purifier stated to be "human mutagen" and why does it not act as such if that is the lore? No threshold, no member traits appropriate for the species, basically it acts as "anti-mutagen" and somehow has access to a memory of what your character was like at creation instead.

If you search the words “human mutagen” in the devcord it is referenced repeatedly including at least once by Kevin on the first page of search results.

**Comment by Maleclypse** [comment]
> When was Purifier stated to be "human mutagen" and why does it not act as such if that is the lore? No threshold, no member traits appropriate for the species, basically it acts as "anti-mutagen" and somehow has access to a memory of what your character was like at creation instead.

If you search the words “human mutagen” in the devcord it is referenced repeatedly including at least once by Kevin on the first page of search results.

**Comment by Maleclypse** [comment]
> Are... we gonna have to butcher people for our purifier now?

Im thinking this will have a number of other spawn locations like hospitals and microlabs and ferals. Assuming it gets accepted as not too ghoulish. I’m actually good either way and had remembered discussions about purifier being “human mutagen” while I was doing other stuff in samples.

**Comment by Photoloss** [comment]
> Im thinking this will have a number of other spawn locations like hospitals and microlabs and ferals. Assuming it gets accepted as not too ghoulish. I’m actually good either way and had remembered discussions about purifier being “human mutagen” while I was doing other stuff in samples.

What exactly constitutes a "sample"? Unlike pretty much all other options NPC followers would understand and could consent to donating things like hair, skin shavings, blood, saliva and other fluids. I suppose a pet cat, dog or farm animal might comply as well.

**Comment by Terrorforge** [comment]
> Im thinking this will have a number of other spawn locations like hospitals and microlabs and ferals. Assuming it gets accepted as not too ghoulish. I’m actually good either way and had remembered discussions about purifier being “human mutagen” while I was doing other stuff in samples.

Correct me if I'm wrong, but this PR doesn't add any of that, right? Not even as a dissection reward. So at the moment it just makes Purifier uncraftable. As for ghoulishness... well, you can already butcher people for meat. As long as you get the same morale debuff, I don't particularly see the issue. Then again, I'm pretty blasé about stuff like that.

> What exactly constitutes a "sample"?
It's vague on purpose, but considering that extracting one requires hours of work and specialized medical knowledge, I presume it's something like bone marrow stem cells.

Speaking of specialize knowledge, how does skill interact with the drop rates here? The number says 95, but elsewhere it states these mutagen harvest is regulated by health care and applied science. So is that 95% provided both those skills are maxed? Do they both contribute equally? Either way we'll have to see how it feels in game, but I'm curious.

**Comment by Maleclypse** [comment]
> > Im thinking this will have a number of other spawn locations like hospitals and microlabs and ferals. Assuming it gets accepted as not too ghoulish. I’m actually good either way and had remembered discussions about purifier being “human mutagen” while I was doing other stuff in samples.
> 
> Correct me if I'm wrong, but this PR doesn't add any of that, right? Not even as a dissection reward. So at the moment it just makes Purifier uncraftable. As for ghoulishness... well, you can already butcher people for meat. As long as you get the same morale debuff, I don't particularly see the issue. Then again, I'm pretty blasé about stuff like that.
> 
> > What exactly constitutes a "sample"?
> > It's vague on purpose, but considering that extracting one requires hours of work and specialized medical knowledge, I presume it's something like bone marrow stem cells.
> 
> Speaking of specialize knowledge, how does skill interact with the drop rates here? The number says 95, but elsewhere it states these mutagen harvest is regulated by health care and applied science. So is that 95% provided both those skills are maxed? Do they both contribute equally? Either way we'll have to see how it feels in game, but I'm curious.

I apparently failed to update my copy on github after editing the human harvests locally.   I needed to put this in draft anyway while I test how the 95% works.   I believe that it's 95% after the two skills are maxed.

**Comment by Venera3** [comment]
I'd use samples as tools for the basic mutagen crafting. Our monsters aren't really renewable (or at least not conveniently), so I think having them as an unlock you can cash in for serums would be less busywork. A lot of the game boils down to "drive around and see what spawns", but it's not really a fun way to play.

**Comment by Terrorforge** [comment]
Weren't you concerned that mutagens are a bit one-and-done? If it only takes one sample to craft an arbitrary amount of mutagen, doesn't that put us back to the point where you just batch-craft  40 doses as soon as you get your hands on all the tools, just with a slight speed bump for the serum? If we want mutation to be more of a process, we need something like this to pump the brakes on individual doses. I agree with your concern about trekking all over the place, but surely there has to be a balance point where you need to do some roaming, but not so much it's tedious? But of a tricky tightrope to walk, but we gotta walk somewhere.

**Comment by PatrikLundell** [comment]
Actually, @Maleclypse updated github, but it ended up in the wrong branch (#53205). I assume it will be rectified in not too distant a future. Meanwhile, those curious about what the draft looks like can look at it there.

**Comment by Venera3** [comment]
> Weren't you concerned that mutagens are a bit one-and-done? If it only takes one sample to craft an arbitrary amount of mutagen, doesn't that put us back to the point where you just batch-craft 40 doses as soon as you get your hands on all the tools, just with a slight speed bump for the serum? If we want mutation to be more of a process, we need something like this to pump the brakes on individual doses. I agree with your concern about trekking all over the place, but surely there has to be a balance point where you need to do some roaming, but not so much it's tedious? But of a tricky tightrope to walk, but we gotta walk somewhere.

Not all changes need to happen at once, or in the same PR. 

If books contain mutagen and serum recipes separately then the amount of mutagen you craft will not be a limiting factor. You can essentially "unlock" a given mutagen by finding both its book and a sample, try the prethresh traits, combine it with whatever other lines you managed to get both the book and the samples for without constraining yourself. If you decide to go for the threshold you'd need to find the good book (in specialized labs, when we have them, or TCL/microlab loot vaults until then) *and* you'd have to actually spend samples for it. 

Stamping down on the amount you can make means people can't tinker with it, instead being stuck in the annoying "get twenty bear asses" loop that encourages savescumming and *dis*courages playing with the expensive lines (not a lot of raptor mutants around, eh?). Giving the prethresh traits away for cheap could also lead to players (*gasp*) experimenting on their own instead of running to HHG/the wiki/the Discord and getting their transhumanism spoonfed to them, but that might just be my personal bugbear.

**Comment by Terrorforge** [comment]
I see what you're saying, but there's a more fundamental mechanical obstruction standing in the way of any pre-threshold experimenting, namely that crossing the threshold is based on the strength of your mutation in that category, _relative to all your mutations_. I don't know the exact math, but fucking around with different categories pre-threshold could make it practically if not literally impossible to breach the threshold of your choice. The way you're encouraged to do it right now is to thresh first, and only then start mixing in other lines. Which does seem a bit backwards to me. Your Final Form should probably rise from the chaos of your experiments, not be the starting point.

I also feel like experimentation isn't rewarded because different lines largely just overwrite each other. I don't feel comfortable mixing different mutagens without meticulous HHG study because if I just take different things that seem cool together, odds are I'll just lose the cool traits I already have.

Here's a thought. Not even a suggestion, just spitballing. But what if, instead of e.g. raptor being its own special mutagen that you create by mixing other mutagens, it was just what happens when you take both bird and lizard mutagen? If categories were more flexible like that and tended to combine rather than conflict, then you would have a serious incentive to just chug various mutagens and try to find the cool combinations. That could also be a path to implementing that tiered mutation system you've ben talking about

**Comment by Maleclypse** [comment]
" I don't know the exact math, but fucking around with different categories pre-threshold could make it practically if not literally impossible to breach the threshold of your choice." 
Good news the tests as they exist prevent this from occurring in the in-repo mods.  At least for magiclysm.  I need to check that for Aftershock.

**Comment by Terrorforge** [comment]
Oh, good. I'd assumed those just made sure there was _a_ way, not that it was always possible.

Did you figure out how the drop rate works re:skills?

**Comment by Maleclypse** [comment]
> Oh, good. I'd assumed those just made sure there was _a_ way, not that it was always possible.
> 
> Did you figure out how the drop rate works re:skills?

I've tested it and I ended up removing the probability because either I was having exceptionally bad luck but at least for cows I was seeing a 20% no sample rate.

**Comment by Terrorforge** [comment]
Dumping my experiences here in case you're interested in some real-world data:

I'm currently 52 days into a character looking to breach Cattle, and then probably expand into other lines. I'm on 0.5 item rate, which I don't _think_ influences dissection, but presumably does influence lab drops.

The good news is that this has made mutation much more of an ongoing project. It's no longer feasible to just do it all in one batch, so I've ended up mutating bit by bit instead, which makes for some interesting interstitial issues. Serums in particular seem very much not worth it to craft, except for attempting to breach, which is kind of a relief because it cuts down on tedious crafting.

The bad news is that dissection drops are nowhere near what the json numbers seem to imply. My base stats are 12 (now 18)/8/10/8, I have Applied Science 8 and health care 7, and I have a scalpel. So not maxed, but high. The majority of my dissections are complete failures; zero samples. I've dissected some 15-20 cows by now, and that got me maybe 7 or 8 samples. The json implies each cow should give 2-5 samples, but I've only gotten 2 once, and never more than that.

In terms of balance, this isn't _too_ bad for cattle. It's not hard to find cows you can kill at low risk, and finding samples and especially serums in labs/TCL really takes the edge off bad dissection luck. But the fact that Cattle is still kind of a struggle suggests that less convenient lines must still be borderline impossible. Worse, the size of the disparity makes it borderline impossible to eyeball reasonable numbers. I mean, if min:2 max:5 translates to at best a single bovine sample every two or three dissections, how high would you have to go for molerats to be remotely reasonable? min:10 max:30?

**Comment by Maleclypse** [comment]
Hmm if they show up in the cargo area I may have misplaced them. I thought I was placing them in lab refrigerator areas.  But all in all good feedback. I’ll try and do another tuning run after I get mouse and rat spawning.

**Comment by Terrorforge** [comment]
Yes, there's plenty in the crates in the aboveground cargo area. Recently I've gotten into the habit of just breaching that and leaving the rest of the TCL untouched, because it's much safer and more convenient than descending into the lab areas, where you can also get samples. Presumably they spawn there because those crates have random lab stuff and they're in the "samples" group that used to just be kidneys and such.

Also, as I mentioned on Discord, finding live cows has become rather difficult at this point, almost a season in. That's specifically a cow thing, but it does further shift the balance I'm favor of TCL raids.

**Pull request merged**
