### PR TITLE
[CR] Ensure that `make app` with LANGUAGES flag compiles localization files

### PR DESCRIPTION
**Pull request by mnacamura**
This is a localization specific issue on macOS.

In the present `Makefile`, `make app` only copies `lang/mo` into `$(APPRESOURCEDIR)`, so one has to `make localization` beforehand. Without preceding `make localization`, build fails.
Probably it's better to ensure that `make app` compiles localization files when `LANGUAGES` flag is defined?

### CODE REVIEW

**Comment by patternoia** [comment]
I do not agree that `app` target should build all the translations by default.
But even if so, to build it you add the $(L10N) to `app` target
`app: appclean version data/osx/AppIcon.icns` **$(L10N)** `$(APPTARGET)`
as it is done in `dmgdist` target

**Comment by mnacamura** [comment]
> I do not agree that app target should build all the translations by default.

Right.

> But even if so, to build it you add the $(L10N) to app target
app: appclean version data/osx/AppIcon.icns $(L10N) $(APPTARGET)
as it is done in dmgdist target

  So, the better way could be that `app` target depends on `$(L10N)` in place of `dmgdist` target because `dmgdist` already depends on `app`?

`$(L10N)` is defined only if `LANGUAGES` is defined. Therefore, if my understanding is correct, even if `app` or `dmgdist` depends on `$(L10N)`, translations are compiled (and installed) only when `LANGUAGES` is defined.

**Comment by mnacamura** [comment]
By the way, `install` target in `LINUX` and `CYGWIN` seems to compile and install all translations unconditionally. It lacks consistency but would be another issue.

**Comment by patternoia** [comment]
BTW you can achieve the desired behavior, and produce a localized `app` without modifying makefile at all. Like this:
`make localization LANGUAGES=all && make app NATIVE="osx" OSX_MIN="10.7" USE_HOME_DIR=1 CLANG=1 -j4 LANGUAGES=all`

**Comment by mnacamura** [comment]
My wording and first commit might have been misleading.
My intention is not to install all translations by default but to let `make app` by itself do the following:

| Command                                | Compiles translations?  | Installs translations? | 
| -------------------------------------- | ----------------------- | ---------------------- |
| `make app ...` (`LANGUAGES` undefined) | No                      | No                     |
| `make app ... LANGUAGES=somelang ...`  | Yes (only `somelang`)   | Yes                    |
| `make app ... LANGUAGES=all ...`       | Yes (all langs)         | Yes                    |

`make dmgdist` does not need preceding `make localization`, so I just hope that `make app` behaves alike.

**Comment by mnacamura** [comment]
Let me explain more.

Any make rule should not try to copy things which may not exist. They have to be prepared beforehand in the commands inside the make rule itself or by letting the rule depend on another make target that generates them.
As @patternoia said, `make localization LANGUAGES=foo && make app ... LANGUAGES=foo` can achieve to make a localized app. However, this means has a human error; one may forget to run `make localization` beforehand and `make app` tries to copy non-existing translation files. That's why I want to ensure `app` target with `LANGUAGES` flag depends on `localization` target (if `LANGUAGES` is defined).
Does it make sense?

**Pull request closed without merging**
