### PR TITLE
Hotel improvements (JSON, new lobbies, updated item, monster, and vehicle spawns)

### PR DESCRIPTION
**Pull request by vickio**
This PR:
- Converts the hotel mapgen to JSON
- Adds two new variations for the entrance/lobby
- Adds curtains to hotel room windows
- Adds snacks to the coffee bar in each room
- Adds luggage with clothing on the floor in some rooms
- Adds bibles to bedside dressers
- Adds swimmer zombies to the pool
- Adds fat and strong zombies to the gym (mostly fat)
- Adds variety to vehicles in the parking lot
- Removes 700+ lines from `map::draw_map()`

Overmap terrain ids are the same, but save file conversion was needed to handle rotation. Tested old saves with the hotel in all orientations.

### CODE REVIEW

**Comment by vache** [comment]
I like the new lobbies.  More structures should do that with alternate mapgens.

**Comment by sparr** [comment]
> Removes 700+ lines from map::draw_map()

A laudable goal, all by itself! :)

**Comment by RogueYun** [comment]
Is there anything that can be done about bringing basements to the json files? I have some ideas for basement designs but I have nothing to go by.

**Comment by Coolthulhu** [comment]
Basements require some code-side improvements, like the ability to spawn "sets" of objects on a tile - for example, a gun safe full of guns. This isn't possible with jsons alone.

**Pull request merged**
