### PR TITLE
Mainline Medieval Stuff mod, part 1.

### PR DESCRIPTION
**Pull request by Rail-Runner**
Move some stuff from Medieval Stuff mod, mostly armor.

Full list of moved items:

Armor:

galea (+recipe) (+itemgroups)
nasal helm (+recipe) (+itemgroups)
conical helm (+recipe) (+itemgroups)
tunic (+recipe) (+itemgroups)
gambeson (+recipe) (+itemgroups)
lorica segmentata (+recipe) (+itemgroups)
chainmail hauberk (+recipe) (+itemgroups)
lamellar armor (+recipe) (+itemgroups)
baldric (+recipe) (+itemgroups)

Book:

Arms and Armor of Imperial China (+itemgroups)

Non-mod recipes changed by mod:

crossbow
boiled leather armor
plated leather armor
leather armor boots
black gunpowder

### CODE REVIEW

**Comment by SeanMirrsen** [comment]
Can we /please/ not have autolearn on chainmail? It's a bit... /too/ complex and medieval a thing for an average person to spontaneously learn how to craft. Don't you think? :)

**Comment by Darkyhard** [comment]
This recipe assumes that a character simply connects some chainmail items together into a suit, not makes them from scratch. This may need some experience, but this is not something that is impossible to figure out on your own, in my opinion.

**Comment by Shadefang** [comment]
Speaking from personal experience chainmail isn't difficult to make so much as time consuming. Figuring out a basic chainmail weave on your own would be on par with (if not easier than) figuring out how to knit on your own.

**Comment by SeanMirrsen** [comment]
It is, in my opinion, a matter of immersive experience. As in, in-character knowledge. A modern person without a background in historic research or recreations, wouldn't have "chainmail" on his mind when thinking of armor. It doesn't make sense for that knowledge to be available without having read about it in a book.

**Comment by Malkeus** [comment]
That's a comment on the sad state of modern reading habits. I'm an
aberration to be sure, but I read constantly as do my children. My 10 year
old has a great interest in armor and medieval combat. How do we account
for things like that in game? Professions cover what you were doing right
before the cataclysm struck, but we don't touch on the past very much. Your
way leaves everyone in perpetual ignorance, the current implementation
leaves room for imagination. Perhaps the survivor watched lotr and liked
how the warriors looked in their chainmail and the need for personal
protection brought out that memory.

**Comment by Shadefang** [comment]
Malkeus got to it before I did, but throwing on top of that many, if not most, people would've had some contact with medieval armor through school.

Also, as Darkyhard mentioned (and I missed) you can only connect chainmail pieces, not make it from scratch, much to my disappointment.

**Comment by kevingranade** [comment]
I don't know what school you went to where any, much less most of the
students had enough exposure to chain mail to repair it from memory.
I think the comparison to knitting is apt, but I'm skeptical that someone
is going to be able to take some knitting needles and yarn and knit as much
as a sock without instruction, much less something like a glove or sweater.

**Comment by Rivet-the-Zombie** [comment]
>Malkeus got to it before I did, but throwing on top of that many, if not most, people would've had some contact with medieval armor through school.

Here in the USA, many students don't even get enough of an in-depth education about *the two World Wars* to know what the fighting was about. Where in the world are kids learning about medieval armor in school, and why didn't I get to attend such an awesome institution of learning?

**Comment by Shadefang** [comment]
I'm not saying a school will teach how to make it, but mention it. The state of the education system aside, most people I know have the basic facts. It's called chainmail, and made of little rings. Given this basic information and mid to high fabrication skill, I see little reason that they couldn't figure it out.
This is something that you should have to experiment with to figure it out, but that's a different issue.

**Comment by kevingranade** [comment]
> This is something that you should have to experiment with to figure it
out, but that's a different issue.

No, it's part of the same issue, such learning should wait until we have
that kind of system in place, not just ignore the requirement for
experimentation out of convinience.

**Comment by Shadefang** [comment]
Before I go further, I'm going to bring up the fact that when it comes to what is in the game the recipe is putting different premade parts together into a whole. I can't think of any knowledge you'd need for that that you wouldn't get from the pieces of chainmail that you already have to have to be able to put them together in the first place, and some basic fabrication skill.

That said, the argument that recipes should not be autolearned if they would require experimentation would imply the removal of many, if not most, if the currently autolearned recipes, especially tools. How are you supposed to make edged stone tools without experimenting with knapping?  Make a crude lockpick without experimenting with locks? Know what bits you need in a swage and die set without experimenting with forging?
Implementing experimentation is a great idea, and I'd love to see it; but we still need ways of learning recipes until that happens.  While learning recipes through books and disassembly works, there are many cases where those don't apply well, and leaving only those methods forces the player to rely purely on random loot. Until a more in depth method of experimentation is implemented the alternative we have is the autolearn feature. Giving recipes as the related skills increase under the assumption that as you learned the skill you were experimenting.

/rant

**Comment by Frost-wood** [comment]
This is probably why we need a research mechanic-you could learn how to craft chainmail without a book, but it would take a lot longer, and use more materials.

I'd also like to point in the tech-based society of Cataclysm DDA, a common person knowing how to make chainmail is even more unlikely than it is today.

**Comment by Malkeus** [comment]
Yet apparently they have a lot of museums with medieval weapons and armor
on display now? Why ifs this being mainlined then?

**Comment by chaosvolt** [comment]
Whee. I didn't know that my adapting an existing recipe to assemble a complete set of mail, to make a version that leaves the head free, would lead to a glorious argument on how easy mail is to make in the first place.

By the way, the hauberk was originally added in the first place largely for the man-at-arms profession, due to the great helm clashing with the hood. >.>

**Pull request closed without merging**
