### PR TITLE
bronze horse armor

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary
Content "bronze horse armor"

#### Purpose of change

More crafting diversity and pet fashion options

#### Describe the solution

Copies work from #55969 and applies the same logic to existing horse armor recipes. Bronze armor is heavier but easier to make. Also applies a longest side entry to all horse armor copying human equivalent. Horse armor segment lengths should be longer probably but couldn't find a clear source.

#### Describe alternatives you've considered

N/A

#### Testing

Game loads no errors, recipe appears, item spawns and works as expected. No horse can wear this yet but maybe a Clydesdale PR is coming

#### Additional context

Based on #55969

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Is this useful in practice? The "horses" in the game are ponies that seem to have a maximum carrying capacity of 100 kg, which means it's not capable of carrying an average armored person, let alone any armor for itself on top of that. It MIGHT work for an extremely small human or one of the decreased size mutants, though.

**Comment by LyleSY** [comment]
Ha, maybe not. I'll do some testing and see what makes sense. Might need to do something lighter. Or maybe we need some more horse options.

**Comment by PatrikLundell** [comment]
I think the game would need a small minority of full sized horses as well as the current horses. The horses used by knights and cataphracts (who rode heavily armored horses) were the largest ones available, despite the average medieval horse being rather small. However, this is outside of the scope of this PR.

**Comment by Zireael07** [comment]
@PatrikLundell: Yep, but the biggest medieval horses were pretty much the size of modern ponies

https://www.smithsonianmag.com/smart-news/medieval-warhorses-were-actually-the-size-of-ponies-180979389/

**Comment by LyleSY** [comment]
Looks like I wrecked this trying to fix my fork, trying again

**Pull request closed without merging**
