### PR TITLE
Add plants and seeds

### PR DESCRIPTION
**Pull request by Rail-Runner**
1. Rhubarb seeds.
2. Buckwheat seeds.
3. Wild herbs seeds.
4. Wild vegetable stems.
5. Dandelion seeds.
6. Mushroom stems.
7. Morel mushroom stems.
8. Hallucinogenic mushroom stems.
9. Poisonous mushroom stems.
10. Bee balm plant.
11. Mugwort plant.

Based on Wilderness Overhaul mod by MormonPartyboat.
( http://smf.cataclysmdda.com/index.php?topic=9568 ):

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
Mushrooms don't grow from transplanted stems. They grow from spores, and morels are notoriously difficult to farm.

**Comment by Darkyhard** [comment]
I know about it. Actually, I couldn't find any information on how you extract spores from mushrooms and simply took these from the mod as they are.

**Comment by Rivet-the-Zombie** [comment]
[Like this!](http://homeguides.sfgate.com/harvest-mushroom-spores-47693.html)

**Comment by Darkyhard** [comment]
Thanks, will do.

**Comment by Rivet-the-Zombie** [comment]
You need to push your changes.

Enter ````git push```` in the Git shell.

**Comment by Darkyhard** [comment]
It says "Everything up-to-date". Not too surprising, considering that I've already pushed them before.

**Comment by RadaRadaRada** [comment]
I think that, extracting spores from mushrooms should be more difficult then extracting seeds from plants.

**Comment by KA101** [comment]
OK.  We already get complaints about food being too plentiful, so though this makes sense from a realism/survivalism perspective, I'd rather hold this until & unless we have some check on the process.  Sorry, Darkyhard.

**Comment by Rivet-the-Zombie** [comment]
I think most players can't be bothered to stay in one place long enough to actually farm. The only folks I see this as rewarding is those who are willing to put in the required effort to become a self-sustaining farmer as opposed to the default scavenger/hunter-gatherer type, and I think that's a pretty good limiter right there.

**Comment by KA101** [comment]
Any other opinions?

**Comment by PropaneSoup** [comment]
I agree with Rivet, I'm the the middle of a character right now and I'm finding myself going hunter scavenger simply because I can't find enough seeds to keep myself fed in my nice little base

**Comment by facepalm** [comment]
Shouldn't buckwheat (and wheat) BE seeds?  It's the seeds that we eat.

Also, from a realism perspective, mushrooms shouldn't be planted the same way other plants are.  You split the mycus and embed both halves on additional substrate, which is generally some kind of wet, decaying fibrous matrix that needs to be kept humid and preferably dark.  "Spore" action would work better as a way to get the mycus initially: make the substrate, wait for something to take root and sprout, see if that's something you'll want to culture, otherwise destroy the substrate.

**Comment by Darkyhard** [comment]
> Shouldn't buckwheat (and wheat) BE seeds? It's the seeds that we eat.

Plantable item's ID needs to start with "seed_" in order for the item to actually behave like seeds, as far as I know.

> Also, from a realism perspective, mushrooms shouldn't be planted the same way other plants are. You split the mycus and embed both halves on additional substrate, which is generally some kind of wet, decaying fibrous matrix that needs to be kept humid and preferably dark. "Spore" action would work better as a way to get the mycus initially: make the substrate, wait for something to take root and sprout, see if that's something you'll want to culture, otherwise destroy the substrate.

Actually, it's a great idea, but this is out of my capabilities since this would need some actual coding.

Alternatively it could be possible to make farming mushrooms similar to how tanning hides behave: you craft a tanning hide, and after some time has passed you can activate it to get a tanned hide.

**Comment by Tomcost** [comment]
I think that the problem with the overabundance of food was how easy was to get it. Having to wait an entire season to get stuff you would normally find by foraging doesn't seem to break balance, it is just a quality of life improvement for those who don't want to visit a city in their lives and so don't need to loot a gardening shop.

And I like the future implications there are for being able to farm poisonous and hallucinogenic mushrooms.

**Comment by Darkyhard** [comment]
So, what's preventing this PR from getting merged?

**Comment by Zireael07** [comment]
I think it's lack of time on devs' part.

**Comment by KA101** [comment]
Lack of time/energy/morale, etc.  For those issuing death threats, schedu

**Pull request merged**
