### PR TITLE
Alphas get Cardio

### PR DESCRIPTION
**Pull request by DukePaulAtreid3s**
#### Summary
Balance "Alphas get Indefatigable pre-threshold"

#### Purpose of change
The evolutionary niche humans have always occupied is that of a pack-based persistence predator, being able to run down other animals until they collapse. In fact, humans have some of the best heat dissipation abilities of all members of the animal kingdom.

#### Describe the solution
Give alpha mutants the indefatigable trait.

#### Additional context
https://new.nsf.gov/news/how-humans-evolved-super-high-cooling-capacity
http://doc.rero.ch/record/15289/files/PAL_E2588.pdf

### CODE REVIEW

**Comment by Holli-Git** [comment]
Ehh I think giving them hyperactive is a bit much. Just indefatigable sounds good to me

**Review by kevingranade — CHANGES_REQUESTED** [review]
Take a look at the overall balance of Alpha and then specifically look at how this changes that.
"just add major buff on top" is not a reasonable thing to do without reviewing balance, and you're not showing any indication of having done that.

**Comment by fairyarmadillo** [comment]
Alphas are supposed to be peak humans, not superhumans. Hyperactive is a superhuman ability that only shows up at the extreme end of animal lines that are specialized in sprinting.

The human "persistence hunter" thing is also a bit of a misnomer/myth. The advantage humans possess is that our bipedal gait allows us to walk, slowly jog, or intermittently run for incredible distances over long periods of time. Compared to other animals, we are particularly poor sprinters, slow-footed and with no stamina advantage when it comes to explosive activity.

**Comment by DukePaulAtreid3s** [comment]
Done!

**Comment by kevingranade** [comment]
You haven't done what I asked.  I need *you* to look at the current balance and the balance implications of your change, not just throw stuff out and expect other people to do that part for you.

**Comment by DukePaulAtreid3s** [comment]
Alright, closing right now, I'll put out a feature request in a moment to fulfill the trade-off I would like to add for this.

**Pull request closed without merging**
