### PR TITLE
Amphib. Adds #4 - Dead Frogs Draft

### PR DESCRIPTION
**Pull request by TheSaddestGoomba**
#### Summary
Content "Add 7 new frog zombie varities and audit existing frog zombies"

#### Purpose of change
To add more distinct frog zombies to fit the existing frog mutants and to clean up entries for existing frog zombies.
For example, giant treefrogs and toads will no longer zombify into zombullfrogs but rather more fitting variants.

#### Describe the solution
Add an abstract entry for frog zombies and have all others use "copy_from" to reduce json size.
Remove flags like FILTHY from frog mom and dad, and remove the FROG species from gastro bufo.
Adds 7 new zombie frogs:
1. Zombie Toad - a simple reskinning of zombullfrog for mutated toads to zombify into.
2. Bloated Zoad - a mid-point toad zombie that trails light sludge and leaves a puddle of it on death.
3. Warted Monstrosity - large version of bloated toad, full sludge trail and huge splash of sludge on death.
4. Deathmask Zoad - zombification of the great beaked toad mutant that keeps its bony platings and beak.
5. Zapping Zombfrog - zombie for the electric frog mutants; this one is intended to only have the electric abilities it had in life (like an electric eel), in anticipation of shocker zombies being reworked
6. Croaked Climber - zombified giant treefrog, weaker but more nimble than zombie toads and zombullfrogs.
7. Shadow Leaper - shady variant of the zombified treefrogs.

#### Describe alternatives you've considered
Moving the gastro bufo entry into the same file as the rest, or moving all frog zombies into their own .json file.

#### Testing
Testing is complete:
- All zombifications and upgrades are functioning as intended.
  - As noted elsewhere ( #63791 ), the sample drop issue rears its head here when 'warted monstrosities' revive from 'gargantuan toads.'
- Combat tests completed for each new creature (using the standard loadouts). 
  - Most are manageable by even early game characters that are prepared (rubber gloves against 'jumping jolter', etc.)
  - Numbers and situation (such as fighting 'leaping shadows' at night) make them much more challenging.
  - The 'death mask zoad' is appropriately difficult even late game; like a weaker but more mobile 'skeletal juggernaut.'
  - Special abilities like sludge trails feel properly tuned.
  - Difficulty ratings seem fitting to experience.

#### Additional context
4th implementation of #67029
Thanks to BlizzDA for help with naming

### CODE REVIEW

**Comment by BlizzDA** [comment]
The variants seem neat but the names don't exactly scream 'undead' to me. Aside from the one that actually says 'Zombie Toad'. Maybe something like 'Zoad' or 'Zrog' so it's easier to keep track of? 

e.g. Zapper Zrog, Deathmask Zoad. (Shady Zrog also makes me think of Crazy Frog)

**Comment by TheSaddestGoomba** [comment]
> ...the names don't exactly scream 'undead' to me.

Thanks, and yeah, that's a concern I had with some of them. I tried to avoid the 'add a Z to the front' naming convention but it does help with clarity. I like Zoad, I think I'll give that treatment to the 'Bloated Zoad' and 'Death Mask Zoad.'

**Comment by Nebnis** [comment]
I'm really against more electric shooting enemies in the game specially when most people already hate shockers to the guts, and specially because those electric frogs show up very often too. I don't think i would like a swarm of electric spitting frogs everywhere

**Comment by TheSaddestGoomba** [comment]
If the other (living) electric frogs are too common then that's a mostly separate issue. Those are also non-aggressive and only have zapback.
This (zombie) one will only appear as a revival of those and not from any other source.

**Comment by BlizzDA** [comment]
> Thanks, and yeah, that's a concern I had with some of them. I tried to avoid the 'add a Z to the front' naming convention but it does help with clarity. I like Zoad, I think I'll give that treatment to the 'Bloated Zoad' and 'Death Mask Zoad.'
if 'Zom' doesn't fall under the same umbrella, 'zombullfrog' is in the game and 'zomfrog' or 'zompfrog' (like 'swamp') rolls a bit better of the tongue than 'Zrog'. If you're considering anything for the remaining evos. Shocker, Shady Zom/Zompfrog etc.

**Comment by TheSaddestGoomba** [comment]
This is ready for review.
The only test fails are unrelated mapgen errors.

**Comment by Maleclypse** [comment]
Looks neat. Thanks!

**Pull request merged**
