### PR TITLE
Deprecate improved survivor weapons mod

### PR DESCRIPTION
**Pull request by mugling**
I wrote this mod a while ago and it has become so outdated that it doesn't really work as intended any more. As it only overrides items in `core` it can be dropped without migration and the relevant items will continue to function using their definitions from `core`.

If someone wants to write a replacement that would be interesting but should take place in a new mod (otherwise old savegames could suddenly acquire a lot of content the player might not wish for).

### CODE REVIEW

**Comment by DangerNoodle** [comment]
It might be more useful if it covered a wider range of makeshift weapons, like the survivor melee weapons.

It could even go beyond that and outright make the recipes output their closest non-makeshift equivalent, thus fulfilling the intended spirit of the mod (allowing the player to craft useful things that would be unbalanced) in a manner that might entail less upkeep.

Though that might require blacklisting the survivor weapons, then adding copies of their recipes that output different results. That is currently not doable though, as recipes do not support `copy-from` properly yet.

**Comment by mugling** [comment]
> It might be more useful if it covered a wider range of makeshift weapons, like the survivor melee weapons.

All well and good but the currently mod is useless and should therefore be dropped

**Comment by DangerNoodle** [comment]
Odd. Is there a bug, or some other reason for it being useless?

**Comment by mugling** [comment]
> Odd. Is there a bug, or some other reason for it being useless?

It was never updated after the aiming rebalance. Most of the survivor weapons remain useless in it. To be honest it's existence probably stands in the way of something better.

**Comment by DangerNoodle** [comment]
That seems like the main thing would thus be to rebalance the mainline versions as needed, then ensure that the mod weapons copy from the mainline versions in a way that will make them stay consistent even if their parent weapons are further changed.

I suppose if removing it *until* this has been accomplished is actually needed, then very well then.

**Comment by jokermatt999** [comment]
Heh, I'd never actually noticed this before. I put together like half of those, and honestly the main thing I did balance-wise was make the craftable guns as nerfed versions of existing weapons in that caliber. If I'm reading this mod correctly, it just basically undoes those nerfs by copying the stats from (what I recall) the weapons I based them off anyway. I think it pretty much works as is, if the intention was to make craftable weapons comparable. I'm quite amused at how perfectly it re-balances it.

The main reason why they're worse is detailed in the PR for that, so I'll dig that up in a second. Basically, balance and lack of precision tools/environment/materials dictated they be worse than existing weapons. I mostly took away from accuracy/damage as a start, but larger magazine sizes were largely ruled out, and full auto is definitely out.

Survivor melee weapons largely don't need improving. They're already typically better than similar weapons either through stats or additional techniques.

**Comment by Coolthulhu** [comment]
Honestly I'd rather see it mainlined than deprecated.

**Comment by mugling** [comment]
Yes, I'll take a look at overhauling survivor weapons in mainline (currently they are useless) but that would make this mod redundant in any case so prefer to drop it here

**Pull request merged**
