### PR TITLE
Add's disassembly of different glasses for high quality lens and plastic

### PR DESCRIPTION
**Pull request by ItsJustAlexC**
High Quality lenses seem to be quite rare (only obtainable disassembling binoculars, telescopes, eyebot, cameras, and cranial flashlight CBM, 3 of which are rather rare in of themselves). This PR fixes this by giving more options to obtain high quality lens through items that make sense.

### CODE REVIEW

**Comment by Mecares** [comment]
I do not think regular glasses are made of what we call high quality lenses in-game and I am actually quite fine with high quality lenses being kinda rare.

**Comment by 0be1isk** [comment]
Currently DDA doesn't have different types of lens, so there is already a huge inconsistency with what does and doesn't have lens.

> I do not think regular glasses are made of what we call high quality lenses in-game

I'd argue the opposite. The in-game description of what high-quality lens are strongly hint that they have a strong relationship with the glasses in-game. Especially since the lens and bifocal glasses both state to focus light, and the lens and pair of eyeglasses both state the diffusion of light. So the in-game descriptions both match up, as well as the material of the glasses being glass (lens) and plastic (plastic chunk)

4 out of the 7 items (that I'm aware of) that use high quality lenses (magnifying lens, cranial flashlight, telescope, binoculars) have more in common with glasses than with microscopes. A magnifying glass and cranial flashlight CBM logically don't have the High power magnification that microscopes do. In fact, a lenses in glasses are just miniature magnifying glass lenses (this is somewhat over simplifying it, but with what we have in-game currently it will have to be "good enough" for right now, until it's changed". the cranial flashlight is less powerful than a regular flashlight (which doen't use high quality lenses). The two that seem to have the most arguing points would be the telescope and binoculars. This however is what I mean by inconsistency. A magnifying lens and a LED flashlight do not have the same magnification as telescopes and binoculars, yet telescopes and binoculars do not have anywhere near the high magnification and clear imagery that a microscope does. If we really boil it done, all telescopes and binoculars do is enlarge what is in front of you. It doesn't increase the quality of what you are looking at, just like the lenses in glasses, a magnifying glass, and the ability to shine light through (such as in its description, and in the cranial flashlight).

If there is demand to create new lenses, and items, i'll look into it, but I just find it very odd to not be able to disassemble glasses for their lenses.

**Comment by kevingranade** [comment]
None of telescope, binoculars, or microscopes have lenses even remotely resembling eyeglass lenses.
If you want to reuse these lenses you're going to need to find some evidence of something useful you can do with them.  Considering the magnifying lens is mostly used as a solar collector, that seems reasonable, but I'm drawing a blank for anything else that you could do with them.

**Comment by TechyBen** [comment]
Seems two magnifying lenses are needed for a telescope:
https://www.wikihow.com/Make-a-Telescope
Some strong prescription glasses may allow this.
http://www.unawe.org/activity/eu-unawe1353/
Seems glasses are not quite the best for this, will work in combination with a magnifying lense for less than optimal performance ("makeshift telescope" could be an option in game for 1 mag lense + 1 glasses lense crafting, and 2 lenses needed for full telescopic performance).

Would vr goggles be a possible source of good quality lenses? (In game I'm tempted to just trigger eyebots if I really need em :P ).

**Comment by 0be1isk** [comment]
@kevingranade 
> None of telescope, binoculars, or microscopes have lenses even remotely resembling eyeglass lenses.

I brought this up in my previous reply, idk if my reasoning was quite a stretch in coming up with the conclusion I did, but I do believe I provided a reasonably rebuttal to 2 of those items. This also has to do with how DDA doesn't currently have more then one variant of lenses. (I could possibly add more variants?) That being said, I stand my ground on how the in game description of the lenses match perfectly with the different glasses in game descriptions.

> If you want to reuse these lenses you're going to need to find some evidence of something useful you can do with them. Considering the magnifying lens is mostly used as a solar collector, that seems reasonable, but I'm drawing a blank for anything else that you could do with them.

I took this into account actually. For now I just wanted to make the lenses more available, however my main proposal had to do with gun sights. ACOG sight, red dot sight, reflex sight. Seeing as these can't be crafted, I was thinking they should and could use the lenses as a component. These sights don't have the magnifying power of telescopes. So depending on how you view what a "high quality lens" is, I think this is quite reasonable. however these sights should be limited to crafting by also requiring a gunsmith repair kit (as these also seem relatively rare).

**Comment by TechyBen** [comment]
Lots of items in game have no use except as spawned items.

As to the different lenses, that is exactly what I mentioned (glasses plus high quality lense) and what I linked. :)

**Comment by 0be1isk** [comment]
@TechyBen 

> Lots of items in game have no use except as spawned items.
Which is why I hope to make most items have a use (whether functionality, or just for scrap, idk yet though)

> As to the different lenses, that is exactly what I mentioned (glasses plus high quality lense) and what I linked. :)

lol I apologize, I have a terrible habit of just skimming through stuff to get the gist of it. Upon further reading, your links pretty much perfectly confirms and justifies this PR that much more. Seeing as there may be no way around making different lenses, I'll work on it later lol.

**Comment by kevingranade** [comment]
> your links pretty much perfectly confirms and justifies this PR that much more

They absolutely do not >_<
You could disassemble "reading glasses" (not eyeglasses) to get "small magnifying lens"es, and disassemble a magnifying glass to get a "large magnifying lens" or just "magnifying lens", then those two together could be used to make a "makeshift telescope" (I would not expect to be able to make functional binoculars from these components).

Neither of those remotely resemble what we call a "high quality lens".

It's already a huge stretch that you can do optics crafting at all, please stop trying to push it even further.

> however my main proposal had to do with gun sights. ACOG sight, red dot sight, reflex sight. Seeing as these can't be crafted, I was thinking they should and could use the lenses as a component.

This is a hard no in the main game.  Please look into what is actually required for these mechanisms to work (hint, *very* custom optics).

If you do some due diligence and find out what is required to craft a more primitive sight (e.g. a telescopic sight with a recticle), we can look into adding it.

Some other random issues:
> Currently DDA doesn't have different types of lens, so there is already a huge inconsistency with lenses.

The existence of an inconsistency does not justify more inconsistencies.  The lack of lens differentiation is fine right now because there is very little you can do with them.  If you are attempting to enlarge what can be done with lenses, you need to increase the variety of lenses so it does not increase the inconsistency.

> I just find it very odd to not be able to disassemble glasses for their lenses.

AFAIK eyeglass lenses are almost completely worthless outside of correcting myopia.  Reading glasses act as magnifiers, which can be useful in creating primitive optics, but not sophisticated ones.

**Comment by 0be1isk** [comment]
fair enough

**Pull request closed without merging**
