### PR TITLE
Update stepladder volume

### LINKED ISSUE #59452: Stepladder requires more planks to repair than is made of
### Describe the bug

A |\ damaged stepladder requires 20 planks to repair.
Making a new ones needs 12 and 30 nails.

### Steps to reproduce

Get a stepladder.
Drive over it with your car.
Yell a bit at the fool who left it on the ground.
Repair with misc repair kit.
Be amazed at the inefficiency.

### Expected behavior

Requiring slightly less than 160% of the original wood when it's slightly damaged.

### Screenshots

image

### Versions and configuration

Win 10 Tiles 42a7fde

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TheKFB**
#### Summary
Balance "Reduce volume of stepladder"

#### Purpose of change

Fixes #59452

#### Describe the solution

Reduced the volume of the stepladder from 50L to 15L, reducing the number of planks needed for repair from 20 to 6. Also added a length of 200cm since the ladder is long enough to traverse z-levels.

#### Describe alternatives you've considered

Change the volume of the stepladder to some other value.

#### Testing

Looked at a stepladder, saw it had a volume of 15L. Ran over a stepladder, repaired it, saw it used 6 planks.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
Do you have a basis for it's volume being 10L?

**Comment by TheKFB** [comment]
Not really, just that its longest side is 37 cm so to have a 50L volume would require it to basically be a cube which would be an odd shape for a ladder, so I imagined one of those sides to be significantly shorter.

**Comment by AtomicFox556** [comment]
> Not really, just that its longest side is 37 cm so to have a 50L volume would require it to basically be a cube which would be an odd shape for a ladder, so I imagined one of those sides to be significantly shorter. Also, a lot of the "volume" within the bounds of the ladder is just empty space.

In this case it also needs a suitable "longest side" stat so that you can't just stuff your stepladder into a backpack.

**Comment by natsirt721** [comment]
A stepladder can be used to move between Z levels right? I can't see any item/ladder that allows that to be any less that 2m/6'/72" long. Give or take. OTOH, when I was a kid we had a wooden stepladder that was about 3' tall - more in-line with the item description but probably NOT able to do z-level transitions. Also too large to fit in a backpack.

**Comment by TheKFB** [comment]
Alright, I changed the weight and length to more accurately mirror real world ladders. Volume is still more or less a guess because it's difficult to get an exact value, but hopefully 15L is a good compromise between realism and fixing the issue.

**Comment by anothersimulacrum** [comment]
Make it match reality. Making the volume incorrect to make repair costs more sensible isn't fixing anything, it's masking a bug (repair costs are calculated incorrectly) and creating another one.

**Comment by TheKFB** [comment]
I'm trying to, but there aren't detailed enough dimensions (at least from my searching) to calculate an accurate volume. I've done some napkin math to get to my number, but between the several dimensions I had to estimate and the discrepancies between a factory made ladder and a homemade one, I imagine it could change a decent amount. If you have any suggestions about what I could do to give a satisfactory answer, I'm all ears.

**Comment by natsirt721** [comment]
The proper solution would be to inform the repair materials calculation that most of the volume is empty space. This could be explicit - a new attribute on the item representing the approximate percentage of volume that is empty space. Or it could be approximated from the density of the item vs the density of the materials it is made from. E.g, if I know the ladder is made of wood (density 0.6 kg/L) and the ladder has a mass of 10 kg and a volume of 50 L (density 0.2 kg/L) then ~2/3 of the ladder is empty space, reduce the volume accordingly before determining how many materials are required for repair.

**Comment by natsirt721** [comment]
Also, if you want to change the volume, it should go way UP, not way DOWN. The ladder I'm envisioning is the kind with a hinge at the top that you unfold with metal arms to keep the back side from splaying out, and 7 or 8 steps. Somewhere around 200 cm tall by 80 cm wide by 15 cm deep for a volume of 240 L.

**Comment by TheKFB** [comment]
The idea behind reducing the volume was to calculate only the volume of the physical material which makes up the ladder, as realistically you would still be able to store items between the steps. The idea of using mass/density to determine repair costs sounds great, but seems like a lot of refactoring for one edge case. A new attribute in the JSON seems like it would have less potential unintended consequences, but for a 240L ladder to take 4 planks to repair would require saying it's ~98% air which I would assume to be equally undesirable. 

Honestly I was just trying to do something simple for my first PR to get a feel for the process, but it seems I chose poorly. I didn't think it would take significant code changes, so I'll leave that to someone willing to take on that work.

**Comment by natsirt721** [comment]
[Here's a list](https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3A+issue+is%3A+open+label%3A%22Good+First+Issue%22+label%3A%22%5BJSON%5D%22+) of issues that are both json-related and a good first issue; there's also usually enough discussion that proper path to close has been identified. I'd recommend starting with one of those. If you're looking to do C++ work as well, the resolution for the underlying issue _should(tm)_ also be fairly straightforward. Just not with JSON changes.

**Comment by Zireael07** [comment]
@natsirt721: ooh, the game vaccilates between using weight and volume for calculating repair materials. Keep forgetting which one it is currently.

Either way, a special flag for the edge cases is still needed (IIRC there's at least one other item resulting in nonsensical amounts of repair materials needed)

**Pull request closed without merging**
