### PR TITLE
Expand blacklisting to all map item placement functions

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: Infrastructure "Expand blacklisting to more item spawning"

#### Purpose of change
I was playing around with blacklisting all items, and, once I fixed the single crash (I'm impressed there was only one), I noticed that blacklisted items were still spawning in the world. Prevent these items from appearing.

Changes to `item_factory.cpp`:
The game would crash on loading while trying to inline an empty list of requirements.

Changes to `map.cpp`:
Things such as turrets firing weapons and taking down furniture could place items on that map that were blacklisted.

#### Describe the solution
`item_factory.cpp`: Check that that list is not empty before attempting to do anything with it.
`map.cpp`: In the functions that did not already,  make sure an item is not blacklisted before placing it.

#### Testing
Using this mod blacklisting all items in the game: [no_items.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4584726/no_items.zip)
Ran around in the world, had turrets shoot things, took down furniture, killed monsters - no items were spawned.
Ran the tests, and all test passed.

#### Additional context
There is some minor possibility for additional crashing here, by adding a new way this function can return a null item reference. There were already ways this function could return a null item reference, so anything where this would cause a crash could already be problematic.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
This only affects spawning items, right?

**Comment by anothersimulacrum** [comment]
What do you mean? This effects all item placement. If you have say, casings blacklisted, and fire a gun, those casings will not be placed because they are blacklisted, where they would have been previously.

**Comment by Night-Pryanik** [comment]
Just wanted to know if it would fix showing blacklisted items in item info menu, like in #22294.

**Comment by anothersimulacrum** [comment]
Oh, yeah, it doesn't fix that.

**Pull request merged**
