### PR TITLE
Remove redundant entry in tool quality (amount:1)

### PR DESCRIPTION
**Pull request by illi-kun**
no-brainer change, as response on  #18607.
It's not complete clean up, it's not linting PR - it's just small step forward in solving the mentioned issue.

### CODE REVIEW

**Comment by mugling** [comment]
How did you do this? Hopefully (for your sanity) not via manual editing?

**Comment by Coolthulhu** [comment]
Regex in Notepad++ sounds like a safe bet.

**Comment by mugling** [comment]
This can also be done via `jq` (see the example in #19085). That approach does require linted files though.

**Comment by illi-kun** [comment]
Of course it was not manual edit, and it's not even regex (I used it previously in pre-lint era), it's simple replacement of ",amount:1" by notepad++.

**Pull request merged**
