### PR TITLE
[RDY] i18n: Decouple calendar::name_season from static const array

### PR DESCRIPTION
**Pull request by BrettDong**
Those strings are initialized upon the start up of the program thus they
will not be affected by in-game language switching.

### CODE REVIEW

**Comment by kevingranade** [comment]
This is going to fail to capture these strings for the .pot, the _ macro performs both translation and string capture.  It needs to also arrange to capture the strings now that they aren't statically translated.

**Comment by BevapDin** [comment]
> This is going to fail to capture these strings for the .pot,

I though so, too. But they are captured elsewhere, for example in options.cpp as translations for the values of the INITIAL_SEASON option.

**Comment by Rivet-the-Zombie** [comment]
Why `[Blocked]`?

**Comment by BrettDong** [comment]
Waiting for #21454 to be merged first.

**Comment by BrettDong** [comment]
Now it's ready. #21386 is ready too.

**Pull request merged**
