### PR TITLE
[WIP] Widen Fire Lookout Tower Garage

### PR DESCRIPTION
**Pull request by a-chancey**
#### Summary
Content "Widens new Fire Lookout Tower garage and restore some vehicle spawns"

#### Purpose of change

The changes to Fire Lookout Towers in #59025 were _awesome_, however, they had the unintended side effect of effectively removing the Survivor RV from the game. It previously had an 8% chance to spawn at fire lookout towers, and removing it left it only in the "Highway" vehicle group with a (currently) 1 in 17,552 chance of being picked by weight. No related issue, I brought it up in discord.

#### Describe the solution
widens the garage and path into it by 2 squares. Also widens gates and shifts the water tank and walking path.
Adds Survivor RV and Survivor Car to the vehicle list at their old spawn rates..

#### Describe alternatives you've considered
Weeping at the almost complete death of my beloved Survivor RV.

#### Testing
I tested each vehicle at 100% to ensure they fit, then rolled back the spawn chances to the old rates.
Spawned a handful of fire lookout towers, each vehicle was able to spawn.

#### Additional context

Apparently I can't change to draft from the GitHub app. I need to rework the basecamp layout to get the new garage to fit. I'll look at that tomorrow.

### CODE REVIEW

**Comment by LovamKicsiGazsii** [comment]
This is going to cause some issues with the basecamp upgrades.   The garage is already right next to Shack 1, and extending it by 2 tiles would cause them to collide.

Also, I'm pretty sure that vehicles have a small chance of spawning inside each other (if multiple spawn at once).
kép

Sorry for ruining the game!  I wasn't aware this was the only location that semi-consistently spawned the mighty Survivor RV.

**Comment by a-chancey** [comment]
Oh crap! I didn’t realize it could be a basecamp. I’ll play around with spacing of stuff tonight and see what I can do with it. The new layout is way better than the old location, so kudos on the redesign.

Worst case, I’ll move the survivor rv to be a rare variant of the luxury rv at campgrounds, and maybe add it to a variant one of the other survivor bunker/campsite locations. 

Nothing is ruined, I just happen to be a “trophy hunter” when I’m playing CDDA, so I keep tabs on locations where rare loot spawns and notice very quickly when it goes missing lol

**Comment by a-chancey** [comment]
Is it cool with you if I redesign the faction camp portion? I've got some ideas to better incorporate the tower structure into the camp building that would solve the spacing issue as well. 

I'm going to have to use nests for the vehicle spawns, so I may only widen the gates (and garage) if the RV is spawning. I'm gonna work on it tomorrow.

**Comment by a-chancey** [comment]
This has ballooned a LOT now, and I'm just going to close this because I don't have the time to go fixing mapgen code for basecamps.

Essentially:
The garage wasn't wide enough to hold the RV, so I made it wider.
In doing so, I overlapped the garage with the base camp building.
I could move it, but the shacks look kinda bland, so i was going to incoporate the basecamp building into the lookout tower.
Well, apparently, a roof won't be placed if I have stairs. or a hold in the nest so it doesn't overwrite stairs. Even if the stairs are completely enclosed by walls.
I'm giving up. I'll find a new location for the Survivor RV and Survivor Car.

**Pull request closed without merging**
