### PR TITLE
Feral blackbelt

### PR DESCRIPTION
**Pull request by WeisserRitter**
#### Summary
Content "Add a rare feral blackbelt martial artist to increase the risk of looting martial arts from dojos"

#### Purpose of change

Dojos are currently too free despite providing some of the most important survival tools in the game. They do spawn with some zombies inside, but these are hardly a threat until they evolve substantially, making it relatively low-risk to swipe a dojo early on for a book on martial arts. Adding a dangerous monster can act to punish the player for their greed unless they are prepared for conflict. If they want martial arts, then maybe they should deal with a monster capable of using them.

#### Describe the solution

Adds a rare monster to Dojos, the 'mad blackbelt'. By default the feral has an aggression of 0, meaning it acts as a sort of 'guardian' type monster. It is slow to rouse and won't immediately attack the player, much like a wasp. Once it becomes hostile it will bumrush the player and apply its various techniques to disable them, making it a very dangerous opponent to any slow melee-based character. It is hard to run from, which is generally bad, but its initial passive state means you get a grace period before it dragon kicks you to the moon.

#### Describe alternatives you've considered

Add a weaker but more aggressive variant that spawns more frequently, increase the zombie spawn rate within dojos or add more dangerous variants. 

#### Testing

Set the spawn chance of the mad blackbelt to 100 and spawned a dojo. The monster spawned correctly without any errors.

#### Additional context

image

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
Howcome this got downvoted? It solves a problem and it's extremely funny.

**Comment by NetSysFire** [comment]
One single person out of three reacting to your PR has given you a thumbs down and has not left any feedback. I would not worry for now. Making specific parts of the game harder is always going to upset someone.
Reactions are also not votes, they are just reactions.

**Comment by fairyarmadillo** [comment]
> One single person out of three reacting to your PR has given you a thumbs down and has not left any feedback. I would not worry for now. Making specific parts of the game harder is always going to upset someone. Reactions are also not votes, they are just reactions.

It's not my PR, I was just curious to hear the argument behind it.

**Comment by PatrikLundell** [comment]
I don't think this is good because it introduces a feral that doesn't act like one. Also, it risks being a meta gaming monster that you can only deal with after having gained meta gaming info about it, and risks being lethal trap (turn a corner and then you're screwed because you're immediately attacked and won't get any chance to act again before death).

**Comment by Zireael07** [comment]
@PatrikLundell: " It is slow to rouse and won't immediately attack the player" from the OP

**Comment by PatrikLundell** [comment]
@Zireael07 : That quote, to me, just seems to mean that it won't attack until you're too close to get away, and probably won't protect you if you're suddenly in its face. Wasp attack you immediately if you turn a corner and end up close to them, but they'll let you approach somewhat before getting aggressive, so in the open you can back off (if you do it in time: once it's aggressive it doesn't matter if you try to retreat), but not in close quarters.

**Comment by Zireael07** [comment]
In that case (I've never encountered wasps ingame so couldn't speak to their behavior) it might be worth it to introduce some sort of a ~cooldown~ spinup mechanic, where the enemy is neutral for X rounds after detecting you before getting hostile.

(And that spinup might be useful for some other enemies, too)

**Comment by sonphantrung** [comment]
"Your future hinges upon this fight"
Here are my concerns about him:
- Is he mutated from the start, or is he just a regular black belt who has gone feral?
- Assuming he's just gone mad, why does he have 120 speed? This is roughly equal to a survivor with Quick trait + 15 Dex (w/ Speedydex enabled)

**Comment by WeisserRitter** [comment]
I was envisioning him as a human with the Deft and Quick traits due to his high physical conditioning. Statwise he'd be a 12 in STR and DEX, not world-class but close to it.

**Comment by fairyarmadillo** [comment]
> I don't think this is good because it introduces a feral that doesn't act like one. Also, it risks being a meta gaming monster that you can only deal with after having gained meta gaming info about it, and risks being lethal trap (turn a corner and then you're screwed because you're immediately attacked and won't get any chance to act again before death).

Ferals are not necessarily mindless killers. They seem capable of acting out their former lives well enough for people to have assumed they were overzealous protesters, for instance, and the feral security guards are still patrolling like they're on duty. These are individuals who can make tools, use guns, and open doors.

I'm not sure what you mean by "meta gaming monster." Half the enemies in the game fit that description and they're way worse than this one. Talons, turrets, hounds of Tindalos, sludge crawlers, and armored centipedes to name a few. These only spawn in one location and they're weaker than all of those.

> In that case (I've never encountered wasps ingame so couldn't speak to their behavior) it might be worth it to introduce some sort of a ~cooldown~ spinup mechanic, where the enemy is neutral for X rounds after detecting you before getting hostile.
> 
> (And that spinup might be useful for some other enemies, too)

Wasps already have this mechanic, it's called anger. They generally ignore you unless you get too close or mess with their buddies, based on a counter that increments when you satisfy certain conditions. You can also see the anger mechanic in play with anything that has the player-hurt anger trigger, which will cause enemies to become more aggressive if you're already injured.

**Comment by PatrikLundell** [comment]
No, wasps do not have that mechanic. They attack when you get close, as well as when their friendlies are attacked, of course. They don't have a wind up mechanic. If you get too close you're too close immediately, but if you stay outside of that range they won't attack regardless of how long you stay there.

**Comment by fairyarmadillo** [comment]
> No, wasps do not have that mechanic. They attack when you get close, as well as when their friendlies are attacked, of course. They don't have a wind up mechanic. If you get too close you're too close immediately, but if you stay outside of that range they won't attack regardless of how long you stay there.

The mechanic that wasps have is perfectly suitable here and I don't see the need for a windup. These black belts are inside of dojos minding their own business, you're not going to bump into them on the street. And even if you did, so what? There are shockers, talons, and hulks outside that can quickly overwhelm you if you weren't expecting them.

**Comment by sonphantrung** [comment]
Here's a fact: The wasps' "wind up" is actually the STALK flag
And looking at his stats, it seems like he has 120 hp, has a throw strength of 30 (Knockback 2-3 tiles?!), and 120 speed, slower than Mr. Hulk (130 speed), becomes zombie wrestler when revived (The wrestler is 95 speed and 280 hp). Unless he wanders around randomly, or gets angered by other sources (not really likely though), he won't be much of a threat. Also you can use the homewrecker to break into the book room though.

**Comment by WeisserRitter** [comment]
The knockback is actually meant to help you get away since it will break the grab. It's probably nonsensical though, which is a point in disfavor to the whole concept.

**Comment by fairyarmadillo** [comment]
> The knockback is actually meant to help you get away since it will break the grab. It's probably nonsensical though, which is a point in disfavor to the whole concept.

Some martial arts have knockback moves, though they only move enemies one tile.

**Comment by WeisserRitter** [comment]
Yeah, not my finest hour, balancing this one. I'm not sure what throw strength would result in a 1-2 tile knockback, maybe 15?

**Comment by kevingranade** [comment]
This doesn't match the lore for ferals, they don't have significant knowledge retention like this implies, at most they retain enough intelligence to figure out how to use weapons from scratch.

**Pull request closed without merging**
