### PR TITLE
Use a wider type for symbols

### LINKED ISSUE #19632: Windows builds are broken
May relate to #19518. Ping @codemime?

### PR DESCRIPTION
**Pull request by codemime**
Fixes #19632.

### CODE REVIEW

**Comment by mugling** [comment]
Lets see if it keeps Jenkins happy

**Comment by codemime** [comment]
I don't have a Windows environment at hand, but it should do the trick. Though, I hoped that someone who has it, would test the fix before merging it.

**Comment by mugling** [comment]
It's an entirely reasonable change and we don't have a lot of windows users (that post to github anyway)

**Comment by NickGrease** [comment]
Win10 x64 0.C-20128-gbcb7a7b (6016)(tiles)

I think I was up to build 948806de (build 6000ish) before updating to the version that includes this commit, and it crashed while loading my saves. Best I can tell you was it crashed in the 'Finalizing and Verifying' stage of the load.

New world with new character, no problem.

**Comment by mugling** [comment]
The problem is that the last 17 windows builds are all failures so it could be any of those. Stack trace could be helpful if you have one?

**Comment by NickGrease** [comment]
Sorry, I tried using WinDbg, since I'm still trying to get my build environment set up, but I couldn't figure out how to use it. Hopefully I'll be more help in a few days.

**Comment by DanmakuDan** [comment]
Can you try renaming only keybindings.json and see if your game starts up without crashing? It was the only file I renamed to avoid crashing on 'Finalizing and Verifying' with my preexisting save on build 6016. 

Separately, I can't reproduce the crash when compiling in Windows.

**Comment by NickGrease** [comment]
>Can you try renaming only keybindings.json and see if your game starts up without crashing?

That did the trick. No crash.

**Pull request merged**
