### PR TITLE
Overmap/mission adjustments

### LINKED ISSUE #47368: "Unable to find and assign mission target cabin" ("Recruit Tracker" mission, the one after the "Kill Horde Leader")
# Describe the bug
When accepting the "Recruit Tracker" mission, the game fails to place the npc to search (I think), and leaves you without a place (or way) to complete the mission.

# Steps To Reproduce

1. Load the attached save (same as the one in #47366)
2. Accept the mission to kill the Horde Leader (And wait 30 seconds for the game to respond)
3. Lie about completing it
4. Ask for new mission, accept it
5. See the bugs

# Expected behavior

To place the npc I need to search, to know where it is, and be able to complete the mission.

# Screenshots

bug

No coordinates shown.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9532-g57d594e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    Estadísticas a través de las muertes [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

 DEBUG    : Unable to find and assign mission target cabin.

 FUNCTION : cata::optional<coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 252

 DEBUG    : Mapgen update function called with overmap::invalid_tripoint

 FUNCTION : bool update_mapgen_function_json::update_map(const tripoint_abs_omt&, const point&, mission*, bool) const
 FILE     : src/mapgen.cpp
 LINE     : 6532

[Spartanburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5949848/Spartanburg.zip)

Edit: Sorry for any bad english, I corrected some of it, and added the info about versions and configuration (2 AM in my country, I need to sleep)

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary

Bugfixes "Overmap/mission adjustments"

#### Purpose of change

With the adjustments to the overmap special rates some problems crept in, mostly in the form of missions acting up now that their target might not exist on the same overmap.
Fixes #47368 , reduces the chances of #47225 

#### Describe the solution

- A tiny optimization to the mission start code ( the new overmaps generated for the specials allowed for optional specials to be placed in the first round of placement)
- Adjusted all missions' search range, adding fallback terrains and more importantly `om_special` entries to help them spawn their targets
- Threw even more spawn locations at the Isherwood farms so that they can *pretty please* spawn more consistently
TODO:
- [x] Adjust the range of road maps 
- [x] Replace the field/forest tiles in Isherwood with a variant that doesn't allow for special spawning ( so they don't build an airport in their backyard out of boredom while waiting to spawn)
- [x] Look into the old guard scientist hardcoded mission line for any easy fixes - not necessary, they search on new overmaps anyway
- [x] General special adjustments if necessary 

#### Describe alternatives you've considered

~~Not messing with the code, but the change was easy and doesn't seem to break anything. I'll put the worldgen through a good bit of testing to be sure.~~ Turns out people more competent than me don't overlook such low-hanging optimizations. Go figure.
Hacking together a last-line fallback option for mission gen to just plop the special down wherever, but I'm not good enough to get away with such a dirty solution.
Moving the lab quest line over to the new mission infrastructure to cut down on the hardcoded weirdness, but that's out of scope.

#### Testing

Replaced Lapin's quest to find the Isherwood farm with the updated mission data, accepted each 5 times on a fresh start, 5 times after reading a map (which generates the surrounding overmaps because of their range), no errors.
More testing to follow.

### CODE REVIEW

**Comment by actual-nh** [comment]
Since maps are now slightly less useful, perhaps turn up their spawning rate a bit? Admittedly, that will also act to "fix" more area... sigh.

**Comment by Venera3** [comment]
The thing is, I'm honestly skeptical about how used maps are in general. You basically read them so you can disassemble/drop them without missing out on info, but you sure as hell aren't scanning the whole 3x3 block of overmaps they revealed for suspicious roads. The adjusted values allow them to reveal an area about the size of an overmap around their city of origin, which is a bit smaller infodump.

**Comment by Venera3** [comment]
It appears my teeny-tiny low-hanging code optimization was actually counterproductive, so the meat of the fixes is just adding the `om_special` to the missions that were missing that (and consequently couldn't spawn the targets on demand). I still need to figure out how to add nice procgen shores to the farm, but I can generate them on both saves provided in the issues.

**Comment by Venera3** [comment]
Adjusted the military locations to be rare-ish ( 80% chance per overmap for helipads, 50% for bunkers and outposts ), since they have a pretty skewed risk-reward ratio and added a minimum city distance to the microlabs to hopefully cut down on the overlap with subway stations and raise the chances of city-adjacent specials. I'll run some extra spawn rate tests, but this should be good to go.

**Comment by Maleclypse** [comment]
I was wondering if there's a way for this to be turned into a test that determines if various specials beyond uniques will spawn under normal mapgen.  I say this because I don't think regional schools spawn anymore naturally.

**Comment by Venera3** [comment]
> I was wondering if there's a way for this to be turned into a test that determines if various specials beyond uniques will spawn under normal mapgen. I say this because I don't think regional schools spawn anymore naturally.

Schools count as city buildings, so they should be completely unchanged by this (and city gen happens before specials, so the chances of interaction are pretty slim). I'll look into them, to be on the safe side.

**Pull request merged**
