### PR TITLE
Mix condensed milk and water for 2 milk.

### PR DESCRIPTION
**Pull request by Cyrano7**
Recipe to mix condensed milk and water for 2 milk to stretch that milk just a little farther.
Edit: I guess I should elaborate a bit more. This doesn't effect the the current milk recipe which is:
1 powdered milk + 1 clean water = 1 milk

It adds a second parallel milk recipe also called milk in the crafting menu.
1 condensed milk + 1 clean water =  2 milk

### CODE REVIEW

**Comment by ejseto** [comment]
So:
1. 10 milk -> 10 powdered milk
2. 10 powdered milk -> 20 milk
3. ???
4. Profit?

**Comment by sparr** [comment]
@ejseto powdered milk is not the same thing as condensed milk

**Comment by Griffinhart** [comment]
@ejseto Further, [there already exists a recipe to craft milk from powdered milk.](http://cdda-trunk.estilofusion.com/milk/craft)

**Comment by ejseto** [comment]
Woops, I guess I read that wrong.

**Comment by chaosvolt** [comment]
So, here's a thought. As it is, you can currently make cheese from reconstituted milk, whether from powder or presumably via this added recipe.

Plausible or not, is the question.

**Comment by Cyrano7** [comment]
Hmm. I don't think you can make cheese from strait milk irl, I never really do any cheese making in the game as powdered milk already stores so well. Just use milk for baking/drinking. Here's another thought. There is always talk of having some cows you could domesticate in the game. Maybe once that happens we could have different types of milk. Pasteurized milk (like in stores in the beginning of the game), reconstituted milk, raw milk (like from cows) that you could then processed to cheese, cream, butter milk or pasteurized milk.

**Comment by RadaRadaRada** [comment]
@Cyrano7 Milkable cows or other animals is a common suggestion. It would be relatively easy to code this feature in, once effects could expire outside reality bubble. Coolthulhu has laid down foundation for this in past PR. He's busy guy though, so someone else might implement it. So, it might come "soon".

**Comment by Cyrano7** [comment]
@RadaRadaRada Ya there is always a decent amount of cow chatter. Until then though I think this is a good way of stretching in game milk a little bit. irl you pretty much get 1% milk if you add equal parts unsweetened canned milk and water. Might be able to ad a bit more water to condensed milk. Once we get cows though I can see changing the recipes for milk from powder/can to reconstituted milk that you could use for cooking or drinking but can't use to make cheese or something like that.

**Comment by chaosvolt** [comment]
Hmm. True. I was going to say, assuming you can't plausibly make milk from reconstituted milk, it would be best to save the idea of splitting reconstituted milk from fresh milk until after milking cows or other animals becomes a thing. After all

**Pull request merged**
