### PR TITLE
Make mining costs scale with time spent mining

### PR DESCRIPTION
**Pull request by halfahermit**
#### Summary
SUMMARY: Balance "Make mining costs scale with time spent mining"

#### Purpose of change
Mining time decreases with strength, but mining costs (kcal, thirst, fatigue, pain) are hard-coded values per activity. So a high-str character is limited to about the same amount of mining as a low-str character despite mining much faster. For example, a fresh 8-str character can burrow through ~10 tiles of solid rock before getting tired. A 20-str character burrows 5 times faster, but can still only get through ~13 before getting tired.

#### Describe the solution
This replaces the hard-coded costs at the end of the 3 mining activities with periodic costs during the activity, so that the cost scales with time spent mining. I set the frequencies so that the costs are about the same as before for an 8 str character.

Some other stuff this addresses -
 - The kcal cost is (I think) redundant after #30321, so I removed it.
 - The pain charged at the end of the activity would pop up warnings, and cancel movement in the case of auto-mining. This adds pain in increments of 1 so these warnings don't get triggered.
 - Apply STOCKY_TROGLO bonus more consistently (it was only applied for pickaxe before)

### CODE REVIEW

**Comment by darktoes** [comment]
Is this really appropriate? Wouldn't a stronger character expend the same amount of energy to perform the same task regardless of how quickly they perform it?

**Comment by Inglonias** [comment]
If it were up to me, I'd go the other way. A stronger character takes the same amount of time to mine, but uses less energy to do it. That way they can keep going for longer.

**Comment by darktoes** [comment]
That's somewhat reasonable. My point is more that the overall work done is the same. Perhaps have the same calorie cost, but allow stronger characters to store more energy? Or something along those lines? Not sure.

**Comment by eilaattwood** [comment]
Stronger character can break a rock with two hits, less strong need five hits. Sounds realistic for me.

**Comment by Dekker3D** [comment]
The stronger character breaks the rock faster by swinging the pick faster. This would expend more energy. You can look up some BMR tables if you'd like: doing any activity faster makes it burn more calories per minute, and it's pretty linear, though I figure a stronger character might chip away rock a little bit more efficiently than a weaker one.

I would calculate it like this:
Calories per turn = calories per tile / turns per tile
Calories per tile = base rate / efficiency factor
Efficiency factor = 1 + 0.025 * strength // 50% more tiles per kcal at 20 strength

**Comment by kevingranade** [comment]
The total energy expended is the same, therefore the stamina costs are the same as has been pointed out. Higher strength value does not equate to higher muscular efficiency or greater stamina reserves.

**Pull request closed without merging**
