### PR TITLE
NPC AI + interaction update

### LINKED ISSUE #13468: NPC not entering vehicles
build : cataclysmdda-0.C-3646 64bit
tiles : yes modded m shock
windows 7 64 bit

Ok NPC from start shelter agreed to travel with me.

I went out side and spwaned a sports car I entered seat and woooot he got in and sat on spare seat.
I spawned a fire  truck and she just stands on the door never sitting on seat.

I then spawnded a metlab and same problem.

I have no idea why there not sitting 99% of the time :(

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26355801-npc-not-entering-vehicles?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
- NPC pathfinding will now avoid traps. It is clairvoyant: NPCs see all non-benign trap. Null trap is now benign, to simplify the code.
- NPC finding a seat on vehicle should work better now. Closes #13468 and allows NPCs to tell apart seats and aisles when selecting a good spot to sit on. Removes the "hop" that NPCs were doing before (a short-ranged teleport that they would do when getting into the vehicle)
- Implemented a NPC menu, similar to zlave menu. Activated by examining a friendly NPC or walking into one. Allows pushing NPCs (more or less like old pushing, except won't make NPCs bash stuff), swapping places with NPCs, examining their wounds (no using healing items, but this makes it way simpler to implement) and attacking. Pushing and swapping is only for friendly NPCs, all can be examined. Good first aid and perception allows seeing exact hp, as Self Aware does for player.
- Big refactoring of "limb menu". Moved from iuse to `Character` and got rid of a page worth of redundant code (per-limb code was literally ctrl+c+v, 4 times)
- Walking into a zlave will displace it rather than attacking
- Allowed NPCs to push each other out of the way. They don't path around each other yet, but pushing should prevent deadlocks (except when the target NPCs sleeps...)
- Fixed NPC "roaming" (long term goal of acquiring stuff). Due to performance limitations on pathfinding, old deterministic roaming would often result in them getting locked up, trying to wall into a wall of a building. New one will have them stare into the wall for a while, then change direction and get unblocked.

### CODE REVIEW

**Comment by stk2008** [comment]
Wow dude thank you so much :)

I love npc fixes etc :)

**Comment by Rivet-the-Zombie** [comment]
>NPC pathfinding will now avoid traps. It is clairvoyant: NPCs see all non-benign trap.

So no more killing/driving off NPCs using traps? I hope this is a temporary thing.

**Comment by Coolthulhu** [comment]
Just pathfinding, they still can be murdered by pushing them into traps and it still won't credit the player for the murder with -100 morale.

This was mostly to make them not blunder into open air and pits.

**Comment by chaosvolt** [comment]
Interesting. If there was a way to make them ignore undiscovered traps without adding to complexity or lag, though...

**Comment by kevingranade** [comment]
Shouldn't be hard, the method we use with players should scale to NPCs
doing the same thing just fine.

**Comment by chaosvolt** [comment]
Ah. Now if we further made a distinction between "spotted by player" and "spotted by NPC" that would be useful. However, that would add more code to juggle. Simply one list for players and one for NPC would be a step up and not too complex, but giving EVERY NPC their own detection list would get out of hand rapidly.

**Comment by kevingranade** [comment]
No, it would be just fine to give each NPC a separate list, no problem.

**Comment by chaosvolt** [comment]
Hmm. I do wonder how many traps, and how many NPCs, it takes to cause problems using that method. X3

**Comment by kevingranade** [comment]
IIRC they're stored in unordered lists, so it'll be fine until we run out
of ram.

**Comment by chaosvolt** [comment]
Ah right. And compared to map data and other stats, guess it wouldn't be a substantial addition to the amount of data tracked and saved.

**Comment by Zireael07** [comment]
I <3 this, @Coolthulhu!

**Pull request merged**
