### PR TITLE
Reenable auto deconstruction removing wheels

### LINKED ISSUE #39153: Vehicle deconstruction zone task wont remove wheels
# Describe the bug
Vehicle deconstruction task wont remove wheels from vehicles even if you have all the tools required on you to do so.

# Steps To Reproduce
1. spawn a basic car, a toolbox and a bottlejack
2. Set skills high enough to perform the tasks.
3. setup the vehicle to be in a deconstruction zone using the zone manager
4. Initiate the process and watch as the vehicle is taken apart until it comes to wheels where the process just wont work anymore.

# Expected behavior
For the wheels to be removed if I have the requirements met to do so.

# Screenshots
gets stuck like this.
image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13506-g221b0a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

### PR DESCRIPTION
**Pull request by starlightsys**
#### Summary
Bugfixes "Reenables removing wheels during auto deconstruction of vehicles"

#### Purpose of change
Fixes #39153

#### Describe the solution
This removes the check in the code which currently aborts if the part to be removed is a wheel. I don't know the reason this check was added, and this decision is not documented. I can't find that the original author has commented on this. In the gif provided with the original PR, the NPCs can be seen to remove wheels while deconstructing.

Original PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/33708
GIF: https://gfycat.com/clutteredinformaldolphin

#### Describe alternatives you've considered
* Try to contact the original author and ask why the check was added.
* Assume that there is a good reason, and manually remove wheels from all vehicles to be deconstructed.

#### Testing
* Create new world with no monsters and NPC needs disabled
* Create new Evacuee character
* Mutate debug traits
* Recruit NPC
* Set all NPC skills to 10
* Have NPC follow you
* Walk to nearest town to find a car
* Spawn in survivor rucksack, firearm repair kit, tire iron, bottle jack and atomic headlamp (active)
* Ask NPC to wear the rucksack and the headlamp
* Trade the rest to the NPC
* Start Vehicle Construction with a foldable-light frame and name the vehicle Engine Crane
* Add 10" set of wheels
* Add telescoping cantilever
* Make sure the Engine Crane is positioned near the car's engine position
* Define a Vehicle Deconstruction Zone around the car
* Ask NPC to work on deconstructing vehicles
* Wait until the process completes (may have to move the Engine Crane if the vehicle comprises other parts that require lifting)

With this change, the car will be completely disassembled, including the wheels, wheel mounts and the last few frames.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I don't know why this restriction was put in place either. A guess is that it might have something to do with things that seems to deal with flat tires and management of those, but I don't think that's used (and I don't know if it once was).

As an aside, the game has (at least) two single tile vehicles that provide lifting, so you could spawn those rather than constructing them. Also, you can spawn multiple such vehicles so you can place them around the vehicle to be deconstructed (so you don't have to move a single one around the vehicle).
Instead of looking for a vehicle to deconstruct, you can spawn one.

**Comment by vegarbg** [comment]
> As an aside, the game has (at least) two single tile vehicles that provide lifting, so you could spawn those rather than constructing them. Also, you can spawn multiple such vehicles so you can place them around the vehicle to be deconstructed (so you don't have to move a single one around the vehicle). Instead of looking for a vehicle to deconstruct, you can spawn one.

Neat, I didn't know about any of these features.

**Comment by Alex-Folts** [comment]
I think it is not require bottle jack(or any jack) yet. I could be wrong, but looking at code i see only checking mass of the part NPC will remove, there is no checking for total vehicle mass(thats what suppose to be in that if section you removing), so i think if you get rid of lift and jack with this fix NPC still will be able to remove wheels.

https://github.com/CleverRaven/Cataclysm-DDA/blob/dc1f03f1850a532b7cf067e504c1b7a123077987/src/activity_item_handling.cpp#L1157
here `base` is the single part right, not the whole vehicle, so it checks only for part mass?


@vegarbg can you test it?

**Comment by vegarbg** [comment]
@Alex-Folts You are correct, the NPC can remove wheels without caring about strength or jack quality. They were however not able to lift out the engine or disassemble the frame it's connected to.

**Pull request merged**
