### PR TITLE
Grasshopper nymphs

### PR DESCRIPTION
**Pull request by Karol1223**
#### Summary
Content "Adds the nymph variant for mutant grasshoppers"

#### Purpose of change
Just for the sake of consistency, grasshoppers missed this life stage and it didn't feel right.

#### Describe the solution
Adds a grasshopper nymph and change grasshopper eggs to hatch into that.

#### Describe alternatives you've considered
None with this particular PR. Alternatives will appear individually.

#### Testing
Booted up the game, the nymph works fine and runs away, all nice.

#### Additional context
While this PR started with the hope of adding a mega grasshopper as well, the general conclusion was that it didn't feel good to have it in the game while it cannot impact the environment around itself by destroying foliage in a 3-mile radius. The code for it is stored in an XML file on my device and if anyone, for any reason, wants to use it I am willing to share it with anyone contacting me on discord.

### CODE REVIEW

**Comment by Venera3** [comment]
These really don't need a `_mega` as a fourth variant, tbh - they don't really do anything the small ones don't, and adding more chonkers just for consistency's sake isn't necessary.

It's a different matter if you come up with some flavor for them, but all the megabugs boiling down to `punny name + random special attack + more chonk` is the main reason I started (slowly) reworking them.

More small bugs are always welcome, though - when we have something like dynamic monster pops they'll be great to show "something weird is happening to bugs" before we get to the actual monstery monsters.

**Comment by Karol1223** [comment]
> These really don't need a `_mega` as a fourth variant, tbh - they don't really do anything the small ones don't, and adding more chonkers just for consistency's sake isn't necessary.
> 
> It's a different matter if you come up with some flavor for them, but all the megabugs boiling down to `punny name + random special attack + more chonk` is the main reason I started (slowly) reworking them.
> 
> More small bugs are always welcome, though - when we have something like dynamic monster pops they'll be great to show "something weird is happening to bugs" before we get to the actual monstery monsters.

My idea for this was that if one insect grows to a particular size then probably that's the same thing that would happen to all insects (of a similar size). Just felt logical to me but I do see where you're coming from

**Comment by MNG-cataclysm** [comment]
If you could tame a hillhopper, could it be ridden as a mount?

**Comment by Karol1223** [comment]
Right, so to close this off: the Hillhopper has been indefinitely scrapped until herbivores can actually impact the world in one way or another as that was the conclusion me and Venera came to. It is safe in an XML file on my device until the time is right. Until then, farewell grasshopper cowboy.

**Pull request merged**
