### PR TITLE
Bugfix: Two-handed weapons and tools now require two hands

### LINKED ISSUE #25743: Zweihander should require two hands to wield
**Describe the bug**  
The zweihander does not require two hands to use.

**To Reproduce**  
1.) Obtain Zweihander
2.) Wear anything that requires a hand, e.g bindle or briefcase.
3.) Wield Zweihander without any trouble

**Expected behavior**  
"Zweihander" means 'two hander.'  The in-game description calls it a two handed sword.  It should require two hands.

### PR DESCRIPTION
**Pull request by ericlimer**
#### Summary
SUMMARY: Bugfixes "Tools and weapons described explicitly as 'two-handed' now actually require two hands."

#### Purpose of change
Fixes #25743 - Zweihander does not require two-hands despite a description (and name) that suggests otherwise. Also fixes a similar bug for other explicitly two-handed weapons and tools including the nodachi, wood axe, and fire ax.  

#### Describe the solution
Adds "ALWAYS_TWOHAND" flag to weapons and tools that are described as "two-handed" in their text description.

### CODE REVIEW

**Comment by ericlimer** [comment]
resubmitting with corrected summary line to pass automated checks.

**Comment by DracoGriffin** [comment]
I don't think this is a bug and just confused with what ALWAYS_TWOHAND should be used for; items that require both hands to operate independent of strength. For instance, it is basically impossible to fire a bow without two limbs, regardless of strength (ignoring using it as a makeshift ballista).

```
bool item::is_two_handed( const player &u ) const
{
    if( has_flag( "ALWAYS_TWOHAND" ) ) {
        return true;
    }
    ///\EFFECT_STR determines which weapons can be wielded with one hand
    return ( ( weight() / 113_gram ) > u.str_cur * 4 );
}
```



The weapons that are considered "two-handed" should already be forcing to hold as a two-handed for characters with weak enough strength, whereas forcing this flag will make post-threshold urvine/bovine or CBM-enhanced characters unable to wield a weapon with one hand when they should be perfectly capable (hence one of the reasons why greatbows were added that require 18 strength).

Otherwise, you could adjust the weight formula if you believe it is set too low currently.

**Comment by ericlimer** [comment]
Yes, I understand that the metric for two-handability insofar as melee weapons are concerned is currently just a matter of strength. In this case, (and the case of weapons explicitly described as two handed) I was operating off the, I think sound, [logic laid out by logros13 in the related issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/25743), namely that the two-handedness of a weapon like Zweihander (literally two-hander) is a function of length and leverage, not a function of weight and strength. 

[This video](https://www.youtube.com/watch?v=DbNL_At0IVw) is pretty indicative of the extreme functional difference between wielding a two-handed sword with two hands vs. one, To the degree that a two-handed sword (or axe) requires two hands for the purpose of creating a stable pivot-point (which is impossible with one hand no matter how strong you are), the two-handed requirement for a Zweihander is actually quite similar to the two-handed requirement for a longbow.

**Comment by JacobKessler** [comment]
But, as that video showed, it is _possible_ for someone within the normal strength range of a human to wield it one-handed, although with difficulty - and in Cataclysm terms, he probably doesn't have more than 12 strength, given that 8 is 'average' and 14 is 'world class'. Cataclysm mutants with 18-20 strength aren't uncommon. Hydraulic muscles boosting to 30 strength isn't uncommon. Post-threshold bear mutants with 22 strength _and_ several extra feet of height are possible. 

Those characters shouldn't be forced to use the two-handed sword two-handed even if a human-standard character should - The current formula might not be great (since it looks like you need ~8 strength, which is probably too low), but a long, heavy sword definitely doesn't _need_ two hands in the same way that a bow (where you need to be effectively pulling against yourself) does.

**Comment by DracoGriffin** [comment]
Here's some deeper research, but still confined with human limits rather than hypothetical mutants/cyborgs:

[Video explaining it is possible](https://youtu.be/8bzCKfpLLA0) (but the benefits of why to use two-handed for average human).

[Great feedback by two users on one-handed use of two-handed weapons](https://www.quora.com/Is-it-possible-to-swing-a-greatsword-with-one-hand-or-can-you-create-a-style-if-possible-to-swing-a-greatsword-one-handed) ([Eric Lowe](https://www.quora.com/Is-it-possible-to-swing-a-greatsword-with-one-hand-or-can-you-create-a-style-if-possible-to-swing-a-greatsword-one-handed/answer/Eric-Lowe-6) and [Don Church](https://www.quora.com/Is-it-possible-to-swing-a-greatsword-with-one-hand-or-can-you-create-a-style-if-possible-to-swing-a-greatsword-one-handed/answer/Don-Church) specifically).

[Useful human metric charts](https://msis.jsc.nasa.gov/sections/section04.htm) provided by Don Church in his response, citing NASA research, [specifically on Strength](https://msis.jsc.nasa.gov/sections/section04.htm#_4.9_STRENGTH).

Combat in CDDA doesn't differentiate yet between using a weapon one-handed style or two-handed style, and generally assumed the survivor magically knows how to best use any weapon wielded (even with melee skill 0 and relevant combat skill (bash,cut,pierce) 0). There could be something to add to martial art styles menu as "combat skill -> one-handed / two-handed" that would essentially require strength check plus increase/decrease in stamina usage on weapon swing. Another option could be low skills (or lack thereof) have higher cost of stamina since survivor isn't use to or aware of best way to hold the weapon and thus increase endurance drain.

Neither of which really solve the problem posed by implementing this PR: mutants (especially ones with strength and/or size changes like [Little mutation line](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Little) (Little, Tiny, Unassuming) / [Large mutation line](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Inconveniently_Large) (Inconveniently Large, Large, Freakishly Huge, Huge)) and/or CBM-enhanced humans (noticeably [Hydraulic Muscles](http://cdda-trunk.chezzo.com/bio_hydraulics), which essentially doubles a survivor's strength, which is exactly what using two hands would do for a normal human being:
>Now, this is torque. If we increase the lever arm (ie: add a second hand on the grip), then even if the hands are smashed together, the applicable counter-torque doubles— and could take that blow. In reality, it’s even more than this because by adding the second hand, the arms and core become the counter-force generators rather than just the hand and forearm of single-handed grips.

) would be restricted in their ability to perform such feats; it's a portion of the ability itself. And just to clarify, I believe the strength requirement check should be higher for survivor size decreases (like Tiny) due to the change in center of gravity and such.

**Comment by ericlimer** [comment]
Yeah, this criticism all tracks. Thanks for the considered input, folks! I appreciate it!

**Comment by kevingranade** [comment]
Upon review this is a totally reasonable set of changes.

**Comment by DemAvalon** [comment]
It does not seem to be as all the research above says that its possible for a normal human to wield those weapons one-handed (with difficulty) and this would force post-human cyber/mutant monsters to wield them two-handed when they should be able to juggle I beams with their crazy strength (massive exaggeration but if a normal human can someone that is much more should too)

**Comment by kevingranade** [comment]
It says nothing of the sort, it says you can pick it up one handed and swing it around, it does not say you can fight with it in any meaningful way.
If someone is interested in writing a more nuanced system that has the performance of weapons impacted appropriately by one handed wielding vs two handed wielding (I am, but it's not a priority), they can feel free, but until then, the best option for the game is to slap ALWAYS_TWOHAND on these weapons.

**Comment by dunstad** [comment]
Would this then mean that like the greatbow, there would be space for new versions of these weapons that can leverage greater strength?

**Comment by kevingranade** [comment]
Re-implemented in #32984

**Pull request closed without merging**
